alphagov/govuk-developer-docs

Gemfile, Gemfile.lock, README.md, config.rb, lib/content_schemas/content_schema.rb, run-refresh.sh, source/error.html.erb, source/index.html.erb, source/layouts/api_layout.html.erb, source/layouts/layout.erb, source/layouts/schema_layout.erb
See individual commits for details.
=> Small improvements

data/dashboard.yml
=> Add govuk-display-screen to dashboard

bin/deploy-to-s3
This deploy script currently lives in jenkins. Moving it here will make it easier to change.
=> Move deploy script into repo

data/applications.yml
Assigns apps to core team in applications.yml
=> Add Core Formats team apps

Rakefile, data/applications.yml
https://github.com/alphagov/content-performance-manager is new!
=> Add page for content-performance-manager

source/guides.html.md.erb
Trello: https://trello.com/c/bh7iFV7G/311-document-a-b-testing-workflow-make-it-easy-to-use
=> Add pros and cons for A/B testing options

source/guides.html.md.erb
Add another trade-off to the A/B testing guide.
@suzannehamilton
=> Update the A/B testing guide

source/guides/_taxonomy.html.md.erb
This new filter was added in https://github.com/alphagov/rummager/pull/748.
@klssmith @MatMoore @carvil 
https://trello.com/c/dIMlC5JH
=> Add link to the taxonomy tree search

source/document-types.html.md.erb
See individual commits for details.
=> Update super type docs

.template_version, source/stylesheets/_core.scss, source/stylesheets/modules/_technical-documentation.scss, source/stylesheets/modules/_toc.scss
=> Update to latest tech-docs-template

data/applications.yml, lib/app_docs.rb, source/templates/application_template.html.md.erb
Did this the "hard way", so errors or omissions are expected. 
[Source](https://gov-uk.atlassian.net/wiki/pages/viewpage.action?pageId=130560605)
[Trello](https://trello.com/c/bM1an40m/48-make-it-easy-to-determine-ownership-of-a-repo-project)
=> Update application ownership details

config.rb, source/layouts/opsmanual_layout.html.erb, source/opsmanual.html.erb, source/opsmanual/ab_testing.html.md, source/opsmanual/keeping-software-current.html.md, source/opsmanual/taxonomy.html.md, source/stylesheets/screen.css.scss
See individual commit for details.
https://trello.com/c/5x8NHLhf
=> Improve Opsmanual layout

config/tech-docs.yml, source/getting-started.html.md.erb, source/layouts/getting_started_layout.html.erb, source/opsmanual/dictionary.html.erb
Initial integration of the Getting Started documentation into this app.
=> Getting started guide

bin/deploy-to-s3, config.rb
This adds a cache header so browsers will cache the page. Also minifies the assets.
https://trello.com/c/kiWZcJkv
=> Make the docs a little faster

Jenkinsfile, Rakefile, circle.yml
=> Use GOV.UK CI instead of CircleCI 

source/layouts/layout.erb, source/layouts/layout_with_sidebar.erb, source/partials/_search.html.erb, source/stylesheets/_core.scss, source/stylesheets/modules/_search.scss
See also:
- https://trello.com/c/vSbk1HoF
- https://github.com/alphagov/tech-docs-template/issues/66
=> Add minimum viable search via Google

spec/app/external_doc_spec.rb, spec/fixtures/markdown.md
Prep for PR for https://trello.com/c/vSbk1HoF
=> Add test coverage for fetching external docs

config.rb, source/manual.html.erb, source/manual/cache-flush.html.md, source/manual/emergency-publishing.html.md, source/manual/kibana.html.md, source/manual/rebooting-machines.html.md, source/manual/running-rake-tasks.html.md
These are tasks that are performed most often.
https://trello.com/c/l33LPxcU
=> Add list of most important pages in the manual

source/stylesheets/screen.css.scss
=> Left aligns meta links

source/manual/alerts/reboot-required-by-apt.html.md, source/manual/encrypted-hiera-data.html.md, source/manual/logging.html.md, source/manual/testing-projects.html.md
This fixes some broken links. Found by running [Screaming Frog SEO spider](https://www.screamingfrog.co.uk/seo-spider/).
=> Fix broken links

source/getting-started.html.md.erb
=> Fix title & add description

source/manual/ab-testing.html.md, source/manual/alerts/asset-master-attachment-processing.html.md, source/manual/alerts/elasticsearch-cluster-health.html.md, source/manual/cdn.html.md, source/manual/changing-organisation-slug.html.md, source/manual/create-a-gpg-key.html.md, source/manual/setting-up-request-tracing.html.md
These are some pages that are currently flagged by our review system. Should silence the donkey for the next couple of days.
=> Review & update some pages

source/getting-started.html.md.erb
=> Fix URL for the get started readme

data/applications.yml
I don't know which team owns this.
@kevindew
=> Add a page for the link-checker-api

data/applications.yml
We split up the apps we care for a couple of weeks ago.
=> Split Navigation & Taxonomy teams

source/manual/creating-a-new-environment.html.md
From https://github.com/alphagov/govuk-developer-docs/pull/150
=> Add note to "Create environment page"

data/applications.yml, source/layouts/application_layout.html.erb
This updates app ownership according to https://trello.com/c/79tPALe7. Also removes the subnav from the sidebar to de-clutter the UI.
https://trello.com/c/79tPALe7
=> Update app ownership

source/manual/heroku.html.md
Add a more active "how to" title and give an example of something deployed to Heroku.
=> Improve Heroku page

source/manual/alerts/postgresql-replication-too-far-behind.html.md
=> Update postgres replication resync link

source/manual/alerts/mongod-replication-lag.html.md
Looks good and relevant, helped me this week on 2ndline. Setting new review date to a month from now.
=> Review 'mongod replication lag' page

source/javascripts/modules/datetime-relative.js, source/javascripts/start-modules.js, source/partials/_source.html.erb, source/stylesheets/screen.css.scss
I was confused what review-by meant since I thought it meant, 'this was reviewed by this person'
---
---
=> Human review-by dates

source/manual/deploying.html.md
"Something" is a little vague. Also adds it to the list of most important pages so we can find it easily.
=> Update "Deploy an application"

source/manual/taxonomy.html.md
Some updates since this page was written.
=> Update taxonomy documentation

source/manual/add-deployment-dashboard.html.md, source/manual/deployment-dashboards.html.md
Next review in 6months by the search team.
=> Review dashboard related documentation

source/manual/alerts/search-benchmarking.html.md, source/manual/alerts/search-spelling-suggestions.html.md
https://trello.com/c/TXeHcOnY/53-revive-the-search-healthcheck
I've set the review date to be in two months' time because we may make some changes to the healthcheck this quarter.
=> Add Icinga alert pages for search healthchecks

source/manual/blocking-apps-from-release.html.md, source/manual/pact-broker.html.md
- Seems to all make sense and the links work.
=> Review pact-broker and blocking-apps-from-release pages for 2ndline

source/manual/troubleshooting-vagrant.html.md
This threw me when on the rare occasion I actually tried to provision the development-vm.
=> Add bundler permissions error

source/manual/retiring-an-application.html.md
Mostly, adding proper headings with numbers. Also adds a step to remove jobs from CI.
=> Update retirement docs

source/manual/bouncer.html.md, source/manual/data-sources-for-transition.html.md, source/manual/howto-transition-a-site-to-govuk.html.md, source/manual/side-by-side-browser.html.md
[Trello](https://trello.com/c/Rzil6Irn/74-consolidate-transition-and-bouncer-documentation)
=> Update Transition docs

data/redirects.yml, source/error.html.erb
Sets up a redirect and improves the 404 page with search box and instructions on how to set up a redirect.
=> Add redirect & improve 404 page

data/applications.yml
Otherwise this project won't build.
=> Mark contacts-frontend as retired

source/manual/ab-testing.html.md
We now set up up A/B testing using Fastly a little differently.
=> Update A/B testing documentation

source/manual/alerts/free-memory-warning-on-backend.html.md, source/manual/alerts/high-memory-for-application.html.md, source/manual/restart-application.html.md
Will be linked from Icinga via https://github.com/alphagov/govuk-puppet/pull/5928.
=> Add page about high memory Icinga alert

source/manual/alerts/puppet-last-run-errors.html.md
https://github.com/alphagov/govuk-puppet/pull/5946
=> Add page for puppet errors alerts

source/manual/rescan-infected-file.html.md
I just did this and it worked, so remember it for next time.
=> Add page about rescanning a file in whitehall

source/manual/alerts/user-monitor.html.md
Triggered by:
https://deploy.publishing.service.gov.uk/job/user-monitor
=> Add Icinga alert page on user monitor

source/manual/alerts/nginx-requests-too-low.html.md
Hopefully this makes this easier to read.
=> Rephrase the nginx requests too low page

source/manual/resync-mongo-db.html.md
This documentation seems good. The links still work, and we executed the steps without problem.
=> Review resync mongo

source/manual/alerts/mongod-replication-lag.html.md
This documentation still looks good, bumping review for 6 months
=> Review mongod lag

source/manual/alerts/rabbitmq-high-watermark.html.md
This documentation still looks good, bumping review for 12 months.
=> Review rabbitmq high watermark

source/manual/alerts/nginx-requests-too-low.html.md
=> Fix year in review date

source/manual/alerts/root-filesystem-is-readonly.html.md
Update this documentation to have more of an emphasis on who has access to vCloud director instance
=> Review root filesystem is readonly

source/manual/troubleshooting-vagrant.html.md
Paired with @Rosa-Fox 
We've moved around this file to try bring the more relevant content to
the top.
We've set a low review date of 2 months on this for a couple of reasons:
- We're due to move offices so the Aviation House information will
become out of date
- There's a lot of information that may be becoming redundant.
=> Update troubleshooting vagrant docs

source/manual/emergency-publishing.html.md
Add some additional instruction to help with clearing cache, fix a broken image and add some nicer formatting.
=> Update Emergency Publishing of banner docs

source/manual/alerts/elasticsearch-cluster-health.html.md
- Add some links to ES docs
- Put more useful stuff higher up
- Discourage restarting nodes to fix cluster health issues. This seems to be a solution for a specific situation, but I think there are situations where it will make things worse too.
- Make search team do the next review (we should know about this stuff)
=> Review elasticsearch cluster health page

source/manual/mongodb.html.md, source/manual/mysql.html.md, source/manual/offsite-backup-and-restore.html.md, source/manual/postgresql.html.md, source/manual/restore-from-offsite-backups.html.md
Re-arranging, re-formatting and simplifying the page as I followed the
instructions. Should be a bit easier for someone who may be trying to
read it at 4am in the morning to follow.
=> Update restore from backups guide

source/manual/elasticsearch-dumps.html.md
This is the word people normally use
=> Use "backup" instead of "dump"

source/manual/data-sources-for-transition.html.md
=> Update transition logs docs

data/applications.yml
Template consolidation owns this application.
=> Feedback frontend - error on ownership

source/manual/replicate-app-data-locally.html.md
A number of devs have encountered this problem, so it's common enough to warrant adding some documentation around.
=> Add info on how to fix full MongoDB

source/manual/encrypted-hiera-data.html.md
Small improvements to the readability:
- Use 'rotated' to describe changing credentials
- Describe the steps one would take to manage access to the encrypted Hiera data when someone leaves in the order they are likely to be carried out.
=> Encrypted hiera data improvements

data/dashboard.yml
This repo has been moved to the attic.
=> Remove govuk_content_models

source/manual/create-a-gpg-key.html.md
Add a step to test the passphrase.
=> Add step to verify passphrase

source/manual/alerts/ruby-version.html.md
Use clearer English, use the same terminology as Jenkins (hard restart vs full restart) and describe how a hard restart can be done.
=> Update ruby version docs

source/manual/running-rake-tasks.html.md
=> Update "Run a rake task"

source/manual/alerts/enhanced-ecommerce.html.md
https://trello.com/c/cuhxDKMB/150-add-documentation-around-enhanced-ecommerce-data-export
=> Add documentation about enhanced ecommerce task

source/manual/debian-packaging.html.md
On instruction from Daniel the Manual Spaniel
=> Fix formatting in debian-packaging

source/manual/mongodb.html.md
This was reviewed in https://github.com/alphagov/govuk-developer-docs/commit/5e26e4c720ba4c96f544a16e1efcbf01f5744dbd.
=> Bump review date for MongoDB docs

source/apis/search/content.html.md.erb, source/layouts/api_layout.html.erb
See https://github.com/alphagov/rummager/pull/820
=> Add a page for content indexed in search

source/manual/alerts/fetch-analytics-data-for-search-failed.html.md
And assign it to the search team.
@MatMoore
=> Update "Fetch analytics data for search failed"

source/manual/alerts/aws-ses-email-quota.html.md, source/manual/alerts/low-available-disk-space.html.md, source/manual/alerts/mysql-replication-lag.html.md, source/manual/alerts/offsite-backups.html.md, source/manual/alerts/prolonged-gc-collection-times-check.html.md, source/manual/rotate-offsite-backup-gpg-keys.html.md
See individual commits for the details.
@pmanrubia
=> Review a bunch of docs

source/manual/clone-mysql-slave.html.md
This changes the advice for copying backups between servers from copying
private keys to one of the servers to instead use agent forwarding.
Whilst agent forwarding is not ideal ([see this blog for
details](https://lyte.id.au/2012/03/19/ssh-agent-forwarding-is-a-bug/))
it is a strict improvement on copying private keys to a remote server
and having to remember to remove them.
Please review this carefully and confirm the command (I've personally tested it but I'd like to be sure).
=> Replace slave to backup mysql command

data/redirects.yml, source/manual/docs-style-guide.html.md, source/manual/monitor-docs-traffic.html.md, source/manual/review-page.html.md, source/manual/where-to-find-what.html.md, source/partials/_source.html.erb
This PR improves the docs about this docs site.
=> Improve meta-docs

source/manual/ab-testing.html.md
This commit adds instructions for how to remove an A/B test.
=> Add steps for removing an A/B test

source/manual/bouncer.html.md, source/manual/data-sources-for-transition.html.md, source/manual/howto-transition-a-site-to-govuk.html.md, source/manual/side-by-side-browser.html.md
=> Change ownership of transition docs to taxonomy

source/manual/github-enterprise.html.md
Fix broken link to the GitHub Enterprise installation.
=> Review GitHub Enterprise page

data/redirects.yml
I left a forward slash in there :-(
=> Fix redirect path

data/applications.yml
=> Assign collections to taxonomy

source/manual/attachments.html.md
- Clarify how the asset-slave machines are backed up
- Link to other manual pages on monitoring and restoring backups
=> Review attachment backups page

source/manual/alerts/unicorn-herder.html.md
Replace Fabric instructions with links to the Fabric docs.
=> Review docs for unicorn herder alert

source/manual/alerts/mysql-xtrabackups-to-s3.html.md, source/manual/mysql.html.md
- Fix a broken link to the docs on the MySQL backup strategy
- Fix syntax for links in MySQL backup docs
=> Review MySQL Xtrabackups docs

app/app_docs.rb, config.rb, source/templates/json_response.json.erb
So that we can re-use the data in a slack bot for example.
=> Add small API for application data

source/manual/access-ci.html.md, source/manual/github-enterprise.html.md
We've seen a bunch of questions around this in 2nd line. Hopefully this should make it easier to figure out how to get access.
👉 https://govuk-tech-docs-pr-330.herokuapp.com/manual/access-ci.html 📖
=> Add page on accessing CI

source/manual/content-preview.html.md
=> Review 'How the draft stack works'

source/manual/cache-flush.html.md
=> Review 'Purge a page from cache'

source/manual/environments.html.md
This commit adds some information about the upcoming training environment.
=> Add information about training environment

source/manual/add-an-icinga-passive-check.html.md
Also fix the filename so that the page appears in the manual.
=> Review Icinga passive alert docs

source/manual/alerts/enhanced-ecommerce.html.md
Still applicable. Review in 3 months.
=> Review GA Enchanced Ecommerce docs

source/manual/setting-up-new-rails-app.html.md
- Don't mention versions - it'll get out of date
- Expand introduction to explain that not everything has to be on our
VMware infrastructure.
=> Review setting up new rails app

source/manual/ab-testing.html.md
- Fixes some formatting issues
- Restructures chapters so that the content is flatter
- Trims down the introduction text to keep it focused
=> Update & restructure A/B testing manual

source/manual/alerts/pagerduty-drill.html.md, source/manual/create-a-new-open-source-project.html.md, source/manual/keeping-software-current.html.md
See individual commits for the details.
=> Review few overdue pages 

app/app_docs.rb, source/apps.json.erb
We'll use this in other places instead of using the YAML directly like
https://github.com/tijmenb/deploy-lag-badger/blob/93230af938cc7f884355edc69d276bc697423603/Rakefile#L15-L19.
=> Add API endpoint for all the applications

source/manual/alerts/nginx-5xx-rate-too-high-for-many-apps-boxes.html.md, source/manual/alerts/nginx-high-conn-writing-upstream-indicator-check.html.md, source/manual/encrypted-hiera-data.html.md, source/manual/howto-update-pingdom-ip-ranges.html.md, source/manual/mysql.html.md, source/manual/packer-vagrant-image-creation.html.md, source/manual/pingdom-bouncer-canary-check.html.md, source/manual/reprovision.html.md, source/manual/troubleshooting-vagrant.html.md, source/manual/vpn.html.md
Mainly date bumps as content was fine, a couple needed some typos or formatting fixes.
=> Update a bunch of pages

source/manual/howto-find-hardcoded-markup-govspeak.html.md
=> Add manual page to show how to search for hardcoded markup

source/manual/emergency-publishing.html.md
- added links to Jenkins
- added non-cache busting links to pages to check for ease of use
=> Add links to emergency publishing banners page

source/manual/patching-jenkins.html.md
This is more accurate to list in a hiera esque way.
=> Update command for Jenkins plugins

source/manual/rebooting-machines.html.md
- added link and clarification to reviewing updates
- added more information about rebooting safe machines
=> Update rebooting machines documentation

source/manual/monitor-sidekiq-workers.html.md
=> Add instructions to view Sidekiq queues locally

source/manual/kibana.html.md
I've reviewed the page and updated it as appropriate. As requested by @tijmenb
in PR #382.
=> Review Kibana queries page

source/manual/alerts/mysql-replication-running.html.md, source/manual/alerts/postgresql-replication-too-far-behind.html.md, source/manual/alerts/rkhunter-warnings.html.md, source/manual/alerts/whitehall-app-healthcheck-not-ok.html.md, source/manual/logging.html.md, source/manual/postgresql.html.md
I had a look through a number of documents which I felt I knew enough about. They all look fine so I've just bumped the review date.
=> Review various docs

source/manual/rebooting-machines.html.md
This addresses a few areas that I find confusing each time I'm on 2nd line and documents the practices.
=> Update rebooting documentation

data/applications.yml
=> Update team ownership with latest info from the wiki

source/manual/upgrade-to-sentry.html.md
Sets explicit versions and copyable Gemfile lines to the steps.
=> Update Sentry upgrade docs

source/manual/alerts/reboot-required-by-apt.html.md
This task seems to be a frequent source of confusion on 2nd line, so it
has been updated with more specific instructions for someone dealing
with it.
=> Update documentation on rebooting machines

source/manual/adding-disks-in-vcloud.html.md, source/manual/alerts/low-available-disk-space.html.md
We went through this process this week on 2nd line, so I've updated it on the bits we found confusing and any bits that seemed to be missing.
=> Update adding new disk documentation

source/manual/side-by-side-browser.html.md
All information is now in the README. Fixes #402
=> Update information about side-by-side browser

source/manual/deploy-puppet.html.md
I had to ask how this worked in Slack. Hopefully adding this note will help 
other people find the answer more easily in future.
=> Add note about puppet deploys in integration

source/manual/alerts/pingdom-search-check.html.md
Still looks good, fixed the "see check above"
=> Review Pingdom search check

source/manual/alerts/elasticsearch-cluster-health.html.md, source/manual/rummager-traffic-replay.html.md
https://trello.com/c/CdZiSBIb/280-deploy-es-to-production
=> Add documentation around GOR traffic replay for rummager

source/manual/create-a-gpg-key.html.md
* Added link to next step in the process - encrypt heira data
* Remove flag from example that is obsolete in latest version of GPG
=> Update GPG create documentation

source/manual/alerts/outstanding-security-updates.html.md
Still looks relevant, fixed a few errors and things that no longer have
affect (<div class="admonition note">)
=> Review Outstanding security updates

source/manual/restore-from-offsite-backups.html.md
This is a number of tweaks that are aimed to improve the experience of using this file, particularly in a 2nd line drill setting.
=> Update the restore backups documentation

source/manual/alerts/offsite-backups.html.md
=> ACK offsite-backups

source/manual/add-an-icinga-passive-check.html.md
Add instructions on making an Icinga passive alert a warning rather than critical.
https://trello.com/c/vtGDAiVi/305-review-icinga-alert-thresholds
=> Explain how to downgrade Icinga passive alerts

config/tech-docs.yml, source/manual/get-started.html.md, source/partials/_intro.html.md
This might not be clear if people land on the docs.
=> Make clear that these are internal tech docs

source/manual/howto-find-hardcoded-markup-govspeak.html.md
The component guide URL referred to in this repo has changed.
=> Update references to component guide

data/applications.yml
We should really be #blue-steel but there's some naming RFC or other that spoils my fun
=> #benchmarking is now #modelling-services

source/manual/alerts/gor.html.md
=> Update gor docs to include info about expect prod issues

source/manual/alerts/github-enterprise-connectivity.html.md
This page is correct, but GHE is going away in a month so I've set a low review date.
=> Update GHE connectivity page

source/manual/on-call.html.md
=> Update on call page

data/dashboard.yml
=> Add deploy lag badger repo to dashboard

source/manual/tools.html.md
I've reviewed this, all of the advice makes sense and it's still relevant.
=> Update tools doc with latest review date

source/manual/error-reporting.html.md
We're almost done with upgrading.
=> Update Sentry page

source/manual/testing.html.md
https://github.com/alphagov/styleguides/blob/f93b7e347140a4537847dcdbb8a2312d41f78f49/testing.md
@rubenarakelyan
=> Add "Testing" page from Manual

source/manual/readmes.html.md
https://github.com/alphagov/styleguides/blob/f93b7e347140a4537847dcdbb8a2312d41f78f49/use-of-READMEs.md
=> Add readme page from styleguides

source/manual/development-disk-space.html.md, source/manual/howto-update-pingdom-ip-ranges.html.md, source/manual/managing-product-support-tickets-zendesk.md, source/manual/patching-jenkins.html.md, source/manual/replicate-app-data-locally.html.md, source/manual/testing.html.md, source/manual/upgrade-rails.html.md, source/manual/upgrading-mysql.html.md, source/manual/using-database-gui-tools.html.md
We're supposed to write descriptive titles that describe a task ("Do a thing").
https://docs.publishing.service.gov.uk/manual/styleguide.html#good-titles
=> Make titles conform to styleguide

source/manual/alerts/asset-master-slave-disk-space-comparison.html.md
Update document to make it clear where this folder is and which machine.
=> Make it clear where the folder lives

data/applications.yml, source/apps/by-team.html.md.erb
I've done this with Antonia on the basis of https://docs.google.com/spreadsheets/d/1r5Tc0ddDZpBzFGUJRIB2zPvvUjZed_0Ctk0YPAS4I0o/edit#gid=0.
=> Update teams for Q3

source/manual/bowl-error.html.md, source/manual/run-application.html.md, source/manual/unable-to-mount-virtualbox-shared-folders.html.md
A go again at https://github.com/alphagov/govuk-developer-docs/pull/449 , now rebased on top of master.
=> Govuk puppet development vm fix additions

source/manual/heroku.html.md, source/manual/review-apps.html.md
Our process for creating Heroku Review Apps was wrong. Also the
link to the credential for the Heroku account was wrong.
=> Update heroku details

source/manual/docs-style-guide.html.md, source/manual/monitor-docs-traffic.html.md, source/manual/review-page.html.md, source/manual/where-to-find-what.html.md
They expired last week. They're mostly accurate.
=> Review pages about the docs itself

source/manual/alerts/search-benchmarking.html.md, source/manual/alerts/search-spelling-suggestions.html.md
=> Update search docs

source/manual/publishing-a-ruby-gem.html.md
To match the style across the developer docs.
=> Update title of ruby gem publishing page

data/applications.yml
=> Update ownership for TAP

source/manual/rabbitmq.html.md
- Link to hearbeat rake task in publishing-api not the content-store
- Update next check date
=> Update RabbitMQ docs

source/manual/setting-up-new-sidekiq-monitoring-app.html.md
=> Set new review date for sidekiq monitoring docs

source/manual/setup-postgresql-replication.html.md
=> Update review date for postgres replication docs

source/manual/alerts/publisher-app-healthcheck-not-ok.html.md
=> Update review date for publisher app healthcheck docs

source/manual/alerts/clamav-definitions-out-of-date.html.md
=> Update review date for clamav definitions docs

source/manual/alerts/mongodb-rollback.html.md
=> Update review date for mongodb rollback docs

source/manual/alerts/low-available-disk-inodes.html.md
=> Update review date for low available disk inodes docs

source/manual/ab-testing.html.md
I found this diagram in the architecture Google Drive:
https://docs.google.com/drawings/d/1rx4brKZBzj-9q3evkiUw2MbqwqTYWkc0Lku6u3cLXqU/edit
I'm not sure who created it ("Deleted user", perhaps @carvil?). It looks accurate so maybe it'll help someone.
I got the URL by doing `File > Publish to the web...`. I think it auto-updates.
=> Add diagram about A/B testing

source/apis/search/search-api.html.md.erb, source/layouts/api_layout.html.erb
See https://github.com/alphagov/rummager/pull/946
=> Split off faceted search guide from search API documentation

source/manual/configure-github-repo.html.md
=> Clarify the permissions GOV.UK repos should have

source/manual/setting-up-new-mirror.html.md
=> Bump review date for New Mirror docs

source/manual/alerts/redis.html.md
=> Bump review date of Redis docs

source/manual/restore-from-offsite-backups.html.md
After running through the drill on 2nd line, we came up with a number of improvements for the docs.
=> Improve restore from offsite backups docs

source/manual/on-call.html.md
Things you should do before going on call
=> Add an on-call checklist

source/manual/kibana.html.md, source/manual/logging.html.md
This should not be merged until we're using Logit everywhere.
This PR reflects any changes to our documentation.
https://trello.com/c/YrTOpoq7/746-logit-migration
Ideally users should check this branch when we're testing on Integration.
=> [DO NOT MERGE] Update docs on how logging works

source/templates/application_template.html.md.erb
=> Hide "Relevant manual pages" if there aren't any

source/manual/alerts/aws-ses-email-quota.html.md
Doesn't really look like anything needs updating here, although the "and
machine email" so that's been removed.
=> Review AWS SES Email Quota

data/applications.yml
=> Make clearer that start pages team owns apps

source/manual/alerts/mysql-xtrabackups-to-s3.html.md
Update the fields to match those used in the latest version of Kibana, which was recently upgraded.
=> Fix Kibana queries in MySQL Xtrabackups guides

source/manual/retiring-an-application.html.md
Remove broken links and links to github enterprise leave notes about
private repos that the user might not have access to.
/cc @pcraig3 does this resolve the issues you encountered?
=> Update retire application documentation

source/manual/redirect-routes.html.md
This should be rare, but worth noting down *somewhere*.
=> Add how to redirect campaign sites

source/manual/setting-up-request-tracing.html.md
I've added a few more details which I think are accurate, but it would be good  if someone could check I've got it right.
=> Review docs on request tracing

source/manual/rabbitmq.html.md
https://trello.com/c/KDfyOeS1/331-specialist-publisher-implementation
=> Details on previewing the message sent via rabbit MQ

source/manual/logit.html.md
I ran into some problems following the instructions, so I've attempted to improve them in light of my experience.
=> Improve Logit sign-in instructions

source/manual/send-test-email.html.md
Guide on how to send a test email to a specific email
address using Notify
=> Instructions on how to send an email using the dev VM

source/manual/pact-broker.html.md
- Link to better documentation
- Give publishing api as an example provider
- Explain a bit more what pact is trying to do
=> Review pact broker page

source/manual/alerts/asset-master-attachment-processing.html.md
This is fine for now, but asset hosting is currently being reimplemented,
so review this in 3 months.
=> Review asset master attachment processing

source/manual/blocking-apps-from-release.html.md
This page was completely out of date
=> Update process for blocking apps from release

source/manual/upgrade-rails.html.md
As part of the dependency upgrade project we are working on standardising rails configs. This outlines the initial guidelines that were created
=> Update rails upgrade guide to include config guide

source/manual/environments.html.md
I had to find this information by asking in Slack. This should hopefully help people with the same question in future.
=> Add info about integration shutdown/startup

source/manual/add-deployment-dashboard.html.md, source/manual/alerts/enhanced-ecommerce.html.md, source/manual/deployment-dashboards.html.md
Deployment dashboards review now notifies 2ndline channel.
=> Set search team check dates

source/manual/cant-connect-to-elasticsearch.html.md
Elasticsearch wouldn't start on my dev-vm and it took a while for me to
work out what to do. This page should hopefully save people time if they
find themselves in a similar situation.
=> Add page about problems connecting to elasticsearch in dev-vm

source/manual/upgrade-rails.html.md
As opposed to the other time when we went backwards :)
=> Going forward

source/manual/development-disk-space.html.md
* Add default disk size for information
* Extend the review period to 6 months since this information doesn't change that often
=> Update development disk space manual page

source/manual/retiring-an-application.html.md
This is the GDS Way now: https://github.com/alphagov/gds-way/pull/93
=> Archive repos, don't send them to the attic

data/applications.yml, source/apis/whitehall.html.md.erb, source/layouts/api_layout.html.erb
https://trello.com/c/9ePBo7GC/363-document-and-comment-whitehall-api-usage
Whitehall PR: https://github.com/alphagov/whitehall/pull/3548
=> Embed Whitehall's API documentation

source/manual/fall-back-to-mirror.html.md, source/manual/nfs-errors-vm.html.md
As these are no longer relevant.
=> Remove references to Aviation House

source/manual/alerts/search-reindex-failed.html.md
https://trello.com/c/9nZLUhqi/439-regularly-test-reindex-task
=> Add `search reindex failed` documentation

source/manual/alerts/puppet-last-run-errors.html.md
Related to https://github.com/alphagov/govuk-puppet/pull/6848/commits/4d0562f34d01c7f5a0d0a464431c5ca648fd713e
=> Add further docs on Puppet last run errors

source/manual/elasticsearch-dumps.html.md
https://trello.com/c/nOr4dBw4/436-make-nightly-popularity-update-work-on-integration
=> Update elasticsearch backup and restore documentation

source/manual/restore-from-offsite-backups.html.md
https://trello.com/c/dlE58jkG/387-restore-from-backups-drill-monday-13-november
=> Update restore from backup instructions

data/applications.yml, data/rendering-apps.yml, source/manual/creating-a-new-environment.html.md, source/manual/howto-switch-off-app.html.md
For: https://trello.com/c/M45WyUGZ/261-retire-design-principles
=> Mark design-principles as retired

source/manual/incorrect-content-in-search-or-navigation.html.md
To the Content that doesn't show up correctly in search or list pages
page.
=> Add information about Smokey

source/manual/keeping-software-current.html.md, source/manual/manage-ruby-dependencies.html.md
There's not much here, but enough to give some guidance & context. Will be reviewed very soon because it's likely to change.
=> Add initial page about dependabot

source/manual/howto-switch-off-app.html.md
Move to "Deployment" section & bump review date.
=> Update "Switch an app off"

source/manual/howto-backup-and-restore-in-aws-rds.html.md
- In our upcoming New World of AWS, how we manage databases has changed. We have a lot of docs to write for everything, so we thought we'd make a start.
https://trello.com/c/vBkLAvM8/852-aws-backups-review-processes-and-add-documentation
=> Add some AWS database backup and restore docs

source/manual/incorrect-content-in-search-or-navigation.html.md
Add link to task in publishing API.
Clarify the republishing of the person's page.
=> Update docs for incorrect content in search or navigation

app/document_types.rb, config.rb, source/document-types.html.md.erb, source/layouts/document_type_layout.html.erb, source/templates/document_type_template.html.md.erb, source/templates/supertype_template.html.md.erb
=> Update document supertype pages

source/manual/manage-ruby-dependencies.html.md
=> Explain how to manually bump dependencies

source/manual/emergency-publishing.html.md
=> Emergency banner docs improvements

source/manual/logit.html.md
More context: https://github.com/alphagov/govuk-puppet/pull/6990
👉  [Rendered doc](https://govuk-tech-docs-pr-636.herokuapp.com/manual/logit.html)
=> Update Logit docs after re-adding kibana.* domains

source/manual/assets.html.md, source/manual/attachments.html.md
I've reviewed the the following pages and added notes about the ongoing asset management development work. I've also reduced the `review_in` period from 6 months to 1 month in both cases to reflect the ongoing work.
* "Assets: how do they work"
* "Attachment backups"
=> Update assets documentation

source/manual/alerts/email-alerts.html.md
Some minor edits, and claiming the page for the email team pending further changes in Q4.
=> Update email alerts not sent page

source/manual/taxonomy.html.md
The name of the link type is changing.
=> Change root_taxons to level_one_taxons

source/manual/metrics.html.md
High level stuff, just explaining the tooling.
=> Add some documentation on Metrics

source/manual/debian-packaging.html.md
These docs have always been pretty clear and concise and I can't see any
noticeable improvements to add at the current time.
=> Reviewed debian packaging

source/manual/alerts/postgresql-s3-backups.html.md
Update the field names to the ones used in the latest version of Kibana.
=> Fix Kibana queries in PostgreSQL backup docs

source/manual/testing-projects.html.md
=> Review Jenkins CI docs

source/manual/alerts/rabbitmq-no-consumers-listening.html.md, source/manual/rabbitmq.html.md
- Fix list layout
- Update references to the heartbeat message. This was moved from the content store to the publishing API: https://github.com/alphagov/content-store/pull/137
=> Review RabbitMQ docs

source/manual/howto-ssh-to-machines-in-aws.html.md, source/manual/ssh-config.html.md, source/templates/application_template.html.md.erb
Now DNS is migrated we can make the docs more consistent.
I have also added a (simplified) SSH configuration for people to use in the future.
=> Update SSH docs

source/manual/redirect-routes.html.md
=> Fix broken links in Redirect docs

source/manual/alerts/puppet-last-run-errors.html.md
Fix quote style in Kibana query and explain the `hostname` format.
=> Update Kibana query for puppet last run errors

source/manual/manage-ruby-dependencies.html.md
=> Update "Manage Ruby dependencies with Dependabot"

source/manual/concept-of-stacks.html.md, source/manual/content-preview.html.md, source/manual/deploy-fixes-for-a-security-vulnerability.html.md, source/manual/govuk-in-aws.html.md, source/manual/review-page.html.md
Update review dates and fix minor link issues.
=> Review documentation

app/app_docs.rb, app/applications_by_team.rb, app/apps_csv.rb, data/applications.yml, source/templates/application_template.html.md.erb
See individual commits for details.
=> Update application ownership for teams

source/manual/reindex-elasticsearch.html.md
Explain how to stop a reindexing job or to switch the alias back to the original index.
cc @elenatanasoiu
=> Add troubleshooting section to reindexing docs

source/manual/alerts/virus-scanning.html.md
Add some clamav troubleshooting advice.
Also update the last reviewed date.
=> Add clamav troubleshooting

source/manual/alerts/email-alerts.html.md
Just update the date for another month since we're going live at some point soon.
=> Update email alerts page

source/manual/who-do-i-ask-for-support.html.md
This has been agreed between Platform Support, Reliability Engineering
and GOV.UK lead technologists
=> Document who to ask about things

source/manual/alerts/redis.html.md
Existing documentation states what command to run to investigate redis memory issues, but doesn't clarify how to use the results of that command
=> Expand redis investigation tips

source/manual/add-a-new-document-type.html.md, source/manual/make-a-new-document-type-available-to-search.html.md
To fix https://github.com/alphagov/govuk-developer-docs/issues/611.
=> Review pages about document types

source/manual/alerts/asset-master-slave-disk-space-comparison.html.md, source/manual/alerts/elasticsearch-cluster-health.html.md, source/manual/alerts/high-disk-time.html.md, source/manual/hmrc-paye-files.html.md
- HMRC PAYE uploads
- Elasticsearch cluster health
- High disk time
- Asset disk usage
=> Review some out-of-date docs

source/manual/get-started.html.md
The old file is now just used for CI and other things.
=> Update the integration hieradata path

source/manual/alerts/es-rotate.html.md, source/manual/alerts/pagerduty-drill.html.md
- PagerDuty drills
- es-rotate alerts
=> Review some expired docs

data/applications.yml
GOV.UK will be taking care of updates to these apps.
=> Move service manual apps to platform support

source/manual/make-a-new-document-type-available-to-search.html.md
- Fix and update links
- Add reindexing step
=> Review docs on adding a document type to search

source/manual/adding-disks-in-vcloud.html.md
- There was some data missing on how to access Carrenza. This has been
covered by this commit.
Solo: @suthagarht
=> Carrenza Access

source/manual/keeping-software-current.html.md
This is up to date at the moment.
=> Bump "Policy on keeping software current"

source/manual/testing-projects.html.md
We now load an external library: [govuk-jenkinslib](https://github.com/alphagov/govuk-jenkinslib/)
https://trello.com/c/88RFcs4R/994-make-jenkinslibgroovy-its-own-repo-refactor
=> Update docs for Jenkinsfile

source/manual/emergency-publishing.html.md
Part of improvements during a emergency publishing drill: https://trello.com/c/ktLcZLIN
=> Emergency publishing docs improvements

config/tech-docs.yml
This adds "Internal" to the header.
=> Make a little clearer that these docs are internal

source/apis/content-store.html.md.erb
Fixes https://github.com/alphagov/govuk-developer-docs/issues/643.
=> Note that content store isn't complete

source/manual/ab-testing.html.md
- Move to #2ndline
- Add step to add the test to the A/B testing register
=> Update A/B testing page

source/manual/alerts/unicorn-herder.html.md
I don't know how regularly unicorn herder breaks these days, but the docs seem useful for when it does.
=> Review unicorn-herder alert docs

source/manual/nagios-nrpe-connection-failures.html.md
=> Review Nagios NRPE connection failures

source/manual/alerts/whitehall-app-healthcheck-not-ok.html.md
I suspect more info could be added as the healthcheck can report other failures, but what we have looks good and I don't have the context to add what's missing.
=> Review whitehall-app-healthcheck-not-ok

source/manual/github-unavailable.html.md
=> Review Deploy when github is unavailable

source/manual/ssh-config.html.md
Minor change to the "titles" in the SSH stanza to make the title and underline match up.
=> Review SSH configuration

source/manual/elasticsearch-dumps.html.md
Leave the review time as 2 months because this process will change once all environments are on AWS.
=> Review the Elasticsearch dump docs

source/manual/attachments.html.md
Reviewed the doc and all seems to make sense, however I have left the
`review_in` value at 1 month as it seems like changes will be happening and
this doc will potentially be out of date in the near future.
=> Update last reviewed on date

source/manual/logit.html.md
Remove to reference to infrastructure team.
=> Update adding user to logit section.

source/manual/postgresql.html.md
Clarify that `backup-fetch` and `wal-fetch` can be found in the WAL-E docs.
Reviewed and update `last_reviewed_on` date
=> Clarify the docs that contain restore commands

source/manual/metrics.html.md
Change the owner to #2ndline, as this is not specific to the Taxonomy
team. Bump the review date, and improve the wording the in first
paragraph.
=> Review the metrics page

source/manual/alerts/whitehall-scheduled-publishing.html.md
The process is slightly different.
=> Add info about requeueing from a database restore

source/manual/alerts/onsite-backups.html.md
=> Add command for rerunning failed onsite backups

data/dashboard.yml
=> Remove boxen from running on the VM docs

source/manual/development-disk-space.html.md
See https://github.com/alphagov/govuk-puppet/commit/268d0035711a590bccb0d09eeda9e6201d0889f6#diff-902ea9102b9f5de7f1c36aab035c813d
=> Fix script name to delete Elasticsearch indexes

source/manual/lint-ruby-code.html.md, source/manual/publishing-a-ruby-gem.html.md, source/manual/readmes.html.md, source/manual/testing.html.md
They're all still good. Minor edits to the rubygems page.
=> Review pages about testing/readmes

source/manual/docs-style-guide.html.md, source/manual/monitor-docs-traffic.html.md, source/manual/review-page.html.md, source/manual/where-to-find-what.html.md
These are still accurate. Probably valid for a year too.
=> Review the docs about the docs

source/manual/troubleshooting-jenkins-performance.html.md
Off the back of the issue we've had with Jenkins over the last few
weeks, I've documented some of the information we've gleaned and a
process to clean up the situation that was causing us problems.
=> Jenkins troubleshooting documentation

data/applications.yml, source/manual/side-by-side-browser.html.md, source/manual/transition-a-site.html.md, source/manual/transition-architecture.html.md, source/manual/whitelist-site-in-transition.html.md, source/manual/who-do-i-ask-for-support.html.md
The team and Slack channel has been renamed.
=> Change platform_support to platform-health

data/applications.yml, source/manual/alerts/reboot-required-by-apt.html.md, source/manual/assets.html.md, source/manual/rebooting-machines.html.md, source/manual/who-do-i-ask-for-support.html.md
Reflecting the Q1 changes.
I haven't updated the review dates as I didn't have enough context on the areas to review them.
=> Change Platform Support to Platform Health / 2nd line

source/manual/incident-management-guidance.html.md, source/manual/incident-reports.html.md, source/manual/incident-what-to-do.html.md
This PR:
- Adds a page that links out to the laminated "So, you're having an incident" sheet
- Copies over the "Write an incident report" page from the Wiki (https://gov-uk.atlassian.net/wiki/spaces/PLOPS/pages/33619999/Incident+report+style+guide)
- Adds direct links to the wiki page
We expect more updates soon, this is a start!
=> Update incident management docs

source/manual/emergency-publishing.html.md
Trello: https://trello.com/c/eyPmZqho/7-emergency-publishing-drill
=> Fix ssh instructions in Emergency banner docs

source/manual/stop-all-email-subscription-sending.html.md
This looks like it'll be valid for a reasonable time forward since it's not actively being worked on.
=> Bump stop email subscription time

source/manual/manage-email-subscribers.html.md
Add direct links to Jenkins instead of just the rake tasks.
=> Update email docs

source/manual/who-do-i-ask-for-support.html.md
It looks up to date with the correct information.
=> Update the review date on who-do-i-ask-for-support

source/manual/incident-management-guidance.html.md
Added 'the' to:"Guests are welcome to observe the incident review if they let [the] review facilitator know in advance of the session."
=> Made a small edit

source/manual/incident-management-guidance.html.md, source/manual/incident-reports.html.md, source/manual/incident-what-to-do.html.md
I want to add more guidance to the section to include 2nd line things.
=> Rename 'incident' section to '2nd line'

source/manual/emergency-publishing.html.md
https://github.com/alphagov/govuk-puppet/pull/7536
https://trello.com/c/yFrK9Hue/119-update-emergency-publishing-process-to-not-require-fabric-2
=> Update emergency publishing banner docs

source/manual/user-management-in-aws.html.md
Make it explicit how to sign in to AWS.  I just spent a bit of time trying to work it out, as I forgot about the "gds-users" bit.
=> Document how to sign in to AWS

source/manual/emergency-publishing.html.md
Trello: https://trello.com/c/AHsIRPU4/71-emergency-publishing-drill-16-23-may
This includes links to run the job in production and adds integration preview links
=> Additional links for emergency-publishing docs

source/manual/transition-architecture.html.md
=> Update last reviewed date on transition architecture

source/manual/alerts/app-healthcheck-failed.html.md
The page isn't very helpful, but as healthchecks are so varied it's hard to imagine what would be better.
=> Update last reviewed date of healthcheck alert

source/manual/kibana.html.md
Tried them all.  The publishing API timeouts query didn't give any results, but maybe there just weren't any timeouts in the time period I checked.
=> Update last reviewed date of useful Kibana queries

source/manual/alerts/high-priority-tests.html.md
[Trello Card](https://trello.com/c/ufIErt2Y/103-👻-smokey-loop-process-sometimes-dies-in-production-because-phantom-js-segfaults)
=> Add smokey-loop process dying in high priority docs

source/manual/alerts/aws-ses-email-quota.html.md, source/manual/alerts/fastly-error-rate.html.md, source/manual/alerts/mysql-xtrabackups-to-s3.html.md, source/manual/attachments.html.md, source/manual/howto-find-hardcoded-markup-govspeak.html.md
This updates various docs pages which were out of date.
=> Update various docs

source/manual/raising-issues-with-reliability-engineering.html.md
This has been updated to reflect the higher emphasis on Zendesk tickets
in the process than I had prreviously realised.
=> Update RE documentation to not discourage Zendesk tickets

source/manual/manage-email-subscribers.html.md
=> Clarify what the admin interface is, and mention drug alerts

source/manual/deploy-fixes-for-a-security-vulnerability.html.md
Review and update `review_in` date.
=> Review-deploy-fixes-for-a-security-vulnerability

source/manual/debian-packaging.html.md
- Platform health have asked for improved guide-lines on package
building for GOV.UK.
- These changes are based on the recent addition of govuk-python custom
build packages and repository
Solo @schmie
=> Extension of Debian packaging documentation

source/manual/rename-a-country.html.md
Based on notes from @steventux
=> Add instructions to rename a country

source/manual/data-gov-uk-deployment.html.md
https://trello.com/c/3r6gUCTG/405-rewrite-the-dgu-developer-docs
=> Fix link in DGU deployment manual

source/manual/data-gov-uk-monitoring.html.md
https://trello.com/c/3r6gUCTG/405-rewrite-the-dgu-developer-docs
=> Fix CKAN link in monitoring docs

source/manual/alerts/aws-ses-email-quota.html.md
* Remove Licensing from list of applications that use SES (now uses Notify).
* Add information about what each application uses SES for.
=> Update SES account usage information

source/manual/rename-a-country.html.md
Country name changes need to be updated in smart-answers as well, as per: https://github.com/alphagov/smart-answers/pull/3567.
=> Add smart answers instructions to rename a country

source/manual/data-gov-uk-architecture.html.md
https://trello.com/c/3r6gUCTG/405-rewrite-the-dgu-developer-docs
=> Add DGU legacy sudomains/services to the arch doc

source/manual/alerts/aws-cache-cpu.html.md, source/manual/alerts/aws-cache-memory.html.md, source/manual/alerts/aws-rds-cpu.html.md, source/manual/alerts/aws-rds-memory.html.md, source/manual/alerts/aws-rds-storage.html.md
- We have introduced checks to AWS RDS and AWS ElasticCache. This change
covers the URL link embedded in the check URL.
https://trello.com/c/C7SY8edZ/1123-monitor-rds-and-elasticache-in-aws-and-alert-icinga
Solo: @suthagarht
=> AWS Monitoring via Icinga

source/manual/data-gov-uk-architecture.html.md
https://trello.com/c/3r6gUCTG/405-rewrite-the-dgu-developer-docs
=> Move legislation redirect into GOV.UK Transition

source/manual/ab-testing.html.md, source/manual/access-ci.html.md, source/manual/github-unavailable.html.md, source/manual/howto-merge-a-pull-request-from-an-external-contributor.html.md, source/manual/howto-switch-off-app.html.md, source/manual/restart-application.html.md, source/manual/running-rake-tasks.html.md
This reviews some of the overdue pages. See commits for details.
=> Review overdue pages

app/page_review.rb, source/manual/architecture.html.md, source/manual/before-you-start.html.md, source/manual/docs-style-guide.html.md, source/manual/incident-management-guidance.html.md, source/manual/incident-reports.html.md, source/manual/incident-what-to-do.html.md, source/manual/monitor-docs-traffic.html.md, source/manual/review-page.html.md, source/manual/welcome-to-2nd-line.html.md, source/manual/where-to-find-what.html.md, source/manual/working-on-2nd-line.html.md
Also fix the Slack URL in the footer.
=> Fix ownership for pages

data/applications.yml
This app will be built this quarter.
https://trello.com/c/CPWJzL9y/5-create-skeleton-rails-app
=> Add content-publisher application to docs

source/manual/howto-ssh-to-machines-in-aws.html.md
=> Review 'SSH into AWS machines'

source/manual/environments.html.md
Still correct.  But hopefully won't be by the end of the quarter!
=> Review 'GOV.UK's environments'

source/manual/setting-up-new-rails-app.html.md
https://trello.com/c/CPWJzL9y/5-create-skeleton-rails-app
The instructions for creating a rails app are now explicit in this
document, as using the previous automated scripts proved to be to
brittle due to rails changing over time.
Setting up a rails app involves lots of interacting services. Rather
than documenting the processes here, we've made an effort to improve the
surrounding docs and link to them from here.
=> Rewrite Setting Up A New App

source/manual/dns.html.md
Recently we added a new application and found we needed changes in these
terraform repositories to get our DNS working. These docs aren't comprehensive
but should point people in the right direction.
=> Add some docs for making changes to internal DNS

source/manual/ruby.html.md
Updates a GitHub enterprise url and point two specific sections in two others.
=> Update URLs on Ruby manual

source/apps.html.md.erb
=> Remove outdated sentence from apps

source/manual/concept-of-stacks.html.md, source/manual/govuk-in-aws.html.md, source/manual/howto-backup-and-restore-in-aws-rds.html.md
These look fine to me, although I don't have good knowledge of AWS, they will get reviewed fairly regularly since the `review_in` is set to `1 month`.
=> Update out of date docs related to AWS

source/manual/patching-jenkins.html.md
=> Review Jenkins patching doc

source/manual/cant-connect-to-elasticsearch.html.md
I've run this recently, all looks fine to me. Just updating the last updated date.
=> Review can't connect to Elasticsearch docs

source/manual/manage-sign-on-accounts.html.md
All looks fine to me. Just updating the last updated date.
=> Update last updated date for signon account docs

source/manual/content-preview.html.md, source/manual/debian-packaging.html.md, source/manual/deploying.html.md, source/manual/elasticsearch-dumps.html.md, source/manual/jenkins-ci.html.md, source/manual/make-a-new-document-type-available-to-search.html.md, source/manual/mongodb.html.md, source/manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html.md, source/manual/redirect-routes.html.md, source/manual/restore-from-offsite-backups.html.md, source/manual/retiring-an-application.html.md, source/manual/rummager-traffic-replay.html.md, source/manual/send-test-email.html.md
This updates various documentation pages related to 2nd line which are currently out of date. There aren't many changes as it mostly seems up to date and correct.
=> Update various out of date 2nd line docs

source/manual/alerts/high-memory-for-application.html.md, source/manual/alerts/high-memory-for-mapit.html.md
This is typically being caused by zombie processes from a failed soft restart of the application.
=> Add specific docs for mapit high memory

source/manual/rename-a-country.html.md
I've just worked through the process for Gambia -> The Gambia and spotted some areas for improvement.
=> Clarify rename-a-country docs

source/manual/brakeman.html.md
It's a new tool we're going to be using, this isn't meant to be comprehensive but it should be enough to get started as we learn the best way of using this tool.
[Trello Card](https://trello.com/c/JyrOAef3/363-fix-sql-injection-vulnerabilities-in-govuk-applications)
=> Add some initial docs about Brakeman

source/manual/github-unavailable.html.md
I bumped the date but not the month last time I reviewed this
=> Bump review date

source/manual/postgresql-advisory-locks.html.md
[Trello card](https://trello.com/c/zcbWIyoF/390-add-advisory-locking-to-the-dev-docks)
=> Document which apps use advisory locks

source/manual/pgbouncer.html.md
I'll add to this page as we get closer to the switch.
---
[Trello card](https://trello.com/c/BosbZ9n9/336-investigate-postgres-connection-pooling)
=> Add a manual page on pgbouncer

source/manual/data-gov-uk-operations.html.md, source/manual/data-gov-uk-troubleshooting.html.md
* Makes the full re-sync docs clearer (including specifying which machine to run this on)
* Adds a troubleshooting section with some common diagnostic tasks
=> Update DGU documentation

source/manual/add-a-new-document-type.html.md, source/manual/emergency-publishing.html.md, source/manual/fix-blank-finder-filter-options.html.md, source/manual/howto-remove-change-note-from-whitehall.html.md, source/manual/publishing-e2e-tests.html.md, source/manual/restore-from-offsite-backups.html.md, source/manual/transition-a-site.html.md, source/manual/who-do-i-ask-for-support.html.md
Mostly bumps the last reviewed date and makes some updates to aid readability.
=> Update some docs

data/applications.yml, data/dashboard.yml
This is a new app we're building.
[Trello Card](https://trello.com/c/qJONbAdR/411-make-and-deploy-a-new-basic-non-rails-app)
=> Add cache-clearing-service

data/applications.yml, source/manual/data-gov-uk-deployment.html.md
This is by no means comprehensive, but it does at least make them more public and less hidden.
[Trello Card](https://trello.com/c/YI7T7rfM/106-review-and-understand-datagovukinfrastructure-repo)
=> Add some words about datagovuk infrastructure and cf_scripts

source/manual/data-gov-uk-monitoring.html.md, source/manual/data-gov-uk-supporting-ckan.html.md
This wasn't documented anywhere and it's quite important that we know how to manage CKAN..
=> Add more information on managing Bytemark CKAN servers

source/manual/data-gov-uk-monitoring.html.md
Trello card: https://trello.com/c/tMxktv9p/440-add-an-alert-for-significant-data-size-changes-in-dgu-elasticsearch
=> Add reference to new DGU Elasticsearch monitoring app

source/manual/cache-flush.html.md
This commit fixes some formatting issues.
=> Fix cache flush documentation

source/manual/before-you-start.html.md
This commit adds a link to the CI Icinga as well as making a few tweaks.
=> Update before you start on 2nd line

source/manual/govuk-in-aws.html.md
This commit adds information about PostgreSQL database splitting and makes some other tweaks.
=> Update GOV.UK in AWS

source/manual/upgrade-rails.html.md
This commit adds a missing link.
=> Update upgrade rails

source/manual/rebooting-machines.html.md
This commit fixes a number of formatting issues, and groups all Carrenza-specific sections together, marking them as such.
=> Update rebooting machines docs

source/manual/deploy-puppet.html.md
This commit makes some formatting tweaks.
=> Update deploy puppet docs

source/manual/deploy-fixes-for-a-security-vulnerability.html.md
This commit makes some formatting tweaks.
=> Update deploy fixes for a security vulnerability

source/manual/ssh-from-vm.html.md
This commit fixes a broken link.
=> Update SSH from VM docs

source/manual/adding-disks-in-vcloud.html.md
This commit clarifies that this manual page only applies to Carrenza environments. It also makes some formatting tweaks.
=> Update adding disks in vCloud

source/manual/replicate-app-data-locally.html.md
This commit makes some formatting tweaks.
=> Update replicate data docs

source/manual/setting-up-new-rails-app.html.md
This commit makes some formatting tweaks.
=> Update setting up a new rails app docs

data/dictionary.yml
Make capitalisation consistent.
=> Update the dictionary

source/manual/howto-update-pingdom-ip-ranges.html.md
This commit makes some formatting tweaks and fixes broken links.
=> Update Pingdom IP docs

source/manual/changing-organisation-slug.html.md
This commit makes some formatting tweaks and numbers the heading so that the note makes more sense.
=> Update changing organisation slug docs

source/manual/editing-an-existing-route.html.md
This commit adds instructions for AWS.
=> Update edit an existing route docs

source/manual/check-for-gone-route.html.md
This commit adds instructions for AWS.
=> Update check for a gone route docs

source/manual/redirect-routes.html.md
This commit adds instructions for AWS.
=> Update redirect routes docs

source/manual/github-unavailable.html.md
This commit adds AWS instructions.
=> Update GitHub unavailable docs

source/manual/clone-mysql-slave.html.md
This commit adds a note to clarify that this process is only applicable in Carrenza.
=> Update clone MySQL slave docs

source/manual/data-gov-uk-supporting-ckan.html.md
We've recently been having to use these docs for some things and noticed some of it was out of date.
[Trello Card](https://trello.com/c/GFsSiRgM/446-find-out-why-this-harvester-isnt-working-and-fix-it-%F0%9F%8D%90-portunity)
=> Improve docs about supporting CKAN

source/manual/alerts/clamav-definitions-out-of-date.html.md
asset-master-1 no longer does virus scanning
=> Recommend checking the clamav version on backend-1

source/manual/cache-flush.html.md
See https://github.com/alphagov/cache-clearing-service/pull/6 and https://github.com/alphagov/fabric-scripts/pull/271
https://trello.com/c/f8U7EfUh/427-make-the-new-cache-clearing-app-invalidate-cache-in-varnish
=> Update varnish clearing instructions

source/manual/data-gov-uk-troubleshooting.html.md
We don't need to be double-n-up
=> Spell production correctly

source/manual/data-gov-uk-architecture.html.md
This looks like a cut and paste mistake to me.
=> Remove broken link for CKAN

source/manual/data-gov-uk-backups.html.md
Trello: https://trello.com/c/RBXYBuml/504-identify-and-document-backups-on-bytemark-for-dgu-ckan
=> Add docs on data.gov.uk backups

source/manual/use-aws-xray-to-trace-app-requests.html.md
This was left out of the last PR by accident.
Trello: https://trello.com/c/CN2i0fxG/514-write-documentation-on-aws-x-ray
=> Add information about AWS X-Ray daemon

source/manual/get-started.html.md
The tech lead on each team should go through the overview slides with
new joiners. Add this in to the get started guide as a first step. We might want to actually bring this in to the docs wholesale and this might not be the best place for it, but it's a start.
Also tidy up some empty whitespace and update review date.
=> Add note to get started to ask tech lead to go through overview

source/manual/deploying-terraform.html.md
Preview: https://govuk-developer-docs-pr-1271.herokuapp.com/manual/deploying-terraform.html
=> Improve "Deploy AWS infrastructure with Terraform"

source/manual/alerts/postgresql-replication-too-far-behind.html.md, source/manual/postgresql.html.md
Things I'd like to document:
---
[Trello card](https://trello.com/c/CcvoQvJx/540-document-wal-e-backup-restore-process)
=> [WIP] More WAL-E documentation

source/manual/environments.html.md
Documentation has been reviewed and is correct as of 12-10-2018
=> Document reviewed for environments

source/manual/aws-console-access.html.md, source/manual/set-up-aws-account.html.md
I used the wrong key (or the tech-docs-gem does).
cc @rubenarakelyan @stephenharker
=> Fix AWS page redirects

source/manual/cdn.html.md
We now have the CDN available for integration.
=> Update CDN docs

source/manual/alerts/check-mirror-repos.html.md
Docs entry describing what Check Mirror Repositories alert is about.
=> Add manual entry for Check Mirror Repositories alert

source/manual/architecture.html.md
https://govuk-developer-docs-pr-1270.herokuapp.com/manual/architecture.html
=> Update architecture.html.md to add new Logical architecture diagram

source/manual/query-cdn-logs.html.md
We now have a CDN in integration.
=> Update CDN log querying docs

source/manual/ab-testing.html.md
We now also have a CDN for integration.
=> Update A/B testing docs

source/manual/github.html.md.erb
Github processes are still the same and have not changed.
=> updates to last review time

source/manual/data-gov-uk-troubleshooting.html.md
There isn't currently any documentation on how Celery works, and although this isn't comprehensive, it's a start.
[Trello Card](https://trello.com/c/qhBkgOZ3/532-find-out-why-the-map-preview-option-is-not-displayed-on-this-dataset)
=> Add some notes about troubleshooting data.gov.uk celery

source/manual/tools.html.md
Fixes broken links to Grafana dashboards.
=> Fixes broken links

source/manual/error-reporting.html.md
Reviewed and updated `last_reviewed_on` date
=> Reviews error reporting page

source/manual/lint-ruby-code.html.md
Reviewed and updated `last_reviewed_on` date
=> Reviews linting with govuk linter

source/manual/readmes.html.md
Reviewed and updated `last_reviewed_on date`
=> Reviews readmes

source/manual/nfs-errors-vm.html.md
This commit updates the section on issues between the developer VM and the VPN. It removes the old VPN details and adds information about bypassing NFS.
=> Update information on using the dev VM with the VPN

source/manual/alerts/email-alerts.html.md
=> Update email alerts docs

source/manual/howto-update-pingdom-ip-ranges.html.md
This commit adds information on how to deploy your changes and also makes some minor tweaks.
=> Update docs on Pingdom IP changes

source/manual/incident-what-to-do.html.md
No updates to content - just updated the review at date.
=> Review incident-what-to-do

source/manual/incident-reports.html.md
No updates apart from to the review date - this all still looks relevant.
=> Review for incident-reports

source/manual/heroku.html.md
This is still correct and relevant, so I'm just updating the 
`last_reviewed_on` date.
=> Review `source/manual/heroku.html.md`

source/manual/postgresql.html.md
This may become not relevant shortly, so I set it to be reviewed in 2 months.
=> Review and update `source/manual/postgresql.html.md`

source/manual/create-a-gpg-key.html.md
Reviewed and updated `last-reviewed-on` date
=> Review create-a-gpg-key

source/manual/ab-testing.html.md
After feedback from getting the last test live, it's worth adding a little bit more context about the things you need to choose before putting a test live.
[Lovely preview](https://github.com/alphagov/govuk-developer-docs/blob/d8b56b78d04bf9ee55a9e364dca3e4735cd0ed5b/source/manual/ab-testing.html.md#3-how-to-set-up-an-ab-test) 👈
=> Add context to AB testing

source/manual/tools.html.md
Putting this here in case future 2nd liners don't know the URL for Incinga in AWS
=> Add URLs for Icinga in all environments

source/manual/who-do-i-ask-for-support.html.md
We tend not to have Tech Leads for objectives at the moment so
changed this to be a Lead Dev on the programme.
=> Update docs about who to ask for support

source/manual/data-gov-uk-architecture.html.md, source/manual/data-gov-uk-backups.html.md, source/manual/data-gov-uk-deployment.html.md, source/manual/data-gov-uk-hacks.html.md, source/manual/data-gov-uk-map-previews.html.md, source/manual/data-gov-uk-migrating-ckan.html.md, source/manual/data-gov-uk-monitoring.html.md, source/manual/data-gov-uk-operations.html.md, source/manual/data-gov-uk-supporting-ckan.html.md, source/manual/data-gov-uk-troubleshooting.html.md
These pages will all change once the CKAN upgrade is complete.  Extending the review period to reflect this.
=> Extend the review period for DGU documentation

source/manual/add-a-new-document-type.html.md, source/manual/adding-disks-in-vcloud.html.md, source/manual/change-base-path-in-specialist-publisher.html.md, source/manual/changing-organisation-slug.html.md, source/manual/clone-mysql-slave.html.md, source/manual/create-a-gpg-key.html.md, source/manual/debian-packaging.html.md, source/manual/deploy-puppet.html.md, source/manual/dns.html.md, source/manual/elasticsearch-dumps.html.md, source/manual/emergency-publishing.html.md, source/manual/encrypted-hiera-data.html.md, source/manual/fetching-packages.html.md, source/manual/get-started.html.md, source/manual/howto-manually-remove-assets.html.md, source/manual/howto-update-pingdom-ip-ranges.html.md, source/manual/kibana.html.md, source/manual/move-apps-between-servers.html.md, source/manual/nagios-nrpe-connection-failures.html.md, source/manual/publishing-a-ruby-gem.html.md, source/manual/rabbitmq.html.md, source/manual/rebooting-machines.html.md, source/manual/rename-a-country.html.md, source/manual/reprovision.html.md, source/manual/restore-from-offsite-backups.html.md, source/manual/stop-all-email-subscription-sending.html.md, source/manual/transition-a-site.html.md, source/manual/upgrading-mysql.html.md, source/manual/use-aws-xray-to-trace-app-requests.html.md
This commit is just to use the same style in all the notes. We had notes in many different styles, so I picked the one that seemed used most often and applied it everywhere. As I haven't reviewed the content of the docs, I left `last_reviewed_on` unchanged.
=> Make notes consistent by using same style

source/manual/set-up-aws-account.html.md
I noticed when following this guide that there are four groups, and not three.
=> Corrects minor typo

source/manual/emergency-publishing.html.md
This was after using it for the publishing drill.
=> Bump review date on Emergency Banner page

source/manual/graphite-and-deployment-dashboards.html.md
The text looks OK and I tested the links
=> Review change for graphite documentation

source/manual/data-gov-uk-migrating-ckan.html.md
Updating the instructions for migrating data from CKAN on Bytemark to CKAN on AWS.
Trello card: https://trello.com/c/IOJpy2to/126-document-process-for-getting-postgres-database-dump-onto-aws
=> Update instructions for migrating CKAN data

source/manual/frontend-architecture.html.md
A small update and bump the review date
=> Update frontend-architecture docs

source/manual/howto-replace-an-assets-file.html.md
Also make it a bit less confusing, the replacement is probably
the same extension as the original.
=> Fix formatting issues & replacement instructions

source/manual/reprovision.html.md
Makes some tweaks and clarifications.
=> Update machine re-provisioning docs

source/manual/data-gov-uk-architecture.html.md, source/manual/data-gov-uk-backups.html.md, source/manual/data-gov-uk-deployment.html.md, source/manual/data-gov-uk-hacks.html.md, source/manual/data-gov-uk-map-previews.html.md, source/manual/data-gov-uk-migrating-ckan.html.md, source/manual/data-gov-uk-monitoring.html.md, source/manual/data-gov-uk-operations.html.md, source/manual/data-gov-uk-supporting-ckan.html.md, source/manual/data-gov-uk-troubleshooting.html.md
Push for another 8 weeks until the new version is released.
=> Review all data.gov.uk docs

source/manual/rename-a-country.html.md
Tidied up layout and made PR links hyperlinks.
=> Review rename a country doc

source/manual/use-terraboard-to-monitor-terraform-state.html.md
Bump the date and make it expire after 6 months.
=> Update Terraboard docs

source/manual/assets.html.md
Update to show that all environments now use the CDN.
=> Update assets docs

source/manual/rotate-offsite-backup-gpg-keys.html.md
Make the note nicer and bump the date. Also make it expire quicker since we're working on backups.
=> Update offsite backups key rotation docs

source/manual/add-an-icinga-passive-check.html.md
=> Update Icinga passive check docs

source/manual/elasticsearch-dumps.html.md
Bump the date and make it expire in 3 months since we're working on this.
=> Update Elasticsearch dumps docs

source/manual/govuk-in-aws.html.md
Bump the date and make it expire later.
=> Update AWS docs

app/app_docs.rb, data/applications.yml, source/templates/application_template.html.md.erb
=> Simplify code for application pages

source/manual/alerts/signon-healthcheck-not-ok.html.md
https://trello.com/c/pvSF3FTe/5-rotate-gds-sso-tokens
=> Add alert manual about rotating tokens in signon

source/manual/aws-cli-access.html.md
This is needed for the `govukcli` tool.
=> Add `mfa_serial` to `gds` profile too

source/manual/business-readiness-update-content.html.md
https://github.com/alphagov/govuk-app-deployment-secrets/pull/38
=> Update business readiness finder release instructions

data/applications.yml, source/manual/pact-broker.html.md
=> Update Pact Broker docs

source/manual/data-gov-uk-monitoring.html.md
It was mildly annoying me to have to copy/paste the URL.
=> Link to sidekiq UI directly

data/applications.yml
[Trello card](https://trello.com/c/xNNHprUZ/20-set-up-new-search-api-app)
=> Add search-api, owned by govuk-search-perf

source/manual/data-gov-uk-deployment.html.md
These seem to work well to deploy the publish app.
=> Add a note about the DGU deploy scripts

source/manual/deploying-terraform.html.md
=> Fix spelling mistake

source/manual/which-gem-to-use.html.md
=> Specify that apps should use govuk_sidekiq and govuk_message_queue_consumer

source/manual/data-gov-uk-2nd-line.html.md
Trello card: https://trello.com/c/KkaFHYpE/749-add-a-new-schema-to-datagovuk
Related PR: https://github.com/alphagov/ckanext-datagovuk/pull/139
=> Document how to add schema vocabulary definitions to ckanext-datagovuk

source/manual/content-store-times-out.html.md, source/manual/dns.html.md, source/manual/email-notifications-how-they-work.html.md, source/manual/gds-hubot.html.md, source/manual/move-apps-between-servers.html.md, source/manual/mysql.html.md, source/manual/packer-vagrant-image-creation.html.md, source/manual/pingdom-bouncer-canary-check.html.md, source/manual/post-a-statuspage-message.html.md, source/manual/postgresql.html.md, source/manual/ram-vm.html.md, source/manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html.md, source/manual/resync-mongo-db.html.md, source/manual/resync-postgres-standby.html.md, source/manual/send-test-email.html.md
Reviews documents for February 2nd 2019.
=> Document review

source/manual/data-gov-uk-2nd-line.html.md
The content is not currently very readable. This should fix this issue
and display the content more clearly.
=> Fix display issues in data gov uk 2nd line

source/manual/alerts/whitehall-app-healthcheck-not-ok.html.md
Just used this to troubleshoot an icinga alert and all worked as described.
=> Doc review

source/manual/data-gov-uk-2nd-line.html.md
These two resources have been invaluable during the last week.
=> Add links to CKAN user list and revision log

source/manual/before-you-start.html.md
Updated information on how to get a Zendesk account with appropriate access.
=> Update Zendesk information in before-you-start

source/manual/whitelist-site-in-transition.html.md
The link to whitelisted hosts was broken, this fixes that 😄
=> Fixes link to redirection whitelist

source/manual/hmrc-paye-files.html.md
This previously returned an error, unless you were in the correct directory
=> Fix instructions for HMRC assets

source/manual/alerts/gor.html.md, source/manual/rummager-traffic-replay.html.md
The app is now called goreplay in the repo.
=> Update gor docs

source/manual/adding-disks-in-vcloud.html.md, source/manual/connect-to-vcloud-director.html.md, source/manual/on-call.html.md, source/manual/vpn.html.md
This commit adds documentation on how to connect to the Carrenza vCloud Director using the VPN.
=> Add docs on connecting to Carrenza vCloud

source/manual/brakeman.html.md
I've also increased the review in time to 12 months because I don't think it's likely to go out of date quickly.
=> Update last reviewed date for Brakeman

source/manual/data-gov-uk-2nd-line.html.md
This came up in a ticket but the answer was not documented.
=> Add Dataset Analytics requests to 2nd line FAQs

source/manual/naming.html.md
It's probably good for the next 12 months. Added a sentence to make clear that these rules should be broken if there's a good reason to.
=> Bump "Name a new application or gem"

source/manual/development-pipeline.html.md
We've been talking about replatforming GOV.UK and what that would look like for the development experience. This is an attempt to document what  our current pipeline looks like, so we're all on the same page.
=> Describe the GOV.UK development/deployment pipeline

source/manual/alerts/content-performance-manager-app-healthcheck-not-ok.html.md
For the Content Data App (Data Warehouse).
=> Add rake task to repopulate Monthly Agggregations

source/manual/elasticsearch-dumps.html.md
Trello card: https://trello.com/c/CWsNG8Ou/63-documentation-for-backup-restore
=> Add information on restoring AWS Elasticsearch snapshots

source/manual/rename-a-country.html.md
Trello card: https://trello.com/c/jRoXhf6T/805-update-docs-on-renaming-a-country
=> Update rename a country

source/manual/howto-manually-remove-assets.html.md, source/manual/pgbouncer.html.md, source/manual/postgresql-advisory-locks.html.md
We can use the cache clearing instructions.
=> Update removal of assets instructions

source/manual/alerts/duplicate-ssh-host-keys.html.md
This whole check should be removable when carrenza is gone.
=> Still valid.

source/manual/alerts/high-zombie-procs.html.md
The date isn't set to today to help stagger the reviews in the future.
=> The document is still valid.

source/manual/alerts/root-filesystem-is-readonly.html.md
The date is off set to stagger future reviews.
=> Added additional context

source/manual/howto-ssh-to-machines-in-aws.html.md
Everything seems to be still up to date.
=> Confirm review date for howto-ssh-to-machines-in-aws

source/manual/components.html.md
Removes references to components in static.
=> Update the component system page

source/manual/alerts/user-monitor.html.md
Removed some extra, unneeded, bonus words.
=> Reviewed and tidied up

source/manual/alerts/low-space-for-automongodbbackup.html.md
Fixed minor type and made the script url into a hyperlink.
=> Reviewed and everything looks upto date.

source/manual/fetching-packages.html.md
The date is slightly staggered due to a big influx of docs to be
reviewed around this time.
=> Reviewed and looks upto date.

source/manual/setting-up-new-rails-app.html.md
=> Update docs for setting up a new rails app

source/manual/add-a-secret-to-a-concourse-pipeline.html.md, source/manual/concourse.html.md, source/manual/create-a-concourse-pipeline.html.md
Split the how-to from the learning docs, and add docs on applying config.
=> Update Concourse docs

source/manual/ssh-from-vm.html.md
Added some minor details and bumped the last reviewed date.
=> Update SSH from VM doc

source/manual/alerts/search-spelling-suggestions.html.md
This looks good. Setting date to 2019-02-28 to stagger the next check dates.
=> Update 'search spelling suggestions'

source/manual/alerts/ntp-drift-too-high.html.md
=> Update doc for 'ntp drift too high'

source/manual/alerts/rummager-queue-latency.html.md
=> Update doc for rummager queue latency runbook

source/manual/reindex-elasticsearch.html.md
Added additional bits of info on approx reindexing time and
changes to the govuk_document_types gem.
=> Update reindexing elasticsearch docs

source/manual/business-readiness-update-content.html.md
We need to republish the finder content item when we make changes to it.
=> Update business readiness finder doc

source/manual/add-deployment-dashboard.html.md
I removed some text specific to the deployment, as they are now application dashboards.
=> Updated doc on app dashboards

data/applications.yml
This commit updates all the frontend and router apps now they have been migrated to AWS.
=> Update hosting location for frontend apps

source/manual/alerts/fastly-error-rate.html.md, source/manual/alerts/free-memory-warning-on-backend.html.md, source/manual/alerts/high-disk-time.html.md, source/manual/alerts/logs-are-not-being-received-from-the-cdn.html.md, source/manual/alerts/postgresql-replication-too-far-behind.html.md, source/manual/alerts/reboot-required-by-apt.html.md, source/manual/alerts/ruby-version.html.md, source/manual/alerts/rummager-index-size-change.html.md, source/manual/alerts/signon-app-healthcheck-not-ok.html.md, source/manual/editing-an-existing-route.html.md, source/manual/emergency-publishing.html.md, source/manual/keeping-software-current.html.md, source/manual/redirect-routes.html.md
Add jitter to the last reviewed on dates so they don't all show up in the same week next time
=> Review many docs

source/manual/data-gov-uk-troubleshooting.html.md
It seems to be crashing fairly regularly so I've added a section outlining what to do in that case to get harvesting up and running again.
[Trello Card](https://trello.com/c/07jTJBX5/823-make-ckan-harvesting-restart-when-it-fails)
=> Add information about how to restart CKAN harvesters

source/manual/data-gov-uk-troubleshooting.html.md
We don't use celery anymore :-).
=> Remove celery doc for DGU

source/manual/alerts/nginx-requests-too-low.html.md
Added a link to a related dashboard and bumped the date.
=> Updated doc on Nginx requests too low

source/manual/vpn.html.md
- Skyscape is now known as UKCloud.
- Date matches the the other VPN page reviewed today.
=> Reviewed page for VPN details

source/manual/alerts/aws-rds-memory.html.md, source/manual/alerts/aws-rds-storage.html.md, source/manual/alerts/aws-ses-email-quota.html.md, source/manual/alerts/clamav-definitions-out-of-date.html.md, source/manual/alerts/elasticsearch-cluster-health.html.md, source/manual/alerts/mysql-xtrabackups-to-s3.html.md, source/manual/alerts/nginx-high-conn-writing-upstream-indicator-check.html.md, source/manual/alerts/pingdom-search-check.html.md, source/manual/alerts/recreate-a-mongo-instance-in-aws.html.md, source/manual/alerts/varnish-port-not-responding.html.md, source/manual/fall-back-to-mirror.html.md, source/manual/howto-remove-change-note-from-whitehall.html.md, source/manual/logging.html.md, source/manual/restore-from-offsite-backups.html.md, source/manual/uptime-metrics.html.md
See individual commits for more details. Generally the docs are up to date and these are only stylistic changes.
=> Review some docs that are overdue

source/manual/alerts/content-performance-manager-app-healthcheck-not-ok.html.md
For the Content Data API (Data Warehouse).
=> Add info on rake task to refresh materialized view

source/manual/alerts/prolonged-gc-collection-times-check.html.md, source/manual/alerts/publisher-app-healthcheck-not-ok.html.md, source/manual/alerts/unicorn-herder.html.md, source/manual/cache-flush.html.md, source/manual/changing-organisation-slug.html.md, source/manual/check-for-gone-route.html.md, source/manual/fall-back-to-mirror.html.md, source/manual/logging.html.md, source/manual/restore-from-offsite-backups.html.md, source/manual/retiring-an-application.html.md
This reviews some of the docs that are currently out of date, I've introduced some different review dates to try and avoid these all needing review again at the same time. See individual commits for more details.
=> Review various due docs

source/manual/transition-architecture.html.md
This all looks up to date. I've also increased the review length to 6 months.
=> Review transition-architecture

source/manual/development-disk-space.html.md, source/manual/replicate-app-data-locally.html.md
See individual commits for more details.
Please feel free to suggest changes to give more context, be more/less specific or correct grammar, stylistic errors. Let me know if something needs rephrasing.
=> VM setup troubleshooting related to data replication and low disc space

source/manual/alerts/aws-cache-cpu.html.md, source/manual/alerts/aws-cache-memory.html.md, source/manual/alerts/aws-rds-cpu.html.md
=> Review for AWS related docs

source/manual/changing-organisation-slug.html.md
=> Fix year in changing-organisation-slug review date

source/manual/business-readiness-update-content.html.md
We'll use this, in addition to dropping messages into `#govuk-2ndline`, to update on the state of the migration.
---
[Trello card](https://trello.com/c/8B0HvaDY/100-prepare-some-documentation-while-the-migration-is-happening)
=> What's up with search?

source/apis/search/add-new-fields-or-document-types.html.md.erb, source/apis/search/content.html.md.erb, source/apis/search/faceted-search.html.md.erb
[Trello card](https://trello.com/c/MvemOpZV/93-update-medium-priority-documentation)
=> Point external rummager documentation to search-api

source/manual/business-readiness-publish-changes.html.md, source/manual/business-readiness-update-content.html.md
[Trello card](https://trello.com/c/roOVfL9T/98-make-sure-emails-triggered-by-the-business-readiness-finder-will-continue-to-work)
=> Rummager is no longer involved in updating the business readiness finder

source/manual/alerts/content-performance-manager-app-healthcheck-not-ok.html.md
Added missing comma's and double quotes around dates.
=> Fix commands for repopulating data in Content Data

source/manual/cache-flush.html.md, source/manual/hmrc-paye-files.html.md, source/manual/howto-manually-remove-assets.html.md
https://github.com/alphagov/cache-clearing-service/pull/102
https://trello.com/c/RASJllyU/916-update-hmrc-paye-tools-cache-clearing-documentation
=> Update docs for clearing cache on assets

source/manual/data-gov-uk-contracts-archive.html.md
We sometimes receive contract take down requests. This is what to do.
[Trello](https://trello.com/c/rgS41p36/929-delete-the-files-from-the-contracts-archive-finder-that-the-mod-has-demanded)
=> Add contract takedown requests

source/manual/change-in-hours-time-period-for-dst.html.md
Set it to be reviewed the day before the clocks next change.
=> Add documentation on changing the Icinga office hours

source/manual/nfs-errors-vm.html.md
Links to the documentation on how to fix this issue without rebooting your machine.
=> Update NFS errors doc

source/manual/data-gov-uk-contracts-archive.html.md
This was a little confusing. Substitute the actual command used with the
elastic IP that's currently attached to the machine.
=> Correct ssh command for contracts archive

source/manual/data-gov-uk-contracts-archive.html.md
Add the current IP address and also clarify how to find the currently
assigned address.
=> Clarify the contracts finder elastic IP

data/applications.yml
2ndline were unaware that this service existed.
=> Add search-analytics as a service we run

source/manual/business-readiness-publish-changes.html.md
Trello: https://trello.com/c/65iA9DSO/36-add-a-way-to-publish-the-finder
=> Adds documentation on new task for publishing business finder

source/manual/publishing-a-facet-group.html.md
https://trello.com/c/KYvbTPDh/15-document-how-to-import-a-facet-group-and-tag-data-by-csv-in-content-tagger
I've split this commit out from https://github.com/alphagov/govuk-developer-docs/pull/1658
This document explains what a facet group is and how to draft and publish a facet group.
=> Document how to publish a facet group

source/manual/set-up-aws-account.html.md
Wasn't too clear whether or not I needed to "Request user access" (does my user exist yet?) or "Request an account" (is this for me or for creating a new test/prod environment?)
Have added a line of explanation to make it clearer.
=> explain "Request an AWS account" step

source/manual/publishing-a-facet-group.html.md
This was preventing the docs from building.
=> Fix incorrect date

source/manual/adding-disks-in-vcloud.html.md, source/manual/alerts/postgresql-s3-backups.html.md, source/manual/generate-csr.html.md, source/manual/renew-a-tls-certificate.html.md
Bump review date of still current articles
=> Bump review date of still current articles

source/manual/before-you-start.html.md, source/manual/hmrc-paye-files.html.md, source/manual/managing-product-support-tickets-zendesk.html.md
HMRC PAYE doc update gives context on time-sensitive nature of the request.
Zendesk doc update will help 2nd line manage the queue better (hopefully).
Before you start: added a link to the Zendesk guidance.
=> Hongoose updates to 2nd line docs

source/manual/connect-to-vcloud-director.html.md
This commit changes the instructions for using openconnect to point to the correct password.
=> Update password for openconnect

source/manual/bowl-error.html.md, source/manual/change-base-path-in-specialist-publisher.html.md, source/manual/nfs-errors-vm.html.md, source/manual/replicate-app-data-locally.html.md, source/manual/ssh-config.html.md, source/manual/tools.html.md
Includes review of the following docs:
- Fix NFS errors in VM
- Change a specialist document base path - small change for consistency
- Tools page - added link to Icinga CI alerts
- Fix bundler errors when running bowl
- Replicate application data locally for development
- Set up your SSH configuration
=> Review docs

source/manual/elasticsearch-dumps.html.md
This referred to a page which has been redirected.
=> Review elasticsearch dumps

source/manual/architecture.html.md, source/manual/docs-style-guide.html.md, source/manual/monitor-docs-traffic.html.md, source/manual/review-page.html.md, source/manual/taxonomy.html.md, source/manual/where-to-find-what.html.md
Some pages were owned by individuals who aren't around, or teams which no longer exist.
=> Update page owners

source/manual/taxonomy.html.md
Everyone's tagging to taxons these days
=> Update taxonomy docs

source/manual/search-api-traffic-replay.html.md
[Trello card](https://trello.com/c/QFqYu8XR/656-%F0%9F%92%80-update-rummager-code-and-documentation-to-refer-only-to-search-api-%F0%9F%92%80)
=> Update whitehall search replay task

source/manual/data-gov-uk-operations.html.md
Add line on how to reset password
=> Edit data-gov-uk-operations

source/manual/get-ssh-access.html.md
Fix a link and do the next review in 6 months.
=> Review SSH access to integration docs

source/manual/encrypted-hiera-data.html.md
Make a distinction between new starters getting integration secrets access versus people with production access getting production secrets access.
=> Clarify GPG access to secrets

config/tech-docs.yml, data/applications.yml, source/manual/pgbouncer.html.md
Do not merge until the GitHub repository has been renamed.
=> Rename the Content Performance Manager

source/manual/docs-style-guide.html.md, source/manual/where-to-find-what.html.md
Reviewed two pages, no issues found. Updated the review timer for another 12 months.
=> Reviewing documentation

source/manual/data-gov-uk-contracts-archive.html.md
The snapshot contains some older log files that might be useful.
[Trello](https://trello.com/c/AdWss0Em/1016-enhance-our-understanding-of-logs-and-resilience-of-the-contracts-finder-archive)
=> Add info on contract archive finder snapshot

source/manual/get-started.html.md
Reviewed page, no problems. 
Reset date to 22 May 2019, ready for review in three months time.
=> Review of 'Get Started' manual page.

source/manual/alerts/outstanding-security-updates.html.md
=> Review of 'Outstanding security updates' page.

source/manual/get-started.html.md
The name is all lowercase, so we should be consistent in the docs
=> Correctly style the name 'pip'

source/manual/debug-underperforming-search.html.md
I don't really know what would be useful here
---
[Trello card](https://trello.com/c/GELFAgoC/664-documentation-for-2nd-line-during-a-search-incident-%F0%9F%8D%90)
=> Add some documentation for how to debug underperforming search

source/manual/connect-to-vcloud-director.html.md
Added some more notes and examples to this doc.
=> Update the Connect to vCloud Director instructions

source/manual/pgbouncer.html.md
https://trello.com/c/XJDsLgE6/1006-remove-pgbouncer-in-aws
=> Update pgbouncer docs

source/manual/data-gov-uk-deployment.html.md
Added some information on how to set up an interactive SSH session.
=> Update to DGU deployment doc

source/manual/alerts/aws-lb-healthyhosts.html.md
Documentation for new Icinga check, added here: https://github.com/alphagov/govuk-puppet/pull/9285
=> Add aws-lb-healthyhosts documentation

source/manual/govuk-env-sync.html.md
- This was checked in outdated to test Daniel the manual spaniel in the #re-govuk Slack channel
solo: @schmie
=> Change review date for govuk_env_sync

source/manual/deploying-terraform.html.md
And reformat the paragraph so it's not just one long line.
=> Say what scope the govuk-aws deploy.rb script GitHub token needs

source/manual/upgrade-terraform.html.md
Add instructions to help upgrading Terraform versions in our platform.
=> Add Upgrading Terraform guide

source/manual/nagstamon.html.md
I wasn't clear on what to put into the `CGI URL` field.  Updating to make this explicit.
=> Update instructions for connecting Nagstamon

source/manual/add-translation-whitehall.html.md, source/manual/rename-a-country.html.md
Adds a page about supporting a new locale
=> [WIP] Add translation whitehall

source/manual/data-gov-uk-supporting-ckan.html.md
Added more clarification on cancelling a harvest job which came out of our recent 2ndline shift.
=> Update to the CKAN support doc

source/manual/deploy-puppet.html.md, source/manual/restart-application.html.md, source/manual/running-rake-tasks.html.md
Bumping the review data on reviewed documents.
Also added links to AWS where relevant.
=> 2nd line dev docs review

data/applications.yml
Updating the slack channels used for Content Data and Content Audit Tool to Platform Health
=> Update content-data apps to notify platform health

source/manual/cdn.html.md
We use VCL for caching logic in Fastly. It does lots of different stuff! This adds some docs about it, and a guide for testing.
https://trello.com/c/6P4c8RiN/396
=> Add documentation on Fastly caching logic

source/manual/intro-to-docker.html.md
To help devs who have never used Docker before, this tutorial introduces basic concepts that are worth knowing before using [govuk-docker](https://github.com/alphagov/govuk-docker) itself.
https://trello.com/c/kAGAxXX6
=> Add Docker tutorial

source/manual/cdn.html.md
This addition relates to the following PR:
https://github.com/alphagov/govuk-cdn-config/pull/160
=> Add caching detail

source/manual/remove-redirected-url-from-transition.html.md
[trello](https://trello.com/c/RVP3vVZ3/1113-remove-redirected-urls-from-transition-tool)
=> Add page about removing a URL redirect from Transition

source/manual/frontend-performance.html.md
=> Document our usage of SpeedCurve

source/manual/before-you-start.html.md, source/manual/incident-management-guidance.html.md, source/manual/incident-reports.html.md, source/manual/incident-what-to-do.html.md, source/manual/welcome-to-2nd-line.html.md
Made a few small copy edits as the 2nd line and incident management process itself remains unchanged. The big change is updating the page owner to the new delivery manager for 2nd line and incident management. I'll miss your bark Daniel the Manual Spaniel.
=> 3-month review of 2ndline pages

source/manual/run-ab-test.html.md
https://trello.com/c/JO3Ihzcp/855-set-up-the-es6-a-b-test
=> Add note about the search performance explorer

source/manual/howto-change-a-government-following-an-election.html.md
They're not showing up correctly at the moment. Also capitalise
Publishing API.
=> Fix the layout of the lists on the change government page

source/manual/alerts/ddosdetected.html.md
We have added a new alert to Icinga as part of the work
on the Web Application Firewall (WAF). This doc provides
guidance on the steps that should be taken.
co-authored-by chrisfarms <chris.farmiloe@digital.cabinet-office.gov.uk>
=> Add DDOS Detected Alert Guidance to Docs

source/manual/republishing-content.html.md
Trello: https://trello.com/c/bO9vwRMG
=> Republish an organisation from whitehall

source/manual/transition-a-site.html.md
👉 [Rendered version](https://govuk-developer-docs-f-pr-1893.herokuapp.com/manual/transition-a-site.html#7-point-the-domain-at-us)
=> Add dns config when transitioning a site

source/manual/howto-find-hardcoded-markup-govspeak.html.md
I left the year as 2018 in https://github.com/alphagov/govuk-developer-docs/pull/1895
=> Fix review date for howto

source/manual/data-gov-uk-supporting-ckan.html.md
To enable devs to access the database in order to run queries.
=> Add information for access to ckan database

source/manual/data-gov-uk-supporting-ckan.html.md
There are some fairly commonly used queries which it would be useful to document
[Trello card](https://trello.com/c/7zYOvAGp/1181-add-some-useful-dgu-api-calls-to-the-dev-docs)
=> Add more example CKAN API queries

source/manual/republishing-content.html.md
This page was due to be updated
=> Update republishing content

source/manual/aws-cli-access.html.md
This updates the requirement text and updates the review date.
=> Update the requirements for using AWS CLI

source/manual/email-alert-api-callback-from-notify-fails.html.md
=> Reviewed `Email callbacks from Notify fails`

source/manual/change-base-path-in-specialist-publisher.html.md
- Reviewed the doc
- Updated the markdown for consistency with newer doc styles
=> Update change specialist document base path doc

source/manual/postgresql-backups.html.md
bump review date of postgresql-backups doc
=> bump review date of postgresql-backups doc

source/manual/alerts/user-monitor.html.md, source/manual/debian-packaging.html.md, source/manual/deploying-terraform.html.md, source/manual/dns.html.md, source/manual/environments.html.md, source/manual/jenkins-ci.html.md, source/manual/mongodb.html.md, source/manual/mysql.html.md, source/manual/patching-jenkins.html.md
- Reviewed a number of docs on topics relevant to RE
- Reassigned a number of docs to the #re-govuk Daniel
=> Reviewing and reassigning docs relevant to RE

source/manual/alerts/enhanced-ecommerce.html.md
The rake task and behaviour of this process has changed, so the changes here reflect that.
Related PRs:
- https://github.com/alphagov/govuk-puppet/pull/9479
- https://github.com/alphagov/search-api/pull/1647
Trello: https://trello.com/c/xJP8a5KE
=> Update Ecommerce docs

source/manual/encrypted-hiera-data.html.md
This adds a note about the No key found error.
Co-authored-by: Jon Hallam <jonathanhallam@users.noreply.github.com>
=> Add to troubleshooting section for secrets

source/manual/data-gov-uk-monitoring.html.md
I had difficulty understanding what to do when viewing the sidekiq UI, this should be clearer for anyone else
=> Adds link to other documentation for clarity on steps

source/manual/data-gov-uk-monitoring.html.md
I missed .html at the end of the url
=> Fix missing part of url

source/manual/data-gov-uk-map-previews.html.md
Checked links and added harvesting information to generate WMS map previews.
=> Update WMS map preview doc

source/manual/cdn.html.md
The old way of updating the Firewall is broken at the moment due
to the settings in carrenza having diverged from the code base.
This is a manual method to update the Firewall rules in Carrenza
when Fastly update their list of IP ranges.
=> Add documentation to update Carrenza firewall with new Fastly IPs

source/manual/data-gov-uk-supporting-ckan.html.md
This https://github.com/alphagov/govuk-puppet/pull/9456 needs to be deployed to make `csw` endpoint available to users.
Updates the DGU supporting ckan manual to include useful `csw` information on how to resync `csw` with `ckan`, starting the `csw` server and logs.
https://trello.com/c/kwGqR4pe/1158-update-dev-docs-with-csw-information
=> Add csw to data-gov-uk-supporting-ckan.html.md

source/manual/alerts/data-sync.html.md, source/manual/govuk-env-sync.html.md
The alert provides little information on what to do, this may help
=> Add documentation about what to do with data sync Icinga alerts

vale-lint.sh
This is a proposal to run with `fail-at-the-end` rather than `fail-fast` approach.
=> Iterate through each file all at once rather than once per commit

source/manual/alerts/duplicate-ssh-host-keys.html.md, source/manual/howto-backup-and-restore-in-aws-rds.html.md, source/manual/move-apps-between-servers.html.md
=> Give some docs to RE

source/manual/transition-a-site.html.md
Following a chat with our content team, update the wording.
=> Update wording around HTTPS sites and transition

data/applications.yml
This reverts commit 73ee584c676eddecc75083f5fcc1e4a234d79868, reversing
changes made to b1c7d3ed529be3aac11b2345a7f2d239e09905be.
=> Revert make finder frontend private

source/manual/alerts/datagovuk-publish-healthcheck-not-ok.html.md, source/manual/alerts/fastly-error-rate.html.md, source/manual/alerts/high-disk-time.html.md, source/manual/alerts/high-memory-for-application.html.md, source/manual/alerts/high-zombie-procs.html.md, source/manual/alerts/logs-are-not-being-received-from-the-cdn.html.md, source/manual/alerts/nginx-requests-too-low.html.md, source/manual/create-a-gpg-key.html.md, source/manual/editing-an-existing-route.html.md, source/manual/provision-machines-for-data-science-research.html.md, source/manual/rotate-offsite-backup-gpg-keys.html.md
This pull request contains reviews for a number of overdue items reported by the Manual Spaniel. All were checked for continued relevancy and accuracy with their respective authors when possible, and a single item was modified to remove a now dead link.
=> Manual Spaniel reviews

source/manual/alerts/nginx-5xx-rate-too-high-for-many-apps-boxes.html.md, source/manual/auto-scaling-groups.html.md
This addresses comments missed in https://github.com/alphagov/govuk-developer-docs/pull/1986.
=> Small updates to auto scaling groups docs

source/manual/alerts/smokey-json-older-than-30m.html.md, source/manual/alerts/unknown-error-with-postgresql-mapit.html.md
We saw some odd errors in Integration that had no documentation that really applied to
the problem at hand. After RE finding solutions for both, I wrote these pages to shed
light on them in the rare case that either happen again.
=> New documentation in regards to errors seen in Integration

source/manual/alerts/content-data-api-app-healthcheck-not-ok.html.md
Adds documentation covering https://github.com/alphagov/content-data-api/pull/1313
=> Add note to ETL re-run task

source/manual/auto-scaling-groups.html.md
Add step to tell 2nd line about the manual scaling up/down
=> Review auto scaling groups

source/manual/redirect-routes.html.md
Adds documentation on how to redirect HMRC manuals and HMRC manual sections.
=> Add docs on redirecting HMRC manuals

source/manual/publishing-e2e-tests.html.md
This wasn't rendering correctly in https://docs.publishing.service.gov.uk/manual/publishing-e2e-tests.html
=> Add extra new line preceding list

source/manual/alerts/mysql-xtrabackups-to-s3.html.md, source/manual/alerts/nginx-high-conn-writing-upstream-indicator-check.html.md, source/manual/alerts/renew-tls-certificate.html.md, source/manual/concept-of-stacks.html.md
=> Jon document reviews

source/apis/search/add-new-fields-or-document-types.html.md.erb, source/apis/search/content.html.md.erb, source/apis/search/faceted-search.html.md.erb, source/apis/search/fields.html.md.erb, source/apis/search/search-api.html.md.erb
As the repository is now public again.
This reverts commit 7333a240d03c6350ec55df459a53b933c099faa6.
=> Revert "Hide search-api docs"

source/manual/data-gov-uk-architecture.html.md
DGU architecture diagram has been updated to include CSW components
=> DGU architecture diagram updated

source/manual/alerts/aws-cache-cpu.html.md, source/manual/alerts/aws-cache-memory.html.md, source/manual/alerts/aws-rds-cpu.html.md, source/manual/alerts/aws-rds-memory.html.md, source/manual/alerts/aws-rds-storage.html.md, source/manual/alerts/aws-ses-email-quota.html.md, source/manual/alerts/clamav-definitions-out-of-date.html.md, source/manual/alerts/elasticsearch-cluster-health.html.md, source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md, source/manual/alerts/free-memory-warning-on-backend.html.md, source/manual/alerts/low-available-disk-inodes.html.md, source/manual/alerts/pingdom-search-check.html.md, source/manual/alerts/prolonged-gc-collection-times-check.html.md, source/manual/alerts/rabbitmq-high-watermark.html.md, source/manual/alerts/rabbitmq-no-consumers-listening.html.md, source/manual/alerts/recreate-a-mongo-instance-in-aws.html.md, source/manual/alerts/search-api-index-size-change.html.md, source/manual/alerts/search-api-queue-latency.html.md, source/manual/alerts/signon-app-healthcheck-not-ok.html.md, source/manual/alerts/varnish-port-not-responding.html.md, source/manual/alerts/whitehall-scheduled-publishing.html.md, source/manual/changing-organisation-slug.html.md, source/manual/emergency-publishing.html.md, source/manual/global-banner.html.md, source/manual/logging.html.md, source/manual/make-a-new-document-type-available-to-search.html.md, source/manual/purge-cache.html.md, source/manual/retiring-an-application.html.md, source/manual/run-application.html.md
This reviews docs which are out of date, or assigns them to RE where appropriate. See individual commits for more details.
I've made sure the review date doesn't end up all the same to avoid a similar thing happening again in 6 months.
=> Review out of date docs

source/manual/data-gov-uk-deployment.html.md
Improve understanding of Heroku prototypes and add some information about the CSW service which is part of the CKAN publisher.
=> Update data gov uk deployment docs

source/manual/data-gov-uk-2nd-line.html.md
Add some information about how to handle problems with map preview links on DGU.
=> Add DGU map preview  guidance

source/manual/rabbitmq.html.md
During the migration to AWS we setup a federation between the
rabbitmq cluster in Carrenza and the one in AWS.
=> Add documentation for the rabbitmq federation.

source/manual/alerts/aws-cache-cpu.html.md, source/manual/alerts/aws-cache-memory.html.md, source/manual/alerts/aws-rds-cpu.html.md, source/manual/alerts/aws-rds-memory.html.md, source/manual/alerts/aws-rds-storage.html.md, source/manual/alerts/aws-ses-email-quota.html.md, source/manual/alerts/duplicate-ssh-host-keys.html.md, source/manual/alerts/recreate-a-mongo-instance-in-aws.html.md, source/manual/howto-backup-and-restore-in-aws-rds.html.md, source/manual/move-apps-between-servers.html.md, source/manual/raising-issues-with-reliability-engineering.html.md
- Mostly quick/noop reviews
- Mentioned Pagerduty in context of raising issues with RE
- Mention fix/deprecation for AWS cluster networking issue
=> Update/review RE related docs

source/manual/data-gov-uk-deployment.html.md
As the pycsw web process is started automatically we don't need to manually restart the workers.
=> Update DGU deployment notes

source/manual/components.html.md
Nothing change since last reviewed.
=> Bump components page

source/manual/cookies-and-sessions-in-frontend-apps.html.md, source/manual/development-disk-space.html.md, source/manual/documents-arent-live-after-publishing.html.md, source/manual/fix-signature-expired-errors.html.md, source/manual/help-with-publishing-content.html.md, source/manual/manually-setting-search-popularity-of-content.html.md
See individual commits for more details. The docs themselves all look up to date and correct to me.
=> Review docs assigned to govuk-developers

source/manual/data-gov-uk-map-previews.html.md
Improve DGU Map preview docs to make it easier to respond to 2ndline support tickets
https://trello.com/c/qnqUUhOb/1311-55-investigate-why-resources-are-not-populated
=> Update DGU Map preview

source/manual/cant-connect-to-mongo.html.md
Don't know how relevant this is due to GOV.UK moving to docker but the
documentation still looks sound to me.
=> Update cant-connect-to-mongo doc

source/manual/web_application_firewall_rules.html.md
Changes to the wording, not the details.
=> AWS WAF - slight rewording and date bump

source/manual/rules-for-getting-production-access.html.md
- It's better that these are discoverable by everyone rather than hidden
in Google Drive.
=> Import the docs on 'criteria for production access' from Google Drive

source/manual/analytics.html.md
Update the description of cross domain tracking to reflect the changes made in the last few months by the cross domain tracking team (and ongoing work).
=> Review analytics documentation

source/manual/encrypted-hiera-data.html.md
While infrequent, there may be a need to update the GPG key of puppetmaster. This update to the documentation will help to fill in important missing steps that were not documented as the infractructure has changed.
=> Update the hiera gpg documentation to fill in missing steps

source/manual/intro-to-docker.html.md, spec/pages/manual_page_spec.rb
This makes a number of tweaks to fix our Intro to Docker, so it's possible
to follow it from start-to-finish and get passing tests.
=> Iterate our Intro to Docker

source/manual/github-unavailable.html.md, source/manual/manage-ruby-dependencies.html.md, source/manual/publishing-a-ruby-gem.html.md, source/manual/readmes.html.md
- The one with actual changes is `manage-ruby-dependencies`, ab7cc107.
- The rest are date bumps as they looked OK.
=> Review more docs

source/manual/schemas.html.md
[Updated page](https://govuk-developer-docs-f-pr-2101.herokuapp.com/manual/schemas.html)
This is not exhaustive as yet, but I want to try and get some things out of my head.
I've listed the govuk-searchandnav team as the owner because it's likely to be the longest lived team involved with it. govuk-datalabs and others also have their fingers in this pie.
=> Add detail to schema.org implementations page

source/manual/environments.html.md, source/manual/heroku.html.md, source/manual/ssh-config.html.md, source/manual/unable-to-mount-virtualbox-shared-folders.html.md
Reviewed. No changes, just updating the reviewed date.
=> Review some docs
