alphagov/govuk-developer-docs

source/manual/data-gov-uk-2nd-line.html.md
There are a number of tickets where the harvest job has been hanging for days, at the moment there is no way to Stop and rerun the job by Users for support will have to manually restart the process.
Reduce the number of support tickets around hanging harvesters.
=> Add next steps with hanging harvest jobs

source/manual/add-deployment-dashboard.html.md, source/manual/kibana.html.md, source/manual/monitor-docs-traffic.html.md, source/manual/setting-up-request-tracing.html.md
We used to prefix some log fields with `@fields.`, but gradually removed them to converge on a standard approach (as documented in the [GDS way logging manual](https://gds-way.cloudapps.digital/manuals/logging.html#naming-conventions)).
There are a couple of remaining apps (like Router) that still use a `@fields.` prefix, but these examples will no longer work unless we correct them.
=> Remove @fields prefixes from kibana examples

source/manual/alerts/data-sync.html.md
It wasn't clear how to only run certain parts of the job.
=> Mention JOBLIST argument in data sync docs

source/manual/replicate-app-data-locally.html.md, source/manual/replicating-whitehall-data-with-docker.html.md
We developed a means to replicate data easily into a Docker container
for use with Whitehall, which is especially beneficial due to the
weight of the tool and amount of data present.
Before this commit there was no documentation on the process, and thus
this commit adds both this documentation and a relevant link from the
existing data replication page.
=> Create documentation for local replication of data with Docker

source/manual/replicating-whitehall-data-with-docker.html.md
The docs build is failing with:
```
== Request: /manual/replicating-whitehall-data-with-docker.html
error  build/manual/replicating-whitehall-data-with-docker.html
undefined method `strftime' for nil:NilClass
/var/lib/jenkins/bundles/deploy-developer-docs/ruby/2.6.0/gems/govuk_tech_docs-1.8.3/lib/govuk_tech_docs.rb:79:in `format_date'
```
=> Add date to doc

source/manual/alerts/puppet-last-run-errors.html.md
The docs initially said to provide the ip like `10-1-2-3` to the query. However, when I did this it came back with 0 results. It seems it needs the full `ip-10-1-2-3`.
=> Add 'ip-' to puppet Kibana query

source/manual/frontend-architecture.html.md
This page was due for review, but since `govuk-developer-docs` uses a hotlink to the updated diagram no changes were actually required in the file.
- `govuk_publishing_components` is not dependent on `govuk_frontend_toolkit` anymore (although a direct dependency on `govuk_frontend_toolkit` still remains for most public frontend apps)
- there is ongoing work to remove dependencies on `govuk_elements` and `govuk_frontend_toolkit` from public frontend apps
- some work has been done towards removing dependencies on `govuk_template` and `govuk_frontend_toolkit` from `static`
- two 'new' admin frontend apps were build using `govuk_publishing_components` (`content-data-admin` and `content-publisher`) instead of `govuk_admin_template`
- admin frontend apps are starting to migrate towards using …
=> Update the current state diagram

source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md
Rename SubscriptionContentWorker to ProcessContentChangeWorker following this change:
https://github.com/alphagov/email-alert-api/commit/9b3e5b77f6256fca0579d27ecd71c61c93078f9a
=> Update email-alert-api app healthcheck documentation

app/app_docs.rb, source/templates/application_template.html.md.erb
Previously it was only setting the machine class correctly for apps hosted on carrenza.
It will now set the machine class for carrenza and AWS correctly.
=> Correctly set machine class for running rake tasks

source/manual.html.erb
Fixes links in the manual section.
Fixes https://github.com/alphagov/govuk-developer-docs/issues/2018
=> Fix links in manual

source/manual/add-a-secret-to-a-concourse-pipeline.html.md, source/manual/concourse.html.md, source/manual/create-a-concourse-pipeline.html.md
- Bump the last reviewed date.
- Trim trailing whitespace.
- Where there are numbered lists, set each number to 1 to enable the
magic Markdown auto-numbering.
- Add a line about how to set a target if `cd-govuk-tools` doesn't
exist.
=> Review Concourse pipeline docs

source/manual/on-call.html.md
- The `govuk_mirror-puppet` repo is archived, so no-one new can add
themselves to it. Also they don't need to, because the mirrors
architecture has
[changed](https://docs.publishing.service.gov.uk/manual/fall-back-to-mirror.html#hosting)
(https://github.com/alphagov/govuk-developer-docs/pull/1835).
=> On-call: Remove the 'access to govuk_mirror-puppet' line

app/http.rb
Similar to 48236cad38608b6a7bdf3dd29c575f59312a00de, this partially reverts 98cba9927c3e10d8a59a983c28d9b9e49cd952d6 which seems to have stopped us being able to deploy the developer docs.
We should be able to trust the YAML here as we always load from a hard coded string that we control, although ideally it would be good to investigate why we can't use `safe_load`.
This should [fix the error we're seeing](https://deploy.publishing.service.gov.uk/job/deploy-developer-docs/339/consoleFull):
```
Unknown alias: node_class
/usr/lib/rbenv/versions/2.6.3/lib/ruby/2.6.0/psych/visitors/to_ruby.rb:397:in `visit_Psych_Nodes_Alias'
...
/usr/lib/rbenv/versions/2.6.3/lib/ruby/2.6.0/psych.rb:360:in `safe_load'
/var/lib/jenkins/workspace/deploy-developer-docs/app/http.rb:6:in `get_yaml' …
```
=> Use YAML.load over YAML.safe_load

source/manual/manage-email-subscribers.html.md
This is a task to remove superfluous subscriber lists.
=> Adds rake clean:remove_empty_subscriberlists to email alert docs

source/manual/data-gov-uk-2nd-line.html.md, source/manual/data-gov-uk-supporting-ckan.html.md, source/manual/data-gov-uk-troubleshooting.html.md
Our docs for Harvesters are duplicated in a few places (I’ve just had to cancel a harvest job that got stuck and found 3 similar pages).
This PR looks at consolidating CKAN harvester information in one page.
=> Improve ckan docs

source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md
Not that we ever cut and paste into the command line. But were we to do
so, namespacing in rake tasks should only contain a single colon.
=> Remove spurious colon in rake task code block

source/manual/documents-arent-live-after-publishing.html.md, source/manual/help-with-publishing-content.html.md, source/manual/hmrc-paye-files.html.md, source/manual/howto-manually-remove-assets.html.md
The file name was recently changed, which caused the links to break.
=> Fix links to purge cache

source/manual/howto-block-arbitrary-urls.html.md
- Following a recent security incident we blocked a location on the
frontend instances
- This step-by-ste doc is intended to speed up the process if this is
required in future
- Incident action for https://docs.google.com/document/d/17_8Jb4OaPzfqKKzNzXkRxyA5Ffm5Pg2i2Mvyc2t7yrk/edit#heading=h.p99426yo0rbv
pair: @schmie @seb-szy
=> Add documentation on how to block GOV.UK URLs

source/manual/limited-staging-access.html.md
- During a recent incident review it was decided to consistently lock
down access to the staging environments in AWS and 6DG.
- The incident review is available from: https://docs.google.com/document/d/17_8Jb4OaPzfqKKzNzXkRxyA5Ffm5Pg2i2Mvyc2t7yrk
- The PR documenting the actual IP ranges for 6DG is: https://github.com/alphagov/govuk-provisioning/pull/96
- AWS staging was already access limited to those IPs via SG
=> Add documentation of the staging IP whitelisting

source/manual/aws-cli-access.html.md, source/manual/aws-console-access.html.md
Now, Cyber has started to monitor the IPs which are used to access AWS. It is advised to use only approved GDS network if you are accessing AWS either via console or cli.
=> add a note to say that aws should be accessed on a GDS network

source/manual/alerts/redis.html.md
as part of an incident action, elasticache reboots are done daily at 11 00 GMT in AWS Integration. Therefore, we include this in the documentation.
=> add documentation about elasticache reboot in AWS integration

source/manual/data-gov-uk-supporting-ckan.html.md
This is often needed on 2nd line to debug tickets that come in and it's not obvious how to get the data because it's not visible in the user interface.
[Trello Card](https://trello.com/c/5vgaDIu3/1435-1-add-documentation-on-finding-which-harvester-is-responsible-for-a-dataset)
=> Document how to find the harvest source of a dataset

app/app_docs.rb, data/applications.yml, source/templates/application_template.html.md.erb
This will help govuk-dependencies post dependabot messages to the
correct channel for these applications.
Also add the ability to have no production version of an application
yet.
=> Add data science apps to applications.yml

source/manual/merge-pr.html.md
- With GitHub's `hub` CLI tool, there's no more faffing about finding
the GitHub username and forked repo and branch of the contributor, one
can simply `hub pr checkout` in the repo, then push that branch to
origin.
=> Simplify docs on how to run CI on external contributors' PRs

source/manual/deploying-terraform.html.md
The order of arguments was changed in this commit:
https://github.com/alphagov/govuk-aws/pull/1129
=> Update Command Example to Match Change In Arguments Order

source/manual/alerts/high-priority-tests.html.md
This adds a recently seen error which can be fixed using the same commands as
for the 'Traceback' error. There's also some repeition of killing the existing
Java process which doesn't seem necessary - having just worked through this
issue it seems doing so in conjunction with stopping and starting the
smokey-loop process does the trick.
=> Review High Priority Tests documentation

source/manual/knowledge-graph.html.md
This PR adds documentation about the GOV.UK knowledge graph - what it is, what it's being used for and how it might progress in the future.
=> Add documentation about the knowledge graph

source/manual/browser-support.html.md
This page was due to be reviewed.
I added reference to GOV.UK Frontend browser support matrix (since it was defined looking at analytics data on GOV.UK) and it reflects the current state of frontend applications that serve pages to the general public.
I also added a paragraph about informing browser support with analytics data for applications that are not serving pages for the general public (e.g. admin apps).
=> Update "Which browsers we support"

source/manual/publishing-a-facet-group.html.md
- Correctly capitalize the app names.
- Tweak the descriptions of the links to the Run Rake Task job so we
don't need to have codeblocks to show what the Rake task is.
- Don't hardcode something about Brexit in the , people can work this
out for themselves with `path-to-facet-group-config` in the box.
- Use the `1.` Markdown trick for numbered lists.
=> Review publishing-a-facet-group

data/applications.yml
These apps should be owned by the search and navigation team.
[Trello card](https://trello.com/c/kZcAODIZ/1486-make-search-and-nav-team-owners-of-some-applications)
=> Change app ownership for search-analytics and search-admin

source/manual/govuk-app-domain-handling-during-migration.html.md, source/manual/govuk-in-aws.html.md
- Due to the app by app strategy of the migration into AWS, the current
service discovery may be configured with significant differences
reflecting the state of the migration of an app as well as its
dependencies.
- We add rough documentation on the edge cases to raise awareness that
changes may not be as straightforward as expected by developers.
=> Add docs for the state of service resolution during migration

source/manual/removing-a-user-from-puppet.html.md
If we merge the second set of puppet PRs (that remove the user manifest
file) before we've removed the user from govuk-secrets, we risk errors
during a puppet deploy.
Rejig the ordering so that removing the user from govuk-secrets comes
before removing them from puppet. This makes it more explicit and will
encourage us to merge the secrets PR before the puppet PR.
=> Correct steps for leavers process

data/applications.yml
This app should be owned by the GOV.UK Publishing Workflow team. 
[Trello](https://trello.com/c/z9o9vBAf/1487-1-make-publishing-workflow-team-the-owners-of-content-publisher)
=> Change app ownership for content-publisher

source/manual/get-started.html.md, source/manual/intro-to-docker.html.md
This tweaks the doc to 'Get started on GOV.UK' to better signpost the
Docker training manual, and update that for people landing on it.
=> Signpost Docker docs better when getting started

source/manual/keeping-software-current.html.md
The versions therein are no longer accurate, and no longer maintained (last edit July 2018
by 'Deleted user'). An automated dashboard would be a better solution in future so that it
stays up to date without manual intervention.
=> Remove reference to out of date spreadsheet

source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md, source/manual/alerts/email-alert-api-delivery-attempt-status.html.md
This is a new alert which replaces two of the healthchecks. See https://github.com/alphagov/govuk-puppet/pull/9786 for more details on why we've replaced part of the healthcheck with individual alerts.
[Trello Card](https://trello.com/c/abNGpq1l/1480-5-extract-the-technicalfailures-check-from-the-healthcheck-endpoint-in-email-alert-api-to-a-separate-icinga-check)
=> Add a page on Email Alert API Delivery Attempt statuses

source/manual/cdn.html.md
Digging into the Fastly configs, the default value is actually 3600s (1 hour):
```
set beresp.ttl = 3600s;
```
=> Correct default TTL value is 3600s

data/dashboard.yml, source/manual/brakeman.html.md, source/manual/lint-ruby-code.html.md, source/manual/migrate-from-govuk-lint.html.md, source/manual/publishing-a-ruby-gem.html.md, source/manual/setting-up-new-rails-app.html.md, source/manual/which-gem-to-use.html.md
This guide helps user migrate from [govuk-lint](https://github.com/alphagov/govuk-lint) which has been deprecated to [rubocop-govuk](https://github.com/alphagov/rubocop-govuk) and [scss-lint-govuk](https://github.com/alphagov/scss-lint-govuk).
Also removes old references to `govuk-lint`.
=> Add migration guide for govuk-lint

source/manual/rebooting-machines.html.md
This morning a router_backend machine didn't come back correctly. We've agreed with RE to pair on rebooting AWS machines out of hours as they have better knowledge of the machines in AWS and can help quicker if required.
=> Add a note about rebooting in AWS

source/manual/alerts/backup-passive-checks.html.md
This adds some more guidance for the generic alert doc about passive
backup failures, as it's not currently clear what to do if the Mongo S3
backups fail.
=> Add some guidance for mongo-specific backups

source/manual/remove-machines.html.md
Monitoring cannot be disabled for machines in AWS first, because
arbitrary instances will be terminated to reach the desired capacity.
This means that the node has to be removed from the puppetmaster
afterwards.
=> Rewrite instructions for removing a machine in AWS

README.md
- I think most people use Homebrew, and if they don't they can figure
out installation instructions themselves. The 0.9.0 release is really
old.
=> README: Make Vale install instructions less verbose

source/manual/nagstamon.html.md
govuk-cli was a failed attempt at moving the `govuk connect` script
out of govuk-guix, so revert to the previous state in the docs.
This reverts commit 9c9cffc5f9d2fde032e293e1f4a36739fe76ef51.
=> Stop mentioning govuk-cli on the Nagstamon page

.rubocop.yml, Gemfile, Gemfile.lock, Jenkinsfile
- The GOV.UK Lint gem is deprecated in favour of using Rubocop directly
with a set of shared configs.
- See https://github.com/alphagov/govuk-rfcs/pull/ 100 for more context.
https://trello.com/c/CdBFg6yw/1521-replace-govuk-lint-with-rubocop-govuk
=> Replace govuk-lint

source/manual/alerts/ddosdetected.html.md
The bug in the alert which led to frequent `UNKNOWN`s is fixed, so remove the specific note about it.
Add a note about why the graphs might not show up on the Amazon Shield service dashboard, since Amazon have told us that this is known issue which happens when there are no metrics (which happens when there hasn't been any DDoS-like activity detected for a long time).
=> Update DDoSDetected playbook entry.

source/manual/run-ab-test.html.md
=> Remove instruction to deploy A/B VCL to mirror

README.md
- Vale's Homebrew formula has moved to
[Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core/commit/64f3da3e4687faa0129680d2bde1417696cf05f1).
=> README: Update Vale docs again

source/manual/transition-a-site.html.md
They are necessary if you want to use the [side-by-side browser](https://github.com/alphagov/side-by-side-browser) when transitioning a site.
=> Add short description of AKA domains

app/app_docs.rb, data/applications.yml, source/manual/alerts/pingdom-homepage-check.html.md, source/manual/vpn.html.md
- Licensing was the last thing in UK Cloud, so we can remove the docs
about that specific VPN, and the mapping of "ukcloud" to "UK Cloud".
=> Licensing is in AWS now!

source/manual/vpn.html.md
Describe the consequences of the Licensify VPN being down.
Troubleshooting steps to follow separately in the playbook for the
alert.
=> Document the AWS-UKCloud Licensify VPN.

source/manual/deploy-puppet.html.md
- Based on a quick Slack poll, no-one has used this script in a very
long time.
- Closes #1274.
=> deploy-puppet: Remove the docs for the puppet-versions Fabric script

source/manual/alerts/email-alerts.html.md
https://trello.com/c/13JaJ5mQ/203-review-the-email-alert-traffic-dashboard
This clarifies the description of the email alert check to say that it
(currently) works against two mailboxes, not just one.
=> Clarify how the email alert check works

data/applications.yml
We have now migrated the following apps to AWS:
email-alert-api
email-alert-service
publishing-api
=> Update Location of Publishing API & Email Alert API to AWS

source/manual/get-ssh-access.html.md, source/manual/howto-find-hardcoded-markup-govspeak.html.md, source/manual/howto-ssh-to-machines-in-aws.html.md
It was being referred to in 'howto-ssh-to-machines-in-aws.html.md', which
is not in the standard flow of setup instructions for new joiners. Other
instructions expect govukcli to be set up already, which tripped up our
new starter.
We now move the setup instructions closer to the beginning of the
onboarding journey so that the step cannot be missed.
There's also a commit for removing an anchor link to a section that no longer
exists, which I discovered while double-checking my change doesn't affect
other files.
=> Fix onboarding instructions for setting up 'govukcli'

source/manual/install-development-vm.html.md
Searching for "get started" gives two identical-looking results. One is for the old dev VM setup page, so I have renamed the title here to prevent confusion.
=> Change title to stop it getting confused with /manual/get-started.html

source/manual/howto-change-a-government-following-an-election.html.md
This makes sure that the documentation on change of governments are up to date, especially with our recent changes around representing governments in the Publishing API.
[Trello Card](https://trello.com/c/FYbrMgbg/1591-1-review-history-mode-docs-and-make-sure-theyre-up-to-date)
=> Review change of government docs

source/templates/application_template.html.md.erb
These used to link to Carrenza Jenkins even for apps in AWS, which was exceedingly unhelpful.
I really really don't like that I've had to specify `blue.` in the domain names here, but it's necessary until we fix the problem with the GitHub OAuth config so that deep links in Jenkins work without the `blue` (stackname) part.
=> Fix "run rake task" links for apps in AWS.

source/manual/create-a-gpg-key.html.md
- This was added back when these docs were on GitHub Enterprise. I've
not experienced these problems, and I would hope that they're fixed now.
- GPG Tools is excellent software, so recommend `brew cask install
gpg-suite` for install and update consistency.
=> create-a-gpg-key: Remove outdated Homebrew install caveat

source/manual/howto-restore-an-individual-postgres-database.html.md
Add more detailed instructions on using govuk_env_sync to restore
a postgres database in Production and other environments.
=> Add New Documentation For Restoring an Individual Postgres Database

app/app_docs.rb, app/apps_csv.rb, data/applications.yml, source/templates/application_template.html.md.erb
This is to allow shared dependabot responsibilities between different
teams. This will allow teams to be notified by slack when a PR requires
merging.
Co-authored-by: Alan Gabbianelli <alan.gabbianelli@digital.cabinet-office.gov.uk>
Trello: https://trello.com/c/2SYgweYT/1590-3-create-application-ownership-override-to-govuk-dependencies
=> Add option to show team responsible for dependencies

source/manual/cookie-consent-on-govuk.html.md
Various changes to reflect changes to the GOV.UK cookie consent mechanism
Includes:
- reflecting explicit opt-in
- change of cookie names
[Trello](https://trello.com/c/cynH4Cxx)
=> Update with changes to cookie consent on GOV.UK

source/manual/transition-architecture.html.md
We have removed the MDRA reverse proxy special case from our config.
Dependent on merging and deploying:
[Trello](https://trello.com/c/v6DwqTy8/1640-3-remove-mhra-reverse-proxy)
=> Remove MHRA reverse proxy special case

config/tech-docs.yml
It's not something we look at, and we don't have an appropriate cookie policy.
=> Remove GA tracking

source/manual/monitor-docs-traffic.html.md
`kibana.publishing.service.gov.uk` was replaced by LogIt in 2018. This cleans up the last remaining reference to it in Developer Docs.
=> Fix an outdated reference to self-hosted Kibana.

source/manual/alerts/rabbitmq-high-watermark.html.md
* This alert can also trigger when there are no free memory issues but the `rabbitmq_management` plugin is not enabled.
* We have changed the documentation to include this error scenario and how to respond to it.
* Stephen and I noticed this in late November when we were shadowing second line.
Co-authored by: Sarah Young <sarah.young@digital.cabinet-office.gov.uk>
Co-authored by: Stephen Ford <stephen.ford@digital.cabinet-office.gov.uk>
=> Amend RabbitMQ High Water mark alert to reflect new error scenario

source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md
email-alert-api has now migrated to AWS.
=> Update Grafana dashboard link

source/manual/nagios-nrpe-connection-failures.html.md
Remove small typo, 'ssh' duplicated in command example
=> Review Nagios NRPE connection failures

source/manual/local-frontend-development.html.md
Instructions did not include up to date docs when using govuk-docker.
However some frontend devs are no using docker yet, so we are keeping both sets of instructions for now.
=> Update how to work on frontends locally

source/manual/govuk-env-sync.html.md
* Document the `transformation_sql` feature for data sanitisation scripts.
* Remove mention of the unused `rsync` feature, which is about to be removed.
* Mention that there are exceptions to the Prod -> Staging -> Integration waterfall model.
* Various other edits for style and readability.
=> Update govuk_env_sync documentation.

source/manual/alerts/email-alerts.html.md
As these jobs have been moved to AWS [1].
1: https://github.com/alphagov/govuk-puppet/pull/10010
=> Update Email alert check Jenkins job links

source/manual/govuk-env-sync.html.md
Also fix a typo.
Tested locally; links now work.
=> Fix broken links on govuk_env_sync page.

source/manual/related-links-on-govuk.html.md, source/manual/related-links.html.md
We had a content request to modify the related links of a page and we thought this was a dev task but it turned out that the content designer could do this themselves using Content Tagger.
=> Add a section about manual related links

source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md, source/manual/alerts/email-alert-api-unprocessed-subscription-contents.html.md
This is a new alert which replaces one of our `email-alert-api`
heathchecks. See https://github.com/alphagov/email-alert-api/pull/1096
for more information.
Trello card: https://trello.com/c/dtdY0kAK/1606-5-extract-the-subscriptioncontents-check-from-the-healthcheck-endpoint-in-email-alert-api-to-a-separate-icinga-check
=> Add page for subscription contents alert

source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md, source/manual/alerts/email-alert-api-unprocessed-content-changes.html.md
We have introduced this new alert to reduce the responsibilities of the 
`email-alert-api health-check-not-ok`alert, to make our alerts more specific 
and reliable.
[Trello](https://trello.com/c/c6mWg9jP/1627-3-extract-the-contentchanges-check-from-the-healthcheck-endpoint-in-email-alert-api-to-a-separate-icinga-check)
=> Add page for email-alert-api unprocessed content changes icinga alert

.vale
- I ran `vale source/manual/` in here and it complained about repeated
"n" characters in PNGs.
=> Vale: Only try to lint Markdown files

source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md, source/manual/alerts/email-alert-api-delivery-attempts-status-updates.html.md
This is a new alert which replaces one of our email-alert-api
heathchecks. See https://github.com/alphagov/email-alert-api/pull/1073
for more information.
=> Add page for delivery attempts Icinga check

source/manual/connect-to-vcloud-director.html.md, source/manual/on-call.html.md
- There used to be instructions at step 7 which required all devs to
have vCloud Director set up. In reality, these instructions never
worked and messed up the existing VPN configuration. :scream:
- Instead, escalate to RE. RE GOV.UK team members know how to do access
vCloud Director and do Carrenza machine things, and can help us.
- While I was there, though, @sengi told me that the instructions aren't
100% reliable for AnyConnect depending on the versions of things, and
they require rewriting on every version. The OpenConnect ones require
less manual effort, so keep those, but delete the AnyConnect ones as
it's less faff to only update one set!
There's more context in the commit messages.
=> on-call: Note that devs should escalate to RE for vCloud Director issues

source/manual/analytics.html.md, source/manual/where-to-find-what.html.md
Instructions live in the GDS Wiki, which I realised we haven't yet linked to from the Dev Docs.
Spoke with Simon Hughesdon and we agreed it makes sense to add the link to the documentation sources at https://docs.publishing.service.gov.uk/manual/where-to-find-what.html, so I've added that too.
=> Instructions for gaining access to the GA platform

source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md, source/manual/alerts/email-alert-api-incomplete-digest-runs.html.md
We have introduced this new alert to reduce the responsibilities of the `email-alert-api health-check-not-ok` alert, to make our alerts more specific and reliable.
[Trello](https://trello.com/c/vmcbj23s/1662-5-extract-the-digestruns-check-from-the-healthcheck-endpoint-in-email-alert-api-to-a-separate-icinga-check)
=> Add page for email-alert-api incomplete digest runs icinga alert

source/manual/alerts/email-alert-api-unprocessed-messages.html.md
This is a new alert which replaces one of our `email-alert-api`
healthchecks. See https://github.com/alphagov/email-alert-api/pull/1108
for more information.
Trello card: https://trello.com/c/z3QoArLh/1661-5-extract-the-messages-check-from-the-healthcheck-endpoint-in-email-alert-api-to-a-separate-icinga-check
=> Add page for email-alert-api message Icinga check

source/manual/local-frontend-development.html.md
[View rendered file here](https://github.com/alphagov/govuk-developer-docs/blob/c8031edd8127913833f2ab523f3d1c2febc49fad/source/manual/local-frontend-development.html.md)
I've removed references to updating `govuk_app_config` - I tested the instructions locally and didn't need them. I'd be interested in getting someone else to test these instructions themselves to double check though.
=> Expand local frontend development docs

source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md
We have recently moved out some healthchecks into individual Icinga
checks. I have re-reviewed the healthcheck doc to check what is left
is still applicable.
=> Tidy and review email-alert-api healthcheck doc

source/manual/emergency-publishing.html.md
This repo is no longer being maintained (will be archived) and it would
be safer to perform manual checks.
=> Remove reference to the archived emergency-publishing-scraper

Jenkinsfile
This resolves an issue where every master build of this project fails
since it tries to deploy to integration but this does not exist as a
project there.
=> Skip deploy to integration on master build

data/applications.yml
This is so the dev channel is alerted about Dependabot rather than the
wider team channel.
=> Change Publishing Workflow channel name

data/dashboard.yml
Looks like this was accidentally [duplicated here](https://github.com/alphagov/govuk-developer-docs/commit/0735ada71b4572779e0bc3ea07894c6170a980d0) when we removed the old reference to `scss-lint-govuk`
=> Remove duplicate reference to rubocop-govuk

source/manual/alerts/content-data-api-app-healthcheck-not-ok.html.md, source/manual/concourse.html.md, source/manual/create-a-concourse-pipeline.html.md, source/manual/data-gov-uk-supporting-ckan.html.md, source/manual/use-terraboard-to-monitor-terraform-state.html.md
Four of these are standard date bumps because the content is still OK.
But I'll copypaste the contents of 1e527ed3 here because it's the most
important.
---
terraboard: Bump review date but reduce time between reviews
- There are some things here that I'm not completely comfortable with,
but that require engineering effort to change. And an assurance that
Terraboard is still being used. These things are:
- We currently have our own Docker image for oauth2_proxy, based on
the original creators of oauth2_proxy. Our repo (linked in the doc
still) is archived, as is the upstream repo that we cribbed from. The
current maintainers of oauth2_proxy are now on version 4.1.0 - but
we're still on 2.2.0.
- There's some work here not just on these docs but to stop us
maintaining so much code ourselves …
=> Review docs (one isn't just a date bump!)

source/manual/alerts/recreate-a-mongo-instance-in-aws.html.md
Fix typo.
Fix numbering (markdown automatic numbering doesn't
work correctly after code blocks ).
This alert has not occurred in production for 53 days. This fix
appears to have worked:
https://github.com/alphagov/govuk-aws/pull/1097
Let's think about moving this to general documentation and removing the
alert from Icinga if this hasn't reoccured by the time of the next
review ( in another 3 months).
=> Review Re-create an AWS mongo instance

source/manual/alerts/redis.html.md
This PR updates the Redis docs to remove the section on cluster restarts, which have recently been removed from Puppet (https://github.com/alphagov/govuk-puppet/commit/8f5d6745a6c84c9dc2cb371ffa408049a2e7471c).
=> Update Redis docs to remove section on cluster restarts

data/applications.yml
This updates the link, which changed when email-alert-api was moved to AWS
[Trello card](https://trello.com/c/1FPV9PIo/1687-fix-the-dev-docs-link-to-the-email-alert-api-metrics-dashboard)
=> Update link to email-alert-api metrics dashboard

source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md, source/manual/alerts/email-alert-api-high-queue-size.html.md
This alert has been extracted from the email-alert-api healthcheck.
Related to this [puppet change](https://github.com/alphagov/govuk-puppet/pull/10064)
[Trello](https://trello.com/c/lyTVPild/1681-2-extract-the-queuesize-check-from-the-healthcheck-endpoint-in-email-alert-api-to-a-separate-icinga-check)
=> Add page for email-alert-api high sidekiq queue size

source/manual/logging.html.md
- We did this recently and it [went wrong](https://trello.com/c/7pAvfM8R/167-only-some-of-our-fastly-cdn-configuration-is-currently-automated), so let's document how to do it _correctly_ for the next people!
=> Add docs on how to add a new column to our Fastly logs and Athena

source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md, source/manual/alerts/email-alert-api-high-queue-latency.html.md
This is a new alert which replaces one of our `email-alert-api`
healthchecks. See https://github.com/alphagov/govuk-puppet/pull/10069
for more information.
Trello card: https://trello.com/c/A4RfUXGG/1680-2-extract-the-queuelatency-check-from-the-healthcheck-endpoint-in-email-alert-api-to-a-separate-icinga-check-5
=> Add page for email-alert-api queue latency Icinga check

source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md, source/manual/alerts/email-alert-api-high-queue-size.html.md, source/manual/alerts/email-alert-api-high-retry-queue-size.html.md
This alert has been extracted from the email-alert-api healthcheck.
[Trello](https://trello.com/c/EfKW5u1T/1682-2-extract-the-retrysize-check-from-the-healthcheck-endpoint-in-email-alert-api-to-a-separate-icinga-check)
=> Add page for high number of message for email-alert-api sidekiq retry queues

source/manual/install-development-vm.html.md
Although these instructions are deprecated they still seem useful if for
whatever reason (testing puppet changes etc) you'd want to install the vm.
=> Update review date

source/manual/alerts/jenkins-agent-not-connected-to-master.html.md
Mention clearing out the workspaces directory as a possible fix for an
agent which is crashing on startup.
Remove the instructions about how to restart the agent, because they're no longer applicable. In our current configuration, the master starts the agent by sshing into the agent machine; there is no longer any daemon or service for it.
Update SSH commands to use `gds govuk connect`.
=> Update playbook for Jenkins agent not connected to master.

source/manual/aws-iam-key-rotation.html.md
In order to make the process of rotating keys incrementally easier, we
maintain a list of these keys with their location. This is currently a
very brief list but we are hoping for it to eventually contain
all keys.
This list is in a [Google Spreadsheet called GOV.UK AWS User Keys](https://docs.google.com/spreadsheets/d/1L6H3-wh9J1p18fjnODmit2WbGOA8wZgr5wL-5wN0IgE/edit#gid=0).
=> Add point to record location of user keys

config/tech-docs.yml
- We renamed this recently, but we didn't account for other places where
the original doc was linked from. Oops!
=> Redirect /manual/gds-cli.html to /manual/access-aws-console.html

app/app_docs.rb, spec/app/app_docs_spec.rb
This fixes the links to the application dashboards in AWS as they were previously hard coded to Carrenza.
[Trello Card](https://trello.com/c/3S3UCsgK/1465-make-developer-docs-link-to-the-correct-deployment-dashboard-for-applications)
=> Fix dashboard links in AWS

source/manual/government-changes.html.md
We've added these new Rake tasks to help content designers perform bulk changes.
[Trello Card](https://trello.com/c/tDJ5oeIu/1702-add-rake-tasks-to-handle-machinery-of-government-changes)
=> Add documentation on machinery of government changes

data/applications.yml, diagrams/supporting_apps.puml
Content Audit Tool is a legacy application created before Content Data. It was used to help tag content - it shared a codebase with Content Performance Manager.
It is being retired as it should no longer be used, to clean up references to it in our codebase, and remove the need for developers to maintain it.
[trello](https://trello.com/c/V6bXwwtx/1700-3-retire-content-audit-app)
=> Remove content audit tool

source/manual/alerts/whitehall-scheduled-publishing.html.md
This means we can link directly to the Rake tasks rather than having to use Fabric scripts.
=> Use Rake tasks to handle Whitehall overdue publications

source/manual/deploying-terraform.html.md
The previous wording made it sound like deploy.rb is about deploying
Terraform locally, which it isn't. It deploys Terraform via Jenkins.
Avoid potential confusion by not using the word 'locally' when talking
about deploying Terraform via Jenkins.
=> Fix confusing use of the term 'local' in the Terraform how-to.

source/manual/retiring-an-application.html.md
As we move from the VM to Docker this page needed updating.
I've kept the VM information in the meantime as it is not fully deprecated.
=> Update Retiring Application doc to reference GOV.UK Docker

app/app_docs.rb, spec/app/app_docs_spec.rb
The puppet name uses underscores whereas our dashboards use hyphens, for example: https://grafana.blue.production.govuk.digital/dashboard/file/email-alert-api.json?refresh=5s&orgId=1
[Trello Card](https://trello.com/c/3S3UCsgK/1465-make-developer-docs-link-to-the-correct-deployment-dashboard-for-applications)
=> Use application name to generate dashboard URLs

source/manual/cdn.html.md
This is to reflect the new API version for an upgraded vCloud Director (v8.2 -> v9.7).
=> Update to a connection string for vcd-cli tool. 

source/manual/govuk-app-domain-handling-during-migration.html.md
* Adds spacing for readability.
* Tightens language for brevity.
* Fixes typo.
* Incorporates comments from [closed PR](https://github.com/alphagov/govuk-developer-docs/pull/2253).
* I've tested this locally and it appears to be all in order.
=> Update app_domain handling documentation

source/manual/mysql.html.md
* Add subheadings to direct readers to the relevant explanation.
* Consolidate and tighten language
* Break longer paragraphs into smaller chunks for readability.
I have tested this locally and it looks OK.
=> Update MySQL backups documentation

source/manual/merge-pr.html.md
Just a bump, since it's all up to date.
Next review it could be worth swapping "unofficial" `hub` with official [`gh`](https://github.com/cli/cli) - `gh` is probably too early in development to be recommended at the moment.
=> Bump pull request guide

source/manual/troubleshooting-jenkins-performance.html.md, source/manual/which-gem-to-use.html.md
We seem to use the latter much more often. I'm changing this only for
consistency and I'm not currently reviewing the content of these two doc
pages so I'm leaving the dates untouched.
=> Rename "1 year" to "12 months"

source/manual/alerts/offsite-backups.html.md
- Tried to distinguish between "i.e." and "e.g." by removing these abbreviations
- Removed stray quotation mark
- Added "bash" to bash code blocks, hopefully for better syntax highlighting
- Broke up long paragraphs into smaller chunks
=> Update "Offsite backups" page

source/manual/run-application.html.md
Contents still relevant, so not changed. 
Slight tweak to update note at the top of the page to emphasise that the VM is deprecated.
=> Update "Run an application in the VM" page

source/manual/restrict-paas-applications-to-gds-office-ips.html.md
Add docs offering instructions on how to restrict PaaS application
access to GDS office IPs.
[Trello](https://trello.com/c/GPW8XB6L/306-add-some-auth-to-the-user-intent-survey-app)
=> Restrict PaaS app access to GDS IPs

source/manual/intro-to-docker-even-more.html.md, source/manual/intro-to-docker.html.md
https://trello.com/c/gl5911VV/116-advanced-tutorial-on-docker
This extends the existing 'Intro to Docker' manual to cover additional
concepts that we use in govuk-docker.
👉 [Rendered version](https://github.com/alphagov/govuk-developer-docs/blob/a4b8d97f9143283c93401cf7d84b51eed2e962dc/source/manual/intro-to-docker-even-more.html.md)
=> Add follow-on tutorial for Docker

source/manual/rename-a-country.html.md
Minor tweaks to remove a couple of acronyms and make examples clearer.
=> Update "Rename a country" page

source/manual/howto-ssh-to-machines-in-aws.html.md
Updated code blocks to be consistent. 
Added `sh` for syntax highlighting.
=> Update "SSH into AWS machines" page

source/manual/analytics.html.md, source/manual/data-gov-uk-map-previews.html.md, source/manual/docs-style-guide.html.md, source/manual/intro-to-docker-even-more.html.md, source/manual/intro-to-docker.html.md, source/manual/non-ha-node-classes.html.md
I haven't reviewed these docs, or gone through the full manual, but these seem more Learn docs than How Tos to me.
=> Move some docs from How To to Learn

source/manual.html.erb
This ensures that, in every category, the order of subcategories ("Learn" or "How to...") will be consistent.
At the moment the order is determined somewhat arbitrarily (by the type of the lexicographically first page), so we have this situation:
Now we have:
---
[Trello card](https://trello.com/c/YEPSn3cR/1371-tlc-for-dev-docs)
=> Sort pages by type

app/manual.rb, source/manual.html.erb, spec/app/manual_spec.rb
It seems Ruby's sort_by isn't a stable sort, so sorting by type loses
the sorting by title.  Fix that by sorting lexicographically.
=> Sort pages by type and title

source/manual/cdn.html.md
- Update links to examples in config VCL
- Update link to page about contacting Reliability Engineering
- Update Bouncer CDN link to AWS from Carrenza
=> Update "Our content delivery network (CDN)" page

config/tech-docs.yml, source/manual/access-aws-console.html.md, source/manual/auto-scaling-groups.html.md, source/manual/brakeman.html.md, source/manual/cant-connect-to-mongo.html.md, source/manual/content-store-times-out.html.md, source/manual/debug-underperforming-search.html.md, source/manual/documents-are-published-but-links-arent-updated.html.md, source/manual/email-alert-api-callback-from-notify-fails.html.md, source/manual/error-reporting.html.md, source/manual/errors.html.md, source/manual/fetching-packages.html.md, source/manual/government-changes.html.md.erb, source/manual/how-govuk-docker-works.html.md, source/manual/install-development-vm.html.md, source/manual/load-testing.html.md.erb, source/manual/nagios-nrpe-connection-failures.html.md, source/manual/nagstamon.html.md, source/manual/packer-vagrant-image-creation.html.md, source/manual/publishing-e2e-tests.html.md, source/manual/ram-vm.html.md, source/manual/readmes.html.md, source/manual/screens.html.md, source/manual/unable-to-mount-virtualbox-shared-folders.html.md, source/manual/which-gem-to-use.html.md
This commit does a basic review of all the "how to" docs:
- is it actually a how-to?  if not, make it a "learn" doc
- is the title action-oriented?  if not, make it so
---
[Trello card](https://trello.com/c/YEPSn3cR/1371-tlc-for-dev-docs)
=> Move "how to" docs around and fiddle with titles

source/manual/government-changes.html.md.erb
Clarify that new organisations replace old ones when bulk retagging content. 
[Trello card](https://trello.com/c/Bcet3LjB/1749-add-clarification-to-docs-about-bulk-retagging-content)
=> Adds detail about bulk document retagging

source/manual/manage-email-subscribers.html.md
Before links were pointing at Carrenza, now they are pointing at AWS.
=> Correct links for productions

source/manual/taxonomy.html.md
Some URLs were appearing as text rather than clickable links. This commit
turns them into URLs, and also DRYs up other URLs that use the []() syntax
unnecessarily. Also I've tidied up a couple of stray newlines.
Fixes this bug:
> ![Screenshot 2020-02-18 at 11 35 26](https://user-images.githubusercontent.com/5111927/74732736-c8e52100-5242-11ea-9d86-b2793e7dfcaf.png)
=> Fix links for URL strings

source/manual/restrict-paas-applications-to-gds-office-ips.html.md
This PR fixes a typo in the application name, from `govuk-paas-office-ip-route-service` to `govuk-paas-office-ip-router-service` in the example for binding the route service to your app.
=> Fix typo in application name

source/manual/howto-change-slug-and-create-redirect.html.md
Whitehall is now in AWS in all three environments, but the Jenkins URLs for Staging and Production are quite different from the one for Integration. This has caused confusion, so provide ready-made links to each environment.
=> Link to AWS Jenkinses from Whitehall reslug instructions.

source/manual/query-cdn-logs.html.md
- Most of the people who used to use these real-time logs have left.
- Athena is good enough for most people's purposes.
- We can clear up a lot of code (and save ourselves money) if we stop
storing them in two places.
- It's able to be reverted though, if we know in advance that we're
going to need instant logs, or if they're deemed useful again in the
future.
Further discussion: https://github.com/alphagov/govuk-puppet/pull/10126 and https://github.com/alphagov/govuk-developer-docs/pull/2285#issuecomment-582373234
=> query-cdn-logs: Note the removal of the real-time CDN logs sent to `monitoring`

source/manual/howto-change-slug-and-create-redirect.html.md
The Whitehall reslug playbook page contained a link to the Publishing API dashboard in Carrenza. Publishing API was moved to AWS some time ago, so update the dashboard link.
=> Fix link to Publishing API dashboard.

source/manual/alerts/athena-fastly-logs-check.html.md
Trello: https://trello.com/c/93jgKiUX/1329-set-up-a-smoke-test-that-athena-is-still-operating-on-new-data
This adds content that is intended for the notes url of the Icinga alert
for: "Athena has recent results for fastly_logs ...". This alert was
introduced in https://github.com/alphagov/govuk-puppet/pull/10154
=> Add documentation for Athena Fastly Logs Check alert

source/manual/rules-for-getting-production-access.html.md, source/manual/set-up-gcp-account.html.md
One of static copies of GOV.UK is stored within Google Cloud Platform. This quick guide clarifies how and when GOV.UK Developers should request access.
=> This adds a guidance how to request access to GCP 

source/manual/alerts/data-sync.html.md
This job is no more. It was replaced by a govuk_env_sync job in
alphagov/govuk-puppet#10163.
=> Remove mention of copy_sanitised_whitehall_database job.

source/manual/alerts/content-publisher-healthcheck-not-okay.html.md
Trello - https://trello.com/c/FaHAEajH/1318-alert-2ndline-when-we-have-no-cached-data-on-governments
https://github.com/alphagov/content-publisher/pull/1748 introduces extra checks to the content publisher healthcheck endpoint. This introduces documentation for 2nd line to look at in the event that one of these new checks causes an alert.
=> Introduce document for content publisher healthcheck alerts

source/manual/alerts/cannot-ping-across-AWS-Carrenza-VPN.html.md, source/manual/alerts/low-available-disk-space.html.md, source/manual/kibana.html.md, source/manual/vpn.html.md
Kibana docs were reviewed in faac40d but the wrong date was entered. 🙈
Review some VPN alert and troubleshooting docs. Update the review date. Set owner to be re-govuk. Set review timeline to be 3 months because we are actively migrating things so these might become obsolete sooner than 6 months.
Review low available disk space.
=> Review old docs 20200227

source/manual/screens.html.md
We no longer use the 4th wall or the deploy lag radiator, so remove
references to those.
Link to the 2ndline split frame.
=> Update docs about monitoring screens.

source/manual/debian-packaging.html.md
* Tightens language
* Adds bolded emphasis
* Fixes typos
* Adds link to Aptly documentation
* Does not change content substance – it all seems pretty clear
I tested the page locally and it looks OK.
=> Update debian package documentation

source/manual/data-gov-uk-monitoring.html.md
As we no longer have the publish GUI running we should remove the docs about sidekiq UI which rely on the GUI
=> Remove sidekiq UI notes from DGU publish

source/manual/global-banner.html.md
We recently deployed a new non-emergency global banner, but didn't know to block the page from certain pages. This info is now part of the doc.
=> Add how to block pages showing global banner

source/manual/alerts/data-sync.html.md, source/manual/govuk-env-sync.html.md
Previously the docs to support alerts for env-sync-and-backup were
mixed with the general documentation about the tool. The section about
the Icinga alert also didn't cover all the steps necessary to fix an
issue. This moves the parts of the general manual on env-sync-and-backup
to the existing docs for data-sync alerts, and modifies the text to
provide a clearer sequence of steps for 2ndline to follow.
Follow up work: modify Puppet to point env-sync-and-backup alerts to
the existing data-sync alert doc, instead of the general manual.
=> Centralise alert docs for data sync

source/manual/govuk-env-sync.html.md
The sections about govuk_env_sync cron jobs and Icinga checks were moved to a playbook page in #2368. Add a link so that the information is still discoverable from the govuk_env_sync documentation.
=> Add link to moved info about govuk_env_sync.

source/manual/data-gov-uk-supporting-ckan.html.md
- Adds an example CKAN API call which is useful for troubleshooting
- Gives a clearer example of using package ID vs name
=> Add another example CKAN API call

source/manual/fall-back-to-aws-cloudfront.html.md
https://trello.com/c/h2vhDRVZ/826-review-pages-that-have-been-due-for-review-for-30-days-or-more
This manual looks heavily reliant on intervention by RE if we were
ever to make use of it, not least because it says the level of access
required means most people can't run it themselves. It's also missing
a lot of detail about the individual steps involved.
=> Move infra-heavy manual to RE GOV.UK to monitor

source/manual/alerts/aws-lb-healthyhosts.html.md
Previously the alert doc for unhealthy AWS LBs was quite verbose and
contained quite a lot of repetition. This rewrites the doc to preserve
the same information and clearly highlight the steps to take in order
to debug the alert.
This also changes the owner Slack channel to 2ndline, since this is an
alert 2ndline may see and need to take action on.
=> Rewrite AWS LB alert doc to highlight actions

source/manual/migrate-from-govuk-lint.html.md
- These docs are somewhat irrelevant now as nothing is using
govuk-lint, but they're a good central place to see what RuboCop
config apps _should_ be using based on the `rubocop-govuk` gem.
- We found that for apps that used Ruby-only cops, the recent changes in
gem version 3.1.0 to exclude `bin/` files from linting worked fine.
- For apps that used Rails cops as well, the changes didn't work for
`bin/` but they did work for `db/schema.rb` which is excluded from
linting in `config/rails.yml`.
- This is because RuboCop by default *overwrites* any previous
definitions of a config option when it detects a later one:
https://rubocop.readthedocs.io/en/latest/configuration/#merging-arrays-using-inherit_mode.
- Unfortunately, we'll have to specify this `inherit_mode` stanza in
every app. …
=> Document new RuboCop `inherit_mode` config option

source/manual/postgresql-backups.html.md
We no longer run this on our machines as of https://github.com/alphagov/govuk-puppet/pull/10215.
=> Remove section on autopostgresqlbackup

source/manual/intro-to-docker-advanced.html.md, source/manual/intro-to-docker.html.md
This renames the follow-on manual about learning GOV.UK Docker, so
that it's clearly second in the learning series.
=> Rename GOV.UK Docker docs to represent series

source/manual/access-aws-console.html.md, source/manual/analytics.html.md, source/manual/dns.html.md, source/manual/govuk-in-aws.html.md, source/manual/howto-ssh-to-machines-in-aws.html.md, source/manual/nagstamon.html.md, source/manual/readmes.html.md, source/manual/set-up-aws-account.html.md, source/manual/set-up-gcp-account.html.md, source/manual/which-gem-to-use.html.md
We have a bunch of sections with only one or two docs in, where I'm not convinced the granularity is worth it.  This PR shuffles some things around to reduce that:
- Analytics -> Frontend
- AWS accounts -> AWS
- DNS -> Infrastructure
- Patterns & Style Guides -> Documentation / Dependencies
=> Get rid of some small sections

source/manual/zendesk.html.md
This updates the link to refer to the general folder where this may
be found, noting that the file itself may change over time.
=> Fix link to Zendesk triage diagram

Rakefile, config.rb, config.ru
This is depended on by https://github.com/alphagov/govuk-jenkinslib/pull/66.
=> Make entire repository pass Rubocop linting

source/manual/alerts/nginx-429-too-many-requests.html.md, source/manual/rules-for-getting-production-access.html.md
https://trello.com/c/h2vhDRVZ/826-review-pages-that-have-been-due-for-review-for-30-days-or-more
This increases the review period for production access rules to one
year, as it seems unlikely the process will change without this manual
being changed also. It's unclear why it was 3 months in the first place.
=> Review a few more overdue developer docs

source/manual/rabbitmq.html.md
Clarify that the rabbitmqctl eval only reports the status on one node.
=> Review rabbitmq federation

source/manual/mongodb.html.md
* Tighten language
* Fix broken link to another manual page
* Create "Restoring" sections to focus reader on relevant content
* Add a way for readers to ascertain which machines have enabled S3 backups and thus also contain the `mongodb-restore-s3` script.
* Replace Amazon with AWS for precision
I have tested the page locally and it looks OK.
=> Update mongodb backups doc

source/manual/sidekiq.html.md
Include a section with some basic commands to query sidekiq from the
console.
Include skip links for easy navigation.
=> Include sidekiq from the console section

source/manual/subject-access-requests.html.md
2nd line are frequently getting these requests and it's not always clear what needs to be done. This page adds a bit of background into what they are and what needs to be done about them.
[Trello Card](https://trello.com/c/PqRTfvcB/1840-3-document-actions-needed-for-subject-access-requests-sar)
=> Add a page about Subject Access Requests (SAR)

app/app_docs.rb, spec/app/app_docs_spec.rb, spec/app/run_rake_task_spec.rb
Rake task links in the  method no longer take you to the correct url.  Staging and Production are correct.  Add test for the integration environment and change as appropriate.
=> Fix broken integration rake task links

source/manual/postgresql-backups.html.md, source/manual/resync-postgres-standby.html.md
* Fix broken link to `postgresql-backups` doc in `resync-postgres-standby` doc.
* Tighten wording.
* Remove references to step numbers which risk getting out of sync.
* Update `postgresql-backups` doc to include special case reference to `resync-postgres-standby` instructions.
I followed these docs yesterday when I resynced the disaster recovery postgres database.
Tested the project locally (found a mising `/` and fixed it) and it all looks fine now.
=> Fix broken link and update Re-sync Postgres docs

app/app_docs.rb, data/applications.yml, data/dashboard.yml
Apparently nothing else that's deployed to paas has a deployment script,
but these apps do (well, a concourse pipeline) so I had to patch the
code to work for them.
=> Add coronavirus apps to the dev docs

source/manual/alerts/whitehall-scheduled-publishing.html.md.erb
Some document editions that are pending publishing are being re-created into the same state each night by the Whitehall scrub-database process.
This change alerts the 2nd line team.
=> Add comment on data scrubbing process

source/manual/get-started.html.md
- These are quite far apart and now we just say "earlier". For people
coming to these docs from other docs, this gives an entry point if
they don't know what the GDS CLI is.
=> get-started: Link from "set up gds-cli" back to "install gds-cli"

source/manual/covid-19-services.html.md
Rendered: https://github.com/alphagov/govuk-developer-docs/blob/covid-19-services/source/manual/covid-19-services.html.md
---
[Trello card](https://trello.com/c/de8Ibudi/154-add-tech-docs-to-govuk-dev-docs-repo)
=> Documentation for COVID-19 services

source/manual/covid-19-services.html.md
We now have a recurring Concourse task that exports user form responses into a S3 bucket on a daily basis.
Trello card: https://trello.com/c/D4mG8WWb
=> Update instructions for exporting business volunteering responses

source/manual/alerts/email-alert-api-incomplete-digest-runs.html.md
This alert had us stumped for a while. We're not entirely sure how it got into this state in the first place, but hopefully if it happens again it will be a similar fix.
=> Document how to fix 'incomplete digest runs' error

source/manual/data-gov-uk-supporting-ckan.html.md
The DB connections regularly time out every few months, so until it is investigated and resolved these notes should help resolve it.
https://trello.com/c/J9NuRBqs/1883-too-many-database-connections-causing-ckan-to-fail-in-staging
=> Update DGU supporting CKAN docs

source/manual/debian-packaging.html.md
Using $(date...) in every example is confusing, because you need to use the same date in them all.
In secrets, the password isn't called "apt", it's "apt/passphrase".  Also use the edit script to avoid problems with comments in the GPG ID list.
=> Clarify some commands

app/publishing_api_docs.rb
The forward slash prefixing the path in the PublishingApiDocs class is
superfluous as when it's resolved to a url there are two forward slashes
prefixing the path. This was causing a 301 moved permanently to be
returned and not the actual page for the document.
An example of the two requests are below:
```
[11] pry(ExternalDoc)> HTTP.get("https://raw.githubusercontent.com/alphagov/publishing-api/master//doc/api.md")
=> "<a href=\"/alphagov/publishing-api/master/doc/api.md\">Moved Permanently</a>.\n\n"
[12] pry(ExternalDoc)> HTTP.get("https://raw.githubusercontent.com/alphagov/publishing-api/master/doc/api.md")
=> "# Publishing API's API\n\nThis is the primary interface from publishing apps to the publishing pipeline....
```
We're unsure as to what caused the issue to surface as there has …
=> Remove forward slash prefixing path

data/applications.yml
This moves application ownership and responsibility for dependabot PRs to the Platform Health team, given changes to other teams.
[Trello card](https://trello.com/c/uQQqNanN/1906-change-dependabot-responsibility-for-some-apps)
=> Switch responsibility for more apps to Platform Health

source/manual/covid-19-services.html.md
- Where relevant I changed "both" to "all" or got rid of the word
entirely as there are now >2 forms.
- Fix some casing of products, like "PaaS" and fix some accidental,
unnecessary double spacing between sections.
- Move the blurb about the IVR to the vulnerable people section, as
that's the only thing it's for.
Trello card: https://trello.com/c/3yABBo1i
=> covid-19-services: Add docs about the new find-support form

source/manual/covid-19-services.html.md
- The team of people doing a lot of the data stuff within TechOps moved the Terraform for these services out of `alphagov/tech-ops-private` and into `alphagov/covid-engineering` so that they could give more people access. It was only put in `tech-ops-private` as we were working at such speed the first weekend, so that makes sense.
=> covid-19-services: The `govuk-corona-data` account Terraform has moved

app/external_doc.rb, source/manual/get-started.html.md
A missing ` caused this issue on the Get Started page:
> ![Screenshot 2020-04-15 at 09 08 39](https://user-images.githubusercontent.com/5111927/79313827-d80de580-7ef8-11ea-98cf-6fc53117561e.png)
=> Fix get started

source/manual/change-base-path-in-specialist-publisher.html.md, source/manual/check-for-gone-route.html.md, source/manual/data-gov-uk-supporting-ckan.html.md, source/manual/editing-an-existing-route.html.md, source/manual/github-unavailable.html.md, source/manual/hmrc-paye-files.html.md, source/manual/make-github-repo-private.html.md, source/manual/pagerduty.html.md, source/manual/redirect-routes.html.md, source/manual/remove-machines.html.md
- Now the rest of the docs match the Get Started guide, we will no
longer confuse new people (or old people trying to decipher which tool
they should use).
- Some of these could be replaced with `gds govuk connect -e production
app_console <app>`, but that's an exercise for later.
- Relates to https://github.com/alphagov/govuk-aws/issues/1159. Come and talk to us in #govuk-dev-tools!
=> Replace all occurrences of `govukcli ssh` with `gds govuk connect ssh`

source/manual/nagstamon.html.md
- Otherwise different places in this manual will diverge from the Get
Started messaging and that'd be bad.
- Also `brew install` is easier to understand than strange, cryptic
errors people were getting about Ruby versions when they used `gem
install`.
=> nagstamon: Link to the canonical source for installing our tooling

source/templates/application_template.html.md.erb
- This is to be consistent with the rest of the docs about SSHing that
now say `gds govuk connect ssh` is the thing one should use.
- When we [delete the dev VM directory from
Puppet](https://trello.com/c/1xBp5GeI/137-delete-the-development-vm-code-in-govuk-puppet),
people won't have the SSH config any more, so these commands won't work.
- And by removing this, we get rid of a lot of instances of SSH agent
forwarding, which is insecure.
https://trello.com/c/7T1NB3ym/135-update-dev-docs-for-govuk-connect
Before:
After:
=> Replace `ssh -A` commands on app pages with `gds govuk connect ssh`

source/manual/alerts/onsite-backups.html.md, source/manual/fall-back-to-mirror.html.md, source/manual/jenkins-ci.html.md, source/manual/reindex-elasticsearch.html.md, source/manual/sidekiq.html.md
- Further to #2462.
https://trello.com/c/ZBGHVlTr/132-deprecate-and-delete-govukcli
=> Replace raw SSH commands with `gds govuk connect` equivalents

source/manual/get-started.html.md
Creates a new "You're all done" section to round off the guide,
just to confirm the developer has finished setting everything up.
This seems a natural point to introduce them to the architecture.
I considered linking them to the [architectural overview](https://docs.publishing.service.gov.uk/manual/architecture.html)
instead, but in my experience the diagram doesn't mean much until
it has been explained, so the deep-dive is a better, if more
daunting piece of documentation to link to.
=> Link to architectural deep-dive from 'Getting started'

app/external_doc.rb, spec/app/external_doc_spec.rb, spec/fixtures/markdown.md
When linking to documentation written in markdown on github we were replacing the `.md` extension with `.html`, however this was linking incorrectly and returning 404 errors. Here we change the behaviour to only modify links pointing internally and not to modify links pointing to external github repos.
=> Fix links leading to 404 pages

source/manual/architecture-deep-dive.html.md
The deep-dive somewhat simplifies just how complicated the frontend of GOV.UK is.
We should link off to this other resource which explains it in more detail:
https://docs.publishing.service.gov.uk/manual/frontend-architecture.html
=> Link to Frontend architecture

source/manual/covid-19-services.html.md
This PR:
- adds information about managing GOV.UK Notify for the COVID-19 services
- reviews all COVID-19 documentation which was out of date in a few places
Trello card: https://trello.com/c/ecivql30
=> Review COVID-19 documentation

data/applications.yml
Adds the Find Support app, and fixed the Slack channel for existing COVID-19 apps (so we'll start getting Dependapanda posts again).
=> Update COVID-19 apps

source/manual/covid-19-services.html.md
- There are so many people, on so many teams, working on so many different bits that obviously they make up their own names (where the services are more than just their forms).
- The vulnerable people form is otherwise known as the Shielded Vulnerable tool/service/form, or SVS.
- The find support form is otherwise known as the Non-Shielded Vulnerable tool/service/form, or NSV.
=> covid-19-services: Document the different service names we have heard

source/manual/configure-github-repo.html.md, source/manual/github.html.md.erb
See commits for more details.
Turns out that Jenkins can't handle `#` characters in branch names, so #2482 didn't work.
=> Review docs about our use of GitHub

config/tech-docs.yml
- Turns out that the `gds-users` "request an account" service, managed
by RE, links to `manual/user-management-in-aws`. A new user complained
the link was broken.
=> Redirect previous paths for our AWS docs to Get Started

source/manual/architecture-deep-dive.html.md
- Correct the reference to 'govuk-jenkinslib', which is a library rather than a job
- Explain how the Jenkins jobs that run app tests are created in the first place
- Remove the confusing 'release tag' terminology, as we currently _do_ create a `release` tag but it is unused. We actually use the build number release tag (e.g. `release_123`) in the deployment pipeline, not the `release` tag.
- Suggest that the CI and Deploy Jenkins live in separate environments.
- Link to some of the code where the tag-pushing and send-message magic happens, to demystify it and to make the docs easier to review.
=> Improve "Deploying" section

data/applications.yml
DGU apps have dependencies too! While 'Publish' is relatively well
maintained, DGU Find has lots of outdated dependencies.
=> Monitor dependencies for Ruby DGU apps

.github/workflows/tests.yml, .rubocop.yml, Jenkinsfile
- This runs Rake and RuboCop checks with the Ruby version defined in
`.ruby-version`, for ease of updating later.
- The deployment of this app is done on the deploy Jenkins, once an hour
on a timer, and the job `bin/deploy-to-s3` builds the site and pushes
the files to S3. The CI Jenkins is not involved in the deployment
process at all, and we don't seem to use the release tags generated in
the master build process for anything.
- This reduces the amount of load on our Jenkins CI servers, and gets us
further towards RFC-123.
=> Use GitHub Actions, not Jenkins, for CI

source/manual/howto-copy-postgresql-between-machines.html.md
I recently had to do this to copy the (correct) Mapit data from
staging and overwrite the equivalent (incorrect) data on
integration. It was fiddly and worth documenting in case we need
to do something similar again.
(We also don't have SCP / jumpbox proxy particularly well
documented at present; this guide should come in handy wherever
we need to upload or download something from an EC2.
=> Document how to copy PostgreSQL from one machine to another

source/manual/frontend-architecture.html.md
Diagram was updated separately to reflect that frontend applications are not dependent on `govuk_frontend_toolkit` anymore (except for one mentioned in the docs) and `govuk_elements`.
=> Update frontend architecture

source/manual/alerts/email-alerts.html.md, source/manual/govuk-notify.html.md, source/manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html.md
We're starting to use GOV.UK Notify in lots of places (not just Email Alert API), so this updates the docs to make this clearer and start to introduce separation between GOV.UK Notify and Email Alert API in peoples minds.
=> Add some docs on how we use GOV.UK Notify

data/applications.yml, source/manual/cdn.html.md, source/manual/covid-19-services.html.md, source/manual/govuk-notify.html.md
"Citizen" is a very specific term and should only be used when we
specifically mean someone with a particular citizenship. Users of GOV.UK
services are generally not only British citizens but the broader public.
Using more general terms ("people", "public", "members of the public")
instead of "citizen" makes this clear and our docs more inclusive.
=> Use more inclusive terminology (public vs citizen)

app/proxy_pages.rb, config.rb, spec/app/proxy_pages_spec.rb
Add Publishing API docs, App docs, DocumentTypes/Supertypes to search
- Moves this config into a new class 'ProxyPages' so that it can be tested
- Adds a 'title' frontmatter property so that it is indexed by middleman-search
This makes the search far more comprehensive and useful, although it does
slow the initial indexing down a bit, so the 'Loading search index'
message will stick around slightly longer. I think this is worth it for
the improved relevancy of search results, and if it becomes a problem we
can investigate a server-side search/index solution, or make better use
of caching. It should also only be a short term decrease in search speed;
when the latest version of middleman-search-gds is published, we'll
benefit by only indexing the titles of these external pages, not their …
=> Add Publishing API docs, App docs, DocumentTypes/Supertypes to search

source/manual/govuk-app-domain-handling-during-migration.html.md
=> Review "app_domain handling in GOV.UK during migration to AWS"

source/manual/covid-19-services.html.md
The process for managing deployment secrets in the COVID-19 services differs from other GOV.UK applications, therefore adding a link to the relevant documentation so anyone searching for "secrets" will be able to find it.
=> Add link for docs on configuring secrets to COVID-19 services page

source/manual/make-github-repo-private.html.md
We can use GitHub actions to do useful things like CI on short-lived private repos. This probably means that enabling branch protection is worth it unless it's for a very short-lived branch.
govuk-lint has been retired in favour of rubocop-govuk, so I've replaced that instruction and put it first in the instructions because it's very quick compared to the other steps.
I've added the assets:precompile step because we run this as part of CI currently too.
I reduced the time period on review because it feels like the GitHub actions instruction may be
default by the time we review again.  (I hope this ages well)
=> Update private repo instructions

source/manual/make-github-repo-private.html.md
- Needed a blank line between the bullets and the main text.
- I also took the opportunity for some rewording.
=> make-github-repo-private: Fix bulleted list Markdown rendering

source/layouts/manual_layout.html.erb
There is no 'Icinga alerts' section on manual.html, as alerts are
their own special thing. We already have logic in the manual_layout
template to do something different with Icinga Alerts, so it doesn't
seem controversial to add another conditional.
I did consider removing all 'section: Icinga alerts' lines from the
docs under /alerts, as they are ALL the same and we can infer it
from the path. But that feels like a future optimisation. In the
meantime I just want to stop linking to an anchor point that
doesn't exist.
Before:
After:
Trello: https://trello.com/c/KNesH0LZ/1939-3-improve-documentation-for-email-alert-api
=> Stop generating 'Icinga alerts' breadcrumb for non-existing anchor

config/tech-docs.yml
- This is good practice, for "no link left behind", and infinitely easier than deploying Puppet across all three environments to fix the alert link itself.
=> Redirect manual/alerts/email-alerts.html to its new location

source/manual/covid-19-services.html.md
We've added prometheus/alertmanager alerts, so this should serve as a runbook for people responding to alerts.
https://trello.com/c/UI6sYR5Y/382
=> Add alerting section to covid-19 services

source/manual/errors.html.md
https://trello.com/c/Uzpw1bDA/243-document-how-error-pages-work-on-govuk
Previously I found this manual hard to read, because the policy at
the top only applied to two of the subsequent sections: most errors
are *not* reported to Sentry. Most of the linked URLs also did not
work for me, and seem largely unnecessary/verbose.
This rewrites the manual to surface the two approaches we have for
errors more concisely, while maintaining the original policy of the
associated RFC. Shortening this general manual about 'errors' will
also allow for a planned addition that describes what happens when
an application errors on GOV.UK (this will be in a future PR).
=> Rewrite errors manual to give the big picture

source/manual/uptime-metrics.html.md
Loadbalancing means that even if a healthcheck fails, the application itself should still be available. We should explain this. 
[Trello card](https://trello.com/c/H51Pcoip/1997-add-note-about-loadbalancing-to-uptime-metrics-docs)
=> Add note about loadbalancing

source/manual/uptime-metrics.html.md
The dashboard is only available to VPN users - and doesn't add value by being embedded here. So let's remove it. 
[Trello](https://trello.com/c/O7Ktz17S/1998-remove-embedded-dashboard-from-developer-docs)
=> Remove embedded dashboard

Rakefile, app/external_doc.rb, source/manual/github.html.md.erb
https://github.com/alphagov/govuk-developer-docs/pull/2519 tests passed but the subsequent [building of the docs in Jenkins](https://deploy.publishing.service.gov.uk/job/deploy-developer-docs) broke.
I've fixed each issue one-by-one, and then added a build instruction to the GitHub Action config to prevent this sort of thing from happening again. This will slow down future PRs slightly, as now we're testing _and_ building, but we can be confident we haven't broken anything (and this also paves the way for post-processing, e.g. checking that all markdown has successfully been parsed into HTML).
I was a little worried we might hit our GitHub API limit with this but [GitHub Actions create a new token on every run](https://help.github.com/en/actions/configuring-and-managing-workflows/authentic …
=> Fix build issues introduced in README-ingestion

source/manual/retiring-an-application.html.md
The dev VM section was removed previously, so we don't need a separate heading for GOV.UK Docker here
=> Remove unnecessary heading

source/manual/architecture-deep-dive.html.md, source/manual/errors.html.md
https://trello.com/c/Uzpw1bDA/243-document-how-error-pages-work-on-govuk
=> Document how we serve error pages on GOV.UK

spec/app/proxy_pages_spec.rb
Rather than indexing the contents of application_template.html.md.erb,
which is more of a 'dashboard' and has little indexable value,
we pass an override of `content: ""` to only index by title,
which keeps the search light and fast.
I've now tweaked the tests to document this properly in code,
and also added a missing test for email_alert_api_docs.
Tangentially related Trello: https://trello.com/c/rzunnimb/143-automatically-consume-all-govuk-repo-readmes
=> Improve ProxyPages spec tests

source/manual/email-alert-api-callback-from-notify-fails.html.md, source/manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html.md
https://trello.com/c/IAj6XWFo/309-create-a-report-to-show-the-content-changes-that-have-triggered-notifications
Depends on: https://github.com/alphagov/email-alert-api/pull/1281
These were changed in the recent rake task reshuffle [1].
[1]: https://github.com/alphagov/email-alert-api/pull/1281
=> Sync task names with Email Alert API

source/manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html.md
https://trello.com/c/IAj6XWFo/309-create-a-report-to-show-the-content-changes-that-have-triggered-notifications
These were incorrect and unfinished in
f569c446c9a6ee16af27f016c4326a1cae698c9a.
=> Fix Email Alert API rake task references

data/applications.yml, spec/app/app_docs_spec.rb
See https://docs.publishing.service.gov.uk/apps/ckanext-datagovuk.html:
This adds the missing alias.
=> Adds tests for the 'aws_puppet_class' method and fixes missing alias

source/manual/manage-sign-on-accounts.html.md
I originally intended to make a separate doc for this but there is
a lot of crossover with the 'create a user account' process so
decided to encapsulate all the info in one doc.
=> Document creating an API user and token using Signon

source/manual/add-a-pingdom-check.html.md
This documentation is produced following a few meetings we've had about
the role Pingdom plays in our monitoring. I felt the most appropriate
place to capture this is in documentation for when you are adding a new
alert as that is the time when you need to consider these things.
Some follow-up work that pairs with this documentation is:
- We will be removing the checks in Puppet that checks are set, this is
very out of date and there isn't an obvious way to ensure this stays
up to date (ideally we'd instead automate populating Pingdom)
- We will remove a number of checks that seemed to not offer any
additional external insights.
=> Add documentation on how to add a Pingdom Check

data/applications.yml, spec/app/run_rake_task_spec.rb
With the AWS migration of publishers, we need to change the location of the publishers to AWS in the developer docs.
=> aws migration publishers

app/github_repo_fetcher.rb, app/proxy_pages.rb, spec/app/github_repo_fetcher_spec.rb, spec/app/proxy_pages_spec.rb
When we click 'View source', we expect it to take us to the main
document representing the page, so that we can easily edit the
information.
Until now, external docs' 'View source' link simply took you to
external_doc_template.html.erb, which is not a very useful
workflow.
We now bubble up the original source URL from the GitHub API
response so that we link to the right place.
Trello: https://trello.com/c/z3wOzJZS/165-create-one-way-to-import-api-docs
=> Set source_url for external docs

source/manual/development-pipeline.html.md
https://trello.com/c/4YxwfpDs/163-consolidate-and-update-dev-docs-for-deployment-to-mention-cd
I debated adding another warning inside the "Deployment" section,
but that would undermine the need to know about it *before* merging.
=> Add warning about Continuous Deployment

source/manual/development-pipeline.html.md
https://trello.com/c/aW59k3Tf/170-activate-continuous-deployment-for-the-publishing-api
Introduced in: https://github.com/alphagov/govuk-saas-config/pull/49
=> Document restriction on merging PRs

app/external_doc.rb
```
Error processing resource for index: apps/licensify.html
undefined method `force_encoding' for nil:NilClass
/var/lib/jenkins/workspace/deploy-developer-docs/app/external_doc.rb:53:in `parse'
```
Not sure why this wasn't caught in the PR checks, as we
simulate a full build. However, in the interests of fixing
the issue quickly, we can force `markdown` to be a string if
it is a `nil`.
=> Fix issue where 'markdown' is nil and docs don't deploy

source/manual/howto-ssh-to-machines.html.md
Addresses https://github.com/alphagov/govuk-developer-docs/issues/2632
=> howto-ssh-to-machines manual steps: govuk_node_list seems to require -c option now

source/manual/architecture-deep-dive.html.md
`[AWS S3 bucket] (read ["Assets: how they work"])`
Was being converted to:
`<a href="read [\"Assets: how they work\"]>AWS S3 bucket</a>`.
I.e. it was mistakingly treating the text following the first `]` as the URL.
We should look at why this parsing issue happens - whether it's down to
a bug in CommonMarker, or our markdown, or the dev docs.
> <img width="492" alt="screenshot demonstrating the issue" src="https://user-images.githubusercontent.com/5111927/85716447-5ac6d400-b6e4-11ea-8a89-087270c08180.png">
=> Fix broken link due to markdown parse error

source/manual/alerts/email-alert-api-delivery-attempt-status.html.md
This is added as it does not seem to be common knowledge that these emails will not be retried and this requires manual steps.
This is added as an incident action step following [Mali Travel Advice Incident](https://docs.google.com/document/d/1PqsO0N_WIUqtVOLMeB_DrO5BvsQcuSXF4POswpVw8gY/edit?ts=5efb3894#heading=h.p3b9bm9twi19), hopefully future work Notifications team has planned will mean we can later remove this as they could be retried automatically.
=> Add note that technical_failure emails will not be retried automatically

source/manual/dns.html.md
I noticed this was missing a link when viewing this doc and as this was the link used elsewhere I assume it's the link intended when introduced in 40fe29c4
=> Add missing link to security incidents

source/manual/howto-manually-remove-assets.html.md
GDS CLI is now the documented method for SSHing into machines, therefore updating the documentation to use that when manually removing assets.
=> Use GDS CLI for connecting to asset master

Rakefile, app/app_docs.rb, data/applications.yml
This PR fixes the errors found by the `verify_deployable_apps` and `check_puppet_names` rake tasks, and adds these tasks to the `default` task so that they can catch configuration errors as soon as they're introduced.
=> Make verify_deployable_apps and check_puppet_names abort on error

source/manual/development-pipeline.html.md
I've also taken the opportunity to restructure the doc slightly, referring to GitHub Actions and Continuous Deployment which we're now encouraging the use of.
=> Update 'deployment' docs to link to Continuous Deployment slides

source/manual/incident-reports.html.md
The incident report template has changed to be GDS-wide, rather than GOV.UK specific.
I'm not convinced there is a user need to have the template duplicated in the developer docs, but since it is already there, I assume someone has decided there was, so I've updated it accordingly.
Trello card: https://trello.com/c/o9lLuXK1
=> Update "Write an incident report" page

source/manual/transition-a-site.html.md
Adds detail about updating the configuration for an already-transitioned site because it wasn't covered
[Trello](https://trello.com/c/doczOPYo/2047-changes-to-transition-config-for-two-beis-sites)
=> Document changing configuration of a transitioned site

source/manual/alerts/high-priority-tests.html.md, source/manual/alerts/smokey-loop-tests.html.md
Related to: https://github.com/alphagov/govuk-puppet/pull/10499
Previously we deprecated priorities in Smokey [1]. This manual was never
specific to high priority tests in the first place. I've also done a
general review of this manual, which was confusing because it conflated
alerts for the manual Smokey job, and the Smokey loop.
[1]: https://github.com/alphagov/smokey/pull/693
=> [DO NOT MERGE] Remove priorities from Smokey alert manual

source/manual/alerts/email-alert-api-unprocessed-content-changes.html.md, source/manual/alerts/email-alert-api-unprocessed-messages.html.md, source/manual/email-notifications-how-they-work.html.md
Adds new latency thresholds and updates the doc with some useful rake
tasks that were recently added.
Previews:
* https://github.com/alphagov/govuk-developer-docs/blob/update-unprocessed-alerts-docs/source/manual/alerts/email-alert-api-unprocessed-messages.html.md
* https://github.com/alphagov/govuk-developer-docs/blob/update-unprocessed-alerts-docs/source/manual/alerts/email-alert-api-unprocessed-content-changes.html.md
---
Depends on:
https://github.com/alphagov/email-alert-api/compare/increase-latency-thresholds?expand=1
Trello:
https://trello.com/c/Li8Zo03f/381-relax-the-thresholds-for-content-change-and-message-alerts
=> Update unprocessed email docs

source/manual/test-and-build-a-project-with-github-actions.html.md
This removes the step to install yarn, as it appears that's already installed with `actions/setup-node@v1`. See the section about ]publishing with yarn in the README](https://github.com/actions/setup-node#usage).
=> Remove install yarn from GitHub Action example

source/manual/alerts/email-alert-api-unprocessed-content-changes.html.md, source/manual/alerts/email-alert-api-unprocessed-messages.html.md
Fixes mis-parsed links on:
* https://docs.publishing.service.gov.uk/manual/alerts/email-alert-api-unprocessed-content-changes.html
* https://docs.publishing.service.gov.uk/manual/alerts/email-alert-api-unprocessed-messages.html
=> Fix links on unprocessed content changes and messages pages

source/manual/query-cdn-logs.html.md
This adds another example query that displays the number of requests for a particular GOV.UK path and groups them by status and hr timestamp.
=> Add another example SQL query for CDN logs

source/manual/debian-packaging.html.md, source/manual/hmrc-paye-files.html.md, source/manual/howto-copy-postgresql-between-machines.html.md, source/manual/howto-replace-an-assets-file.html.md, source/manual/howto-upload-an-asset-to-asset-manager.html.md
I also tweaked the docs a bit:
- use machine `:1` for cases where you need to copy things to and then ssh into a consistent machine, rather than noting down IPs
- use `/tmp` instead of `/home/<username>`, because it's less typing
---
[Trello card](https://trello.com/c/QcGSCmcL/130-support-scp-with-govuk-connect)
=> Replace use of scp with govuk-connect

data/applications.yml
It's more helpful that #govuk-datagovuk gets to see information about these Dependabot PRs. This is already the case for Find and Publisher.
=> Set the dependencies team for ckanext-datagovuk

source/manual/govuk-env-sync.html.md
Trello: https://trello.com/c/koo6gJov/355-increase-visibility-of-sentry-alerts-for-email-apps-and-services
In https://github.com/alphagov/govuk-puppet/pull/10520 we updated the
timings of the traffic replay to reflect the increasing time the
data-sync takes. This brings our docs into sync. I also added UTC into
this since it isn't clear that these timings aren't in Europe/London
time as we might expect.
=> Update gor replay timings

source/manual/alerts/rebooting-machines.html.md, source/manual/alerts/security-updates.html.md
https://trello.com/c/5JpkmLwB/940-fix-not-alerting-about-outstanding-security-updates
Previously this was mixed up with rebooting guidance. Although
the original doc had guidance about choosing when to reboot, this
came from a legacy import [1] and it's unclear if we really need
to check the details of updates that have already been applied.
Note: the original "/var/log/unattended-upgrades" path suggestion
was wrong; the new doc has a corrected version.
[1]: https://github.com/alphagov/govuk-developer-docs/commit/5547bb99c17bbf9acc5841272596d585a61018e6
=> Add new doc to describe auto security updates

Gemfile, Gemfile.lock, app/content_schema.rb
We rebuild gh-pages every hour, and without the seed this means
regenerating entire schema examples for every content schema
type. This leads to ~50,000 line changes per commit, which
quickly makes govuk-developer-docs a very heavy repo to work
with.
We don't care about producing a different random schema on
every run; only that the example itself is easy to generate.
Applying a simple seed (here arbitrarily assigned '777') makes
govuk_schemas generate the same schema example every time we
call it (from v4.1.0 onwards).
Trello: https://trello.com/c/nEP3URQF/171-host-the-dev-docs-on-github-pages
=> Use seed to generate predictably random schema examples

source/manual/alerts/high-nginx-5xx-rate.html.md
https://trello.com/c/ciBPNeOg/945-stop-alerting-for-app-5xx-spikes
Previously we asserted a 'definitely broken' or 'too high' threshold
existed for Nginx, in a variety of circumstances. The reality is that
this alert is just an indicator of a potential problem. This renames
the alert doc to better reflect its indicative nature.
=> Rename nginx 5xx doc to avoid 'too high'

source/manual/related-links.html.md
This PR updates the guidance for related links, adding further detail surrounding managing related links within Content Tagger and what to do should related links need to be rolled back.
=> Update guidance for related links

data/applications.yml
Release app in production is now in AWS as of a few months ago.
=> Update Release app hosting provider

source/manual/govuk-notify.html.md
This updates the figure for how many we send, and links to the new dashboard
[Trello card](https://trello.com/c/r9jvKKIX/2068-update-developer-docs-about-notify)
=> Update Notify usage number and link to dashboard

CNAME
This is required to enable GitHub Pages with a custom domain.
Details on the file formatting:
https://docs.github.com/en/github/working-with-github-pages/troubleshooting-custom-domains-and-github-pages\#cname-errors
=> Add 'docs.publishing.service.gov.uk' CNAME for GitHub Pages

.github/workflows/ci.yml, CNAME
1) CNAME should be on gh-pages, not master.
2) the hourly build overwrite the CNAME on gh-pages, so we
need to add it to the actions-gh-pages config. See:
https://github.com/peaceiris/actions-gh-pages\#%EF%B8%8F-add-cname-file-cname
Trello: https://trello.com/c/nEP3URQF/171-host-the-dev-docs-on-github-pages
=> Fix gh-pages CNAME configuration

source/manual/dns.html.md
I missed the part where I had to deploy to two DNS providers, so now have an explicit
warning about that.
I also had to figure out my role was poweruser - we may as well offer this hint in the docs.
=> Clarify deployment documentation

source/manual/aws-iam-key-rotation.html.md
We now have a number of keys documented in the spreadsheet, and the IAM
roles have been around long enough that we're starting to re-rotate some keys
we've already rotated in the past. It therefore makes sense to point the dev
to the spreadsheet in the first instance, to use it as a guide.
I've updated the last_reviewed_on, but have also tightened up the 'review_in' to
one month from now, as I think we should go into more detail describing where
to find and rotate keys in third-party services. There is a [Trello card][card] for
that, which I hope 2nd line get to in the next few weeks.
[card]: https://trello.com/c/q4gOMIP3/953-rotate-aws-logginglogit-read-iam-key
=> Move Google spreadsheet reference earlier in the documentation

source/manual/alerts/content-data-api-app-healthcheck-not-ok.html.md.erb
- Explain what ETL stands for (was missing from the dev docs)
- Link to where the cronjobs are defined and explain why jobs are
run at different times
- Link to the jobs themselves
- Document the undocumented 're-run' job and why it exists.
Trello: https://trello.com/c/2wiNWp19/2065-investigation-content-data-api-app-healthcheck-not-ok-timebox-2-day
=> Improve ETL documentation

source/manual/govuk-notify.html.md
This updates the GOVUK Notify docs to include the GOV.UK service used by [Feedback](https://github.com/alphagov/feedback/pull/1057) and ant other public e-mails not sent via
email-alert-api.
[Trello](https://trello.com/c/zs2mHfAM/2061-3-feedback-app-uses-its-own-notify-account)
=> Add govuk_public notify service for Feedback app

source/manual/data-gov-uk-supporting-ckan.html.md
Updates the doc to include some support information which includes what
to do if you find a bug or security vulnerability. I haven't reviewed
the full doc as I don't believe I'm the best person to do this.
Trello:
https://trello.com/c/FABYywyd/433-update-2nd-line-documentation-supporting-ckan-to-include-correct-ckan-email-address-if-theres-a-security-incident
=> [INCIDENT ACTION] Update CKAN support doc

data/applications.yml, source/manual/alerts/signon-app-healthcheck-not-ok.html.md
Signon has now been migrated to AWS. Update docs to
reflect this.  Also signon was listed as a dependency
of signon in one doc, I assumed this was an error and
corrected it.
=> Update Docs After Signon Migration

source/manual/govuk-notify.html.md
Includes information on Notify's daily email sending limit with Amazon
SES.
=> Update govuk-notify doc

source/manual/rename-a-country.html.md
- After https://github.com/alphagov/travel-advice-publisher/pull/937, Travel Advice Publisher won't have database migrations any more (see the PR description for more details).
- As a result, in that PR there's a Rake task to rename a country: `bundle exec rake country:rename[<old_country_slug>,<new_country_slug>]`.
=> rename-a-country: Amend Travel Advice Publisher steps

source/manual/aws-iam-key-rotation.html.md
It turns out it's not as simple as rotating security credentials when rotating SMTP credentials.
See https://github.com/alphagov/govuk-secrets/pull/1032 for an example.
=> Add a section about rotating SES SMTP credentials

source/manual/alerts/email-alert-api-high-queue-latency.html.md
We decided to start monitoring the `delivery_transactional` queue in
[this PR][monitor] and so we need some documenation on what to do if we
see this alert. These are being processed super quick on average (under
a second).
There has been a lack of documentation for the existing queue checks but
as we're planning to remove them all (apart from `delivery_transactional`)
in future work we don't need to document these here too.
Trello:
https://trello.com/c/HwvZx0V9/456-update-the-queue-latency-check
[monitor]: https://github.com/alphagov/govuk-puppet/pull/10574
=> Add some info for delivery_transactional latency

markdown_lint.rb, source/manual/emergency-publishing.html.md
Adds a missing step to the emergency banner publishing instructions.
Also removed the hardcoded numbering of lists and replaced all items with `1.`.  This gets parsed by Github (or any other markdown renderer) as a numbered list with the numbers added automatically.  This reduces the number of lines included in a diff when items are added or removed from the list.
Trello card: https://trello.com/c/A96YxL0F
=> Update instructions for publishing emergency banner

source/manual/howto-remove-invalid-about-page-drafts-from-world-organisations.html.md
A [new Rake task](https://github.com/alphagov/publishing-api/pull/1840) was recently introduced to the Publishing API to remove invalid CorporateInformationPage drafts.
This adds some documentation for the task.
[trello](https://trello.com/c/PH2gH5SN/2075-1-document-removeinvalidworldorgdrafts-rake-task)
=> Document Publishing API remove_invalid_worldorg_drafts rake task

data/applications.yml
The find support app has been handed over the the coronavirus smartanswers team,
so the dependapanda slack alerts should be moved too.
=> Update find-support app info

source/manual/alerts/email-alert-api-unprocessed-content-changes.html.md, source/manual/alerts/email-alert-api-unprocessed-messages.html.md
The warning thresholds are removed [here], also makes the two docs a bit
more consistent with each other.
Trello:
https://trello.com/c/BT5x4iAU/457-update-warning-critical-alerts-for-messages-and-content-changes
[here]: https://github.com/alphagov/govuk-puppet/pull/10580
=> Remove redundant warning threshold info

source/manual/alerts/rebooting-machines.html.md
- rebooting-machines: Remove special instructions for `docker-management-1`
- These don't add anything more than we were getting from the Icinga
alert to reboot this machine in-hours. And it was right at the bottom of
all the things about rebooting Carrenza machines which are becoming
increasingly irrelevant.
- reboots-required: De-emphasize "most things are out-of-hours"
- This is apparently untrue, now. A lot of things have been changed to
'careful' which means 'in-hours', including `cache` boxes which
doesn't at all surprise me given how careful we are with them.
- Woohoo, less manual work for on-call to do.
- Source: Pete and I went to do some manual out-of-hours reboots to find
that the alert was only saying about in-hours ones. So we needn't have
both woken up early.
=> reboots-required: Slightly better docs

source/manual/mysql.html.md
Add deprecation note and remove reference to "whitehall-mysql-backup-1.backend"
as this refers to a machine in Carrenza, and Whitehall has now been
migrated to AWS.
I have not yet removed this entire documentation page as we need to investigate if mysql is
relevant to Performance Platform (the last app left on Carrenza).
=> Review MySQL backups

source/manual/clone-mysql-slave.html.md
Added deprecation note. This documentation page should be
deleted after Carrenza is fully shutdown/or we are sure
that nothing is using MySQL (e.g. Performance Platform).
=> Review Clone a MySQL instance

source/manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html.md, source/manual/rename-a-country.html.md
https://github.com/alphagov/email-alert-api/pull/1352#discussion_r465690000
Relates to: https://github.com/alphagov/email-alert-api/pull/1371
=> Update rake task references for Email Alert API

source/manual/alerts/email-alerts-travel-medical.html.md, source/manual/email-troubleshooting.html.md
This updates the docs to take into account work to remove the courtesy
copies email box from the checks.
Depends on:
https://github.com/alphagov/email-alert-monitoring/pull/67
Trello:
https://trello.com/c/kfZC9tes/455-improve-drug-and-travel-advice-checks
=> Update travel advice & medical safety alert docs

source/manual/email-troubleshooting.html.md
https://trello.com/c/Xd47oJKZ/415-remove-the-deliveryattempt-model
=> Remove overly generic email troubleshooting steps

source/manual/transition-a-site.html.md
Relates to commit b4e5e77b, forgot to change this CNAME record for the AKA step too, also added a line of context in case a reader is confused to find a different CNAME compared to previously migrated domains, or if there's any potential for a clash with older docs (Google Docs from 2017 are still doing the rounds for example)
=> Add new CNAME to consider AKA domains step

source/manual/deploy-puppet.html.md
It's no longer possible to deploy Puppet on the Development VM as it no longer exists. So the recommended solution is to deploy to integration.
[Trello Card](https://trello.com/c/uDzBSJ4e/194-document-how-to-test-puppet-changes)
=> Add instructions on how to deploy Puppet branches

app/github_repo_fetcher.rb, data/dashboard.yml, spec/app/github_repo_fetcher_spec.rb
We save around 70 API calls by curling the URL of each
app README directly. This helps prevent hitting API resource
limits locally, as well as making the code easier to read
since there is no base64 conversion required any more.
It also ensures that we don't accidentally expose any
private repo information. If we use the API and the relevant
access token, we could potentially download private repo content
which we wouldn't want to expose on the Dev Docs. By fetching
the public GitHub URL directly, if it's private we'll run
into a 404.
Finally, this PR removes deprecated logic around organisation names
on GitHub, which is no longer needed now that everything is under
@alphagov. Other parts of the code (README and docs/ ingestion)
make this assumption, so `repo` should too.
Trello: …
=> Convert GitHub API calls to HTTP requests

.github/workflows/ci.yml, source/templates/application_template.html.md.erb
We have some [build-time logic](https://github.com/alphagov/govuk-developer-docs/blob/130c6ac6f87f1fe5e6402a534a73ed0128b16a52/source/templates/application_template.html.md.erb#L168-L176) which checks for the presence of a GITHUB_TOKEN ENV variable
before attempting to call `application.readme`. This is so that
devs working on their local machine can compile the dev docs
without having to specify a token, and without hitting the GitHub
API limit.
This commit should fix issues like we're seeing on https://docs.publishing.service.gov.uk/apps/imminence.html:
> <img width="594" alt="Screenshot showing error message 'Error: cannot fetch README without `GITHUB_TOKEN`.'" src="https://user-images.githubusercontent.com/5111927/89397591-f1d17380-d707-11ea-8edb-938da8f001ec.png">
Running …
=> Expose GITHUB_TOKEN as ENV variable when deploying

source/manual/alerts/publisher-unprocessed-fact-check-emails.html.md
By forwarding the message rather than copying it into Publisher, it retains the status of a fact check response (rather than an internal note)  and updates the edition's status in Publisher to "Fact check received" which alerts the content designer to the response having been received.
=> Update process for unprocessed fact check emails

source/manual/howto-manually-remove-assets.html.md
The URL contained the wrong rake task name, so didn't work if you tried to run the task without checking the task name.
=> Fix URL for Whitehall asset removal rake task

data/applications.yml
This is to switch ownership and dependabot notifications for these apps to the notifications team that has been running for a few months now.
=> Notifications team look after email apps

data/applications.yml
`dependencies` was added to applications.yml in 80b672a with very little context
('bla'), and appears to be required by other files in that commit (AppDependencyGenerator,
AppDiagramGenerator, etc), which were once used to generate diagrams.
Those generators and diagrams no longer exist in the dev docs, but for some reason
the application dependencies config still does. This isn't ordinarily a bad thing,
but if it isn't being used, it's not serving any useful purpose as documentation,
and risks falling out of date. It also looks somewhat buggy in the first place
(notice that service-manual-publisher has a dependency of... service-manual-publisher).
Let's just delete this unused config to make the config file simpler.
=> Remove unused `dependencies` config

config/tech-docs.yml
- My bad, should have done this in 19f539aece1fb507a4bf62d092f30f707d9e5378.
=> Redirect old AWS account setup docs to new Getting Started page

source/manual/alerts/user-monitor.html.md
- As of https://github.com/alphagov/govuk-puppet/pull/10691.
=> alerts/user-monitor: The Jenkins job runs in AWS now

source/manual/licensing.html.md
Copies everything with the exception of the Contact section, which
is likely to be outdated now anyway. Nothing else looks particularly
sensitive so can exist in the public domain.
Fixes #1777.
=> Copy over Licensing documentation from Legacy Ops Manual

source/manual/configure-github-repo.html.md
the jenkins job has been moved from integration to production in PR: https://github.com/alphagov/govuk-puppet/commit/a679f00f7cefc26e18e9e6e92d4a8fbd81788934 so need to update the job link in the docs too.
=> update jenkins used to deploy saas config

source/manual/data-gov-uk-supporting-ckan.html.md
Useful for Zendesk queries where an organisation
wants a list of all their datasets, whether
public, drafted or deleted
=> Add documentation for getting CKAN dataset list

source/manual/howto-replace-an-assets-file.html.md, source/manual/whitehall-file-stuck-uploading.html.md
This can happen if there is a particularly large zip collection uploaded
by a user. I have also updated the documentation on replacing an
existing file upload to make it clear that this is not the same as
uploading a new file.
=> New documentation to handle stuck Whitehall uploads

.github/dependabot.yml, Gemfile, Gemfile.lock, app/string_to_id.rb, config.rb
Redcarpet has an [issue from 2015][issue] whereby shortcut
reference links get confused. For example:
```md
See [foo] (example: bla)
[foo]: /bar.html
```
This was being parsed as `See <a href="(example: bla)">foo<a>`,
instead of: `See <a href="/bar.html">foo</a> (example: bla)`
Changing `[foo]` to `[foo][]` explicitly marks the link as a
shortcut reference, fixing the issue, so I originally proposed
that we enforce such a style using Markdownlint. Unfortunately,
Markdownlint has no such rule, so I [raised a proposal][proposal]
with them.
Talking it through with @kevindew, we realised we could swap out
the markdown parsing library instead. Kramdown seems the obvious
choice, given that is [the library we use for GovSpeak][govspeak],
and it can be swapped in relatively easily.
The only …
=> Switch to using Kramdown for parsing markdown

Gemfile, Gemfile.lock
These are the necessary changes for Ruby 2.7.1
I've left the Ruby version as 2.6.6 since there is an automatic script to update all Ruby versions at once. 
There are still some deprecation errors: 
Faraday: 
- Fix merged but not deployed
- https://github.com/lostisland/faraday/commit/722821fab79faa65a1dd2ec0ed1667ed593f06fe
Rspec Expectations
- Fix merged but not deployed 
- https://github.com/rspec/rspec-expectations/pull/1187
Open API parser
- PR open but not merged
- https://github.com/alphagov/tech-docs-gem/pull/125
=> Upgrade to ruby 2.7.1

source/manual/documents-are-published-but-links-arent-updated.html.md, source/manual/documents-arent-live-after-publishing.html.md, source/manual/help-with-publishing-content.html.md, source/manual/publish-special-routes.html.md, source/manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html.md, source/manual/rename-a-country.html.md, source/manual/republishing-content.html.md, source/manual/restart-application.html.md, source/manual/run-ab-test.html.md, source/manual/running-rake-tasks.html.md
Updated our links to rake tasks in Carrenza to AWS, as our apps
are now in AWS.
As well as making these changes I have:
- updated any broken links found
- reviewed some of the docs and updated the review date
=> Update Carrenza links to AWS

source/manual/alerts/smokey-loop-tests.html.md
Link together a few repos and documents in one place to help track down pages
- link to fabric scripts repo where the docs instruct to run fabric scripts to help people who don't have it set up on their machine.
- Link relevant docs on fixing smokey-loop errors
=> Add link for smokey doc

config.rb
In #2785 we changed the parsing engine from Redcarpet to
Kramdown, but this slipped through. Newlines were now being
treated as explicit newlines (`<br>`).
Many of our markdown files split sentences across multiple lines
for clarity in diffs, so we don't want to actually render them
across multiple lines.
Before:
> <img width="400" alt="Screenshot 2020-09-24 at 18 36 48" src="https://user-images.githubusercontent.com/5111927/94180237-9f097200-fe95-11ea-9ad9-2a64b0950e1b.png">
After:
> <img width="400" alt="Screenshot 2020-09-24 at 18 36 40" src="https://user-images.githubusercontent.com/5111927/94180259-a3ce2600-fe95-11ea-8c43-23d58462415f.png">
=> Don't hard-wrap newlines when rendering markdown

source/manual/howto-add-organisation-brand-colour.html.md
This should hopefully make it a smoother process in adding other
brand colours in future.
Trello card: https://trello.com/c/CWcRNQuF/2128-add-docs-on-how-to-add-brand-colour-for-organisations-in-whitehall
=> Add doc on adding an organisation brand colour

source/manual/conventions-for-rails-applications.html.md
This reflects that we now recommend using jasmine_selenium_runner directly and integrating govuk_test as part of that configuration. It also corrects some capitalisation on Jasmine.
=> Update Jasmine configuration reference

source/manual/local-frontend-development.html.md
- Bump review date
- Example changed from `frontend` to `government-frontend` to be less confusing about "frontend apps" vs "the frontend app"
- Docker guidance - the `bundle install` command should be run inside the Docker container
- Added comment showing the `govuk-docker-up` shortcut in example
- Removed reference to `vim` because different people use different tools
=> Update local frontend development docs

source/manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html.md, source/manual/sidekiq.html.md
Minor updates to the docs on how to receive emails sent from integration or staging. 
- Remove the instruction to add your email to hieradata, It's only necessary to add your email to the hieradata for aws.
- Correct the link to the rake task that deploys puppet.
- Correct the link to the grafana dashboard for sidekiq email processing.
=> Update email docs

source/manual/rename-a-country.html.md
https://trello.com/c/J6DOuBBp/569-2ndline-country-updates
Related to: https://github.com/alphagov/email-alert-api/pull/1418
Previously the Specialist Publisher section of the manual had quite
a lot of steps. This combines some of the associated steps together,
and adds a final step to fix any affected email subscriber lists.
=> Rewrite / extend doc to rename specialist country

source/manual/rename-a-country.html.md
https://trello.com/c/J6DOuBBp/569-2ndline-country-updates
This makes a couple of minor improvements:
- Suggest quotes around the new title for email subscriber lists,
to avoid the task failing if the title contains spaces.
- Clarify "slug" as "country slug" when updating email subscriber
list matching criteria.
=> Tweak rake tasks in rename country doc

data/applications.yml
What
Remove the coronavirus services apps from dependapanda.
Why
The find support service has been migrated and is now a smart answer. The
vulnerable people service has been rebuilt by #vulnerable-people-services
team, and the business volunteer service has been replace with a guidance
page.
[Trello](https://trello.com/c/mMboxOo8/570-remove-old-coronavirus-services-apps-from-dependapanda)
=> Remove corona services apps from dependapanda

source/manual/architecture-deep-dive.html.md, source/manual/dns.html.md
The Jenkins job is being moved from Carrenza Production to AWS Production with new URL:
https://deploy.blue.production.govuk.digital/job/Deploy_DNS
This PR updates the URL in this repo.
Ref:
1. [Trello Card](https://trello.com/c/ti7AGfnE/3894-move-jenkins-deploy-dns-to-aws-production)
2. [govuk-puppet](https://github.com/alphagov/govuk-puppet/pull/10772)
=> Update Deploy_DNS Jenkins job URL

source/manual/alerts/email-alert-api-high-queue-latency.html.md
https://trello.com/c/7QA5eAoC/483-do-an-audit-to-check-for-any-more-work-to-do-on-alerts-epic
This was changed in [1].
[1]: https://github.com/alphagov/email-alert-api/pull/1423
=> Fix link to Email Alert API queue info

source/manual/components.html.md
Not much has changed since the last update. Replacing the Heroku URL with the service subdomain URL for the component library.
=> Update frontend components

source/manual/govuk-notify.html.md, source/manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html.md
Trello: https://trello.com/c/Xd47oJKZ/535-remove-the-deliveryattempt-model
In https://github.com/alphagov/email-alert-api/pull/1438 there are a number of renames of Email Alert API concepts. This adapts to these changes by replacing outdated text and links
=> Adapt to Email Alert API renaming

source/templates/application_template.html.md.erb
GitHubRepoFetcher returns 'nil' if a README.md is missing from
the requested repo. But when we pass it to ExternalDoc.parse,
it doesn't know what to do with 'nil' and the build fails.
We're not seeing errors on CI as the README inclusion isn't
working at the moment (no ENV['GITHUB_TOKEN'] detected),
but it is failing locally on
https://github.com/alphagov/ckanext-datagovuk
(this has a README.rst, rather than a README.md).
=> Defend against repos which are missing a README.md

source/manual/howto-ssh-to-machines.html.md
I had to do this recently (and not for the first time) and couldn't remember what follows the IP address.
It's useful having `.eu-west-1.compute.internal` documented here.
I've reviewed the rest of the doc and double-checked the instructions in 'CLI problems' section still work.
=> Document SSH'ing into specific machines

source/manual/conventions-for-rails-applications.html.md
This records two conventions for GOV.UK Rails applications that don't seem to be previously documented.
The first of these is to configure Rails applications to use London as the time zone. This seems to be a long standing convention that isn't consistently applied to apps (we hit some problems with [co-ordinating the local Coronavirus restrictions](https://github.com/alphagov/collections/pull/1985/commits/35e3cb4850ea72b43f64dd5b207d4f3c4369ad74) due to the lack of this in Collections). I'm taking this opportunity to define what our collective convention is to resolve ambiguities in future.
The second is the approach to organise Gemfiles with a distinct preference to not pin Gems to versions unless there is a clear documented reason to do so. This convention is quite new, it was recently …
=> Document two more Rails app conventions

source/manual/bulk-email.html.md, source/manual/email-notifications-how-they-work.html.md, source/manual/email-troubleshooting.html.md, source/manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html.md
Makes the Notifications team the owners of some email-related pages - they have the most current working knowledge of these things, so are the best team to ensure the docs are accurate.
[Trello card](https://trello.com/c/ardPpkNW/2191-transfer-ownership-of-some-dev-docs-to-notifications-team)
=> Change ownership to Notifications team

source/manual/cdn.html.md, source/manual/related-links.html.md
Following on from [PR](https://github.com/alphagov/govuk-puppet/pull/10796)
where we migrate the Production CDN Jenkins job to AWS, we update the
developer docs to reflect the new links.
Refs:
1. [Puppet PR](https://github.com/alphagov/govuk-puppet/pull/10796)
2. [Trello Card](https://trello.com/c/L3325c8c/3900-migrate-cdn-jenkins-jobs-to-aws-production)
=> Update docs for migration of Production CDN Jenkins jobs

Gemfile, Gemfile.lock, app/github_repo_fetcher.rb, app/proxy_pages.rb, config/tech-docs.yml, helpers/commit_helpers.rb, source/layouts/api_layout.html.erb, source/layouts/manual_layout.html.erb, source/partials/_last_updated.html.erb, spec/app/github_repo_fetcher_spec.rb, spec/app/proxy_pages_spec.rb, spec/helpers/commit_helpers_spec.rb
This PR removes the old "last reviewed on" banner from the bottom of the internally hosted docs. In their place - and as a new feature for the externally hosted docs - there's now a "Last updated" banner at the top of each doc. The date is clickable and links to the commit SHA on GitHub so that the changes can be viewed easily.
"Last updated" on internal docs:
"Last updated" on external docs:
This is phase 1 of removing Daniel the Manual Spaniel. Once the 'last reviewed' date is no longer surfaced visually, there's no point in keeping it - we'll remove the 'last_reviewed' and 'review_in' properties from files and discontinue the spaniel.
Trello: https://trello.com/c/OMBV5qM4/198-retire-daniel-the-manual-spaniel
=> Add 'last updated' banner to internal and externally version controlled docs

.github/workflows/ci.yml
We're right on the cusp of breaching the standard 60 API hits
that are allowed for unauthenticated requests to the GitHub API.
GitHub Actions automatically create a GITHUB_TOKEN for authenticated
requests: https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#using-the-github_token-in-a-workflow
We just need to expose that as an ENV variable to each build task.
Using a token increases our limit to 15000 requests per hour.
Before:
```
2020-10-28T08:24:09.4012886Z x-ratelimit-limit: "60"
2020-10-28T08:24:09.4013490Z x-ratelimit-remaining: "1"
2020-10-28T08:24:09.4014106Z x-ratelimit-reset: "1603877018"
2020-10-28T08:24:09.4014667Z x-ratelimit-used: "59"
```
After:
```
x-ratelimit-limit: "15000"
x-ratelimit-remaining: "14995"
x-ratelimit-reset: …
```
=> Increase rate limits for GitHub API requests

.github/workflows/ci.yml, Gemfile, Gemfile.lock, app/github_repo_fetcher.rb, app/proxy_pages.rb, config/tech-docs.yml, helpers/commit_helpers.rb, source/layouts/api_layout.html.erb, source/layouts/manual_layout.html.erb, source/partials/_last_updated.html.erb, spec/app/github_repo_fetcher_spec.rb, spec/app/proxy_pages_spec.rb, spec/helpers/commit_helpers_spec.rb
This PR is identical to #2784 other than one final commit which fixes a [deployment issue we were seeing](https://github.com/alphagov/govuk-developer-docs/pull/2784#issuecomment-717786517), and caused us to have to [revert](https://github.com/alphagov/govuk-developer-docs/pull/2835).
---
This PR removes the old "last reviewed on" banner from the bottom of the internally hosted docs. In their place - and as a new feature for the externally hosted docs - there's now a "Last updated" banner at the top of each doc. The date is clickable and links to the commit SHA on GitHub so that the changes can be viewed easily.
"Last updated" on internal docs:
"Last updated" on external docs:
This is phase 1 of removing Daniel the Manual Spaniel. Once the 'last reviewed' date is no longer surfaced …
=> Add 'last updated' banner to internal and externally version controlled docs (NEW)

source/manual/removing-a-user-from-puppet.html.md
https://trello.com/c/DRbio3g9/1002-leaver-christopher-baines
CI is now part of the same AWS Integration environment, for which
we have another step to remove people from it.
=> Remove redundant leaver step for old CI env

source/manual/environments.html.md, source/manual/grafana.html.md, source/manual/icinga.html.md, source/manual/remove-machines.html.md, source/manual/screens.html.md
Whilst we still have a lot of Carrenza documentation around [backups](https://docs.publishing.service.gov.uk/manual/alerts/postgresql-s3-backups.html), [connecting to vCloud](https://docs.publishing.service.gov.uk/manual/connect-to-vcloud-director.html), [cloning MySQL instance](https://docs.publishing.service.gov.uk/manual/clone-mysql-slave.html) etc, I'm happy to leave those as they could still be useful until we fully migrate away from Carrenza.
But we should remove references to Carrenza with regards to GOV.UK applications, as we now host everything on AWS. We've updated our Blinken dashboard, Grafana processes, etc, so I've made some modest tweaks here to have our docs reflect reality.
=> Remove outdated/inaccurate references to Carrenza

source/manual/add-translation-whitehall.html.md
Part of the government-frontend and whitehall steps of the process needs to be done before the content-schemas in order to ensure that the content-schema tests pass.
=> Update whitehall translation documentation to match correct process

helpers/commit_helpers.rb, source/partials/_last_updated.html.erb, spec/helpers/commit_helpers_spec.rb
This PR adds some contextual 'awareness' to the "Last updated" banner displayed on docs.
Docs that haven't been updated for more than 6 months come with a warning that the content may be out of date.
Default (unchanged) 'last updated' banner:
Example (new) 'last updated' banner for old docs:
This change is intended to highlight old documentation to readers, such that they proceed with caution if a doc hasn't been updated in a while. It should also encourage the reader to update the doc to 'appease' the banner, giving us more of an incentive to keep content up to date.
Trello: https://trello.com/c/OMBV5qM4/198-retire-daniel-the-manual-spaniel
=> Use "Warning" component to highlight old docs in the "Last updated" banner

source/manual/give-a-content-designer-access-to-github.html.md
A new group has been created to include all GOV.UK people who are github
owners. Anyone on this group should be able to add content designers to
github.
=> Update email used to add content designers

data/dashboard.yml, source/manual/configure-linting.html.md, source/manual/conventions-for-rails-applications.html.md, source/manual/setting-up-new-rails-app.html.md
This sequence of commits represents me ending up rather into a rabbit hole and trying to claw my way out. Initially I intended to just update the Gemfile example of https://docs.publishing.service.gov.uk/manual/setting-up-new-rails-app.html to match https://github.com/alphagov/govuk-developer-docs/pull/2830. However once I started the rabbit hole grew.
A brief summary of things this includes is:
- Adding licence and readme approaches to the Setting up new Rails application guide, this is done to reflect that we no longer have the templates from https://github.com/alphagov/govuk-rails-app-template;
- Creates a new document on how to configure linting for Rails apps;
- Some basic modernisation of examples;
- Replace a couple of usages of `scss-lint-govuk` with `stylelint-config-gds` to …
=> Update guide to setting up Rails app and separate linting to a new document

source/manual/alerts/rabbitmq-dead-nodes.html.md, source/manual/configure-linting.html.md, source/manual/mapit-database-not-available.html.md
Since #2837, we don't use these anymore. These particular ones
were updated whilst the PR was open.
=> Remove 'review_in'/'last_reviewed_on' fields

source/manual/data-gov-uk-operations.html.md
Current link in documentation is out-of-date so it's best to point users
to PaaS docs for appropriate reset links.
Fixes: #2860
=> Updated link on forgotten PaaS passwords

source/manual/alerts/whitehall-app-healthcheck-not-ok.html.md
Changes following https://github.com/alphagov/govuk-puppet/pull/10842.
I had raised https://github.com/alphagov/whitehall/pull/5882 to remove the rake task from Whitehall, as it is no longer called by govuk-puppet. However, this alert still runs on Production, and if the queue length become mismatched with the number of scheduled editions, this rake task could still be useful. So for now I've updated the documentation and will close the Whitehall PR.
Trello: https://trello.com/c/RethzUSW/2088-5-fix-assetmanagerservicehelperassetnotfound-errors-on-staging-integration
=> Update note about this alert on Staging and Integration

source/manual/encrypted-hiera-data.html.md
This helps debug the "[hiera-eyaml-core] Unusable public key" error, which may be due to expired keys.
=> Add docs for troubleshooting expired keys in secrets

source/manual/vpn.html.md
One fix for the Licensify VPN is to switch it off and on.
In this PR, we describe the process so that people on support
know this potential fix.
=> Add details how to fix the Licensify VPN

source/manual/pagerduty.html.md
There was a missing path in one step of the instructions.  Also fixed the numbering as we were just showing all steps as `1.` once the markdown was rendered.
=> Update PagerDuty manual drill instructions

source/templates/document_type_template.html.md.erb
This closing element doesn't have a respective opening element so this
displays as plain text. It looks like this is a mistake where someone
forgot this file was markdown.
Before:
After:
=> Remove superfluous HTML element

source/manual/get-started.html.md, source/manual/intro-to-docker-advanced.html.md, source/manual/local-frontend-development.html.md
Quick update to link to developer docs linking to [Docker](https://github.com/alphagov/govuk-docker/blob/master/README.md)
Noticed 404 / Broken link
=> Fix broken link

source/manual/manage-assets.html.md.erb
Previously the previous asset's size would have been presented, which is problematic when a small placeholder has been uploaded. Therefore we should also update the size when changing the attachment.
=> Add instructions for changing asset size when replacing file

source/manual/redirect-routes.html.md.erb
Added documentation to explain how to remove a redirect and how to repurpose the route so a document can be published at that URL.
=> Add instructions for reusing a redirect's route

source/manual/deploying-terraform.html.md
When looking to run terraform commands people may be tempted to use the
`govuk` stack for apps that are within the `govuk` space. However this
is not correct.
This update adds the information about what each stack is usually used
for next to the description of the possible values so it is easier to
spot.
=> Clarify the what the stack is for terraform commands

source/manual/data-gov-uk-supporting-ckan.html.md
The other page is "Common 2nd line support tasks for data.gov.uk" and I always misremember what this page is called and type "common" in the search box.
=> Retitle "Support tasks for CKAN"

source/manual/alerts/email-alerts-travel-medical.html.md, source/manual/email-alert-api-troubleshooting.html.md, source/manual/email-troubleshooting.html.md, source/manual/load-test-email-alert-api.html.md, source/manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html.md
Trello: https://trello.com/c/G35ncFfw/645-simplify-configuration-for-email-sending
This updates a number of documents to reflect recent changes to the Email Alert API system which were introduced in https://github.com/alphagov/email-alert-api/pull/1489.
These changes are mostly done as a quick-pass of these docs as we may manage to change the system further before the weeks out. 
This is recommended to be reviewed commit by commit.
=> Update Email Alert API documentation to reflect system changes

data/applications.yml
https://trello.com/c/GHfDidG0/656-disable-slack-notifications-as-part-of-pausing-the-team
This is because the Notifications team is pausing.
=> Reassign notifications apps to Platform Health

app/external_doc.rb, app/github_repo_fetcher.rb, app/proxy_pages.rb, source/manual/updating-brexit-transition-checker.html.md.erb, source/templates/application_template.html.md.erb, source/templates/external_doc_template.html.erb, spec/app/external_doc_spec.rb, spec/app/github_repo_fetcher_spec.rb, spec/app/proxy_pages_spec.rb, spec/fixtures/markdown.md
Fixes #2851. Now relative links and images in imported READMEs and documents will be rewritten to either:
1. An absolute GitHub URL to the resource, or
2. If appropriate, a relative link to the Developer Docs hosted version of the resource.
The latter can be seen for example on the "How Search Works" page under Search API, where the "learning to rank documentation" link is rewritten from `./learning-to-rank.md` to `/apis/search-api/learning-to-rank.html`.
Trello: https://trello.com/c/PLV6EPXh/199-fix-relative-links-images-on-imported-docs
=> Fix relative links & images in external docs

source/manual/redirect-routes.html.md.erb
It is crucial that we know how to manually redirect routes if we run into issues. Prior to this commit, this knowledge wasn't
particularly well documented anywhere.
Rather than list all the different scenarios in which we want to redirect and making the reader scan the page for the option
relevant to them, I've attempted to provide some brief context at the top of the document, followed by a flow chart of sorts.
The first heading, "Choosing a redirect strategy", describes the thought processes we should follow before applying any redirects.
I've documented the preferred approach for manual redirects, as well as warn the reader that it won't work for Short URL Manager routes (something I discovered by accident while trying the code out!). And, in a recent incident, we were forced to apply …
=> Improve the "Redirect a route" documentation

source/manual/alerts/email-alert-api-high-queue-latency.html.md
Trello: https://trello.com/c/il1TsI3e/658-tweak-alert-latency-thresholds-for-email-alert-api-sidekiq-queues
We're changing the queue latency alerts in https://github.com/alphagov/govuk-puppet/pull/10868 this commit updates the documentation to match those better.
=> Adjust Email Alert API queue latency for alert changes

source/manual/world-taxonomy.html.md
https://trello.com/c/eM5qDG8u/275-we-have-limited-documentation-about-the-confusing-world-of-world
This extends the section on problems with world taxons to mention
the tech debt card, which has some more information about the conflict
between the two. Ideally we should rewrite this manual to be about both
concepts, and this is just an interim measure.
=> Mention world location tech debt

Gemfile, Gemfile.lock
This is unsupported and hasn't been updated since 2015.
Removing it doesn't appear to break anything, so I don't
think we use it anywhere anymore and it can be safely removed.
=> Remove github-markdown gem

source/manual/add-translation-whitehall.html.md
This updates the doc to reflect the change introduced in https://github.com/alphagov/whitehall/pull/5916 (a new mandatory `latin_script?:` key has been added).
=> Update doc on how to add translations in Whitehall

source/manual/renew-a-tls-certificate.html.md
Following changes were made:
1. remove info about reliability engineer having to make the changes
since now all govuk developers are expected to be able to perform
these tasks.
2. add that there is a Gandi cert for www.gov.uk in addition to the
wildcard ones.
3. remove the puppet instructions since the relevant Carrenza infra
has been shutdown and AWS is not configured via Puppet.
4. Clarify that for production, the certs need to be uploaded to AWS
ACM in North Virginia for disaster recovery cloudfront.
Refs:
1. [integration renewal trello card](https://trello.com/c/EjVHpJdg/3947-zendesk-hostmaster-gandi-expiration-of-the-certificate-ssl-standard-integrationpublishingservicegovuk-in-29-days)
2. [www.gov.uk renewal trello card](https://trello.com/c/gdIGvJNL/3946-zendesk-hostmaster-gandi-exp …
=> Update process for Gandi TLS certs renewal

source/manual/renew-a-tls-certificate.html.md
For TLS certificates that are renewed manually, there is a need to add
the certs details in the pass store so that these can be retrieved
easily later when configuring external systems.
This PR add this requirements in the doc which was missing in #2896
=> Add requirement to add TLS certs to pass store

source/manual/alerts/renew-tls-certificate.html.md, source/manual/ask-for-help.html.md, source/manual/cdn.html.md, source/manual/concourse.html.md, source/manual/dns.html.md, source/manual/get-started.html.md, source/manual/govuk-app-domain-handling-during-migration.html.md, source/manual/merge-pr.html.md, source/manual/move-apps-between-servers.html.md, source/manual/retiring-an-application.html.md, source/manual/set-up-gcp-account.html.md
I'm not sure where these "Reliability Engineering" references came
from, but it's never been particularly accurate as far as I
understand. Reliability Engineering has always been a vague way of
referencing either those who support specific things. In particular RE
Autom8 support Concourse and Logit and RE GOV.UK when it existed
supported GOV.UK and DNS. It's always been more helpful to be more
specific than Reliability Engineering.
This issue is more apparent now given that RE GOV.UK no longer exists,
and that the most similar team is the GOV.UK Replatforming team within
the GOV.UK program, which currently has some SRE's on loan. This means
that saying "Reliability Engineering" is now wrong in many cases, as
the documentation should reference the Replatforming team within
GOV.UK.
I think …
=> Change most "Reliability Engineering" references to other things

source/manual/local-frontend-development.html.md
This is as much a proposal as a PR, so feel free to leave
comments about your own thoughts on this:
- Update various documentation:
- Frontend app READMEs should Point to this documentation.
- Other apps should point to the GOV.UK Docker README.
- Fix: https://github.com/alphagov/govuk-docker/issues/444
- Remove `startup.sh` scripts for all non-frontend apps. These are [no different](https://github.com/alphagov/asset-manager/blob/master/startup.sh) to running `rails s` manually, so we're actually making things clearer / easier by removing them for non-frontend apps.
- Change `startup.sh` scripts for frontend apps to always run with `--live`, since this is the only way they currently work. Remove `startup.sh` scripts for certain frontend apps:
- Remove for Email Alert Frontend (doesn't …
=> Clarify when to use "startup.sh" scripts

source/manual/manage-assets.html.md.erb
1. Clarifies that you / the publisher should use the Whitehall UI to upload an attachment in the first instance
2. Fixes the (very important!) Whitehall `find` to a 'find by attachment data ID' (otherwise you'd be updating the wrong asset)
3. Nudges you to update the number of pages for the asset too (assuming it's a PDF, which it often is)
Trello: https://trello.com/c/snmx8e2L/2272-test-uploading-of-massive-pdf-to-whitehall
=> Improve "replace asset" instructions

.github/workflows/ci.yml
Commit 1 simplifies our caching strategy, but brings no performance benefit.
Commit 2 simplifies our code slightly and brings a 39% improvement in build time!
=> Increase performance and readability of GitHub Actions

source/manual/cdn.html.md
Add a new section about the type of DoS/spam mitigation which was used in November 2020 for this incident:
https://docs.google.com/document/d/12DzQsDeu7zUcICy9zVporjprX4qZFIrpOOWtYYRx-nk/edit#
Also various small updates including:
- Our origin moved from London to Dublin quite some time ago.
- Fix confusion between the Fastly cache-clearing ACL (access control list) and the origin ACL.
- The vSphere automation stuff in govuk-provisioning is never coming back, so let's delete the mention of it.
- Clarify that the Fastly IP safelist and alert in Carrenza is only relevant to Performance Platform.
- Fix a broken link to the IP address denylist.
=> Update docs on Fastly, CDN source IPs, DoS mitigation.

source/manual/test-and-build-a-project-with-github-actions.html.md
Using the 'bundler-cache: true' option in 'ruby/setup-ruby'
removes our dependency on 'actions/cache' and is much more
readable config.
After the initial build [1], it leads to build times of just under
4 minutes [2], which is comparable to what we have on master
already [3]. So this is just about readability rather than
improving the build time.
[1]: https://github.com/alphagov/govuk-developer-docs/runs/1589338635
[2]: https://github.com/alphagov/govuk-developer-docs/runs/1589391081
[3]: https://github.com/alphagov/govuk-developer-docs/runs/1588704546
Thanks to @tomnatt for the tip:
https://tomnatt.blogspot.com/2020/12/a-first-look-at-github-actions.html
We've already applied this new config to the Developer Docs
themselves:
https://github.com/alphagov/govuk-developer-docs/pull/2905
=> Use native 'ruby/setup-ruby' options for caching

source/manual/alerts/security-updates.html.md
1) Clarify that a missing log probably means a newly provisioned instance
2) Imply a clearer ordering of debug commands to run
=> Improve 'outstanding security updates' documentation

source/accessibility.html.md
Updated the date for fixing the Tech Docs Template accessibility issues from "end of 2020" to "end of March 2021". As a result of resourcing pressures and re-prioritisation this year, it's taking longer than we hoped to arrange developer and designer resources to fix the accessibility issues.
Trello card: https://trello.com/c/c90no9QJ/2269-make-amendments-to-the-accessibility-statements-on-our-documentation
=> [DO NOT MERGE]Update accessibility statement

source/manual/data-gov-uk-supporting-ckan.html.md
https://govuk.zendesk.com/agent/tickets/4360504
Remote access has been disabled [1] since the steps were written [2].
[1]: https://github.com/alphagov/govuk-puppet/commit/b9f4235091c0b13d900930bea9c8ae7a905f9d12#diff-50b8bfe88e4f51b16978ee56630555fdbaa2372eca7d78029263ef79621c6a52
[2]: https://github.com/alphagov/govuk-developer-docs/commit/8f4e201953120ad30a70f29d0abe50070bf908c6
=> Fix documentation about CKAN bulk deletion

source/manual/bulk-email.html.md
https://trello.com/c/wp7WjPN6/693-draft-email-to-send-out-to-checker-subscribers-following-an-announcement
This makes the content of the manual a bit more concise,
and more importantly adds references to two new features
for sending bulk emails. Please see the commits for more
details.
=> Rewrite bulk email manual

data/dashboard.yml, source/manual/configure-linting.html.md
Trello: https://trello.com/c/MeG1zc2m/195-roll-out-stylelint-config-gds-across-govuk
This updates the JS linting documentation to reference standardx rather than standard and removes references to scss-lint-govuk to consider that the project will soon be archived.
=> Update linting documentation

source/manual/rename-a-country.html.md
https://trello.com/c/dgdLhy2H/777-update-transition-to-brexit-in-email-notifications-for-transition-taxon
Related to: https://github.com/alphagov/email-alert-api/pull/1583
This makes a few changes:
- Promotes the new auto-update behaviour for list titles
- Warns against updating list slugs e.g. at peak times
As a result, the guidance is now bit vague. This is intentional:
- Slugs for subscriber lists are barely visible to the user. We should
avoid causing errors for users unless there's an issue with a legacy slug
appearing in a few query params.
- We should avoid expending effort updating titles for niche subscriber
lists, as the value of doing so is inherently low - the most-used lists
will auto-update without intervention.
=> Update country renaming guidance for email lists

app/external_doc.rb, spec/app/external_doc_spec.rb, spec/app/github_repo_fetcher_spec.rb, spec/fixtures/markdown.md
Imported links like `/public/foo.json` currently get converted to
https://docs.publishing.service.gov.uk/public/foo.json.
These links obviously 404.
Whilst technically they should be converted to
https://www.github.com/public/foo.json (if we were to take them
at face value), those links would also 404. What the developer
intends, and what GitHub obliges to do, is to convert them
relative to the repository, i.e.
https://github.com/alphagov/lipsum/blob/master/public/foo.json.
We must do the same.
This commit should fix a live issue I'm seeing on this page:
https://docs.publishing.service.gov.uk/apps/hmrc-manuals-api/extended_documentation.html#example-json
=> Fix links that are relative to the site root

source/manual/how-to-escalate-to-AWS-support.html.md
These are the steps to creating a support case with
Amazon AWS.
Users need to log into the AWS console and follow the steps.
Trello: https://github.com/alphagov/govuk-developer-docs/pull/2931
=> Add new documentation to raise AWS support case

source/manual/development-pipeline.html.md
This updates the section on code freezes to improve details on informing peers when a code freeze is implemented, as discussed at the tech fortnightly meeting.
=> Add some clarity around comms for a code freeze

data/applications.yml, data/dashboard.yml, source/manual/govuk-account.html.md.erb
We didn't have anything in our main developer docs for these.
=> Add entry for GOV.UK Accounts

source/manual/get-started.html.md
Add section to the docs describing the new access controls that Replatforming are putting in place to allow anyone with production access to assume admin, poweruser or user roles.
=> Add section about new access controls

source/manual/get-started.html.md
Recommend using the least privileged role available.
I think readers will be able to work out to replace integration with
staging / production, so they don't need that pointing out explicitly.
=> Update get-started docs on accessing AWS

source/manual/concourse.html.md, source/manual/create-a-gpg-key.html.md, source/manual/publish-to-puppet-forge.html.md, source/manual/restore-from-offsite-backups.html.md
- Usage of `brew cask install` returns "Error: Calling brew cask install is disabled! Use brew install [--cask] instead." since Homebrew 2.6.0 (released in December). None of the software installed in these docs is both a cask and a formulae, so there's no need to explicitly pick the cask with `--cask`.
:sparkling_heart:
=> Replace mentions of `brew cask` with plain `brew install`

source/manual/common-aws-tasks-for-2nd-line-support.html.md
As the 3rd line support provided by SREs is no longer available, 2nd line will take on extra support tasks related to AWS. This document should be a good starting point for some of those extra tasks.
=> Add documentation for common AWS tasks

source/manual/alerts/signon-app-healthcheck-not-ok.html.md
During a 2nd line shift I found that this documentation was a bit
ambiguous in its present state. I was not sure which commands to run or
where to run them. I think this commit will enable future 2nd line
developers to rotate tokens with more clarity.
[Trello](https://trello.com/c/4sED8XY4/1079-rotate-tokens-for-publishing-api-support-api-in-integration)
=> Add example code to developer docs

source/manual/scale-mapit.html.md
Scaling Mapit is different to other GOV.UK applications and the process has recently changed, so it should be documented.
Trello card: https://trello.com/c/W5I1wGG2
=> Add instructions for scaling Mapit

data/applications.yml
Derived this info from https://release.publishing.service.gov.uk/applications.
Depended on by https://github.com/alphagov/govuk-dependencies/pull/104.
Whilst the Release app is supposed to be the single source of
truth, in reality the Developer Docs is relied upon for its
https://docs.publishing.service.gov.uk/apps.json endpoint, so it
seems reasonable to add continuous-deployment information to our
app configuration here.
=> Add new `continuously_deployed` field for current CD-enabled apps

app/app.rb, spec/app/app_spec.rb
This should have been done in #2949 - I wrongly assumed the
application.yml contents would automatically be consumed in the
apps.json endpoint. It turns out it has to be explicitly added to
the api_payload method.
This commit adds a `continuously_deployed` method to retrieve the
property of the same name from the config, defaulting to `false`
if it doesn't exist. I've added tests for this, as well as a
missing text for the `api_payload` method.
=> Add `continuously_deployed` property to API payload

app/github_repo_fetcher.rb, spec/app/github_repo_fetcher_spec.rb
Fixes #2940. Bug introduced in #2918.
Tests were sensitive to their order of execution. State from a
previous run of tests can remain on the `GitHubRepoFetcher`
singleton object.
The Singleton pattern is somewhat discouraged [1] [2], though it
can be useful to refer to a common instance of a class where its
fetch methods are computationally expensive and we rely heavily
on caching.
This commit follows the guidance in the second referenced article,
to retain the Singleton presentation of the class but also to
allow it to be instantiated (making it much easier to test). I've
also added a test to capture and verify the intended `.instance`
singleton behaviour.
[1]: https://www.rubyguides.com/2018/05/singleton-pattern-in-ruby/
[2]: https://8thlight.com/blog/josh-cheek/2012/10/20/implementing-a …
=> Fix intermittent tests

source/manual/manage-ruby-dependencies.html.md
This is a follow up to the six month review of RFC 126 and finally closes the work we've been doing in the "dev tools" team around [improving our dependancy management processes](https://trello.com/c/FDjUAhAr/203-write-documentation-on-merging-dependabot-prs).
Specifically I've reorganised the content a little bit and added a section on how to review Dependabot PRs.
=> Update docs on Dependabot usage

data/applications.yml
It could be considered a utility, like 'govuk-dependencies'.
Including this repo pulls in its README and `docs/` folder, which
should be useful for developers.
=> Add 'govuk-docker' to list of GOV.UK applications

source/manual/reindex-elasticsearch.html.md
Updates the doc primarily regarding the reindex process by:
* Adding a link to the reindex Jenkins job
* Adding a list of indices available in Search API
Also corrects the strange numbered lists as they all currently start at
0.
=> Update reindex doc

source/manual/ask-for-help.html.md
The GOV.UK RE Autom8 team are responsible for Logit. The doc has been updated to reflect this.
=> RE Autom8 team are responsible for Logit

source/manual/transition-a-site.html.md, source/manual/transition-architecture.html.md
We can now have Fastly create a TLS certificate on our behalf
in order to transition sites to GOV.UK that already served over
HTTPS.
A doc already exists explaining how to do it:
https://docs.publishing.service.gov.uk/manual/request-fastly-tls-certificate.html
This change updates the transition docs to say we can actually
tranisition HTTPS sites to GOV.UK via Bouncer.
=> Update Transition docs to mention creating TLS certs

source/manual/alerts/fetch-analytics-data-for-search-failed.html.md
We have seen this job failing on many occassions with the same issue,
so documenting this for future reference.
Trello card: https://trello.com/c/6fod7LEt/674-investigate-fix-fetch-analytics-data-for-search-api-alert
=> Update doc for search analytics data

source/manual/alerts/content-data-api-app-healthcheck-not-ok.html.md.erb
We have an ongoing issue with content-data-api, as Platform Health
are not actively looking into this we should document the manual fix
2nd line are using for now.
Trello card: https://trello.com/c/d45mq4DS/1081-document-manual-fix-for-content-data-api-sidekiqretrysize-alert
=> Add manual fix for content-data-api

source/manual/rules-for-getting-production-access.html.md
GDS' position on blanket SC clearance has changed, and the default position is now that technologists require BPSS unless their specific role requires a higher level (which the majority of GOV.UK dev roles do not).
=> Remove SC clearance requirement for prod access

source/manual/mapit-database-not-available.html.md, source/manual/scale-mapit.html.md
Updates the Mapit database initialisation instructions to use Postgres 9.6 (instead of 9.3, which we recently upgraded) and adds a missing resource to the scaling documentation.
=> Update Mapit documentation

source/manual/alerts/whitehall-app-healthcheck-not-ok.html.md, source/manual/alerts/whitehall-scheduled-publishing.html.md.erb
In https://github.com/alphagov/govuk-puppet/pull/10963, we added a new healthcheck for the number of scheduled documents that are not queued. The end goal is to remove this from the generic Whitehall app healthcheck, so updating the documentation in preparation for this.
Trello card: https://trello.com/c/UAbbL13x
=> Update Whitehall scheduled publishing worker healthcheck docs

source/manual/vpn.html.md
One of the outcomes of the tech debt review for this was to include a link to the GOV.UK tech debt card for this.
=> Add link to UK Cloud VPN tech debt

source/manual/pact-broker.html.md
I'd gotten my provider and consumer mixed up in #2982.
I've also added a section on changing the Provider's API, which
needs to be co-ordinated in a particular way.
=> Correct the 'Writing Pact tests' section & add 'Updating' section

source/manual/cdn.html.md
Trello: https://trello.com/c/P2Y4nGaw/156-document-asset-e-tags-in-the-cdn
This adds documentation on a caching process Fastly applies for
responses which return conditional headers. It can be a little
surprising that Fastly can modify a response from Origin, a 304, to
convert it to a 200.
This has been added following an incident on 21st January 2021 where
Asset Manager returned the wrong content-type. In order to resolve this
problem we had to remove 10,000 items from the Fastly cache. We
initially thought this incident was resolved after the Cache-Control
time was exhausted, however E-Tags kept the problem occurring.
=> Document conditional request caching at the CDN

source/manual/assets.html.md
Trello: https://trello.com/c/P2Y4nGaw/156-document-asset-e-tags-in-the-cdn
This is updated to reflect that static assets are now served from
www.gov.uk and that uploaded assets aren't served from a share anymore.
I also decided to include the peculiar other thing hosted on
assets.publishing.service.gov.uk since it is rather a surprise to find
that one of our apps is proxied there as only a service to development
versions of GOV.UK. Hopefully I've explained it ok as it's a rather
confusing concept.
=> Bring asset documentation up to date

data/applications.yml
Dependant on the other PRs contained within [this
ticket](https://trello.com/c/zu7IYR6C/2385-enable-continuous-deployment-for-service-manual-frontend).
Trello:
https://trello.com/c/zu7IYR6C/2385-enable-continuous-deployment-for-service-manual-frontend
=> Flag Service Manual Frontend as CD

data/applications.yml
This will import useful things such as the health check document: https://github.com/alphagov/govuk_app_config/blob/master/docs/healthchecks.md
Have also added the missing `sentry_url`/`dashboard_url` overrides for govuk-docker.
=> Adds govuk_app_config to list of applications

config/tech-docs.yml
There's already a link to `/` in the header (The main "GOV.UK Developer docs" link).
Having the same link in the header twice was flagged as an accessibility issue in [a recent audit of the tech docs template](https://docs.google.com/spreadsheets/d/1s53eGMBj2hdTVLRitwi673R-_uERWh0kOxOp9QsOVg0/edit#gid=0). This can't be fixed in the gem, but we can fix it in our docs.
Also what does "Dashboard" even mean in this context?
This might [break some people's workflows](https://xkcd.com/1172/). Happy to discuss removing the other link instead, or keeping both and ignoring the reported accessibility issue.
=> Remove duplicate link in header

source/manual/cdn.html.md
I think it's helpful to refer devs to the specific lines of code where overrides happen.
=> Link to 307/406 special cases in govuk-cdn-config

data/applications.yml
This will fix the build for new PRs e.g. https://github.com/alphagov/govuk-developer-docs/pull/2996, which are failing because the puppet manifest for calculators no longer exists.
=> Mark 'calculators' as retired

source/manual/conventions-for-rails-applications.html.md, source/manual/encrypted-hiera-data.html.md
This is to avoid the use of ableist language.
The use of "dummy" doesn't make the text any clearer and removing it or
replacing it with "placeholder" leaves the text as clear as before, but
more inclusive.
Some resources:
- https://developers.google.com/style/inclusive-documentation#ableist-language
- https://english.stackexchange.com/questions/337478/is-there-a-better-term-than-dummy-to-describe-a-non-functional-part-of-a-progr
=> Remove or replace the use of "dummy"

source/manual/republishing-content.html.md
This came up during a 2ndline shift where a govspeak component change
caused the contact element for press releases to render with different
HTML.
As a result we needed to go in and republish a lot of content publisher
content, and the how-to was missing from our docs.
I also took the chance to rearrange the complex links as footnotes
whilst I was there.
=> Add republishing information for content-publisher

source/manual/configure-github-repo.html.md
Tagging the repo, giving the CI team admin access, and running the
jenkins job is not enough, as the job doesn't take care of the rest of
the permissions.
Also add a note about CD.
=> Clarify how to set up a new repo

data/applications.yml
This is a step in our documentation on [how to set up a new app][0].
[0]: https://docs.publishing.service.gov.uk/manual/setting-up-new-rails-app.html#puppet-dns-sentry-and-beyond
Trello card: https://trello.com/c/ZeAKl2SM/651-set-up-a-new-app
=> Add the new `account-api` app to our docs

source/manual/setting-up-new-rails-app.html.md
During setup of accounts-api we found CI errors and a very obscure stack
trace. It turns out the code is currently set up to expect that each
repo has an "About section". Without it the application listing renders
fine but shows up empty.
However the application page fails to render and there is an error
message when building pages with Middleman.
This was quite confusing, so until we can fix the code to fail more
gracefully or with a better warning, I have added a note for the next
folks who try and set up a repo.
=> Explain that new repositories require github About

source/manual/emergency-publishing.html.md
If we need to use the emergency banner, then we have been cleared to remove the Brexit link in order to reduce the overall height of the banner section.
=> Add instructions for hiding the Brexit link

Gemfile, Gemfile.lock, Rakefile, app/developer_docs_renderer.rb, app/document_types.rb, app/document_types_csv.rb, app/requires.rb, app/snippet.rb, app/string_to_id.rb, helpers/navigation_helpers.rb, helpers/properties_table_helpers.rb, spec/helpers/commit_helpers_spec.rb, spec/spec_helper.rb
Trello: https://trello.com/c/pqXbKZiC/215-test-rubocop-govuk-400pre1-prior-to-400-release
This bumps to the 4.0.0 pre release of rubocop-govuk which is part of [trialling the new rubocop-govuk release](https://github.com/alphagov/rubocop-govuk/issues/129). The gem pin to 4.0.0.pre.1 is intended to be removed once the final release of rubocop-govuk 4.0.0 is out.
=> Update rubocop-govuk to 4.0.0.pre.1

.gitignore, helpers/commit_helpers.rb, spec/helpers/commit_helpers_spec.rb
When creating a file locally, before it has been committed to
version control, if we attempt to build and view the Developer
Docs we see errors such as
```
NoMethodError: undefined method `author_date' for nil:NilClass
```
This is because the code tries to find the last commit associated
with the file, in order to render the 'Last updated' banner. There
is no commit yet, so it errors.
To avoid complicating the 'last_updated' partial with a conditional,
I've gone down the polymorphic route of "it should be able to
render something, even if no data exists". This commit ensures
that today's date is used as the last updated date, and the link
is to nowhere ("#").
This is only an issue on the developer's local machine while
they're developing. It is never an issue on production or on CI,
by …
=> Fix #2875 - local uncommitted files causing build errors

source/manual/transition-a-site.html.md, source/manual/transition-architecture.html.md
It seems the source document was moved into a "manual" section so old links do not work at the moment.
=> Fix links for a manual to request TLS certs

source/manual/publish-special-routes.html.md
This previously linked to the "publish all special routes" task in staging. Updating to link to both available tasks in all environments.
Trello card:  https://github.com/alphagov/govuk-developer-docs/pull/new/update-special-routes
=> Update link to Special Route Publisher's Jenkins task

source/manual/sidekiq.html.md
We can now access Sidekiq Monitoring through a URL, rather than port
forwarding.
Related PR's:
* https://github.com/alphagov/govuk-connect/pull/54
* https://github.com/alphagov/govuk-aws/pull/1432
Trello:
https://trello.com/c/m8O8dC41/2414-add-dns-for-sidekiq-monitoring
=> Update Sidekiq doc

spec/app/app_spec.rb
We have recently moved the Child benefit tax calculator into Smart
Answers and retired the Calculators app.
Trello card: https://trello.com/c/4Sz5s78X/2400-epic-retire-the-calculators-app
=> Remove Calculators app from tests

.github/dependabot.yml, .mdlrc, Gemfile, Gemfile.lock, config.rb, mdl/rules.rb, source/manual/architecture-deep-dive.html.md, source/manual/howto-find-hardcoded-markup-govspeak.html.md
In a9905710c83097b0cebd1e7cbe1a94c64b167fda, we swapped out Redcarpet for Kramdown, as Redcarpet had an [issue parsing shortcut reference links](https://github.com/vmg/redcarpet/issues/471).
However, tech_docs_gem uses Redcarpet for its markdown parsing, and there has been a lot of work recently to improve the
accessibility of its output, so our override was preventing us from benefiting from these improvements.
In this PR, I've removed Kramdown and the Developer Docs uses Redcarpet for its markdown engine, which gives us the accessibility improvements we wanted. I've also added a custom Markdown Lint rule to find and report any occurrences of shortcut reference links followed by parentheses, which exhibit the bug (screenshot of bug below):
> …
=> Switch to Redcarpet for Markdown parsing, and fix shortcut reference link bug

source/accessibility.html.md, source/apps.html.md.erb, source/manual/pingdom-bouncer-canary-check.html.md
As per the guidance in the attached Trello card, tables with more than 2 columns should have a row-level header as well as the column headers.
There were only two tables that qualified in govuk-developer-docs. I took the opportunity to fix up the unsemantic table structure in https://docs.publishing.service.gov.uk/manual/pingdom-bouncer-canary-check.html
Before:
> <img width="785" alt="Screenshot 2021-03-24 at 09 27 46" src="https://user-images.githubusercontent.com/5111927/112286464-415ab480-8c83-11eb-81fd-8b725e419027.png">
After:
> <img width="789" alt="Screenshot 2021-03-24 at 09 27 52" src="https://user-images.githubusercontent.com/5111927/112286480-4586d200-8c83-11eb-9ccb-b864b8bbe2a6.png">
Trello: https://trello.com/c/eTzcjz5u/2422-3-update-govuk-developer-docs-re-accessibility-by-e …
=> Add row headers to tables which have more than 2 columns

source/templates/application_template.html.md.erb
In 21b47c9a2ac6d4805fdaabd6a5480c706377cea3, we switched back to
Redcarpet for markdown rendering, removing the Kramdown dependency.
Redcarpet takes into account spacing when rendering HTML; if it
sees some indented HTML, it assumes it is markdown and attempts to
render it as a code block. This was leading to a very broken page:
> <img width="1056" alt="borked" src="https://user-images.githubusercontent.com/5111927/112299273-8c7ac480-8c8f-11eb-93ef-8011a73a57af.png">
We now call `.strip` to remove indentation from the output, which
fixes Redcarpet's parsing of the HTML:
> <img width="921" alt="good" src="https://user-images.githubusercontent.com/5111927/112299276-8dabf180-8c8f-11eb-8608-8c24ae27485d.png">
=> Fix rendering of app pages

source/manual/alerts/rabbitmq-dead-nodes.html.md
The fab task only runs `sudo rabbitmqctl cluster_status`, so there's
no reason why the user can't just run that themselves.
=> Remove reference to fab scripts from RabbitMQ Dead Node alert doc

source/manual/alerts/free-memory-warning-on-backend.html.md, source/manual/alerts/goreplay.html.md, source/manual/alerts/ntp-drift-too-high.html.md, source/manual/alerts/rebooting-machines.html.md, source/manual/alerts/unicorn-herder.html.md, source/manual/alerts/varnish-port-not-responding.html.md
A lot of the fab tasks are one or two commands, and the only utility the script gives is not needing to SSH into a machine.
For those cases, just replace the task with the actual commands it runs.
I've left references to `fab` where the behaviour is quite complex (eg, [mysql.reset_slave](https://github.com/alphagov/fabric-scripts/blob/master/mysql.py#L105)), or where it's used to run a task across a `class` of machines.
=> Remove fabric tasks from a few docs

source/manual/government-changes.html.md.erb
This adds a link to the Rake task to change the organisations for Manuals.
=> Add link to Rake task for bulk retagging of Manuals

source/manual/create-a-gpg-key.html.md
Adds some lines in the [GPG key](https://docs.publishing.service.gov.uk/manual/create-a-gpg-key.html) manual about setting the keyserver to `http://keyserver.ubuntu.com/`.
Our scripts that use GPG keys run off of that keyserver. GPG will specify an alternative keyserver by default on installation and there's currently no easy way for new devs to know that we're using a different keyserver to the GPG default.
=> Add required keyserver to gpg docs

source/manual/retiring-an-application.html.md
Removed section on a repo that is now archived, and updated link to
AWS file.
Trello card: https://trello.com/c/4Sz5s78X/2400-epic-retire-the-calculators-app
=> Update retire an application doc

source/manual/github.html.md.erb
I wasn't sure if this was the best place to add this, suggestions are welcome!
Trello card: https://trello.com/c/mwVIeHl5/1101-document-access-to-inaccessible-alphagov-repos
=> Add docs on accessing alphagov repos

source/accessibility.html.md
This was fixed in https://github.com/alphagov/govuk-developer-docs/pull/3013 followed by https://github.com/alphagov/govuk-developer-docs/pull/3029.
Trello: https://trello.com/c/eTzcjz5u/2422-3-update-govuk-developer-docs-re-accessibility-by-end-march-5
=> Remove reference to broken tech docs template

source/manual/republishing-content.html.md
Adding some more Content for republishing 
[govspeak](https://github.com/alphagov/govspeak/pull/210) updates prompted to add more detail to documentation on how to republish - https://docs.publishing.service.gov.uk/manual/republishing-content.html
=> Updating republishing steps

data/applications.yml
short-url-manager is now continuously deployed
[trello](https://trello.com/c/C5JUWz5s/2452-enable-continuous-deployment-for-short-url-manager-3)
=> Mark short-url-manager as continuously deployed

source/manual/publishing-a-ruby-gem.html.md
We no longer have a `apt-1.management` machine after the AWS migration, so updating this. Also making it a single line command using the GDS CLI.
=> Update instructions for clearing gemstash

source/manual/add-translation-whitehall.html.md
We want to draw attention to the specific syntax of the tags to ensure the right ones are chosen. Hopefully this should avoid the issue we experienced recently where we had to change one of the live tags on the site: https://github.com/alphagov/publishing-api/pull/1910
=> Improve introductory paragraph on translations

Gemfile, Gemfile.lock, README.md
This follows the changes we're applying to other GOV.UK repos. My
original motivation for this change was just to simplify the GitHub
setup, so if the rest of this PR proves contentious, we could just
focus on that commit instead.
=> Rewrite README and simplify GitHub Token setup

source/manual/architecture-deep-dive.html.md, source/manual/check-for-gone-route.html.md, source/manual/editing-an-existing-route.html.md, source/manual/redirect-routes.html.md.erb
This PR updates the docs to reflect the recent changes to Router and Router API. Router API previously called the `/reload` endpoint of every Router instance to perform a full route reload; this has now been superseded with [Router polling for and applying updates itself](https://github.com/alphagov/router/commit/811ed82d0ecc23b8077ed5dd2c460ccdfe2808ab), which was a result of [RFC 135](https://github.com/alphagov/govuk-rfcs/blob/main/rfc-135-updating-routes-in-router.md).
=> Update docs to reflect route updates within Router

source/manual/alerts/elasticsearch-cluster-health.html.md, source/manual/howto-ssh-to-machines.html.md
This gets rid of two uses of `ssh -A` (which is bad practice) and simplifies things significantly.
There's one more use of `ssh -A` in `source/manual/clone-mysql-slave.html.md`, but I don't understand that doc so I'm leaving it alone.
=> Nicer ssh port forwarding instructions

Rakefile, data/applications.yml
hieradata has been deleted as obsolete in govuk-puppet as per:
https://github.com/alphagov/govuk-puppet/pull/11037
=> Update hieradata path to hieradata_aws

source/manual/republishing-content.html.md
This adds details to the docs on some new rake tasks available for republishing in Whitehall and also links out to dashboards useful for monitoring the publish tasks kicked off by them.
=> Update docs on bulk republishing in whitehall

source/manual/emergency-publishing.html.md
Makes a small number of improvements to this documentation based on the experience we had running this on 9 April 2021.
=> Update emergency publishing documentation

source/manual/setting-up-new-rails-app.html.md
Account team found that the documentation for setting up a new app (https://docs.publishing.service.gov.uk/manual/setting-up-new-rails-app.html) is very out of date.
It has a list of steps but that list is missing things, has parts which are now wrong, and gives the steps in the wrong order.
This PR updates the content to be correct.
trello card: https://trello.com/c/mgltOCbD/671-improve-the-how-to-set-up-a-new-app-documentation
=> Update the set up rails app content

source/manual/pact-broker.html.md
https://trello.com/c/Psf7EzPB/204-move-away-from-startupsh
This is based on the commands we have in other repos, which we can
centralise here [1][2]. In future we should consider improving this
manual further, so there are clear and simple steps to follow for
local development. For now, this will DRY-up our READMEs.
[1]: https://github.com/alphagov/frontend/blob/1f4cb6049f14da2b595597f28c0fe5af18c4f3b4/CONTRIBUTING.md#pact-tests
[2]: https://github.com/alphagov/collections/blame/102836b66772c0c63630e054a15a88859c814fcd/README.md#L190
=> Provide specific instruction for local testing

source/manual/alerts/expiring-api-tokens-in-signon.html.md
This check is getting its own alert, so the page should reflect that.
The current page isn't linked from anywhere, so nothing else needs
updating.
See also https://github.com/alphagov/govuk-puppet/pull/11045
---
=> Rename the page for expiring Signon API tokens

source/manual/howto-switch-default-branch.html.md
This is an important step to make sure that new builds of the `main` branch are building correctly, and to check the new build number is being used.
=> Add a line about rebuilding the main branch

source/manual/government-changes.html.md.erb
This lists Document Type as a required column in the CSV file for bulk retagging of content - where this hasn't been included in the past, a developer has had to add and populate it manually.
=> Changes Document Type to be a required column in the CSV

source/manual/alerts/search-api-app-healthcheck-not-ok.html.md, source/manual/alerts/search-reranker-healthcheck-not-ok.html.md
This is now a separate alert, see
https://github.com/alphagov/govuk-puppet/pull/11051
---
=> Separate out the search-api reranker alert

source/manual/alerts/publisher-scheduled-publishing.html.md
This is now a separate alert, distinct from the app healthcheck.
---
=> Rename the page for the publisher scheduled publishing check

source/manual/alerts/content-publisher-government-data-check-not-ok.html.md
This is now its own alert.
---
=> Rename content-publisher government-data check page

source/manual/reindex-elasticsearch.html.md
We should fix this problem, but at the moment we don't have capacity to do so. Adding a line should prevent people asking questions on Slack and know what to do when it doesn't work.
[Trello Card](https://trello.com/c/9ww3pD2p/1009-add-search-reindex-problems-to-tech-debt-board)
=> Add a line about failed reindex task

source/manual/get-started.html.md
The VPN command in the GDS CLI no longer works as the GDS VPN uses Google SSO to authenticate. The instructions that remain aren't current up to date, but I'm not sure where to link to instead so I've left them for now and we can update them in the future.
=> Remove references to gds vpn command

source/manual/bulk-email.html.md
This adds the need to have a subject line, as it wasn't obvious. 
Also fixed a typo and shortened the text to make it a bit clearer
=> Adds subject line as a requirement for sending bulk emails

source/manual/alerts/goreplay.html.md
Adding context to the Goreplay software name makes it more searchable and clearer what it's related to.
=> Update title to make it more searchable

source/manual/get-started.html.md
The `hieradata/integration.yaml` file is no more (we completely migrated to AWS).
=> Remove reference to non-existent file

source/manual/govuk-env-sync.html.md
Also removes unnecessary and vague reference to legacy sync process (it's not clear why "this isn't ideal").
=> Document why we sanitise data on Integration and not Staging

source/manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html.md
I ended up signing up for subscriptions to the Staging Google account on Integration (by accident), then on Production (on purpose), then on Staging. Only the latter came through with a confirmation email. This makes sense on reflection, but I think can be made a little clearer from the documentation.
Trello: https://trello.com/c/qqxUkxPX/2489-2-send-email-to-all-gds-department-subscribers-pointing-them-to-cddo-alerts
=> Make instructions consistent and clearer between Int & Staging

source/manual/notify-emergency-alerts.html.md
Additional documentation after working through
https://trello.com/c/RTA6ZWJr/2420-2-deploy-govuk-alerts-to-production-%F0%9F%8D%90
Highlights:
- Clarifies that there are two custom hosts
- Links to said hosts
- Clarifies that there is a wildcard capture for `/alerts/*`
- Links to new VCL merging logic
=> Additional documentation for gov.uk/alerts

source/manual/create-a-local-transaction.html.md
The Covid-19 product team have been asked to implement a few new local transaction services over the last few months.
As the majority of the team have not worked with local links manager or local transactions before, we want to be sure that we have everything we need before implementing any new local transaction services.
Unfortunately, the steps required to create a local transaction service do not appear to be well documented.
This change adds the missing documentation.
[Trello](https://trello.com/c/Jfz7eZvQ/381-document-local-transaction-implementation-steps)
=> Add how to create a local transaction documentation

source/manual/find-a-rails-template-based-on-a-govuk-url.html.md, source/manual/kibana.html.md
Adds a new doc around associating a rails `.erb` template with a path on GOV.UK and updates the Kibana docs with some information about one method to do this using Kibana.
The pair of problems of not being able to work out where your work is being rendered and vice versa are fairly uncommon problems for most govuk devs but are both very difficult to overcome when you run into them. This in particular impacts frontend developers as their changes more often are visual/user facing and testing in situ is critical. This is exacerbated when working within our more legacy apps like whatehall-frontend, adding a risk that tech debt continues to go unnoticed and grow further out of date.
These docs are intended to act as a starting point to help developers work out where they are.
=> Update docs for associating a route with a template

source/manual/sentry.html.md
Reflecting changes in alphagov/govuk_app_config#196
https://trello.com/c/13nqv4jy/2474-3-merge-govukerrors-shouldcapture-method-into-beforesend-🍐
=> Update Sentry documentation to reflect should_capture deprecation in favour of before_send

source/manual/covid-19-services.html.md
GDS no longer has access to this data (since December 2020) and the docs should reflect this
=> Change status on Coronavirus business volunteer data

source/manual/manage-ruby-dependencies.html.md
The old instructions no longer work when a repo is transferred to GitHub-native Dependabot (as most of our apps now have).
See screenshot comparing a Dependabot-dot-com project vs a GitHub-native project. Only the former has the "Bump now" button.
=> Update manual bump instructions for GitHub-native Dependabot

source/manual/zendesk.html.md
GOV.UK 2nd line no longer provides first-line support for data.gov.uk, updating the documentation to reflect that.
=> Update Zendesk documentation to reflect changes to DGU support

app/app.rb, data/applications.yml
This change:
- Removes govuk-alert-tracker application, since it is no longer a running tool
- Adds special-route-publisher as an application, since that utility seems a surprising omission from this list despite being on the borderline of whether it could be considered to be an app
- Removes the broken "Deploy script" link for apps that have a production hosting of none
- Removes a duplicated entry of step-by-step-browser in the apps list
- Fixes a comment on what belongs in "Utilities", that no longer reflected usage.
Further details in the commits.
=> Accuracy updates to applications list

source/manual/query-cdn-logs.html.md
Add an example AWS Athena query to give the total number of 5xx responses,
the total number of requests, and the percentage of 5xx responses of the
total number of requests.
In cases where we have high 5xx responses, it saves you having to work
out the total and % manually.
=> Add 5xx example Athena query

data/applications.yml
It's more helpful that #govuk-corona-services-tech gets to see information about
these Dependabot PRs.
[trello](https://trello.com/c/XtUQU9Dj/426-assign-this-team-as-dependabot-maintainers-of-collections-collections-publisher-and-local-links-manager)
=> Set Corona services as dependencies team for 3 app

source/manual/howto-modify-change-note.html.md
Updating a change note is a task that comes up on 2nd Line from time to time and there was no guidance on how to action it if the content is in Whitehall. I figured out how to make it happen with a combination of this Publishing API documentation and the existing [change note remover](https://github.com/alphagov/whitehall/blob/827a41d05358ad9bc36cb443ea1d93af7ab73cae/lib/data_hygiene/change_note_remover.rb)
While this may not be the ideal approach it's a start, it works, it can be iterated on and it didn't require me making Whitehall run on my machine or learning about migrations.
=> Add documentation for modifying a Whitehall changelog

app/external_doc.rb, spec/app/external_doc_spec.rb, spec/fixtures/markdown.md
This protects against a somewhat unusual edge case [first seen in Mapit](https://github.com/alphagov/mapit/pull/133), where the Developer Docs is pulling in external documentation that refers to localhost URLs and port numbers, and wraps said URL in non-ASCII curly quotes. (Straight `"` quotes are fine).
Consider the content below:
> In the commands above, for every line where the 9th field is ‘200’, print the string “http://localhost:3108” followed by the 7th field of that line, which is the postcode.
The markdown parser was detecting the URL and attempting to convert it to a link. But it would treat the closing `”` as part of the URL, so treat `3108”` as the port number, which is invalid. It subsequently raises a `URI::InvalidURIError`.
I considered two outcomes to be desirable here:
1. …
=> Skip over malformed URLs in external docs

source/manual/publishing-a-ruby-gem.html.md
This came up today when trying to release a patch to v3 of govuk_app_config, which currently has v4 in pre-release. The process to manually work around the Jenkins gem publishing should be documented.
For the record, I had a play with the Git history side of things in a personal repo, which you can look at to see the effect of the meta commit: https://github.com/ChrisBAshton/test-repo
=> Document how & when to manually publish to RubyGems

source/manual/on-call.html.md
Adds guidance recommending the enabling of an alert for every new message in the #govuk-incident Slack channel when on call.
=> Add on call guidance for #govuk-incident Slack notifications

source/manual/zendesk.html.md
Zendesk ticket title was "GDPR Subject Access Request". Searching for the title found 0 results in Dev Docs.
Let's do some keyword stuffing to make it easier to find for developers.
=> Adds keyword "GDPR"

source/manual/tech-lead-responsibilities.html.md
This is based off https://docs.google.com/document/d/14X0ncYY5Q6tm5oSSKcEs8jBQurPWmjjqh2Z6sHoTIfA/edit?ts=60cc6b80# which is a document I've been putting together and had reviewed by the current tech leads on GOV.UK.
It isn't supposed to be a finished document, but a common complaint from new tech leads is that there isn't a clear definition of what the tech lead role involves, so hopefully this document will service that need.
It's mostly written based on my experience as the tech lead for the Platform Health team on GOV.UK (which is perhaps the most tech heavy team on GOV.UK) and from reading articles online which I would highly recommend reading as well:
- https://www.codementor.io/@npostolovski/8-tips-for-being-a-good-tech-lead-ke35g7em8
=> Add a page on tech lead responsibilities

source/manual/new-instances-fail-to-provision.html.md
Replatforming have this on their radar. Running the command is more
efficient than reprovisioning the instance, so I've moved it to the
top of the suggestions.
=> Document recommended fix and link to card

source/manual/alerts/app-healthcheck-not-ok.html.md, source/manual/alerts/check-process-running.html.md, source/manual/new-instances-fail-to-provision.html.md
Even though I documented this yesterday, I struggled to find the
doc by searching, and it wasn't linked to from the "check process
running" doc. I knew the underlying cause but couldn't remember
the fix.
This improves the signposting to the doc, and also clarifies that
the workaround requires `sudo`.
=> Signpost the reprovisioning docs a bit more

config/tech-docs.yml, source/manual/google-cloud-platform-gcp.html.md, source/manual/rules-for-getting-production-access.html.md
Add explanations that we have four projects, and document how to use the `gcloud` CLI.
I've also moved the doc from `set-up-gcp-account` to `google-cloud-platform-gcp` to reflect its increased scope. I've put a redirect in, just in case there are any links elsewhere to the old doc.
I'll raise a follow up PR to update the on-call checklist to include making sure you have `gcloud` installed.
https://trello.com/c/LasnNuz4/561-rationalise-use-of-gcp-credentials-eg-for-dns-deployments
=> Update the GCP docs to cover DNS as well as mirrors

source/manual/alerts/slo-rate-checks-account.html.md
[Trello](https://trello.com/c/Crj6Z5SW/841-add-slack-alerts-for-when-we-drop-to-50-and-25-remaining-error-budget)
Documentation that will appear on the Icinga alerts for the GOV.UK
Account Error & Latency rate warnings.
See [govuk-puppet##11171][1]
[1]: https://github.com/alphagov/govuk-puppet/pull/11171
=> Document Alert: GOV.UK Account SLOs - Error rates

source/manual/on-call.html.md
AWS _really_ should already have been on this list. GCP is important
because we use it to manage the DNS for www.gov.uk, which we may need to
change in the event of a CDN outage.
Follows #3148
https://trello.com/c/LasnNuz4/561-rationalise-use-of-gcp-credentials-eg-for-dns-deployments
=> Add accessing AWS and GCP to on call checklist

source/manual/cdn.html.md, source/manual/run-ab-test.html.md
We no longer have a shared 2nd line account for Fastly, so can
no longer rely on a centrally stored API key for deployments. This
PR documents how to create an access token linked to your own
Fastly account, and how to use it to deploy the CDN configuration
for `assets` and `www`. (There is also a third option,
`performanceplatform`, but as this is retired, I assume it should
be removed and we've no need to document it here).
Trello: https://trello.com/c/ShvEW3om/2560-add-documentation-on-how-to-use-individual-fastly-accounts-2
=> Document how to deploy Fastly from our individual accounts

source/manual/rules-for-getting-production-access.html.md
Removed the probation exemption for supervised access to production for SREs. Now they're back in GOV.UK, and there isn't the likelihood of support rotating through a pool of SREs, earning prod access should be the same for everyone.
Also, the production access guidance said that it was relevant for GOV.UK devs, and SREs from TechOps. TechOps is no longer a thing, and the SREs are back in GOV.UK.
=> Removed the probation exemption for supervised access to production for SREs

data/applications.yml
These are key parts of how GOV.UK work, but their README & docs aren't currently imported because they're omitted from this list of applications. govuk_app_config - a gem - is on the list already, so this isn't anything new.
=> Add important gems

source/manual/setting-up-new-rails-app.html.md
Relates to: https://github.com/alphagov/email-alert-api/pull/1650
=> Update reference to Email Alert API README example

source/manual/get-started.html.md
This is an important thing for developers to be aware of as it saves a few extra steps, so we should include this in the Getting Started docs.
=> Add `app-console` to Getting Started docs

data/applications.yml
This sets the ownership of some applications to reflect reality (they were previously unowned). 
[Trello](https://trello.com/c/jrlfr67p/2617-1-change-dependabot-responsibility-for-some-apps)
=> Change ownership of some applications

source/manual/changing-organisation-slug.html.md
The original links were to a Jenkins job that can no longer be accessed.
Also added a note about using single quotes. If double quotes are used the task fails with:
Don't know how to build task 'reslug:organisation[national-probation-service,' (See the list of available tasks with `rake --tasks`)
=> Update links to rake task

data/applications.yml
Following the convention established in 64127d3417788aba3c2c39a7e7c9ce1dbd458356,
we want to make sure that all active GOV.UK utilities are included
in the Developer Docs, to increase visibility and discoverability
of their documentation.
=> Add govuk_schemas to applications list

source/manual/datalabs-aws-sagemaker.html.md, source/manual/datalabs-bigquery.html.md, source/manual/datalabs-content-store.html.md, source/manual/datalabs-govuk-knowledge-graph.html.md, source/manual/datalabs-govuk-mirror.html.md, source/manual/datalabs-onboarding-guidance.html.md, source/manual/datalabs-reference-info.html.md, source/manual/datalabs-setup-local-machine.html.md, source/manual/datalabs-start-new-project.html.md
Create a data labs team manual section in the GOV.UK developer docs.
Add the documented onboarding process for new data science starters to the team manual once it is complete.
Content includes BigQuery, Content Store, Knowledge Graph, GOV.UK mirror, set up local machine, start new project, and reference information.
So new starters have a documented process to follow and refer to, and have immediate access to information needed to get them up and running in their role.
Trello card:
https://trello.com/c/OJQyfn1A/1046-create-a-data-labs-team-manual-and-include-the-onboarding-process
=> Create Data Labs team manual

source/manual/alerts/redis.html.md
We recently went through an incident involving Redis running out of memory. The two immediate solutions were to:
1. Increase the size of the Redis nodes, to buy time/memory
while we investigated the root cause
2. Find the key using large amounts of memory (maps to a
an app's queue), and fix the underlying app bug.
I have update the doc to reflect the various steps we took
for future incidents.
=> Add Redis memory debugging docs

source/manual/encrypted-hiera-data.html.md
The CLI instructions did not work for me for updating two distinct keys.
I'm not sure why using the Mac GPG Keychain application is any different, as if I go into its "Preferences", it appears to use `hkps://keys.openpgp.org`.
If I run `gpg --keyserver keys.openpgp.org --recv-keys THE_KEY_ID` (with or without the protocol prefix), I get `gpg: keyserver receive failed: General error`.
=> Add more troubleshooting steps for GPG key updating

source/manual/readmes.html.md, source/manual/setting-up-new-rails-app.html.md
https://trello.com/c/Psf7EzPB/204-move-away-from-startupsh
This continues the changes from https://github.com/alphagov/govuk-developer-docs/pull/3159.
=> Rewrite template for general READMEs

source/manual/data-gov-uk-2nd-line.html.md, source/manual/data-gov-uk-deployment.html.md, source/manual/data-gov-uk-monitoring.html.md, source/manual/data-gov-uk-supporting-ckan.html.md
Updated dev docs for support of CKAN 2.9 as the commands are different. 
Also removed grafana and prometheus sections and updated the deployment doc for github actions.
https://trello.com/c/iq6oz3CT/2412-investigate-why-ckan-api-response-extras-block-removed-and-fix-or-document-it
https://trello.com/c/DZJFi8z5/2613-create-prs-to-prep-for-29-upgrade
=> Update data gov uk 2ndline notes for CKAN 2.9

source/manual/sentry.html.md
Trello: https://trello.com/c/izP3qFWg/2516-document-how-teams-can-set-up-sentry-slack-alerts
=> Document how to set up custom Sentry alerts per-team

source/manual/rollback-puppet-if-jenkins-is-broken.html.md
Sometimes, a Puppet release may break Jenkins and since Jenkins is used to
release Puppet, there is no straight forward way to rollback Puppet.
This PR documents the rollbacks of Puppet to a previous release so that Jenkins is restored.
[Trello Card](https://trello.com/c/pCKvKF2J/2583-upgrade-jenkins-plugins-to-versions-without-security-vulnerabilities-5)
=> Create rollback strategy for Puppet if Jenkins is broken

source/manual/deploying-terraform.html.md
Adds a section to the docs on [deploying terraform](https://docs.publishing.service.gov.uk/manual/deploying-terraform.html) 
We have a [dedicated jenkins job](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS) that abstracts a lot of the technical work but also isn't actually listed anywhere in our docs. It's useful to publicise this as an option if the first 2 aren't working for whatever reason.
=> Add section on using jenkins to terraform deployment docs

source/manual/setting-up-new-rails-app.html.md
The comma appears to be a typo and should not be there.
=> Remove comma from example Gemfile

data/applications.yml
This is a new application that will interface between GOV.UK's frontend apps and external location APIs (e.g. Ordnance Survey).
The application is not currently deployable, so some attributes will need updating as part of later work.
[Trello card](https://trello.com/c/yGHQYoWC)
=> Add Locations API

source/manual/setting-up-new-rails-app.html.md, source/manual/test-and-build-a-project-on-jenkins-ci.html.md
Updating the documentation for creating a new Rails app to remove duplication of the Jenkins documentation and make the instructions clearer for setting up Sentry.
[Trello card](https://trello.com/c/yGHQYoWC)
=> Update documentation for creating new Rails application

data/applications.yml
Bouncer has been continuously deployed since December!
https://github.com/alphagov/govuk-puppet/pull/10858
Trello: https://trello.com/c/dXp9XIV1/2571-enable-continuous-deployment-for-bouncer-3
=> Mark Bouncer as continuously deployed

source/manual/manage-ruby-dependencies.html.md
The instructions for adding Dependabot to a repo are based on the previous standalone Dependabot that was a GitHub integration. Now Dependabot is available within GitHub natively, we need to set it up differently.
[Trello card](https://trello.com/c/WgK6wWr2)
=> Update instructions for adding Dependabot

source/manual/access-to-licensing-for-third-parties.html.md
The classess are called `licensing_...` not `licensify_...`
Confirmed with:
```
$ ssh jumpbox.production.govuk.digital govuk_node_list -c licensify_frontend
$ ssh jumpbox.production.govuk.digital govuk_node_list -c licensing_frontend
ip-00-00-0-00.eu-west-0.compute.internal
ip-00-00-0-00.eu-west-0.compute.internal
```
=> Fix machine classes for Licensify

source/manual/reindex-elasticsearch.html.md
The instructions previously suggested the indices could only become out of date during working hours. This is not necessarily correct as publishing can take place at any time of day or night.
Updating to suggest the process is run regardless of when the reindexing takes place.
=> Update information for Search API reindexing

source/manual/get-started.html.md
This is changed around so that a user is set-up in the user monitor before GitHub, this is to prevent people (like myself) who add someone to GitHub and not realise 2nd line are about to be nagged.
=> Set up user monitor before GitHub access

source/manual/reindex-elasticsearch.html.md
There are a number of Rake tasks listed in the Elasticsearch reindexing documentation that suggest running the task directly on a machine.
This is generally discouraged, with Rake tasks preferred to be run as a Jenkins job.
Therefore updating the documentation to provide links to Jenkins for each environment, which also reduces the amount of copy and pasting needed.
=> Provide links to Jenkins for Elasticsearch Rake tasks

source/manual/run-ab-test.html.md
Adds extra advice about whether turning on an A/B test at 0% should be considered.
Card: https://trello.com/c/iubAAacJ
The Explore team recently ran an A/B test, and in the retro it was dicussed that it could've been deployed but not switched on to allow other teams to be aware of the impact that the test has on their work. Documenting it here so that it can be considered for future A/B tests.
=> Update A/B test with 0% advice

source/manual/alerts/content-data-api-app-healthcheck-not-ok.html.md.erb
It was too cumbersome for my liking, to figure out and navigate to the healthcheck endpoints.
Ideally this would be linked directly from the Icinga alert too, but adding to the docs is a good start.
=> Add links to healthcheck endpoints

source/manual/get-started.html.md
Not many tech leads actually have the ability to add users to GitHub, so the most efficient
approach is just to ask in the tech leads channel and someone with the necessarily
privileges will action it.
=> Update "who to ask" in getting added to GitHub

source/manual/alerts/rebooting-machines.html.md
The previous instructions were open to ambiguity. For example,
I interpeted them as "disable the unattended reboots on the
docker_management machine class", but this made little sense as
we only had one such class on Production, so why would it be
necessary? It's only by digging into an old govuk-puppet [commit]
that it's clear that actually we need to disable unattended reboots
in ALL machines.
I've also removed the unhelpful link to
https://github.com/alphagov/govuk-puppet/blob/master/hieradata_aws/class/docker_management.yaml,
as this doesn't provide any additional information that isn't
already in the doc.
[commit]: https://github.com/alphagov/govuk-puppet/commit/97ab27fc9a2d79305111280ee3f2a74a0d0f9e12
=> Describe the process for rebooting docker-management machines

source/manual/notify-emergency-alerts.html.md
https://www.pivotaltracker.com/story/show/179482902
Previously the Integration and Staging versions of GOV.UK Alerts
both pointed at the same backend (in Notify's Staging environment).
Now that Notify has a dedicated backend for GOV.UK Integration to
point to, this updates the guidance to reflect that.
=> Update govuk-alerts guidance to match new config

source/manual/add-an-icinga-passive-check.html.md
Recently we've seen a number of warnings where the passive checks
have not arrived in Icinga. In these cases it is helpful to
manually intervene and force another check.
Trello: https://trello.com/c/WtvLEPCN/1202-passive-checks-from-jenkins-not-arriving-in-icinga
=> Troubleshooting "Freshness threshold exceeded" warnings

source/manual/get-started.html.md
It's better to use the GOV.UK group since it's more up-to-date and is GOV.UK specific.
=> Correct GDS GitHub Owners email link

source/manual/republishing-content.html.md.erb
The name of the rake task was updated, so updating the documentation to reflect this.
=> Update rake task for republishing an organisation

source/manual/howto-modify-change-note.html.md
These don't work when copied into a console, so removing the styling.
=> Remove styled quotes from change note instructions

source/manual/dns.html.md, source/manual/renew-a-tls-certificate.html.md
CDDO colleagues monitor the DNS records for gov.uk, and they would like
us to notify them before making changes so they know to ignore the
alarms we set off.
We also need to tell the GOV.UK lead technologists because they're the
people who'll get a call from JISC to confirm. And also it's generally
good for them to know what's going on.
=> Update DNS docs to notify senior tech and CDDO

source/manual/zendesk.html.md
We have been using this queue for product related tickets but we now
have a new group to triage them too. This means 2nd line can use the
low queue for other purposes.
=> Update use of `low` priority Zendesk queue

source/manual/configure-linting.html.md
https://trello.com/c/Cr2TnMtI/193-make-it-easier-to-agree-with-rubocop-govuk
This is so we maintain this convention [1] in new repos.
[1]: https://github.com/alphagov/content-publisher/pull/2411
=> Include new warning in RuboCop header template

source/manual/alerts/publisher-scheduled-publishing.html.md, source/manual/alerts/search-reindex-failed.html.md.erb, source/manual/fix-out-of-date-search-indices.html.md, source/manual/running-rake-tasks.html.md
- Link to Jenkins job with pre-filled parameters
- Reminder of which machine to SSH to
- Reminder of which directory to CD into before attempting to run rake task
- Fix typo
=> Make following the indices-fixing instructions easier

source/manual/emergency-publishing.html.md
This isn't currently visible so including it in these instructions is unhelpful.
Refers to: https://docs.publishing.service.gov.uk/manual/emergency-publishing.html 
Related: https://github.com/alphagov/static/pull/2651
=> Remove reference to Brexit banner

data/applications.yml
Change the name of the team owning the publishing applications so they 
will appear in the correct slack channel when we receive dependency 
updates from the https://github.com/alphagov/govuk-dependencies application.
Trello card: https://trello.com/c/S6LHALdf/40-set-up-alerts-to-slack-for-dependencies-for-the-apps-we-own
=> Change the govuk-publishing to govuk-publishing-tech

source/manual/emergency-publishing.html.md
This updates the docs about publishing an emergency banner:
- adds a note and link to the non-emergency banner docs
- renames the emergency banner from "emergency publishing banner"
=> Update docs on banners

source/manual/emergency-publishing.html.md
This is a temporary step to workaround the fact that Jenkins doesn't
clear these caches. It was added on 2021-11-22, and should be removed
shortly afterwards once the underlying issue is resolved.
=> Add docs to manually clear shared memcacheds

source/manual/emergency-publishing.html.md
The memcached caches clear automatically after 60 seconds.
Currently the jenkins job to clear them is failing.
Therefore our recommendation in the short term is to
wait for the memcached caches to clear, and then re-run
the flush CDN/Varnish jobs.
=> Add Clear the CDN and Varnish caches step to emergency doc

source/manual/merge-pr.html.md
These PRs come up quite regularly, and there's always a bit of confusion as to how to handle them.
It will be useful to have a central guide we can point toward next time this comes up.
=> Add "non-developer" PR category

Gemfile, Gemfile.lock
This should be included by default to make local development
easier.
That said, invoking byebug is surprisingly involved, as the Linter
will fail. It currently involves four lines of code:
```
require "byebug"
byebug
```
Hopefully that can be optimised in a future commit. For now, it's easier just to temporarily remove the linting task when introducing a byebug.
=> Add byebug developer dependency

source/manual/get-started.html.md
Getting access to Signon allows new developers to see the user-facing side of their team's applications and allow them to replicate bugs without needing to access the production environment.
=> Add Signon access to Get Started guide

source/manual/get-started.html.md
All developers with production access can now assume the administrator role, so updating the documentation to reflect this.
=> Update documentation for getting access to AWS integration

source/manual/get-started.html.md
The CLI command given in step '8. Access AWS for the first time' attempted to log the user in to AWS as a power user. However the user will only have read-only permissions at this point (as granted in step 7).
=> Update 'getting started' docs for accessing AWS

source/manual/get-started.html.md
Update the 'Get started on GOV.UK' document so new starters ask to be added to the seal Slack bot.
=> Add 'seal' to the getting started guide

.github/workflows/ci.yml
This repository uses GitHub Actions to automatically build and publish the docs to GitHub Pages.
Deploying to GitHub Pages involves pushing a commit of the built site to the `gh-pages` branch. We use the third-party GitHub Action `peaceiris/actions-gh-pages@v3` to handle this for us.
This commit sets the config option `force_orphan: true` on `peaceiris/actions-gh-pages@v3`, which will cause new commits to `gh-pages` to be orphaned.
Old build commits will therefore no longer belong to the `gh-pages` branch. This should result in future fetches and clones of the repo ignoring or garbage collecting those dangling commits.
Currently the `gh-pages` branch sits at around ~10k builds, so this change should enable a fairly significant size reduction for the repo.
=> Remove old GitHub Pages commits to reduce repo size

app/external_doc.rb, spec/app/external_doc_spec.rb
We already had a [test](https://github.com/alphagov/govuk-developer-docs/blob/6fb3785cfb4386154c89c49598b7ba5913da6e58/spec/app/external_doc_spec.rb#L72-L74) for converting absolute URLs to the correct github.com representation of that URL. But our tests failed to cover the scenario whereby we're parsing a URL within the context of being inside the `docs/` subfolder.
A document with a link to `/config/schema/field_definitions.json` would have the link incorrectly parsed to
`https://github.com/alphagov/search-api/blob/main/docs/config/schema/field_definitions.json`. It should actually be
`https://github.com/alphagov/search-api/blob/main/config/schema/field_definitions.json`.
Fixes #3320.
Zendesk: https://govuk.zendesk.com/agent/tickets/4788958
=> Fix absolute URL parsing

source/manual/test-and-build-a-project-on-jenkins-ci.html.md
Trello: https://trello.com/c/oRrpsveM/64-investigating-running-current-version-of-postgresql-and-mysql-on-govuk-ci
This explains the connection strings and set-up needed to utilise the
Docker hosted versions of the databases in CI. These were installed via
Docker as a means to work around the fact we run CI off a very old
operating system (Ubuntu Trusty).
=> Document how to test with current PostgreSQL and MySQL versions

source/manual/architecture-deep-dive.html.md, source/manual/architecture-shallow-dive.html.md
User research on new developer onboarding highlighted the need for a summary of GOV.UK architecture. This new content is taken from the notes on the Intro to GOV.UK architecture presentation. It is intended to compliment the [architectural deep dive on the GOV.UK developer docs](https://docs.publishing.service.gov.uk/manual/architecture-deep-dive.html).
Please note, I'll add in inline links to different sections once the content is approved.
=> Add architecture shallow dive to developer docs

source/manual/encrypted-hiera-data.html.md
This PR updates the docs to provide an alternative method of adding an existing GPG key from a keyserver when it cannot be found via the `gpg` CLI or via GPG Keychain.
=> Update docs for when GPG key cannot be found

source/manual/architecture-shallow-dive.html.md
A few tweaks to the GOV.UK architecture shallow dive:
- makes search journey less specific (user could also use search function in main menu)
- corrects non-homepage section
- adds Manuals Publisher to the list of publishing apps
=> Changes to architecture shallow dive docs

data/applications.yml
Marks the [tech-docs-monitor](https://github.com/alphagov/tech-docs-monitor) as retired, as it is no longer used by GOV.UK, and the repo is archived.
=> Mark tech-docs-monitor as retired

data/applications.yml
Reverts alphagov/govuk-developer-docs#3334 because some other teams still use it, so we should include it on the list of apps
=> Revert "Mark tech-docs-monitor as retired"

source/manual/alerts/mirror-sync.html.md
Improve the alert description, add some important context, describe the user impact and add a troubleshooting section.
The "service description" of the alert is being changed from "Mirror sync" to "Mirror GOV.UK content to S3" in alphagov/govuk-puppet#10971, hence the change of title while preserving the original URL.
=> Improve playbook for S3 mirror sync alert.

source/manual/test-and-build-a-project-with-github-actions.html.md
We no longer have this restriction and currently publish node modules via GitHub Actions. The point at the top about checking with senior tech before using secrets still remains.
=> Remove gem publishing restriction

source/manual/alerts/speedcurve-lux-js-version-check.html.md
This is documentation to pair with
https://github.com/alphagov/govuk-puppet/pull/11339
It documents what steps need to be taken to update lux.js file. This is
so that anyone who sees the alert can react to it.
I was a little surprised how nuanced this process was and expect that
it'll need some input from someone experienced in the tool whenever it
takes place.
=> Document the update SpeedCurve lux.js process

source/manual/republishing-content.html.md.erb
Updating the documentation to reflect the change in the rake task name.
=> Update rake task for republishing a document.

source/manual/alerts/rebooting-machines.html.md, source/manual/rabbitmq.html.md
This PR updates the docs on RabbitMQ to add details about the web control panel, specifically how it can be used during the process of rebooting instances of the cluster to aid with monitoring when those instances rejoin the cluster. The main RabbitMQ doc page is also updated to add the username and point to where to decrypt the password within the secrets repo.
=> Update RabbitMQ docs to add detail about the web control panel

data/applications.yml
Dependabot PRs for these repos currently notify #govuk-developers, but it is probably more relevant for these to go to specific teams - see commits for details.
=> Update app owners

source/manual/encrypted-hiera-data.html.md
I could not find these error messages in the docs, and the
eventual workaround was not signposted very well. Hopefully this
documentation change will help the next developer who has to
import a GPG key.
=> Document error messages and workarounds for importing GPG keys

source/manual/data-gov-uk-2nd-line.html.md
The link in step 1 under "Update a user account name" in "Common 2nd
line support tasks for data.gov.uk" is broken.
https://docs.publishing.service.gov.uk/manual/data-gov-uk-2nd-line.html#update-a-user-account-name
=> DGU support tasks page link correction

source/manual/encrypted-hiera-data.html.md
The number actually appears before the `::GPG`.
=> Fix example of previously encrypted data

source/manual/manage-assets.html.md.erb
Makes it clearer how to determine whether an asset is a Whitehall asset or from another application.
Also updates a few of the other steps where the process has changed.
=> Update asset removal instructions

source/manual/government-changes.html.md.erb
This has come up a couple of times in previous reshuffles.
https://trello.com/c/5dOf6Icd/1219-create-docs-for-how-to-rearrange-ministers-peoples-role-titles-in-whitehall-collections
=> Add steps on reordering ministerial roles in Whitehall

data/applications.yml, source/manual/2nd-line.html.md, source/manual/alerts/content-data-api-app-healthcheck-not-ok.html.md.erb, source/manual/alerts/fetch-analytics-data-for-search-failed.html.md, source/manual/alerts/high-nginx-5xx-rate.html.md, source/manual/alerts/publisher-unprocessed-fact-check-emails.html.md, source/manual/alerts/search-reindex-failed.html.md.erb, source/manual/ask-for-help.html.md, source/manual/assets.html.md, source/manual/data-gov-uk-2nd-line.html.md, source/manual/data-gov-uk-architecture.html.md, source/manual/data-gov-uk-supporting-ckan.html.md, source/manual/load-testing.html.md.erb, source/manual/manage-assets.html.md.erb, source/manual/mapit-caches.html.md, source/manual/request-fastly-tls-certificate.html.md, source/manual/scale-mapit.html.md, source/manual/sentry.html.md, source/manual/transition-a-site.html.md, source/manual/transition-architecture.html.md, source/manual/whitehall-historical-accounts.html.md
Our Slack channel has been renamed to #govuk-platform-reliability-team.
Some app ownership has also been updated to reflect https://docs.publishing.service.gov.uk/apps/by-team.html which has been recently updated.
https://trello.com/c/65t3VYTd/2818-update-references-to-platform-health-in-dev-docs-and-govuk-techlead-rota
=> Update references to Platform Health

source/manual/deploying-terraform.html.md
The previous docs described in detail how to use the gds-cli and
deploy.rb script to deploy Terraform, but both of these methods
simply trigger the same parameterised Jenkins build under the
hood. There's no particular advantage to this abstraction layer,
and furthermore, no way of triggering a build of a branch of
changes, which can only be done by configuring the job in Jenkins
manually. As this is quite a common use case for the job, it
makes sense to put the Jenkins instructions first, and to highlight
this as the primary means of deploying Terraform.
With this as the preferred approach, we no longer need to
document how to get a GitHub token (it isn't required by the job),
and we don't need to repeat the definition of each parameter either.
I've kept a short section at the end of the …
=> Simplify 'Deploy Terraform' docs

README.md
Add some example start commands while running the app for the first time
Adding some context how to quickly get setup running the app - [prompted from work on this PR](https://github.com/alphagov/govuk-developer-docs/pull/3304)
While `startup.sh` is active, i'm aware we're slowly moving away from this we might want to remove this
=> Update with start commands

source/manual/howto-ssh-to-machines.html.md
@richardTowers  showed me this one recently, it was really useful
to stop hopping around between boxes randomly when I had to run a
command across each and didn't know the IP addresses in advance.
Was surprised this wasn't in the docs!
=> Add the connect to box by index trick to SSH docs

source/manual/ruby.html.md
This section showed how to check for a version of ruby, but using
Fabric, which is deprecated.
Best thing now would be to get into the machines and check manually.
=> Remove section `Testing whether a version of Ruby is in use`

source/manual/emergency-publishing.html.md
[Trello](https://trello.com/c/BUSq6xQn/1270-emergency-banner-publishing-drill)
Whilst doing the regular emergency banner drill Dec 22nd, we commented
that there were not docs linked for convenience. Then thought we should
do something about that.
=> Add links for convenience to emergency banner page

source/manual/tools.html.md
Might be a place to come back to if we decide something like [pssh][1]
is cool and should be more widely used on GOV.UK
[1]: https://linux.die.net/man/1/pssh
=> Remove Fabric from manual tools page

source/manual/guidance-and-tools-for-digital-accessibility.html.md
**What**
https://trello.com/c/LO5gAQHO/996-add-introduction-copy-to-guidance-and-tools-for-digital-accessibilitypage-in-the-manual
Create and add some introductory text to this page https://docs.publishing.service.gov.uk/manual/guidance-and-tools-for-digital-accessibility.html.
**Why**
The manual (for developers) has recently been updated to link to the **Guidance and tools for digital accessibility** page. The page is a bit empty at the moment (essentially only the link to the guidance is included).
=> Update guidance and tools for digital accessibility page

source/manual/how-to-be-a-good-buddy.html.md
Adds documentation on how to be a good "buddy" as part of a new joiner's onboarding process.
The buddy convention is something we follow stringently in the frontend community. Following a presentation I did to said community, it was proposed some documentation to the effect of that presentation could be added to these dev docs, potentially as a companion piece to our docs on the [responsibilities of a tech lead](https://docs.publishing.service.gov.uk/manual/tech-lead-responsibilities.html). This is an attempt to capture the contents of that presentation which went into recent positive examples of being a buddy and the differences between other roles like line manager to a new joiner.
=> Add documentation on how to be a good buddy

source/manual/auto-scaling-groups.html.md, source/manual/common-aws-tasks-for-2nd-line-support.html.md
This commit does the following:
* consolidates the removal of instances section from auto-scaling-groups
into common-aws-tasks-for-2nd-line-support, as the former documentation
is geared towards scaling up, or down, rather than detaching instances.
* Removes 'reboot' as an example of when you would want to detach an
instance as:
a) the reboot docs linked don't mention it
b) for a reboot we probably want to set the instance to 'Standby' as we
expect the instance to be put back in service, rather than terminated.
Using 'Standby' is easier than detaching as the instance capacity is automatically
adjusted.
* Add specific section around terminating an instance, which follows as
a potential action after detaching an instance.
* Uses AWS terminology (detach vs remove).
* Point to AWS docs, …
=> Update docs concerning detaching and terminating

source/manual/get-started.html.md
Documentation here: https://docs.publishing.service.gov.uk/manual/get-started.html#create-a-user-to-ssh-into-integration
...refers to an alphagov RSA key, which isn't mentioned elsewhere, and says the generated key must be RSA. In fact puppet seems to be fine with ED25519, so we could just use the public key generated in an earlier step for Github access.
Changes
- change reference to alphagov.pub to use id_ed25519.pub
- add note that older RSA keys can be used as well.
=> Update getting started docs to fix references to missing keys

source/manual/ruby.html.md
- Remove duplication between this and debian-packaging.html
- Remove references to dev VM
- Add references to 'upgrade-ruby-version'
- Describe how to test the raised PRs
- Describe how to manually force the Ruby versions to be installed to unblock upgrading apps
Trello: https://trello.com/c/ZMrLumn8/2837-upgrade-ruby-for-our-apps-5
=> Update 'Ruby upgrade' instructions

source/manual/alerts/app-healthcheck-not-ok.html.md, source/manual/alerts/email-alert-api-high-queue-latency.html.md
Trello: https://trello.com/c/6fLV2SRM/103-review-documentation-for-references-to-old-database-architecture
We no longer have this RDS instance. I've replaced the specific link
(Email Alert API) as a direct one to the instance, for the generic one
I'm just not including a database variable so Grafana picks the first
one and the user of the graph can determine the appropriate one.
=> Remove references to blue-postgresql-primary

source/manual/howto-redirect-html-attachment-urls-from-whitehall.html.md
The name of the rake task to redirect HTML attachments in Whitehall has
been changed in a refactor. This amends the docs to have the correct
names.
=> Fix the name of the redirect HTML attachment task

source/manual/debian-packaging.html.md
- Clarify that the default 'trusty' value leads to a Debian package being created
- Clarify how to get the associated artifacts
- Clarify how to test without the dev VM
- Use hour & minute in the snapshot name, to allow multiple snapshot publishes per day
- Clarify that publishing can only happen on Production
Trello: https://trello.com/c/ZMrLumn8/2837-upgrade-ruby-for-our-apps-5
=> Improve documentation around creating/testing packages

config/tech-docs.yml, data/repos.yml
This is not a GOV.UK repo, so should not be imported as a GOV.UK
app in the GOV.UK docs.
=> Remove tech-docs-monitor

app/external_doc.rb, spec/app/external_doc_spec.rb
Requests for the `github_readme` method of a private repo return
`nil`:
https://github.com/alphagov/govuk-developer-docs/blob/7427f6886c0676a483e837824fb7d53a19db6df7/app/app.rb#L208
This is useful as it lets us provide specific error messages:
https://github.com/alphagov/govuk-developer-docs/blob/c4b9aebacb3d2c6f2948a5d96ef1c288fc2cd47b/source/partials/application/_readme.html.erb#L9-L13
However, calling `ExternalDoc.parse(application.readme` in
https://github.com/alphagov/govuk-developer-docs/blob/c4b9aebacb3d2c6f2948a5d96ef1c288fc2cd47b/source/partials/application/_readme.html.erb#L15
meant we were passing `nil` to the HTML::Pipeline's `to_html`
method. Even though we're attempting to be defensive and cast it
with `.to_s`, this was raising a "Cannot modify frozen string"
exception. …
=> Handle private repos' lack of README gracefully

source/manual/architecture-shallow-dive.html.md
Update the cache time for fastly to be 5 minutes, reasons for this are outlined in this [RFC](https://github.com/alphagov/govuk-rfcs/blob/main/rfc-144-consistent-cache-expiry.md)
https://trello.com/c/OaUhq6uI/722-replatform-emergency-banner
=> Update fastly cache time to 5 minutes from 30

README.md, config.rb
Often I find myself wanting to work on a few pages of the dev docs which
are local to this repository.
It's annoying having to wait for my laptop to download all of GitHub
before middleman will start serving the entirely local content I want to
edit.
Adding this flag gives me a way to run the middleman server and work on
these pages without needing to make requests to GitHub.
Unfortunately, middleman server will still download stuff that's
requested via .erb files when you go to the homepage / apps page etc. I
had a look at disabling all of this, but I'd need to do a big refactor
to make it clean so this small change was the best I could come up with.
=> Skip loading of proxy pages with an env var

data/dashboard.yml
[Trello](https://trello.com/b/TlvJ4j59/doing-accounts)
A bit of a clear up as we look to hand over some of our stuff.
- Increase visibility of the GOV.UK Personalisation Gem, folks can use that for future personalisation needs
- Remove a GOV.UK Account section, it was empty and probably should remain so.
See commit messages for further thinking.
=> Account docs cleanup

source/manual/access-to-licensing-for-third-parties.html.md
The previous docs assumed a fair bit of GOV.UK knowledge, and also that
things (like the automatic deployment to integration) actually worked.
This made it very difficult for third parties to follow the docs, unless
they'd been shown all the idiosyncracies a few times.
I've updated the docs so they're much more explicit. This means making
more Jenkins URLs public, but these are already effectively in the
public domain since govuk-puppet and govuk-aws are already open source.
Our colleagues at Apto still don't have access to staging or production
Jenkins', but I'm looking into that separately.
=> Update deploy licensing with jenkins docs

source/manual/switch-app-off-temporarily.html.md
Fabric was previously the route to do this across multiple machines in a
class. With fabric gone, the commands will need to be more manual
=> Replace references to fab for how to switch off an app guidance

source/manual/howto-modify-change-note.html.md
This commit:
* Adds both ways to update a change note in Publishing API. Previously,
only one method was documented and didn't actually include the last
step which is to send the document downstream.
* Updates Whitehall guidance to check change note as FuzzyMatch can
sometimes return the wrong note if searching by substring.
We could / should probably turn this documentation into rake tasks at
some point.
Trello:
https://trello.com/c/Xrz8kzbW/1043-documentation-update-for-modifying-a-change-note
=> Update modify change history doc

source/manual/alerts/mirror-sync.html.md
This adds a link to an overview of how the mirror is created and used, to give more context. It also removes some superfluous content.
=> Update mirror sync alert information

source/manual/add-translation-whitehall.html.md
Most of this is still relevant, but how we use Rails Translation
Manager has changed.
Trello: https://trello.com/c/G9cqeYfl/2688-update-rails-translation-manager-documentation
=> Update docs around adding a new language to Whitehall

source/manual/ruby.html.md
When upgrading Ruby versions apps need to be restarted following a deployment. This PR adds a note and some instructions on how to do this.
=> Add note to restart apps when upgrading Ruby version

source/manual/alerts/rabbitmq-high-number-of-unprocessed-messages.html.md
We added new queues to the email-alert-service to update subscriber
list details when the page they alert for is updated. [[1]]
There are alerts that might go off for these queues that will link to
this document, so we need to add links to the queue config here.
Also refactor the list of queues into a bulleted list - now there are 
five items the comma separated list was a bit clunky.
[Trello](https://trello.com/c/qdE5KvZu/1233-update-docs-for-message-processor-alerts)
[1]: https://github.com/alphagov/email-alert-service/pull/493
=> Add new RabbitMQ queues to alert docs

source/manual/alerts/high-nginx-5xx-rate.html.md
I was setting out to just remove the reference to fab here, but the
archived fab repo seems to have had statsd commands purposely removed
from it before we archived the repo.
Quote from an [old PR](fabric_scripts#291):
> I don't think this has been used in a while, and I also think there
> are better approaches now of addressing the problem it's trying to
> solve.
> I think this was about getting rid of UNKNOWN Icinga checks, but it's
> better just to acknowledge the failing check, or change the Graphite
> query if the data just hasn't arrived yet.
If that's the case then likely better to just clear up this entire
section.
[fabric_scripts#291](https://github.com/alphagov/fabric-scripts/pull/291)
=> Remove fab references - high 5xx

source/manual/common-aws-tasks-for-2nd-line-support.html.md
Following a drill of the process on 2nd line we found a couple of
improvements to add to the docs.
Trello card: https://trello.com/c/s31q1NXW/1286-2nd-line-drill-taking-instances-out-of-service
=> Improve detatch AWS instance doc

source/manual/reindex-elasticsearch.html.md.erb
In https://github.com/alphagov/govuk-puppet/pull/11548, we have added an index selector to the search reindex Jenkins job.
This means we can remove all references to the two options (one being the Jenkins job for all indices and the rake task for single indices). All reindex tasks can now be done with the same Jenkins job.
=> Update instructions for reindexing search

source/manual/manage-assets.html.md.erb
Adds a link to the Google Cloud Platform bucket where assets are mirrored.
This should make it easier to locate this bucket in an unfamiliar user interface.
=> Add link to GCP mirror bucket

source/manual/logit.html.md
The instructions where out of date due to changes in the Logit UI.  This
updates the instructions and gives details on how to resolve the problem
of a user not appearing.
=> Update Logit Team Permission Instructions

source/manual/zendesk.html.md
Some Zendesk tickets do not have a descriptive title (e.g. `Named contact` or `Technical support request`). This makes them difficult to recognise in a queue of tickets.
Adding an instruction to rename the ticket to something more descriptive in these cases.
=> Add instruction to rename Zendesk tickets

source/manual/fall-back-to-aws-cloudfront.html.md
Deploying these changes using Jenkins and Terraform is too slow and
unreliable to do during an incident.
To be honest, I think this would be better as a shell script. I'll raise
this as a PR to get people's opinions.
https://trello.com/c/LasnNuz4/561-rationalise-use-of-gcp-credentials-eg-for-dns-deployments
=> Document fall back to CloudFront as a manual process

README.md, source/manual/alerts/ddosdetected.html.md
This role has been created for AWS SRT to use if they are helping us investigate DDOS events. Rather than manually creating a new one via the console, we should use the one [created in govuk-aws](https://github.com/alphagov/govuk-aws/pull/1550).
=> How to enable use of the AWS SRT role

source/manual/encrypted-hiera-data.html.md
Update the documentation about rotation the puppet server encryption key to reflect that the GPG key and other relevant artefacts are no longer stored in the pass store but in the `puppet_servers_gpg` directory because these artefacts were not created by the pass tool.
Ref:
1. [govuk-secrets change pr](https://github.com/alphagov/govuk-secrets/pull/1244)
=> Update documentation about rotating the puppet server encryption key

source/manual/data-gov-uk-supporting-ckan.html.md
Fabric has been deprecated, we are replacing refrences with commands
that can be run directly on each box
=> Replace restart harvesting instructions referencing fab

source/manual/logging.html.md
We have enabled log shipping to Splunk. These are some basic docs, which I expect to be expanded when we find useful things that can be done with them!
https://trello.com/c/3PEIdbKp/2861-ship-ssh-logs-from-jumpboxes-to-splunk-5
=> Shipping auth logs to Cyber's Splunk

source/manual/get-emails-about-this-page.html.md
The GOVUK Accounts team have just rolled out single page notifications to 157k+ publications on GOVUK but we will not be the owners of this feature in the future. 
This doc is here to document what should be done in the event that there is a request to add or remove a publication from the single page notification button exemption list.
https://trello.com/c/XdtP8gTH
=> Add doc on single page notification exemptions

source/manual/welcome-to-2nd-line.html.md
A few changes to the 2nd Line welcome docs to:
-clarify that there won't *always* be a shadow
-remove mention of RE:GOV.UK team which no longer exists
=> Removes mention of RE GOV.UK team, and clarifies 2nd Line numbers

source/manual/conventions-for-rails-applications.html.md
This commit updates the Rails conventions manual to reflect the new approach we've taken for running Jasmine tests.
This change has come about because the `jasmine` gem has been deprecated, and it doesn't support Rails 7. We've therefore had to introduce this new approach as an enabler for our applications to run on Rails 7.
Ticket: https://trello.com/c/21VMx1NV/264-migrate-apps-to-use-jasmine-browser-runner
=> Update conventions for Jasmine JS testing

source/manual/alerts/smokey-loop-tests.html.md
We've removed fabric and must now provide an alternative in our docs.
=> Remove references to Fabric from "Try kicking the Nginx machines"

source/manual/dns.html.md
This was updated in https://github.com/alphagov/govuk-puppet/pull/11168
to avoid having to store google credentials with administrative
privileges in Jenkins.
The process now involves using the gcloud CLI to get a temporary access
token, and providing this to Jenkins via the API (as we do with AWS
tokens).
=> Update docs to state GCP access is needed for DNS deploys

source/manual/dns.html.md
This changes "lead technologists" to "senior tech" - making it consistent across the developer docs
=> Makes consistent references to senior tech team

source/manual/jenkins-ci.html.md
This old CI icinga monitored the CI machines that used to run in Carrenza.
All of that was decommissioned a while back and CI was moved to AWS integration.
CI is now monitored by the same Icinga that monitors the rest of integration.
=> Remove reference to ci-agent Icinga domain

source/manual/data-gov-uk-architecture.html.md
Update DGU docs as Elasticsearch has been replaced by Opensearch on PaaS
=> Update DGU information to use opensearch

source/manual/get-started.html.md
Across GDS we use the GDS email address of GitHub accounts as a means to establish whether GDS leavers still have access to our GitHub. We previously didn't have any documentation to inform new starters they should do this, which meant we had false positives on leavers.
=> Add associate GDS email with GitHub

source/manual/fall-back-to-mirror.html.md
Fabric previously ran sets of commands across multiple machines.
It has now been archived and is no longer in use due to difficulty in
upgrading python versions.
This begins a process of removing references to fab from our docs. Until
we find a new tool that allows us to run commands across multiple
machines, they will need to be a bit more verbose where a command must
be run on every machine.
=> Remove references to fabric from failover docs

data/repos.yml
This will mean Locations API appears on https://docs.publishing.service.gov.uk/apps.json, which will allow us to add it to Sentry.
Trello: https://trello.com/c/gPRVvLXh/2848-set-up-remaining-infrastructure-for-locations-api-5
=> Mark 'Locations API' as a deployed app

data/repos.yml
This marks govspeak as an app owned by govuk-publishing, since publishing acquired as part of owning govspeak-preview (as per https://trello.com/c/al645JXy/230-change-url-of-govspeak-and-govspeak-preview-application-to-show-they-are-a-govuk-service)
This also updates the ownership data of govspeak preview so that that tool is represented as a hosted application rather than un-hosted utility.
=> Update publishing govspeak/govspeak-preview ownership

app/app.rb, data/repos.yml, source/partials/application/_links.html.erb, source/templates/application_template.html.md.erb, spec/app/app_spec.rb
Following https://github.com/alphagov/govuk-developer-docs/pull/3478 I noticed there were a few issues with the links metadata for repos so I went down a bit of a 🐰 🕳️ to fix them.
This fixes a bunch of incorrect metadata and the presentation of a number of links. It's easiest review commit-by-commit where each granular change is explained
Some examples:
|Before|After|
|------------|------------|
|<img width="841" alt="Screenshot 2022-03-29 at 12 28 40" src="https://user-images.githubusercontent.com/282717/160601575-6f010ce0-5015-4202-93c6-009a0b4c5525.png">|<img width="792" alt="Screenshot 2022-03-29 at 12 29 35" src="https://user-images.githubusercontent.com/282717/160601681-06ee1930-d87f-4be7-bde8-d82e984727a3.png">|
|<img width="792" alt="Screenshot 2022-03-29 at 12 30 38" …
=> Fix incorrect repo links

source/manual/keeping-software-current.html.md
This follows a discussion between several members of Senior Tech and members of the Platform Reliability team.
[Trello](https://trello.com/c/TQj5sGXq/2881-update-govuk-policy-on-software-versions-and-dependency-management)
=> Rewrite policy around dependency management

data/dashboard.yml, source/partials/_intro.html.md
We linked to a number of Archived repositories, which doesn't seem very useful.
We also had an empty section for 'Specialist apps', which we should just remove.
=> Remove deprecated repos and sections

source/manual/conventions-for-rails-applications.html.md
The content in this convention no-longer reflected reality. Rails has
moved away from Webpacker since Rails 7 and thusly, so has our
preference to use it.
We do however aspire to use modern Javascript, but which form we will
take is not clear. However whatever road we take, we will need to
resolve the asset pipeline coupling of GOV.UK Publishing Components,
which is the main limiter for newer apps.
This update tries to condense that into a single sentence.
=> Retire webpacker aspiration for vaguer modern one

data/repos.yml, source/manual/run-ab-test.html.md
The Heroku-hosted search-performance-explorer app is being retired.
[trello](https://trello.com/c/TvBvDkuF/1218-retire-search-performance-explorer)
=> Retire search performance explorer

source/manual/fall-back-to-mirror.html.md
It's worth mentioning how those pages are handled by the mirrors in the docs as
it might not be expected to get a 403 response for an originally 404 page. 
This behaviour is currently documented in [Smokey tests](https://github.com/alphagov/smokey/blob/aaa0522666d49db116b939276f0e0969357e3ed4/features/mirror.feature#L23-L30) which were identified as
redundant in the [Smokey audit](https://docs.google.com/spreadsheets/d/1i2k4WexywoJurdFddOxiNICN-Elv1D5Mb2sdaCjF1t0/edit#gid=0&fvid=1582574436) and will be removed.
=> Document GOV.UK mirrors responses for search and non-existent pages

data/repos.yml
It is [no longer used anywhere](https://github.com/search?q=org%3Aalphagov+asset_bom_removal-rails+-repo%3Aalphagov%2Fasset_bom_removal-rails+-repo%3Aalphagov%2Fgovuk-dependency-analysis&type=code).
Depends on https://github.com/alphagov/govuk-puppet/pull/11668.
=> Mark asset_bom_removal-rails as retired

data/repos.yml, source/manual/2nd-line.html.md, source/manual/screens.html.md
This was identified as needing renaming, in
https://github.com/alphagov/govuk-developer-docs/pull/3509/commits/75956e5bc70cd0a4dc573c03e200dfd47e4e8784.
=> Rename blinkenjs to govuk-secondline-blinken

source/manual/heroku.html.md
There was a struggle to find out how to access the email account
attached to the Heroku account. This should point people in the right
direction.
=> Add how to change the Heroku password

data/repos.yml
This simply adds the `govuk-developer-docs` repo to the list of repos, for completeness
=> Add developer docs to the list of repos

source/manual/alerts/low-available-disk-inodes.html.md
Current docs only cover the ci-agent machines, and the ci-master needs a slightly different form of help (until we can fix the problem where failed jobs aren't cleaned up automatically by Jenkins).
=> Add guidance for low disk space/inodes on the ci-master machine

config/tech-docs.yml, source/manual/pact-broker.html.md, source/manual/pact-testing.html.md
https://trello.com/c/fRihmgQ8/266-add-top-level-guidance-about-where-we-write-tests-on-govuk
This rewrites the previous manual, which was a mixture of:
1. Description about the govuk-pact-broker app.
2. Guidance about actually writing Pact tests.
The rewrite moves the focus to (2), eventually renaming the 
manual from "Pact Broker" to "Pact Testing".
This wasn't the only guidance about Pact testing: Publishing 
API also has duplicate guidance[^1], so part of the change is 
to merge content from that in here so we can have a single, 
central document about how it's done across all apps.
Relates PRs:
- https://github.com/alphagov/govuk-pact-broker/pull/123
- https://github.com/alphagov/publishing-api/pull/2069
[^1]: https://github.com/alphagov/publishing-api/pull/2069
=> Rewrite guidance about pact testing

source/manual/setting-up-new-rails-app.html.md
https://trello.com/c/fRihmgQ8/266-add-top-level-guidance-about-where-we-write-tests-on-govuk
This was missed for the new Locations API app.
Note that the link won't work until [^1] is merged.
[^1]: https://github.com/alphagov/govuk-developer-docs/pull/3498
=> Add pointer to set up contract tests for new apps

source/manual/rules-for-getting-production-access.html.md
Follows on from: https://github.com/alphagov/govuk-developer-docs/pull/2969/commits/4f2ffed8d5bcf109bde3e9ef48de8a5d86cabdf3
There was a bit of confusion about the minimum level of clearance required for production access.
This page only mentioned a "minimum of BPSS" for temporary access, but did not clarify if that was true for permanent access as well.
=> Clarify the clearance needed for prod access

source/manual/incident-reports.html.md
This prompts the person clicking the link to make a copy of the incident template, which will help prevent people from writing in the template.
=> Change incident doc link to a "copy" version

source/manual/deploy-puppet.html.md, source/manual/flush-the-arp-cache.html.md, source/manual/howto-run-ssh-commands-on-many-machines.html.md
The lack of instructions here was mentioned in an incident review. It's rarely needed, but is sometimes useful.
Better ways undoubtedly exist!
=> Add how to run commands on many machines

source/manual/alerts/rebooting-machines.html.md
This class no is longer required for the synchronisation of DB
across environments since the deployment of govuk_env_sync.
Therefore it's fine to reboot those machines at any time and there
is no need for specific instructions anymore.
=> Update rebooting instructions for jumpbox machines

source/manual/alerts/rebooting-machines.html.md
I was really tempted to just reboot this machine, and needed a bit more context about the warning.
The docker_management machine runs etcd which is used to provide a lock for other machines that wish to perform an unattended reboot. For that reason, we need to be a bit careful about rebooting it.
The etcd host is specified by the [etcd_endpoints](https://github.com/alphagov/govuk-puppet/blob/2a1b4084d8692707a8af72f4ed0f59f194705c86/hieradata_aws/common.yaml#L1532) configuration.
There is further context available in:
- [puppet-unattended_reboot Github repo](https://github.com/alphagov/puppet-unattended_reboot)
- [a presentation by Matt Bostock (@mattbostock)](https://www.dotconferences.com/2015/06/matt-bostock-coordinating-unattended-reboots-using-a-distributed-mutex)
=> Expand on docker_management reboot reasons
