alphagov/govuk-developer-docs

source/manual/auto-scaling-groups.html.md

make clear what happens during austocaling scale in

update docs on aws autoscaling

---

source/manual/incident-management-guidance.html.md
source/manual/incident-reports.html.md
source/manual/incident-what-to-do.html.md
source/manual/welcome-to-2nd-line.html.md

Nila Patel is now the delivery manager for 2nd line. These changes 
reflect that.

Update 2nd line docs

---

source/manual/aws-cli-access.html.md
source/manual/errors.html.md
source/manual/get-ssh-access.html.md
source/manual/hmrc-paye-files.html.md
source/manual/howto-redirect-html-attachment-urls-from-whitehall.html.md
source/manual/manage-email-subscribers.html.md
source/manual/tools.html.md

These documents have been reviewed and no changes are required.

Update review date for documentation

---

source/manual/aws-iam-key-rotation.html.md

Document rotating AWS IAM keys
Rendered 👉  https://github.com/alphagov/govuk-developer-docs/blob/key-rotation/source/manual/aws-iam-key-rotation.html.md or https://govuk-developer-docs-f-pr-2090.herokuapp.com/manual/aws-iam-key-rotation.html

Document rotating AWS IAM Keys

---

source/manual/aws-iam-key-rotation.html.md

Developers typically won't be able to rotate keys so adding a note regarding who can do this.

Add note on permissions to key rotation doc

---

source/manual/running-rake-tasks.html.md

Change the param name from `MACHINE` to `MACHINE_CLASS`

Update linkable rake task example

---

source/manual/generate-csr.html.md
source/manual/renew-a-tls-certificate.html.md

- These went to #govuk-2ndline, but these are things that #re-govuk do
for us.

Review TLS/CSR docs and re-assign them to #re-govuk for the future

---

source/manual/connect-to-vcloud-director.html.md

I just did it and noticed some improvements could me made to the documentation.

Improve docs on connecting to vCloud director

---

source/manual/cookies-and-sessions-in-frontend-apps.html.md

Bump date on cookies and session

---

source/manual/get-ssh-access.html.md
source/manual/github-setup.html.md

- I was inspired by #2154. See commit messages for more info.

Amend guidance on pages linked from Getting Started

---

source/manual/deploying-terraform.html.md

This tweaks (actually, it's more of a rewrite) the manual around
deploying Terraform projects to be a bit more concise and clearly
highlight the steps to take, with less emphasis on explanation.
This also adds more sections to distinguish between deploing directly
from Jenkins vs. triggering a Jenkins job locally, which requires
a bit more effort to setup for small one-time changes.
👉 [Rendered version](https://github.com/alphagov/govuk-developer-docs/blob/ad27d3b862899e515ff430838c72f61f12ca5ca2/source/manual/deploying-terraform.html.md)

Tweak manual on deploying Terraform

---

source/manual/global-banner.html.md

Trello: https://trello.com/c/xEOQ6G96/317-refactor-global-banner-component

Add versioning to global banner docs

---

source/manual/alerts/postgresql-s3-backups.html.md
source/manual/postgresql-backups.html.md
source/manual/resync-postgres-standby.html.md

Add clarity on which method should be used for databases
that live in Carrenza vs AWS RDS.

Update Database Backup/Restore Documentation

---

source/manual/howto-change-a-government-following-an-election.html.md

These are two tasks that we might be called upon to do.

Add backdating governments and ending ministerial roles

---

source/manual/alerts/grafana-dashboards.html.md

https://github.com/alphagov/govuk-puppet/pull/9894

Add doc for new alert about Grafana dashboards

---

source/manual/govuk-env-sync.html.md

Minor typo correction and additional link to code added.

Review Manual Page for Datasync with govuk_env_sync

---

source/manual/upgrade-terraform.html.md

Minor edit to depersonalize one of the command line examples.
Add extra link to Terraform CHANGELOG.

Review Upgrade Terraform Documentation

---

source/manual/manage-ruby-dependencies.html.md

Previously it was hard to find out about this.

Mention auditing app for Dependabot PRs

---

source/manual/incident-what-to-do.html.md
source/manual/on-call.html.md

So that you get to the incident page quicker in the middle of the
night, and also hopefully check the on-call checklist beforehand.

Update on-call page

---

source/manual/raising-issues-with-reliability-engineering.html.md

Everything appears to be correct and up to date.

Review Raise issues with Reliability Engineering

---

source/manual/purge-cache.html.md

We've just run this and got slightly tripped up by the lack of
target application / machine class info, and lack of quotes on the
URL parameter.

Improve Fastly asset cache clear documentation

---

source/manual/aws-iam-key-rotation.html.md

After reviewing the 
> AWS IAM Key Rotation
I have found that there are steps missing so this PR will update the instructions to make it easier to do this task.
Trello: https://trello.com/c/s1yNvsyj/1624-3-find-a-key-that-is-in-use-and-update-the-docs

Update docs on how to rotate IAM keys

---

source/manual/howto-backup-and-restore-in-aws-rds.html.md

Re-tested the majority of the commands. Everything still
works as expected.

Review Backup and restore databases in AWS RDS

---

source/manual/alerts/enhanced-ecommerce.html.md
source/manual/alerts/runs-rake-task-search-api.html.md

Improve search API Icinga alert documentation

---

source/manual/rebooting-machines.html.md

- These didn't have any special instructions and, bleary-eyed yesterday
morning, I didn't remember that there was an intricate and tedious
process across all eight machines.
- So that everyone else can have this knowledge to hand, document the
process.
- Took the instructions from the "restarting router" long-running card
we had when there was the router bug.
- Platform Health has a card to make there be the standard number of
cache machines rather than the current eight, so soon we can change
the number in step 2 and the reboots become _a little_ less tedious.
https://trello.com/c/QWiMOe9Q/1686-document-how-to-safely-reboot-cache-machines-in-aws

rebooting-machines: Add instructions for rebooting AWS Cache machines

---

source/manual/frontend-architecture.html.md

Nothing major changed in the past 3 months.

Bump last_reviewed_on date

---

source/manual/data-gov-uk-operations.html.md

The docs didn't mention how to sign in if you're using SSO.

Add PaaS SSO signin to docs

---

source/manual/access-aws-console.html.md

It's not a direct mapping, so I've added some instruction for this, and also a brief
explanation about the `-l` parameter.

Document how to use the 'role' in the CLI command

---

source/manual/access-aws-console.html.md
source/manual/set-up-aws-account.html.md

- These flaws in the docs were discovered in this morning's workshop.
- See commits for more detail.

Document AWS access key generation & Yubikey MFA constraints

---

source/manual/aws-iam-key-rotation.html.md

Co-Authored-By: Alan Gabbianelli <alan.gabbianelli@digital.cabinet-office.gov.uk>
Co-Authored-By: Mahmud Hussain <mahmud.hussain@digital.cabinet-office.gov.uk>
Trello card: https://trello.com/c/cZQQM8Gu/1623-3-find-a-key-that-is-not-in-use-and-update-docs

Update docs with info for rotating IAM Access Keys

---

source/manual/alerts/ruby-version.html.md
source/manual/alerts/search-spelling-suggestions.html.md
source/manual/documents-are-published-but-links-arent-updated.html.md
source/manual/howto-replace-an-assets-file.html.md
source/manual/rebooting-machines.html.md
source/manual/review-page.html.md
source/manual/taxonomy.html.md

I reduced the review time for the asset replacement doc to 1 month as the asset manager migration will be happening soonish, and the hostname it refers to will be wrong.

Do some reviews

---

source/manual/howto-manually-remove-assets.html.md

Add instruction on how to remove assets from mirrors

Add instruction on how to remove assets from mirrors

---

source/manual/encrypted-hiera-data.html.md

I've added some more details in places and removed mentions of the VM as
this has now pretty much been retired.
All looks fine by me reading though, i've tested the basic stuff in this
doc like decrypting a file and re-encrypting etc.

Update encrypted-hiera-data doc

---

source/manual/elasticsearch-dumps.html.md
source/manual/fix-out-of-date-search-indices.html.md
source/manual/reindex-elasticsearch.html.md

I think this more generic title is more helpful, and closer to what
you'd be looking for in an incident.

Retitle out-of-date search indices page

---

source/manual/content-security-policy.html.md

Checked the docs, nothing seems to have changed on this.

Bump review date for CSP docs

---

source/manual/upload-asset-to-whitehall.html.md

No update needed - so bumping date.

Bump "Upload a large asset to Whitehall"

---

source/manual/alerts/email-alerts.html.md

Updating this section for clarity

Update instructions for troubleshooting failed email checks

---

source/manual/ab-testing.html.md

No update needed, so a date bump is all that's needed.

Bump "How A/B testing works" page

---

source/manual/alerts/vpn-down.html.md

Bump date, no other content edits needed.

Update "VPN down" page

---

source/manual/deployment-dashboards.html.md

- Update link to Whitehall dashboard. 
- Change paragraph to header to improve content structure.

Update "Monitor your app during deployment" page

---

source/manual/run-ab-test.html.md

Links checked, content makes sense - no changes needed.

Bump "Run an A/B or multivariate test" page

---

source/manual/alerts/mongodb-rollback.html.md

No changes needed, so date has been bumped.

Bump "MongoDB rollback" page

---

source/manual/world-taxonomy.html.md

Trello - https://trello.com/c/5Bv3X9zN/1328-document-the-world-taxonomy
This adds a page in that describes the world taxonomy. This will (hopefully) help people gain an understanding of how the taxonomy works, what it's used for and the concerns that exist around it.

Add page on the world taxonomy

---

source/manual/clone-mysql-slave.html.md

- Added code block hints for syntax highlighting
- Bump date

Update "Clone a MySQL instance..." page

---

source/manual/alerts/mongod-replication-lag.html.md

Content makes sense and links work.

Bump "mongod replication lag" page

---

source/manual/zendesk.html.md

- Fixed 'Create an account' link.

Update "Zendesk" page

---

source/manual/2nd-line.html.md

No changes needed - links work and content makes sense.

Bump "2nd line" page

---

source/manual/data-gov-uk-deployment.html.md

Adds the following details:
- Link to DGU staging (staging.data.gov.uk)
- What needs to be provided to create a new release

Expand DGU deployment docs

---

source/manual/howto-manually-remove-assets.html.md

Remove the Carrenza SSH command and update the Jenkins links to be the
AWS deploy Jenkins.

Update "Remove an asset" now that Asset Manager is hosted in AWS

---

source/manual/alerts/cdn-log-freshness.html.md

See alphagov/govuk-puppet#10113.

Add playbook entry for check_cdn_log_s3_freshness Icinga alert.

---

source/manual/alerts/aws-lb-healthyhosts.html.md
source/manual/kibana.html.md

Barely makes a dent in the backlog, but it's a start.

Review old docs

---

source/manual/alerts/datagovuk-publish-healthcheck-not-ok.html.md
source/manual/data-gov-uk-monitoring.html.md

Replace sidekiq console and gui with a grafana link as its more user friendly

Update datagovuk publish healthcheck docs

---

source/manual/dns.html.md

* Update dates.
* Tighten language.
* Consolidate duplicate content under a single heading.
* Add backticks for formatting.
I followed the instructions as far as I could without having an actual change to deploy and it all seemed fine.
I don't know if the rest of the content is out of date, that may require more experienced reviews.
I've also tested the docs locally and it looks fine.

Update DNS documentation

---

source/manual/upgrading-mysql.html.md

* Fix typos
* Add links to govuk repos to provide context and reference points
* Tighten language
* Bold "Note:" sections
* Amend spacing so text is on one line where possible
I've tested the branch locally and the changes appear to be OK.

Update upgrade mysql docs

---

source/manual/patching-jenkins.html.md

* No changes were required, the documentation looks clear and up to to date.
* Bumped review date to today.

Confirmed patching jenkins documentation is up to date

---

source/manual/reindex-elasticsearch.html.md

Do not merge until https://github.com/alphagov/search-api/pull/2001 has been merged in
Trello: https://trello.com/c/spNtyEbO/1403-automate-deletion-of-old-unused-indexes

Add extra documentation discussing the new automatic index cleaning task

---

source/manual/auto-scaling-groups.html.md

I needed to do this in a recent incident, and got it wrong at the
time.

Document how to remove a specific instance

---

source/manual/alerts/postgresql-replication-too-far-behind.html.md
source/manual/alerts/publishing-api-app-healthcheck-not-ok.html.md

https://trello.com/c/h2vhDRVZ/826-review-pages-that-have-been-due-for-review-for-30-days-or-more

Review a few more dev docs

---

source/manual/change-in-hours-time-period-for-dst.html.md

This fits more than "learn", as it's a thing to do.

Make the DST doc a how-to

---

source/manual/howto-find-hardcoded-markup-govspeak.html.md

The instructions are still valid, so updating the review date.

Review find hardcoded markup in Govspeak

---

source/manual/whitehall-historical-accounts.html.md

The instructions are still valid, so updating the review date.

Review adding historical accounts to whitehall

---

source/manual/alerts/fastly-error-rate.html.md
source/manual/icinga.html.md

Also increase the icinga review period, as we're unlikely to upgrade it or something in the next 6 months...

Review a couple of docs

---

source/manual/create-a-gpg-key.html.md

The instructions are still valid, so updating the review date.

Review create a gpg key

---

source/manual/sidekiq.html.md

👉 [Rendered version](https://github.com/alphagov/govuk-developer-docs/blob/a0cf82068b226a2518adad3fd92c438cd24dcb4f/source/manual/sidekiq.html.md)

Add instructions for connecting to sidekiq in AWS production

---

source/manual/bulk-email.html.md

This should mean that this is a task that 2nd line can perform in the future.
[Trello Card](https://trello.com/c/yRCyIaMN/1876-document-how-to-send-bulk-emails)

Add documentation on sending bulk emails

---

source/manual/bulk-email.html.md

Various improvements to the page about sending a bulk email, see individual commits for more details.

Improve bulk email docs

---

source/manual/provision-machines-for-data-science-research.html.md

This PR moves the review date to six months from now - the process is still described correctly in this doc.

Review provisioning machines for data science

---

source/manual/fall-back-to-aws-cloudfront.html.md
source/manual/howto-block-arbitrary-urls.html.md
source/manual/reprovision.html.md
source/manual/web_application_firewall_rules.html.md

All docs are still valid but I've reworded a few minor places.

Timed reviews

---

source/manual/alerts/rabbitmq-high-watermark.html.md

I followed the steps in the doc and they are up to date.

Review RabbitMQ high watermark has exceeded doc

---

source/manual/hmrc-paye-files.html.md

Couldn't work out how to scp with AWS machines. Docs didn't reflect our new world.

Update instructions to upload PAYE files

---

source/manual/change-in-hours-time-period-for-dst.html.md

See https://github.com/alphagov/govuk-puppet/pull/10294
I've set the review date to a few days before the change from BST back to UTC.

Review "Change in-hours time period for daylight savings"

---

source/manual/components.html.md

Nothing changed since last review.

Bump review date for components

---

source/manual/data-gov-uk-map-previews.html.md

Use square brackets instead of angle brackets as the angle brackets don't show in deployed docs.

Improved DGU map preview docs

---

source/manual/alerts/aws-lb-healthyhosts.html.md

This currently causes the link to 404.

Remove .md suffix on internal link

---

source/manual/alerts/onsite-backups.html.md

- I saw the approval, forgetting I'd not actually committed the last
suggested change that was approved.

onsite-backups: Actually commit the last suggestion from #2470

---

source/manual/encrypted-hiera-data.html.md

I had only pulled from master a couple of hours earlier but ran into this issue.
When I pulled from master fresh, there were a couple of commits, and I was
then able to make my changes without any errors.

Advise pulling master when seeing "General error"

---

source/manual/covid-19-services.html.md

See individual commits for more detail.

covid-19-services: We use GitHub Actions, and have widened the Concourse access list

---

source/manual/github-trello-poster.html.md

https://trello.com/c/ia2MkYpQ/1916-2-get-github-trello-poster-using-an-api-key-we-own

github-trello-poster: Emma has left, note the use of a `govuk-ci` token

---

source/manual/alerts/high-memory-for-application.html.md
source/manual/alerts/low-space-for-automongodbbackup.html.md
source/manual/alerts/publisher-app-healthcheck-not-ok.html.md
source/manual/rotate-offsite-backup-gpg-keys.html.md

The docs themselves all look pretty accurate. I've increased the duration of some of the pages to 12 months where they don't need reviewing so regularly.

Review some out of date 2nd line docs

---

source/manual/retiring-an-application.html.md
source/manual/setting-up-new-sidekiq-monitoring-app.html.md

See commits for more details.
https://trello.com/c/1xBp5GeI/137-delete-the-development-vm-code-in-govuk-puppet

Remove more docs about the dev VM

---

diagrams/specialist_apps.puml

- Apparently this is a thing? :shrug:
- I ran `bundle exec rake` and this appeared as changed.

diagrams/specialist_apps: Add govuk-coronavirus-find-support form

---

source/manual/renew-a-tls-certificate.html.md

Fastly has a better interface to import new certs now.

Update cert renewal procedure in Fastly

---

data/applications.yml

[Trello card](https://trello.com/c/SKT4BnIQ/1953-retire-the-calendars-app-%F0%9F%8D%90)

Mark calendars as retired

---

source/manual/move-apps-between-servers.html.md

Added a warning around the Carrenza instructions.

Review "Move apps between servers"

---

data/rendering-apps.yml
diagrams/frontend_apps.puml
source/manual/components.html.md
source/manual/govuk-in-aws.html.md

[Trello card](https://trello.com/c/SKT4BnIQ/1953-retire-the-calendars-app-%F0%9F%8D%90)

Remove some more references to calendars

---

source/manual/alerts/aws-cache-memory.html.md

All information correct and up to date

Review AWS ElastiCache Instance Memory Utilization

---

source/manual/howto-restore-an-individual-postgres-database.html.md

All information still up to date and correct.

Reviewed "Restore an Individual Postgres Production Database in AWS RDS"

---

source/manual/hmrc-paye-files.html.md

Now explicitly uses gds-cli and govuk-connect for the SSH commands,
and documents some of the quirks around permissions (i.e. you need
to upload files to a home directory rather than directly to /tmp.
This may be because we have moved away from govukcli)
It also is more resilient in terms of how to connect to specific
machines. Where there are multiple machines of the same class,
the uploaded files won't have been uploaded to all of them, so
we should only be working with one (named) machine throughout.
It also makes it clearer that production _is_ your test
environment. Partners won't be able to test on staging or
integration, and there is a defined process for prefixing
with 'test-' on production.
Finally, it links to the content item publisher pages for the
pages that need republishing …

Update documentation for uploading HMRC files

---

source/manual/purge-cache.html.md

Let's save the developer a precious few seconds.

Link to rake task for cache clearing

---

source/manual/hmrc-paye-files.html.md

See commits.
Follow-on from #2525, now that I've seen the process through to the end. Want to clarify the role of dev vs content.

Improve HMRC files docs with respect to dev/content roles

---

config/tech-docs.yml
source/manual/allowlist-site-in-transition.html.md

We are slowly transitioning from the use of "whitelist" and "blacklist"
to more inclusive terms like "allowlist" and "blocklist". These changes
reflect this transition.

Review whitelist-site-in-transition.html.md

---

source/manual/alerts/high-priority-tests.html.md

I considered putting this in its own alert document, but the
troubleshoot and remedy steps are almost identical to the
'Run high priority tests' alert - and I also struggled to
articulate the difference between the two errors - so have
kept them in the same document for now.
Hopefully someone else will come along and split them out
in the future if that would make the instructions easier
to follow.

Add troubleshooting tips for 'Smokey failed' alert

---

.github/workflows/ci.yml
Rakefile
data/dashboard.yml

I went in to remove some archived repos, and got distracted by CI improvements!

Remove archived repos from dashboard & improve CI

---

source/manual/alerts/recreate-a-mongo-instance-in-aws.html.md

Information is correct and up to date.

Review "Re-create an AWS mongo instance"

---

source/manual/alerts/aws-cache-cpu.html.md

redis cpu alert doc update

---

source/manual/alerts/duplicate-ssh-host-keys.html.md

update doc of duplicate ssh keys

---

source/manual/remove-machines.html.md

Add extra paragraph on "Scale in protection" .

Review Remove Machines Docs

---

source/manual/alerts/aws-rds-cpu.html.md

Add extra information for looking at statistics in AWS Console.

Review AWS RDS Instance CPU Utilisation Doc

---

source/manual/publishing-a-ruby-gem.html.md

rubocop-govuk doesn't Jenkins anymore

---

source/manual/add-authentication-to-an-application.html.md
source/manual/add-deployment-dashboard.html.md
source/manual/deploy-fixes-for-a-security-vulnerability.html.md
source/manual/docs-style-guide.html.md
source/manual/editing-an-existing-route.html.md
source/manual/environments.html.md
source/manual/errors.html.md
source/manual/github-unavailable.html.md
source/manual/help-with-publishing-content.html.md
source/manual/heroku.html.md
source/manual/learn-govuk.html.md.erb
source/manual/manage-ruby-dependencies.html.md
source/manual/metrics.html.md
source/manual/monitor-docs-traffic.html.md
source/manual/pact-broker.html.md
source/manual/publishing-e2e-tests.html.md
source/manual/setting-up-request-tracing.html.md
source/manual/tools.html.md
source/manual/uptime-metrics.html.md
source/manual/where-to-find-what.html.md

- Here we go. Appease the RoboDog (the bot that posts in #govuk-developers every day that we haven't reviewed our docs).
- Some of these aren't even date bumps as I wanted to add more but didn't have enough 🧠. I've left those for another willing person. But I did do some rewording.
- The commits to review are the ones I've actually edited, so the ones that have more than a single line description.
----
- I hope you lot appreciate my dedication to commit messages. I realised half way through (when I got to `errors`) that I got the date wrong - I'd been thinking it was 17th not 18th - so I went back and rebase-edited all my commits before then to change each date. 😩
- I've also not done *all* the ones that RoboDog moaned about - but there are only eight left for YOU! 💪

Review docs to appease RoboDog

---

source/manual/incorrect-content-in-search-or-navigation.html.md

Clarify that not only unpublished content may be removed from search-admin

Update removing content from search text

---

source/manual/generate-csr.html.md

This has been tried in incident on 28 May 2020 and working

bump date of generate csr doc

---

source/manual/alerts/email-alert-api-unprocessed-content-changes.html.md
source/manual/alerts/email-alert-api-unprocessed-subscription-contents.html.md

This updates:
- source/manual/alerts/email-alert-api-unprocessed-content-changes.html.md
- source/manual/alerts/email-alert-api-unprocessed-subscription-contents.html.md

Review 2 email-alert-api doc pages

---

source/manual/connect-to-vcloud-director.html.md

I ran it locally and it renders well.

fix some rendering out the vpn carrenza vcloud page

---

source/manual/set-up-gcp-account.html.md

Remove pointless numbering in header

---

source/manual/govuk-in-aws.html.md

Review "Migration to AWS" Page

---

source/manual/resync-postgres-standby.html.md

Review "Resync a PostgreSQL Standby in Carrenza/6DG" Page

---

source/manual/alerts/check-process-running.html.md
source/manual/alerts/rebooting-machines.html.md

Based on experience on 2nd line this morning.

Document restarting services/processes and rebooting machines

---

source/manual/alerts/high-priority-tests.html.md
source/manual/alerts/rebooting-machines.html.md
source/manual/alerts/renew-tls-certificate.html.md
source/manual/architecture-deep-dive.html.md
source/manual/data-gov-uk-2nd-line.html.md
source/manual/deploy-static.html.md
source/manual/global-banner.html.md
source/manual/stop-all-email-subscription-sending.html.md

Review of docs

---

source/manual/howto-modify-change-note.html.md

I had to figure this out from looking at old Zendesk tickets.
The process is straightforward enough, but should be documented.

Document how to modify a change note

---

source/manual/updating-brexit-transition-checker.html.md.erb

Trello: https://trello.com/c/WeLDjC2R/342-hand-over-updating-of-transition-checker-to-2ndline
Add transition checker docs to dev docs to increase findability for people who are on 2ndline.

Fetch transition checker docs from finder-frontend

---

source/apis.html.md.erb
spec/app/github_repo_fetcher_spec.rb

Addresses a couple of code review comments from #2595.
https://trello.com/c/z3wOzJZS/165-create-one-way-to-import-api-docs

Code review tweaks

---

source/manual/alerts/free-memory-warning-on-backend.html.md
source/manual/alerts/signon-app-healthcheck-not-ok.html.md

Both are still ok so bump the date

Review free-memory-warning-on-backend and signon-app-healthcheck-not-ok

---

.rubocop.yml
app/app_docs.rb
app/dashboard.rb
app/document_types.rb
app/github_repo_fetcher.rb
app/proxy_pages.rb
source/layouts/api_layout.html.erb
spec/app/github_repo_fetcher_spec.rb
spec/app/proxy_pages_spec.rb

https://github.com/alphagov/rubocop-govuk/issues/73

Remove redundant RuboCop config

---

source/manual/govuk-notify.html.md

Trello:
https://trello.com/c/Hb7kL8pX/354-document-govuk-rate-limiting

Add some rate limiting information for GOV.UK Notify

---

source/manual/cookies-and-sessions-in-frontend-apps.html.md

Nothing changed in the past 6 months, as far as I'm aware.

Bump cookies-and-sessions-in-frontend-apps

---

source/manual/upgrade-terraform.html.md

All information still accurate.

Review Upgrade Terraform Docs

---

source/manual/fall-back-to-aws-cloudfront.html.md
source/manual/web_application_firewall_rules.html.md

Review Fall back to AWS CloudFront

---

source/manual/deploy-puppet.html.md

Correct the carrenza integration puppet deploy link

---

source/manual/alerts/publisher-unprocessed-fact-check-emails.html.md

Related PRs:
- https://github.com/alphagov/publisher/pull/1301
- https://github.com/alphagov/govuk-puppet/pull/10481
Trello card: https://trello.com/c/NbgFTMR4/2022-5-alert-on-fact-check-replies-that-werent-parsed

Add docs for unprocessed fact-check emails alert

---

source/manual/alerts/app-healthcheck-failed.html.md
source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md
source/manual/alerts/email-alert-api-delivery-attempt-status.html.md
source/manual/alerts/email-alert-api-delivery-attempts-status-updates.html.md
source/manual/alerts/email-alert-api-incomplete-digest-runs.html.md
source/manual/alerts/email-alerts-travel-medical.html.md
source/manual/alerts/puppet-last-run-errors.html.md
source/manual/howto-replace-an-assets-file.html.md
source/manual/howto-upload-an-asset-to-asset-manager.html.md
source/manual/removing-a-user-from-puppet.html.md
source/manual/restart-application.html.md

I've tweaked the review periods for a couple of them.

Review a bunch of 2ndline docs

---

source/manual/alerts/clamav-definitions-out-of-date.html.md

Removing the reference to fabric as it's far easier to do so with ssh

Update clamav documentation

---

config/tech-docs.yml
source/manual/alerts/process-file-handle-count-exceeds.html.md

Still valid, but title/filename mispelled

Update and correct process file handle count docs

---

source/manual/email-alert-api-callback-from-notify-fails.html.md
source/manual/pagerduty.html.md
source/manual/update-promo-boxes.html.md

Bumping review dates for documents which don't need updating

Review some documentation

---

source/manual/government-changes.html.md.erb

To match up with the code in Whitehall.

Fix column name on the support government changes page

---

source/manual/howto-manually-remove-assets.html.md

https://trello.com/c/HfMApI04/947-make-it-easier-to-cleanup-stray-whitehall-assets

Review and simplify asset removal manual

---

source/manual/architecture-deep-dive.html.md

Temporary fix until we improve our markdown parser.

Fix Capistrano link

---

.github/dependabot.yml
Gemfile
Gemfile.lock

Fix OSX build and add Dependabot config

---

source/manual/alerts/high-memory-for-application.html.md

This updates the high memory doc to include what happens when an app
hits it's memory threshold. Also removed a broken link.
Trello:
https://trello.com/c/vlSTvEQt/439-update-high-memory-for-application-docs

Update high memory doc with restarting behaviour

---

source/manual/elasticsearch-dumps.html.md
source/manual/incorrect-content-in-search-or-navigation.html.md
source/manual/reindex-elasticsearch.html.md

Review search docs

---

source/manual/alerts/publisher-unprocessed-fact-check-emails.html.md

This includes some more explicit steps on what 2nd line can do when they see this alert so hopefully it will be easier for them to handle. We're doing this as an experiment as we don't believe the alert will fire enough for us to need to put in place some automated systems, but if it does end up being a problem we will revisit this decision.
[Trello Card](https://trello.com/c/ti6D5GBW/2076-5-manage-unprocessed-fact-check-emails-for-publisher)

Improve documentation on fact check alert

---

source/manual/govuk-notify.html.md

https://trello.com/c/0VS0L95O/2077-3-investigate-unnecessary-emails-not-being-sent-in-integration-staging

Update Notify docs to reflect recent Signon change

---

source/manual/non-ha-node-classes.html.md

Review Node Classes Without Redundancy Docs

---

source/manual/howto-restore-an-individual-postgres-database.html.md

Review Restore Postgres Database Docs

---

source/manual/govuk-app-domain-handling-during-migration.html.md

Review app_domain handling in GOV.UK

---

source/manual/raising-issues-with-reliability-engineering.html.md

Review Raise issues with RE

---

source/manual/alerts/content-publisher-app-healthcheck-not-ok.html.md

Review content-publisher app healthcheck not ok

---

source/manual/alerts/publisher-unprocessed-fact-check-emails.html.md

https://trello.com/c/2ZckRO3G/2079-5-switch-fact-check-address-away-from-alphagovcouk

The email address for fact check emails has changed

---

source/manual/government-changes.html.md.erb

From the changes in https://github.com/alphagov/whitehall/pull/5782

Add Document type column to bulk retagging docs

---

source/manual/alerts/rabbitmq-no-consumers-listening.html.md

Updates the doc to be more actionable and useful.
The original discussion around the decisions made in this doc can be
found [here][original_pr].
Trello:
https://trello.com/c/0OHZT3cq/458-investigate-rabbitmq-and-improve-the-documentation
[original_pr]: https://github.com/alphagov/govuk-developer-docs/pull/2733

Updates rabbitmq-no-consumers-listening doc

---

config/tech-docs.yml
source/accessibility.html.md

This was written for us by the technical writers team ahead of the 23rd September deadline.
There are numerous accessibility issues with the developer docs and we plan to fix those before September next year.

Add accessibility statement

---

source/manual/publish-to-puppet-forge.html.md

All information up to date. Also checked credentials in secrets are correct.

Review Publish to Puppet Forge

---

source/manual/govuk-env-sync.html.md

All information up to date and correct.

Review Datasync with govuk_env_sync

---

source/manual/debian-packaging.html.md

All information up to date and correct.

Review Manage Debian packages

---

source/manual/patching-jenkins.html.md

All information up to date and correct.

Review Patching Jenkins

---

source/manual/2nd-line.html.md
source/manual/auto-scaling-groups.html.md
source/manual/kibana.html.md
source/manual/nagios-nrpe-connection-failures.html.md
source/manual/post-a-statuspage-message.html.md
source/manual/republishing-content.html.md
source/manual/restrict-paas-applications-to-gds-office-ips.html.md
source/manual/upload-asset-to-whitehall.html.md

Checked and verified as correct as of 2020/09/17

Manual review

---

source/manual/alerts/gor.html.md
source/manual/alerts/mysql-replication-lag.html.md
source/manual/alerts/mysql-replication-running.html.md
source/manual/alerts/pingdom-homepage-check.html.md
source/manual/alerts/redis.html.md
source/manual/fall-back-to-mirror.html.md
source/manual/nagios-nrpe-connection-failures.html.md
source/manual/on-call.html.md
source/manual/pingdom-bouncer-canary-check.html.md

Some of these were reviewed and delivered in pull request #2777 however
I had inadvertently set their date to 2019 rather than 2020!
Others reviewed today. A further PR will come to stagger the dates of
all the documents reviewed today (over fifty!) such that they don't
make people panic in six months.

Reviewed documents

---

source/manual/load-testing.html.md.erb

This page simply points to other documentation, and is accurate. So I've decreased the checking frequency.

Update load-testing docs

---

source/manual/alerts/check-process-running.html.md
source/manual/alerts/process-file-handle-count-exceeds.html.md

Added a suggestion to the troubleshooting section and reviewed
the rest of the doc at the same time.

Update process running docs

---

source/manual/alerts/mirror-sync.html.md

https://trello.com/c/sVicSDL5/997-mirror-sync-failing-in-staging

Add new alert doc for Mirror sync failing

---

source/manual/rename-a-country.html.md

https://trello.com/c/J6DOuBBp/990-country-updates
We've been prompted to add these after it turned out this app got
missed as part of a previous rename of "Macedonia".

Add rename country steps for Specialist Publisher

---

source/manual/howto-find-hardcoded-markup-govspeak.html.md

I used this guidance a couple of weeks ago and it worked - no content update needed.

Bumped finding hardcoded markup in Govspeak

---

source/manual/query-cdn-logs.html.md

I didn't change the `last_reviewed_on` date as I only fixed this broken link and not actually reviewed the whole doc.

Fix broken link

---

data/applications.yml

We're consolidating our dev slack channel into our main one.
Trello:
https://trello.com/c/LhLRsiEl/533-merge-team-slack-channels

Updates notifications team app slack channels

---

source/manual/browser-support.html.md

Nothing changed; content is still accurate.

Bump review date on browser support

---

source/manual/browser-support.html.md

The heading in the README for GOV.UK Frontend has changed.

Update broken anchor

---

source/manual/fall-back-to-aws-cloudfront.html.md
source/manual/howto-backup-and-restore-in-aws-rds.html.md
source/manual/web_application_firewall_rules.html.md

Bump next review date

---

source/manual/howto-block-arbitrary-urls.html.md

Update developer docs for Block access to arbitrary URLs

Update developer docs for Block access to arbitrary URLs

---

source/manual/govuk-in-aws.html.md

Update developer docs for Migration to AWS

Update developer docs for Migration to AWS

---

source/manual/postgresql-backups.html.md

Update developer docs for PostgreSQL backups

Update developer docs for PostgreSQL backups

---

source/manual/reprovision.html.md

Update developer docs for Reprovision a machine

Update developer docs for Reprovision a machine

---

source/manual/mongodb.html.md

Update developer docs for mongoDB backups

Update developer docs for mongoDB backups

---

source/manual/cookie-consent-on-govuk.html.md

- No change to content as it's still all relevant and useful
- Change inline code snippets to code blocks, as then we can add the language for syntax highlighting

Bump cookie consent on GOV.UK

---

source/manual/alerts/rabbitmq-dead-nodes.html.md

https://trello.com/c/Di1wXCVM/1025-fix-not-being-able-to-reboot-rabbitmq-machines
Related to: https://github.com/alphagov/govuk-puppet/pull/10806

Add new alert manual for dead RabbitMQ nodes

---

source/manual/subject-access-requests.html.md

https://trello.com/c/GZqSmo0H/1030-update-sar-requests-manual
Previously this was quite open-ended.

Update SAR manual with specific steps to follow

---

source/manual/subject-access-requests.html.md

https://trello.com/c/GZqSmo0H/1030-update-sar-requests-manual

Add licensing steps for doing a SAR request

---

source/manual/mapit-database-not-available.html.md

The automatic process is currently not working and when we recently scaled up these machines we had to do this manual process instead.

Add documentation on how to import Mapit data

---

source/manual/subject-access-requests.html.md

https://trello.com/c/GZqSmo0H/1030-update-sar-requests-manual

Clarify overall process for SAR tickets

---

source/manual/covid-19-services.html.md

Update covid-19-services documentation to reflect the changes made during the migration process of the find support service to smart answers.
[Trello](https://trello.com/c/7yaKhyf0/544-update-the-developer-docs)

Covid-19 services post migration update

---

source/manual/alerts/low-available-disk-space.html.md

This details the manual fix for low disk space alerts on
/mnt/crawler_worker

Add low disk space on crawler

---

source/manual/govuk-env-sync.html.md

Summary of changes:
- Moved link to govuk_env_sync to top of document. Previously the
first link was to env-sync-and-backup, so scanning the page and
clicking the first env-related link brought you to outdated code.
- Summarise what it does first, followed by how that works under
the hood.
- Moved 'data sanitisation' to its own subsection, as it's an
interesting and unexpected feature to an outsider.
- Link to the relevant bits in govuk-puppet under the 'How it
works' section, as otherwise it's all a bit theoretical.
- Moved Gor section up to the data sync times section, as they're
closely connected. Also updated it to 'GoReplay' as per the
document it references.
I resisted the temptation to remove the example configuration
and/or the 'meanings of parameters', as someone presumably sees …

Improve 'Environment data sync' documentation

---

source/manual/sidekiq.html.md

- Made clearer the distinction between Sidekiq and govuk_sidekiq
- Describe how there is one shared Redis instance between machines
- Clarify Sidekiq Web port instructions
- Add an example Sidekiq console command for finding named workers

Various improvements to Sidekiq documentation

---

source/manual/give-a-content-designer-access-to-github.html.md

We recently created a new group to handle these request.
Correct the outdated email address and turn it into a mailto link.

Correct email for removing content people

---

source/manual/manage-assets.html.md.erb

Small improvements to asset docs

---

source/manual/alerts/email-alerts-travel-medical.html.md

https://trello.com/c/q3rh4ngJ/543-document-surprise-all-behaviour-for-finder-email-signups
While we are pursuing a fix for the underlying issue as tech debt,
this ensures we're aware of it in case it happens again.

Reference potential cause for medical safety alert

---

source/manual/dns.html.md

The Zendesk queue has been renamed. Also fixed the heading to be more helpful.

Fix docs on domain name requests

---

source/manual/email-notifications-how-they-work.html.md

https://trello.com/c/rhdwVhfw/637-write-a-document-to-share-with-the-future-notifications-team
This fixes various inaccuracies that have crept in since the manual
was last written and also tries to make it more concise.
We're updating this manual since the Notifications team is being
paused. This manual will serve as a starting point for futrue devs.

Rewrite overview of the email system

---

source/manual/manage-sign-on-accounts.html.md

Follow up to https://govuk.zendesk.com/agent/tickets/4344423 and https://trello.com/c/7koTf4OD

Add notes to address APHA parent bug

---

source/manual/alerts/rebooting-machines.html.md

These docs now reflect the new process for rebooting cache machines manually.

Update docs for rebooting cache machines

---

source/manual/add-translation-whitehall.html.md

- Make commands more readable by splitting them in multiple lines
- Fix key name (`language_name:` -> `language_names:`)
- Add whitespace to render block correctly under the lists

Update doc page on how to add a new locale

---

source/manual/alerts/email-alerts-travel-medical.html.md
source/manual/email-notifications-how-they-work.html.md

https://trello.com/c/pZqhXafv/671-update-template-for-individual-type-emails-inc-one-click-unsubscribe

Clarify how email courtesy copies now work

---

source/accessibility.html.md

Update last reviewed date to December 2020.

Update last reviewed date

---

source/manual/2nd-line.html.md

Displays better on smaller screens. See
https://github.com/alphagov/frame-splits/pull/3
Also adds title to the web page.

Switch to responsive 2nd line dashboard

---

source/manual/data-gov-uk-contracts-archive.html.md

This change:
- explains the process for authorising a request
- documents how to change the text content inside a contract
- adds useful headings to structure the page

Update contracts archive guidance

---

source/manual/manage-sign-on-accounts.html.md

This should help whoever next has to deal with a similar ticket understand exactly what to do.
[Trello Card](https://trello.com/c/7koTf4OD/2293-investigate-prevent-parent-organisation-being-swapped-for-another-in-signon-timebox-2-days)

Improve documentation about signon multiple parents

---

source/manual/alerts/low-available-disk-space.html.md

Update and add new actions relevant to the new AWS context

Update documentation for the low available disk alert

---

config/tech-docs.yml
source/manual/grafana.html.md
source/manual/sentry.html.md

Trello: https://trello.com/c/0CsM2Z4l/2202-document-sentry-in-more-detail

Document Sentry in detail

---

source/manual/development-pipeline.html.md

Rewording a title broke the internal link, updating link path to fix.

Fix broken internal link

---

source/manual/jenkins-ci.html.md

The command did not work, so fixing it.
Trello card: https://trello.com/c/hirdtB41

Update SSH command for ci-agent

---

source/manual/common-aws-tasks-for-2nd-line-support.html.md

This is a followup to https://github.com/alphagov/govuk-developer-docs/pull/2946
with changes following Frederic's review.

Clarify common AWS tasks docs

---

source/manual/smart-survey-scheduled-maintenance.html.md
source/manual/zendesk.html.md

These are in Google docs as they contain sensitive information and
email addresses.
Trello cards:
https://trello.com/c/tFwEGrgy/1077-document-steps-if-smartsurvey-is-down-scheduled-maintenance
https://trello.com/c/Vzg3Fze8/1035-subject-access-requests

Link to docs on SmartSurvey and Subject Access Requests

---

data/applications.yml

Mark Smart Answers as continuously deployed

---

source/manual/raising-issues-with-reliability-engineering.html.md

As OOH rota no longer exists, this change has meant that the doc needs updating.

Change in out of hours

---

source/manual/sentry.html.md

We ought to document how to merge, resolve and ignore issues, and when it is appropriate to do so.

Document Sentry issue actions

---

source/manual/scale-mapit.html.md

Add missing step for re-installing the virtualenv needed by Mapit.

Update docs for scaling Mapit

---

source/manual/query-cdn-logs.html.md

Replace instances of `SUM(CASE WHEN ...)` with `COUNT_IF()` after @kevindew's [excellent suggestion][comment].
[comment]: https://github.com/alphagov/govuk-developer-docs/pull/2977#discussion_r581070710

Replace instances of SUM(CASE WHEN ...) with COUNT_IF()

---

source/manual/fall-back-to-aws-cloudfront.html.md

Improve backup CDN instructions.

Improve backup CDN instructions.

---

source/manual/pact-broker.html.md

Trello: https://trello.com/c/Pvoq4sQY/2370-5-enable-continuous-deployment-for-frontend

Document how to introduce Pact tests to existing applications

---

data/applications.yml

Trello: https://trello.com/c/Pvoq4sQY/2370-5-enable-continuous-deployment-for-frontend

Mark Frontend as Continuously Deployed

---

data/applications.yml

Collections is now continuously deployed.
https://trello.com/c/7IDYweEc/2399-enable-continuous-deployment-for-collections

Update collections documentation

---

source/manual/alerts/low-available-disk-inodes.html.md

- Prevents 'permission denied' error.

Add sudo to cmd to clear out old workspaces

---

source/manual/deploy-puppet.html.md

- Remove mention to Carrenza (it's no more)
- Add useful links
- Reword and reorder instructions

Clarify how to deploy a govuk-puppet release

---

source/manual/alerts/rebooting-machines.html.md

Trello card: https://trello.com/c/17S7EQMg/1090-reboot-machines-due-to-apt-updates-in-staging

Update docs on rebooting machines

---

source/manual/unable-to-ssh-into-machine.html.md

We have docs describing HOW to reprovision an instance
(https://docs.publishing.service.gov.uk/manual/reprovision.html),
but no documenation as to WHEN you might do so.
Hopefully this signpost documentation should match developers'
search terms and make it clear what actions they need to take in
the case of an unhealthy instance.

Document when to reprovision an instance

---

data/applications.yml

https://trello.com/c/YPh5Epuc/2433-5-enable-continuous-deployment-for-support-app

Mark Support as continuously deployed

---

source/manual/restart-application.html.md

[Trello card](https://trello.com/c/hS29f6xB/1118-document-restarting-an-app-on-one-machine)

Document restarting an app

---

data/applications.yml

collections-publisher now has CD enabled

Mark collections-publisher as continuously deployed

---

data/applications.yml

Depends on https://github.com/alphagov/govuk-puppet/pull/11024

Mark maslow as continuously deployed

---

source/manual/sentry.html.md

These are both useful things to have documented.

Document bot accounts and cross-GDS usage

---

source/manual/setting-up-new-rails-app.html.md

This makes the doc consistent with RFC 141.
---

Update the example healthcheck routes in the new app docs

---

source/manual/get-started.html.md

Fixed broken link to lists of aws groups 
and clarified the process to get added to them.

Fix broken link and clarify process

---

source/manual/cdn.html.md

URL retrieved from original commit https://github.com/alphagov/govuk-developer-docs/commit/4af734096f5dd89e56d11d617655c5f64cf7fa24

Add missing URL

---

data/applications.yml

Trello: https://trello.com/c/29b0FSiU/2496-3-enable-continuous-deployment-for-cache-clearing-service

Mark cache-clearing-service as continuously deployed

---

source/manual/change-base-path-in-specialist-publisher.html.md

Updates specialist-publisher "change base path" task to include locale parameter,  and updates links to Jenkins.

Update change specialist publisher base path 

---

source/manual/get-started.html.md

This PR updates and corrects the get started information in the developer docs.

Update get started developer docs

---

Rakefile
app/app.rb
app/applications.rb
spec/app/app_spec.rb
spec/app/applications_spec.rb

We no longer have any apps hosted in these environments, nor plans to add new ones, thus the code for them can be removed.

Remove Carrenza and UK Cloud as hosting providers

---

source/manual/purge-cache.html.md
source/manual/request-fastly-tls-certificate.html.md

We won't have a shared 2nd Line account soon, so removing mention of it

Change instructions for logging into Fastly

---

source/manual/kibana.html.md

This took a lot of trial and error on my part this morning, which would have been helped immeasurably by a solid example in the Dev Docs!

Document Elasticsearch JSON example

---

source/accessibility.html.md

This updates the Accessibility Statement to reference issues with the Technical Documentation template. 
I also fixed some style things, to fit with the styleguide https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style
[Trello](https://trello.com/c/3R8fpiGF)

Update Accessibility Statement

---

source/manual/patching-jenkins.html.md

Update Patching Jenkins docs

---

source/manual/how-to-rotate-fastly-api-keys-for-notify-emergency-alerts.html.md

The shared 2nd line superuser account has been deleted.

Update to point to new Notify Emergency Alerts account

---

source/manual/setting-up-new-rails-app.html.md

https://trello.com/c/Psf7EzPB/204-move-away-from-startupsh
This follows on from the work we've done to revise READMEs for most
GOV.UK repos. Please see the commits for more details.

Rewrite template for Rails app READMEs

---

source/manual/zendesk.html.md

Steps to apply a macro to transfer tickets. 
https://trello.com/c/pS6KSylm/1085-how-to-pass-tickets-to-departments

Add some docs on how to transfer a zendesk ticket to another gov dept

---

source/manual/alerts/expiring-api-tokens-in-signon.html.md

https://trello.com/c/XVkX6cvU/1122-trade-tariff-admin-is-run-by-engine-and-uses-signon

Add docs on Trade Tariff Admin tokens

---

source/manual/alerts/check-status-gcp-mirror-sync-job.html.md

This PR adds a doc describing the GCP mirror sync alert and what action to take should it be seen.

Add doc for GCP mirror sync alert

---

data/applications.yml

Trello: https://trello.com/c/LCR0Am73/2541-5-enable-continuous-deployment-for-whitehall

Flag Whitehall as continuously deployed

---

source/manual/howto-ssh-to-machines.html.md

This is quite a scary warning message to see in the console, so
could do with some documentation explaining the cause and the steps
to take.

Document what to do when a jumpbox machine is reprovisioned

---

source/manual/incorrect-postcode-data.html.md
source/manual/logit.html.md
source/manual/sentry.html.md
source/manual/smart-survey-scheduled-maintenance.html.md
source/manual/subject-access-requests.html.md
source/manual/zendesk.html.md

https://trello.com/c/kZj6C6Pa/41-set-up-wiki-page-for-internal-dev-docs
https://trello.com/c/2Kzg5T40/1036-incorrect-postcode-data-responding-to-zendesk-tickets
https://trello.com/c/JTFHqUKA/1172-add-to-docs-log-retention-period-for-sentry-and-kibana

Update various docs for 2nd line

---

source/manual/alerts/low-available-disk-space.html.md

- Link to inode alert as it may be similar/related
- Remove comment about log retention which appears to be untrue/contradictory

Improvements to disk space alert documentation

---

data/applications.yml

https://trello.com/c/WglS9ZVW/2522-3-enable-continuous-deployment-for-imminence

Set Imminence CD to true

---

source/manual/data-gov-uk-supporting-ckan.html.md

Update the CKAN support docs after post CKAN upgrade tidy up.
https://trello.com/c/7HPu6jyN/2647-deployment-of-ckan-29-steps

Update ckan support docs to simplify commands

---

source/manual/alerts/jenkins-agent-not-connected-to-master.html.md

ci-agent-2 got recreated recently, and I had to do this to reconnect
it to the master.

Add note about CI agent SSH host key changes

---

source/manual/alerts/unicorn-herder.html.md

This needs to be run as sudo as the process is owned by the deploy user.

Add sudo to kill command

---

source/manual/data-gov-uk-2nd-line.html.md

Some users have invalid usernames and cannot change them
We can't do it through the interface so this is the easiest way

Add instructions to change a CKAN username

---

source/manual/get-started.html.md

The comment is needed, without it the PR will fail the linter.  Also,
it's the SSH username (which is the FIRSTNAMELASTNAME), not the GitHub
username.

Add needed comment to user class & change "GITHUB USERNAME"

---

source/manual/zendesk.html.md

Added some Zendesk groups as this comes up frequently as a question
on 2nd line.
Trello card: https://trello.com/c/2jlhEtDa/1196-update-zendesk-documentation-to-include-procedure-for-licensing-tickets

Update the Zendesk doc

---

source/manual/update-promo-boxes.html.md

This gives a more recent example PR for changing the homepage promo boxes

Update example PR for homepage promo change

---

source/manual/how-to-remove-jquery-from-javascript.html.md

- provides guidance for removing jQuery from our JavaScript, which is an ongoing task on GOV.UK
Trello card: https://trello.com/c/2T8YA7dv/529-write-down-some-javascript-stuff-make-it-generic

Add jQuery removal doc

---

source/manual/make-github-repo-private.html.md

I went through this process today and found a couple of gaps.

Minor update to private repo doc

---

data/applications.yml

https://trello.com/c/AGNZWDFJ/2693-enable-continuous-deployment-for-email-alert-service-3

Email alert service is continuously deployed

---

data/applications.yml

This shifts some ownership to the new Publishing team, and adds some ownership where it wasn't stated before. 
[Trello](https://trello.com/c/a5blU1nw/2763-change-ownership-of-publishing-apps)

Changes ownership of some applications to new Publishing team

---

source/manual/fall-back-to-aws-cloudfront.html.md

Update link to draft PR for failover

---

data/dashboard.yml

So we can keep these links together in one place.

Add section on dev community stuff

---

source/manual/tech-lead-responsibilities.html.md

This adds a section about attending relevant Incident Reviews

Update Tech Lead responsibilities

---

source/manual/fix-out-of-date-search-indices.html.md

Fix rake task links

---

source/manual/get-started.html.md

This line repeats information which is explained more clearly in the step below it.

Remove duplicated line

---

source/manual/how-to-test-with-assitive-technology.html.html.md

Add some information about [AssitivLabs](https://assistivlabs.com/)
- what it is, what it does
- how to request access
- highlight that it can be used locally
- For reference & future developers.
- Highlight the use of AssitivTunnel for local testing.
[GDS Way](https://gds-way.cloudapps.digital/manuals/accessibility.html#testing-with-assistive-technologies) has also been referenced and linked.
```
govuk-docker-up env GITHUB_TOKEN=$(cat ~/github_token.txt)
GITHUB_TOKEN=$(cat ~/github_token.txt) ./startup.sh
```

Add Assitiv Labs documentation

---

source/manual/create-a-gpg-key.html.md

People having trouble getting GPG working for access to `govuk-secrets` seems to be a recurring issue, so I'm trying to fill in some of the gaps in the documentation.
https://trello.com/c/VZyB4RIu/1242-gpg-secrets-documentation-out-of-date

Update gnupg setup docs

---

source/manual/get-started.html.md

We'll have a bunch of contractor devs joining us for a little while so they'll be needing to join the VPN with their own devices.

Add instructions for BYOD and VPN

---

source/manual/data-gov-uk-supporting-ckan.html.md

Minor update to ckan docs
https://trello.com/c/XriMyZkM/1198-update-ckan-docs-on-how-to-run-ckan-commands-on-the-machines

Add a bit more info to the ckan docs

---

app/github_repo_fetcher.rb

This value is only used locally, and often local development
takes longer than an hour, meaning every page needs to be
re-fetched from GitHub when previewing locally. Better to
increase the cache time to avoid that happening; we can
always clear the cache manually if we need the very latest
data.
I've added a TODO for a startup.sh CLI option that clears
the cache automatically, which would be useful, but out of
scope for this work.

Set local GitHub page cache time to 1 week

---

data/applications.yml

Remove account manager & attribute service prototypes

---

source/manual/test-and-build-a-project-on-jenkins-ci.html.md

This fixes a broken link and updates the main branchname

Couple of minor fixes on Jenkins documentation

---

data/applications.yml

Changes some app ownership to the newly-formed Find and View team
[Trello](https://trello.com/c/wzF7urH5/)

Changed ownership of some apps to Find and View team

---

source/manual/alerts/ask-export.html.md

The job itself is pretty straightforward and there aren't many reasons why it should fail. As such these are pretty minimal!

Add docs for the Ask Export job

---

data/applications.yml

Changes ownership of a couple of apps, to relevant teams.

Change ownership of some apps

---

source/manual/raising-issues-with-reliability-engineering.html.md

The process has changed slightly since this doc was last updated.
https://trello.com/c/FZIixlvA/1261-review-doc-on-raising-issues-with-re

Update docs on raising issues with RE

---

source/manual/data-gov-uk-supporting-ckan.html.md

Update guidance on accessing the database to make it easier.

Update DGU database access to connect to new RDS

---

data/repos.yml

Small change to update the Find and View repo details and direct slack integrations appropriately.

Update name and channel for Find and View owned repos

---

source/manual/alerts/mirror-sync.html.md

https://trello.com/c/SMuSi4bX/2841-add-documentation-about-new-alert

Add page about new alert

---

source/manual/ruby.html.md

Taking inspiration from https://reinteractive.com/posts/499-no-app-left-behind-upgrade-your-application-to-ruby-3-0-and-stay-on-the-upgrade-path
Trello: https://trello.com/c/ZMrLumn8/2837-upgrade-ruby-for-our-apps-5

Outline further ruby testing steps

---

source/manual/fall-back-to-mirror.html.md

Review documentation of the processes to update the CDN mirror, and improve them if applicable
First step is to collate/compare the current docs - then check for accuracy/completeness with help from developers. 
Each time they're looked at, there are questions. We need this documentation to be clear so it can be understood, especially in an urgent situation
Relevant docs at:
https://docs.publishing.service.gov.uk/manual/fall-back-to-mirror.html#updates-to-the-mirror
https://docs.publishing.service.gov.uk/manual/alerts/mirror-sync.html
https://docs.publishing.service.gov.uk/manual/architecture-deep-dive.html#failover
Plus the first part of [Chris's comment here](https://trello.com/c/RmUQlkKO/2798-fix-incorrect-mime-type-for-govuk-homepage-being-served-from-static-mirror-5#comment-61b7031224 …

Update CDN mirror docs

---

data/dashboard.yml

These sections are _not_ generated, they are curated automatically.

Remove misleading comment

---

data/repos.yml

This adds repos to the list, and marks some as "Gems"
[Trello](https://trello.com/c/baN54ay1/)

Add some repos and new type "Gems"

---

source/manual/cdn.html.md

We've recently reduced the TTL.

Reduce documented TTL to 300

---

source/manual/zendesk.html.md

1st line now pass leaver tickets to our 2nd line Zendesk queue.
https://trello.com/c/N2w2qC2V/65-update-docs-on-zendesk-leaver-tickets

Add docs on Zendesk leaver tickets

---

source/manual/welcome-to-2nd-line.html.md

This adds a more obvious link to detail about what 2nd Line actually involves

Adds link to 2nd Line tasks detail

---

source/manual/nagstamon.html.md

Had to set this up again recently, so have polished up the docs a bit.

Nagstamon docs tweaks

---

data/repos.yml

Adds repos to the list

---

source/manual/pagerduty.html.md

https://trello.com/c/CdJdD6lm/1313-add-pagerduty-rota-to-google-calendar

Add docs on adding Pagerduty rota to Google cal

---

source/manual/analytics.html.md

This is a special case of cross domain tracking where we use the same
GA property on both domains, so the tracking setup is more complicated
to pass cookie consent and GA client IDs between domains.
---
---
[Trello](https://trello.com/c/sf1T9BNR/1274-check-that-the-cross-domain-google-analytics-implementation-is-covered-in-the-govuk-developer-docs)

Add docs for GOV.UK Account cross domain tracking

---

source/manual/encrypted-hiera-data.html.md

Fix gpg when you get the error - `Network is unreachable`

Update hiera data to handle network is unreachable

---

source/manual/create-a-gpg-key.html.md

I suspect many people - like me - prefer the mail-free version!

Document no-mail version of GPG Suite

---

source/manual/sentry.html.md

It wasn't immediately obvious how to do this.

Document creating apps in Sentry

---

data/repos.yml
source/manual/alerts/slo-rate-checks-account.html.md
source/manual/get-emails-about-this-page.html.md
source/manual/govuk-account.html.md

[Trello](https://trello.com/c/gE8SSYlm/1493-handover-tasks-govuk-accounts-find-and-view)
We've gone and swanned off to Digital Identity - and Find and View have agreed to become the new owners of this repo.

Hand over accounts

---

source/manual/purge-cache.html.md

Trello: https://trello.com/c/TX9wLihh/101-cache-clearing-app-only-clears-path-not-query-strings
This updates the guidance on purging a page from the cache to be less
focused on the cache-clearing service and to reflect current GOV.UK
reality (where most pages are cached for 5 mins)
It replaces the instructions on how to clear the cache to use the
Jenkins task that is provided for this (which was updated in
https://github.com/alphagov/govuk-puppet/pull/11663 for this purpose)
This has been done in order to reduce dependencies on the cache-clearing
service to prepare for it's potential retirement.

Replace cache-clearing service in suggested purging process

---

data/repos.yml

Added some missing `govuk` repos and assigned owners. Also spotted one repo which has been archived. 
[Trello](https://trello.com/c/50TsmDVr/2895-update-list-of-apps-in-developer-docs)

App owners

---

source/manual/alerts/speedcurve-lux-js-version-check.html.md

Update link to LUX JavaScript in the GOVUK Publishing Components repo.

Update link to LUX JavaScript file

---

data/repos.yml

This adds some missing govuk repos and assigns owners to them. 
[Trello](https://trello.com/c/50TsmDVr/2895-update-list-of-apps-in-developer-docs-and-assign-owners)

Add some repos and owners

---

source/manual/deploying-terraform.html.md

Adds more details about the simpler way to start terraform jobs in jenkins from gds-cli.

Update documentation for cli invocation of terraform actions.

---

data/repos.yml
source/manual/knowledge-graph.html.md
source/manual/provision-machines-for-data-science-research.html.md
source/manual/related-links.html.md

The team have changed their name and Slack channel.

Change Data Products team Slack channel and name

---

source/manual/access-jenkins.html.md
source/manual/alerts/user-monitor.html.md
source/manual/configure-github-repo.html.md
source/manual/rules-for-getting-production-access.html.md

Trello card: https://trello.com/c/docwZ4Gm/2892-implement-production-deploy-access-5

Update docs on new Production Deploy role

---

source/manual/alerts/high-nginx-5xx-rate.html.md

Update the 5xx docs to point to potential areas to check. One of these is flushing the
ARP cache.

Update the 5xx docs to point to ARP cache docs

---

source/manual/manage-assets.html.md.erb

- you shouldn't use a space when adding ', true'
- you should keep the square brackets when replacing LEGACY_URL_PATH

Fix a typo and warn about square brackets

---

source/manual/common-aws-tasks-for-2nd-line-support.html.md

Following drill on 2nd line
Trello: https://trello.com/c/JNfGQDIR/1394-drill-detach-an-instance

Update guidance on detaching an instance

---

data/repos.yml

Apps that were previously owned in common by the Find and View teams are now split between them. Update lists in data/repos.yml to reflect the new owners.
https://trello.com/c/HoT1UCwA/1338-update-dev-docs

Update repo owners for Find and View apps.

---

source/manual/vpn.html.md

This link name has been changed in the relevant UI

Update reference to UI link in VPN doc

---

source/manual/alerts/smokey-loop-tests.html.md

Please see the commit messages for more details.

Small fixes to alert documentation for Smokey Loop

---

source/manual/howto-modify-change-note.html.md
source/manual/zendesk.html.md

https://trello.com/c/En0ZrTE9/1381-add-troubleshooting-tips-to-change-note-developer-docs

Update 2ndline docs

---

source/manual/alerts/rabbitmq-dead-nodes.html.md

This command example was a little confusing, hopefully this clarifies that it needs just the node IP address and not wrapped in square brackets

Update command example to clarify doesn't need square brackets

---

source/manual/repository-mirroring.html.md

Surprised I couldn't find this information more easily.

Clarify which AWS env is mirrored to

---

source/manual/get-started.html.md

This is an action arising from the Developer Survey Winter 2021.

Clarify policy on non-GOV.UK Docker local development usage

---

source/manual/redirect-routes.html.md.erb

James not around anymore and our Head of Content confirmed that the new contact for DXW is Inderjeet.

Update DWX contacts

---

source/manual/logging.html.md

https://trello.com/c/t8t3sT51/2877-ship-auth-logs-from-all-ec-instances-to-cyber-splunk-3

Fix filename of secure.log

---

source/manual/alerts/low-available-disk-inodes.html.md
source/manual/alerts/low-available-disk-space.html.md

These are relating to disk space in general, not inode usage

Move docs about disk space on jenkins to correct location

---

data/repos.yml

This repo has been archived, so we should also mark it as retired here.

Mark govuk-user-intent-survey-explorer as retired

---

source/manual/test-and-build-a-project-with-github-actions.html.md

We now prefer using a shared workflow for publishing rubygems, this updates this documentation to reflect that and explain how a repository gains a secret.

Add shared workflow for publishing gems

---

source/manual/howto-backup-and-restore-in-aws-rds.html.md

Markdown treating this as HTML, so some content is being omitted.

Fix formatting issues

---

source/manual/alerts/low-available-disk-inodes.html.md

Trello: https://trello.com/c/JwTIJsk1/2920-stop-low-available-disk-inodes-alert-3

Document the workspace-deleting process and thresholds

---

source/manual/purge-cache.html.md

[Trello card](https://trello.com/c/O5Wy2X9w/2946-authenticate-fastly-purge-requests-with-an-api-token-3)
[Rendered version of the updated docs](https://github.com/alphagov/govuk-developer-docs/blob/update-cdn-purge-docs/source/manual/purge-cache.html.md)
We are updating our Fastly configuration to authenticate cache purge requests using API tokens instead of an IP address allowlist.[^1]
This PR updates the documentation about purging the CDN cache to help developers authenticate their requests using Fastly API tokens stored in the `govuk-secrets` repo. By authenticating our requests we also remove the requirement to `ssh` onto a `cache` machine before issuing the request, so that step has been removed (though it is still necessary to connect from on-premises or via the VPN due to an …

Update CDN cache purge docs to use auth tokens

---

source/manual/alerts/low-available-disk-space.html.md

See https://trello.com/c/tEItOj0G/2879-review-logs-disk-space-issues

Document the automated removal of logfiles

---

source/manual/alerts/rebooting-machines.html.md

Improve documentation around rebooting machines

---

source/manual/vpn.html.md

* Link to Production Skyscape portal
* Add notice that GDS VPN is required

Update Skyscape VPN docs

---

source/manual/publish-special-routes.html.md.erb

Docs were not very clearly formatted.

Update publishing special route docs

---

source/manual/howto-backup-and-restore-in-aws-rds.html.md

Trello card: https://trello.com/c/uqU7EHja/2949-figure-out-how-to-get-apps-to-point-to-new-database

Add docs on using a restored database in an app

---

source/manual/howto-backup-and-restore-in-aws-rds.html.md

The previous iteration was geared towards how to drill the process. This iteration expands on the instructions to account for what the process would be outside of a drill.
In writing this, I've arrived at the conclusion that the "manually getting back to where we were" steps are quite laborious/risky/error-prone, so documenting a Terraform approach would be better. I'm not quite sure what the implementation steps would be, but that can be documented later. Crucially, we have now documented the immediate steps to follow during an incident, so any tidy-up steps can be discussed post-incident and the docs updated. Hopefully the non-optimal route documented here is still a net improvement on what was there before.
NB I've also fixed a couple of broken headings and links. …

Fixes to the 'restore RDS instance from snapshot' documentation

---

source/manual/zendesk.html.md

There is a best practices slidedeck which developers might find useful as an introduction. I've also moved the advice for DGU tickets into it's own section so that it is easier to find.

Update to the Zendesk doc

---

source/manual/data-gov-uk-2nd-line.html.md

Map previews have been deprecated.
Trello card: https://trello.com/c/4B6gI4VN/1451-dgu-map-previews-deprecated

Update DGU doc

---

source/manual/get-started.html.md

It seems that it's very common to get misunderstandings of this document with people new to GDS working in other programmes (DI is most common).
I've also removed the reference to CDDO as we don't have technical people in there who need this guidance.

Try make it clearer who the getting started guidance is for

---

source/manual/2nd-line-drills.html.md

Trello: https://trello.com/c/dvrdHKDT/99-work-out-new-things-to-drill

Document 2nd line drills

---

source/manual/common-aws-tasks-for-2nd-line-support.html.md

Add some information on logging in to detached instances after they've been detached.
https://trello.com/c/dXJ3PMbu/1460-drill-detach-an-instance

Add command to log into detached instances

---

source/manual/alerts/rabbitmq-dead-nodes.html.md

Update the documentation to include a fix that was used to resolve an Icinga alert.

Add fix for unhealthy nodes

---

data/repos.yml

Ownership is transferring from Platform Reliability to Interaction and Personalisation.

Change ownership of locations-api

---

source/manual/2nd-line-drills.html.md

https://trello.com/c/2fx1PV8E/1548-2nd-line-drill

Clarify steps needed to perform homepage promotion slots drill

---

source/manual/local-frontend-development.html.md

Improve local frontend development documentation page, specifically:
- add an introduction to suggest what option to use when
- include a new option (using both docker and the startup scripts)
- add a troubleshooting entry for cache problems

Expand local frontend dev docs

---

source/manual/2nd-line-drills.html.md

There are some additional drills that developers can do to increase their experience on 2nd line.
Trello card: https://trello.com/c/dvrdHKDT/99-work-out-new-things-to-drill

Update 2ndline drills doc

---

source/manual/common-aws-tasks-for-2nd-line-support.html.md

We currently don't have this documented clearly and will be referred to in one of the 2nd line drills.

Add steps on how to log into the AWS console

---

source/manual/dns.html.md
source/manual/zendesk.html.md

Signpost the SRE docs while we're expected to process these requests.

Document DNS delegation requests

---

source/manual/alerts/smokey-loop-tests.html.md

This has been recently carried out on 2nd line.
https://trello.com/c/STyEnSDp/129-add-documentation-on-drilling-how-to-update-a-secret

Add docs on updating Smokey credentials

---

source/manual/retiring-a-gem.html.md

https://trello.com/c/1IWOqO4r/2980-decide-how-to-properly-archive-a-gem-and-document-it-2

Add page on how to retire a gem

---

source/manual/alerts/expiring-api-tokens-in-signon.html.md
source/manual/data-gov-uk-2nd-line.html.md

Updating a couple of things with some helpful stuff from 2nd line this week.

Update docs on updating tokens and on ckan

---

source/manual/on-call.html.md

See https://docs.google.com/document/d/1W3xGmARrWW4b2eNfINLnHCtHQ7UVd0u2TmGo-v4BYSo/edit

Change SMT escalations link

---

source/manual/data-gov-uk-2nd-line.html.md

Update hyperlink in 2nd Line CKAN documentation

---

source/manual/howto-change-slug-and-create-redirect.html.md

Reslugging a document has now been built into the UI in these PRs 
https://github.com/alphagov/whitehall/pull/7122
https://github.com/alphagov/whitehall/pull/7134
The documentation needs to be updated to use the new workflow

Update documentation for editing a documents slug

---

source/manual/alerts/validate-published-dns.html.md
source/manual/dns.html.md
source/manual/fall-back-to-aws-cloudfront.html.md
source/manual/raising-issues-with-reliability-engineering.html.md
source/manual/retiring-an-application.html.md
source/manual/setting-up-new-rails-app.html.md
source/manual/transition-a-site.html.md

Removes some of the duplication and out of date content.

Rewrite docs around DNS management

---

source/manual/2nd-line-drills.html.md
source/manual/alerts/established-connections-exceed.html.md
source/manual/scale-unicorn-workers.html.md

Trello: https://trello.com/c/20frSJJv/1673-2nd-line-drill

Update drill documentation: scale up the number of workers

---

.github/pull_request_template.md

Taking steps to avoid private information being committed to the public repository.

Add pull request template highlighting public vs private concerns

---

source/manual/test-and-build-a-project-with-github-actions.html.md

I just noticed we've got a h2 when it should be a h3

Fix header at wrong indentation

---

source/manual/pact-testing.html.md

This is an attempt to clarify some confusions that existed in the docs, and present a clearer explanation of contract testing.
[Trello](https://trello.com/c/RMgXVXhO/164-publishing-api-contract-tests-are-different-to-all-other-repos)

Update docs for contract testing

---

source/manual/alerts/rebooting-machines.html.md
source/manual/find-an-instance-in-aws.html.md

Add some tips about how to find an instance in AWS, plus reasons you might want to find on and why rebooting docker_management might clear unattended reboot locks.
https://gds.slack.com/archives/CAB4Q3QBW/p1668428029358079

Add tips about finding an instance, and docker_management locks.

---

source/manual/howto-modify-change-note.html.md.erb

This came up in https://govuk.zendesk.com/agent/tickets/5168849

Document how to add a change note in Whitehall

---

source/manual/cdn.html.md

Trello: https://trello.com/c/LVGgeLG7/3067-add-support-for-logging-and-blocking-requests-at-edge-by-ja3-fingerprint

Document JA3 fingerprint blocking

---

source/manual/merge-pr.html.md

https://gds.slack.com/archives/CADKZN519/p1671028991821039

Note that you'll need GITHUB_TOKEN, rearrange to make easier to read.

---

data/repos.yml

https://trello.com/c/ugwggeMQ/3076-investigate-dependabot-not-posting-on-team-channel

Change slack channel for Interaction and Personalisation team

---

source/manual/architecture-deep-dive.html.md

Remove reference to env-sync-and-backup

---

source/manual/databases.html.md

This was reduced from two exceptions to one exception, in https://github.com/alphagov/govuk-aws/commit/430e8fd7d579694560f80ea11174140d8f966364

Update 'exception' text

---

source/manual/kibana.html.md

Credit to @sihugh for the approach.

Document querying syslogs on a specific machine

---

source/manual/cdn.html.md
source/manual/query-cdn-logs.html.md

Refine the docs around blocking traffic at edge

---

source/manual/2nd-line.html.md

We now start shifts on Monday, not Wednesday.
Trello: https://trello.com/c/j49PT66X/120-implement-shift-change-to-2nd-line-rota

Update to reflect new shift pattern

---

source/manual/redirect-routes.html.md.erb

Updates following a drill
https://trello.com/c/9pvUvMwH/1807-2nd-line-drill-drill-creating-and-changing-redirects

Update creating and changing redirects

---

data/dashboard.yml

Fix schemas link

---

source/manual/running-rake-tasks.html.md

Running a command in a deployment pod is a one-liner.

Simplify "Run a rake task on EKS".

---

source/manual/ruby.html.md

- Shrink scope of where we use rbenv
- Remove obsolete information about adding new ruby versions to Puppet
- Expand a little more on changes needed if using bulk-changer
- Add link to how to get logs in EKS
- Remove item about hard-restarting (note needed in EKS)
Rendered view at: https://github.com/alphagov/govuk-developer-docs/blob/updating-ruby/source/manual/ruby.html.md

Updating ruby pages to reflect replatforming

---

source/manual/dns.html.md

This adds all the steps needed and assumes the person following the instructions has never run this before.
It also gives examples of what to check in the `plan` output.

Update documentation for changing DNS for *.service.gov.uk

---

source/manual/kubernetes-infrastructure.html.md

These are rough and ready pages for now stolen from other places.

Add pages on our new infrastructure

---

data/repos.yml
source/manual/2nd-line.html.md

Update repos list and URL to show new dashboard

---

data/repos.yml

Update team name for Navigation and Homepage

Update team name for Navigation and Homepage

---

data/repos.yml

Fix team channel for Navigation and Homepage

Update team channel for Navigation and Homepage

---

data/repos.yml
source/manual/2nd-line.html.md
source/manual/alerts/content-data-api-app-healthcheck-not-ok.html.md.erb
source/manual/alerts/high-nginx-5xx-rate.html.md
source/manual/alerts/renew-tls-certificate.html.md
source/manual/ask-for-help.html.md
source/manual/common-aws-tasks-for-2nd-line-support.html.md
source/manual/content-data-architecture.html.md
source/manual/dns.html.md
source/manual/flush-the-arp-cache.html.md
source/manual/kubernetes-infrastructure.html.md
source/manual/load-testing.html.md.erb
source/manual/merge-pr.html.md
source/manual/move-apps-between-servers.html.md
source/manual/non-ha-node-classes.html.md
source/manual/raising-issues-with-reliability-engineering.html.md
source/manual/renew-a-tls-certificate.html.md
source/manual/retiring-an-application.html.md
source/manual/sentry.html.md

These teams have changed names.

Update team names

---

source/manual/alerts/RouterErrorRatioTooHigh.html.md

Added Router error rate too high alert playbook to developer docs.

1138 Added router error alert

---

source/manual/content-data-architecture.html.md

Taken from original doc https://docs.google.com/document/d/1XJtJDv5qPoONyGnBqOk9ig2xao24dgdwq99V4DgYxtU/edit#

Add missing alias links

---

source/manual/backups.html.md

This PR attempts to document a shared definition of what a backup is and our current use of backups.
📖 [Rendered page](https://github.com/alphagov/govuk-developer-docs/blob/current-use-of-backups/source/manual/buckups.html.md)
https://trello.com/c/8TESDxDu/3129-write-a-document-of-our-current-use-of-backups-2

Document backups

---

data/repos.yml
source/manual/transition-architecture.html.md

Dunno whether it's actually of any value keeping these in here, but 🤷

Mark assets-{businesslink,directgov} repos retired.

---

source/apps.html.md.erb

This fixes an incorrect column heading.

Fix column heading for apps list

---

data/repos.yml

See: https://github.com/alphagov/govuk-repo-mirror/pull/28

Retire govuk-repo-mirror

---

source/manual/local-frontend-development.html.md

This feature was added a couple of weeks ago:  https://github.com/alphagov/govuk-docker/pull/661

Document running against Integration

---

source/manual/dns.html.md

Link to Terraform Cloud

---

source/manual/purge-cache.html.md

- Our Varnish servers no longer exist 🎉
- We no longer have or need a Jenkins job for issuing cache purge requests, since everyone on tech support is given a Fastly account (and the Fastly UI is much easier to use than the Jenkins job) 🎉
- Simplify and update the playbook instructions.
- Remove the complicated procedure for sending a `PURGE` HTTP request from the command line. We'd never do that in a hurry and it's much easier to use the UI (and we don't want to encourage mucking about with Fastly API tokens if we can at all help it).
- Restructure the article so that we don't have to read through a bunch of background info before getting to the actual playbook steps.
Additional context: we almost never have to purge anything from Fastly these days since moving to `max-age: 300` for the …

Update "Purge a page from cache" playbook.

---

data/repos.yml

Add undocumented Platform Security & Reliability repos

---

data/repos.yml

Add missing Publishing repos

---

source/manual/howto-change-slug-and-create-redirect.html.md

For ease of use these commands have been updated with the new eks cluster in mind. This should make the docs easier to follow.

Update redirect whitehall docs to have the new k8s commands

---

data/repos.yml

Add undocumented DGU-related repositories

---

data/repos.yml

Add router-postgres owner

---

source/manual/get-started.html.md

Add required steps for integration access in `user-reviewer`

Add required steps for integration access in `user-reviewer`

---

source/manual/elasticsearch-dumps.html.md

Update the playbook for restoring the search indices from backup snapshots, with regard to the move to Kubernetes.
- Remove references to `ssh` and update the example commands.
- Remove an unnecessary step (no need to list the available snapshot repos, because there's only one backup repo and its name is fixed).
- Add missing steps for how to tell when the restore is done.
- Add a version of the procedure for restoring all the indices, so that we can recover from losing the search cluster.
Tested: checked formatting by rendering locally with `SKIP_PROXY_PAGES=true bundle exec middleman`
https://trello.com/c/Nq4oZAOE

Update search index restore playbook wrt k8s.

---

source/manual/2nd-line-drills.html.md
source/manual/github-unavailable.html.md

Have included the new CodeCommit process and removed any part of the documentation which is no longer available without jenkins/puppet.

Updated codecommit process to reflect new EKS environment

---

data/repos.yml

New repository for short-lived whitehall analysis work

adding whitehall-asset-analysis repo

---

data/analytics/attributes.yml
data/analytics/events.yml

Update some of the information in the GA4 implementation record section, specifically:
- local lookups
- search results/enhanced ecommerce
- simple smart answers
Part of the work to document our GA4 approach.
Trello card: https://trello.com/c/JbLX3n2C/388-implementation-record-additions-and-improvements

Analytics updates

---

source/manual/sentry.html.md

This is now automated in govuk-user-reviewer.

Document new process for getting Sentry access

---

source/manual/query-cdn-logs.html.md

Update docs on getting access to Splunk

---

source/manual/amazonmq.html.md

Update AmazonMQ password key

---

data/repos.yml

Add govuk-dns-tf repo

---

data/dashboard.yml
source/manual/alerts/RouterErrorRatioTooHigh.html.md
source/manual/get-started.html.md
source/manual/howto-change-slug-and-create-redirect.html.md
source/manual/howto-modify-change-note.html.md.erb
source/manual/kubernetes-infrastructure.html.md
source/manual/redirect-routes.html.md.erb
source/manual/ruby.html.md

https://github.com/alphagov/govuk-kubernetes-cluster-user-docs/pull/92

Update links to govuk-kubernetes-cluster-user-docs.

---

source/manual/retiring-an-application.html.md

Additional instructions on how to clear production and staging K8s when retiring an app

---

source/manual/get-started.html.md

Fix chevrons around john.smith example user addition

---

source/manual/github-unavailable.html.md
source/manual/howto-checkout-and-commit-to-codecommit.html.md

@rtrinque and I tried this out this afternoon and found a few bits missing so thought I'd update it.
I reckon we could simplify the [deploy-with-argo-cd](https://github.com/alphagov/govuk-developer-docs/blob/sengi/dril/source/manual/github-unavailable.html.md#deploy-the-image-to-kubernetes-using-argo-cd) procedure by a few steps if we use `kubectl patch` instead of the Argo CD UI, but I ran out of time to figure out the details for that so I'll leave that for a possible future improvement.

Update CodeCommit / GitHub down playbooks.

---

source/manual/2nd-line-drills.html.md
source/manual/slack-unavailable.html.md

- Documents Google Spaces as a comms option if Slack goes down
- Documents the persistent 2nd line 'Google Space'

Document Google Spaces

---

data/repos.yml

Add an entry for the content-store-proxy repo

Add content-store-proxy to data/repos.yml

---

source/manual/zendesk.html.md

Co-authored-by @nicholsj , who knows Zendesk better than anyone! 🙇 
Zendesk search terms are covered in https://support.zendesk.com/hc/en-us/articles/4408835086106-Using-Zendesk-Support-advanced-search.

Document useful Zendesk searches

---

source/manual/2nd-line-drills.html.md

Updating following a 2nd line drill - https://trello.com/c/fPEXeNU4/2019-2nd-line-drill-scaling-up-an-application

Provide an example PR for scaling up an app

---

data/analytics/events.yml
data/analytics/schemas.yml
data/analytics/trackers.yml
source/analytics/trackers.html.md.erb

Adding some more data to the implementation record for Google Analytics 4.
Part of documenting the GA4 migration on GOV.UK.
Trello card: https://trello.com/c/KjI9KBwC/590-add-schema-to-implementation-record

More analytics updates

---

data/repos.yml

Add new Fastly repos to list

---

source/manual/cdn.html.md

Update CDN documentation to reference new govuk-fastly workflow

---

source/manual/data-gov-uk-2nd-line.html.md

Update staging and integration hostnames for CKAN

---

config/tech-docs.yml
source/kubernetes/cheatsheet.html.md

Move Kubernetes cheatsheet into /kubernetes folder

---

source/manual/alerts/RouterErrorRatioTooHigh.html.md

There were some broken links and also fixed headings to be consistent with the rest of the docs.

Update Router error rate docs

---

data/repos.yml

Seal is no longer hosted on Heroku 🎉

Update Seal hosting

---

data/repos.yml

router-postgres repo was archived

Remove router-postgres repo

---

source/manual/codeql.html.md

Adding documentation for the codeql workflow. 
https://trello.com/c/EyE98PIO/3327-document-codeql-scans

CodeQL workflow documentation

---

source/manual/analytics.html.md

Fix related repos metadata

---

source/manual/sentry.html.md

Document change in terminology from Ignore to Archive

---

data/repos.yml
source/manual/related-links.html.md

Renames team name and slack channel for mainstream publishing experience

---

data/repos.yml

https://trello.com/c/wLuAJkEC/3346-automatically-notify-teams-when-gems-contain-unreleased-changes

Add gem-release-alert repo

---

source/manual/databases.html.md

These are being turned down now that the backups etc. run as Kubernetes cronjobs.
https://trello.com/c/JjTHY62V

Remove info about defunct db_admin bastions.

---

source/manual/send-secret-using-gcp.html.md

This comes up occasionally and is useful to capture in our Dev Docs.

Document how to send a secret using GCP

---

data/analytics/events.yml

Adds the GA4 banner docs, and update page view event

Add GA4 banner docs and update page view event

---

data/analytics/events.yml

Update the GA4 analytics implementation record, specifically the 'search' bit.
Documenting our GA4 approach.
Trello card: https://trello.com/c/JQPHy26m/661-check-implementation-record-is-up-to-date

Update search GA4 analytics data

---

data/repos.yml

https://trello.com/c/jDSDGNyn/814-measure-and-record-our-publishing-latency-sli

Add govuk-sli-collector repository

---

source/manual/data-gov-uk-deployment.html.md
source/manual/data-gov-uk-operations.html.md

https://trello.com/c/2qXYzZYb/1239-switchover-paas-apps-to-k8s-cluster

Update data-gov-uk-deployment.html.md to deploy to kubernetes cluster

---

source/manual/github.html.md

There's a new requirement to set up SCA and SAST scans for all new GOV.UK repos.
https://trello.com/c/gbGaKLLu/3352-add-sca-and-sast-scans-to-all-govuk-repos-2

Add new step to creating repo

---

source/manual/howto-block-arbitrary-urls.html.md

Fix alias links

---

data/analytics/attributes.yml
data/analytics/events.yml

Adds search term sanitisation details to GA4 docs

Add search term sanitisation details to GA4 docs

---

source/manual/howto-change-slug-and-create-redirect.html.md
source/manual/metrics.html.md
source/manual/sidekiq.html.md

Updates some Grafana dashboard links

Update some Grafana links

---

source/manual/migrate-to-dart-sass-from-libsass.html.md

Update "Migrate to Dart Sass from LibSass" docs to remove duplicate title.

Update "Migrate to Dart Sass from LibSass " docs to remove duplicate title

---

source/kubernetes/manage-app/manage-secrets/index.html.md

Update K8 secrets doc

---

source/manual/alerts/email-alerts-travel-medical.html.md

These alerts are soon to be handled in email-alert-api, but the documentation has been broken for a long while, and it should be safe to update immediately, given that most of the diagnostic tools mentioned are already in place and are superior to the ones mentioned in the existing documentation. Plus many of the links were broken post replatforming, this fixes them.
https://trello.com/c/7k2DR4Sb/2293-update-alert-documentation-runbook

Update documentation around travel advice / medical safety email alerts

---

source/manual/snyk.html.md

Documentation for the implementation of the SNYK tool. Includes instructions for including it in a project and managing security alerts. 
https://trello.com/c/iepFKomn/3367-document-snyk-sast-2

SNYK documentation

---

source/manual/get-started.html.md

This makes a couple of minor updates to the 'Get started' documentation.  Full detail in the commit messages.

Minor updates to the get started documentation

---

source/manual/snyk.html.md

Fix link to downloading workflow artifacts

---

source/manual/get-started.html.md

This makes a number of updates to the 'Get started' guide, specifically to reduce the number of non-essential steps required on a new starter's first day.

Updates to 'Get started' guide

---

data/repos.yml

Remove repo as it's managed by the design system team rather than a gov.uk team

Remove fonts repo from repos.yml

---

source/manual/redirect-routes.html.md

The correct name for the app is draft-content-store

Change content-draft-store to draft-content-store

---

source/manual/migrate-to-dart-sass-from-libsass.html.md

https://trello.com/c/0JHew9b7/2307-dart-sass-docs-changes
Update docs on migrating to Dart Sass from LibSass.
[Rendered version](https://github.com/alphagov/govuk-developer-docs/blob/848d06a08783417f5f082e72ad7bf07e802d36e3/source/manual/migrate-to-dart-sass-from-libsass.html.md)

Update Sass migration docs

---

source/manual/data-gov-uk-2nd-line.html.md

A few small tweaks to the documentation for supporting CKAN which have come up in recent tickets - should be self-explanatory.

Some tweaks to the CKAN support docs

---

source/manual/licensing.html.md

This updates the documentation for supporting Licensify for EKS.

Update supporting licensify documentation for EKS

---

source/manual/hmrc-paye-files.html.md

Rendered version: https://github.com/alphagov/govuk-developer-docs/blob/60c97bf377c62b76036ece5e4c429e7763544c7e/source/manual/hmrc-paye-files.html.md

Update documentation for HMRC PAYE file upload for EKS

---

source/manual/access-to-licensing-for-third-parties.html.md

This tweaks the licensify documentation for third parties in the
following ways:
- Removes information about ArgoCD, third parties won't need to use it.
- Updates the role to use with gds-cli
- Adds section about tests
- Adds section about releases
- Removes info about restarting containers (as they don't have permission to do that)

Update licensify documentation

---

source/manual/data-gov-uk-2nd-line.html.md

This limit has caused confusion/problems so worth noting here.

Add note about limit to number of CKAN dataset deletions

---

source/manual/deploying-terraform.html.md

Rendered version here: https://github.com/alphagov/govuk-developer-docs/blob/b637e9be897055ae3a86554523a1b78c130227c0/source/manual/deploying-terraform.html.md

Update docs on deploying terraform

---

data/analytics/events.yml
source/manual/local-frontend-development.html.md

- update the analytics documentation with details of the GA4 data for events on the back link component
- update the local frontend development page with a workaround to a newly discovered problem
Needed for the GA4 work.
Trello card: https://trello.com/c/Z5FYBU5o/782-back-links

Fe updates

---

source/manual/common-aws-tasks-for-2nd-line-support.html.md
source/manual/kibana.html.md
source/manual/logit.html.md
source/partials/repo/_hosting.html.erb

Delete some paragraphs/sections that are obsolete now that we no longer run Puppet, Jenkins etc.

Remove some obsolete Puppet-related info.

---

source/manual/get-started.html.md

Remove Section 10 and some other references to SSH/Jenkins

Update Get Started: Remove SSH / EC2  Instance access references

---

data/repos.yml

We still need to set these for now, until we fix #4259.

Mark some archived repos as retired.

---

source/manual/environments.html.md

[Preview](https://github.com/alphagov/govuk-developer-docs/blob/sengi/environments/source/manual/environments.html.md)
Fixes #4377.

Update environments page.

---

source/manual/query-cdn-logs.html.md

to reflect that we now have DGU fastly logs in Splunk.
Implemented in:
- https://github.com/alphagov/govuk-fastly/commit/74fac480644eef4e137082b4bba4cf3e029d4275
- https://github.com/alphagov/govuk-fastly-secrets/commit/5055cb0a899e24a5bbafdc1b9422734fd99a6bb4

Update 'Query CDN logs' docs

---

source/manual/data-gov-uk-deployment.html.md

General tidy up and removing some out of date references.

Improve data.gov.uk deployment documentation

---

app/repo.rb
spec/app/repo_spec.rb

Fix Kibana URLs

---

source/manual/2nd-line.html.md
source/manual/on-call.html.md
source/manual/rules-for-getting-production-access.html.md

Document new process for getting Production Admin access

---

source/manual/content-preview.html.md

- Remove Puppet references.
- Rewrite the section on authnz, which was in need of some TLC. Distinguish between authentication and authorization, omit extraneous details, use house style, use standard terminology.
[Preview](https://github.com/alphagov/govuk-developer-docs/blob/sengi/content-preview/source/manual/content-preview.html.md)

Update "how the draft stack works" post-Puppet.

---

source/manual/howto-modify-change-note.html.md

- Restructure for clarity.
- Remove extraneous verbiage.
- Avoid unnecessary use of the passive voice.
- Use ordered lists for procedures where the order matters.
- Make code snippets easier to copy/paste.
- Specify language hints on code snippets for syntax highlighting.
[Preview](https://github.com/alphagov/govuk-developer-docs/blob/sengi/change-notes/source/manual/howto-modify-change-note.html.md)

Update playbook for amending a change note.

---

source/manual/transition-a-site.html.md

Failing to verify a *.gov.uk domain blocks the transition of any other sites subsequently added.
Therefore moving this to be the first instruction so it can be carried out before we add the domain into the transition app.

Update transition docs: move domain verification to be first transition step

---

config/tech-docs.yml

These are all either well past being useful or point at pages that no longer exist.

Clean up old redirects.

---

source/manual/web_application_firewall_rules.html.md

[Trello card](https://trello.com/c/5nkX83ng/3404-3-implement-ja3-fingerprinting-on-the-waf-acl-used-by-our-publishing-apps)
* The WAF ACLs live in a different TF project now
* Our WAF logs aren't sent to Splunk anymore
* The backend_public ACL supports JA3 denylisting now

Update WAF documentation

---

source/manual/hmrc-paye-files.html.md

https://trello.com/c/o6HdmLDM/246-20-march-update-to-hmrcs-basic-paye-tools
Updates some cli commands to specify the pod when exec'ing and updates the process to use the **test-** xml provided.

Updates the hmrc paye instructions

---

source/manual/manage-assets.html.md.erb

Several steps have changed since moving to Kubernetes. Therefore updating the guidance to reflect these changes.
Also makes some changes to other parts of the documentation to make the steps clearer.
[Trello card](https://trello.com/c/4J8IJaa1)

Update 'Manage Assets' guidance

---

source/manual/snyk.html.md

This is part of the work done for integrating Snyk with Code scanning.
Trello: https://trello.com/c/srqkwMUh/3430-spike-integrating-snyk-findings-with-github-code-scanning

Update set up instructions

---

source/kubernetes/manage-app/set-env-var/index.html.md

Fix link to secrets doc

---

app/snippet.rb

Similar to #4572. Fixes https://github.com/alphagov/govuk-developer-docs/security/code-scanning/1

Use `Sanitize` for snippet generation.

---

source/manual/data-gov-uk-deployment.html.md

- Restructure for clarity. Find/Publish rollouts are essentially the same as CKAN rollouts now.
- Set out the differences between DGU rollouts and the rest of the GOV.UK content management system (CMS) components.
- Fix broken links and remove some links where there are too many options to provide direct links without excessive maintenance or complexity (like linking to Argo CD for each app x each environment).
- For procedures, prefer ordered lists of step-by-step instructions rather than descriptive prose.
- Tech writing style fixes: avoid unnecessary use of passive voice, prefer simpler sentence structure and so on.
[GitHub preview](https://github.com/alphagov/govuk-developer-docs/blob/sengi/dgu-rollouts/source/manual/data-gov-uk-deployment.html.md)

Revamp data.gov.uk releases and rollouts page.

---

source/manual/zendesk.html.md

We think engineers can do this without involving anyone else.
(I've now moved this out of the Senior Dev section in the [template](https://trello.com/c/GIHPZi2o/3440-production-admin-access-for-2nd-line))

Update Zendesk account creation instructions

---

source/manual/data-gov-uk-2nd-line.html.md

This updates the instructions for changing a user's email address in CKAN. 
I also took the opportunity to consistently use 1. style numbering for ordered lists.

Update instructions for changing user email in CKAN

---

data/repos.yml

https://govukverify.atlassian.net/jira/software/projects/GOVAPP/boards/405?selectedIssue=GOVAPP-412
https://govukverify.atlassian.net/jira/software/projects/GOVAPP/boards/405?selectedIssue=GOVAPP-407

Add two new iOS repos

---

data/repos.yml

Add Android app repo

---

source/manual/data-gov-uk-2nd-line.html.md

A small update to the instructions to reflect the change to the user form here https://github.com/alphagov/ckanext-datagovuk/pull/1689

Update CKAN instructions for changing user email address

---

source/manual/manage-assets.html.md.erb

- Tech writing style fixes: avoid unnecessary use of the passive etc.
- Simplify the example commands and make them copy-paste friendly.

Tidy up `Remove an asset` playbook.

---

source/manual/manage-assets.html.md.erb

Also make it a permalink and give the name of the Rake task. Plus a few more style fixes.

Fix broken link in `Remove an asset` playbook.

---

source/manual/manage-assets.html.md.erb

Update the steps to 'request removal of the asset from Google's search results'.

Update 'removing an asset' steps

---

source/manual/manage-dependencies.html.md

Update doc to reflect changes introduced in RFC-167.
https://trello.com/c/iLYMKGBz/3497-update-documentation-regarding-auto-merging-2

Update Manage dependencies with Dependabot

---

.github/workflows/deploy.yml

No functional changes here, just avoiding deprecations. And some trivial cleanup.

Update GitHub Actions dependencies + syntax cleanup.

---

data/repos.yml

This should fix the broken deployment script.

Rename imminence to places-manager

---

data/repos.yml

- move from CIOP to P&P
- take ownership of Feedback and Finder-Frontend from AI
- 
https://trello.com/c/4NV6YrWB/117-take-ownership-of-feedback-and-finder-frontend-apps

Update ownership of patterns and pages apps

---

source/manual/brakeman.html.md

Add more information on reusable workflow and its usage.
https://trello.com/c/QAGVOM7F/3553-update-brakeman-documention-3

Update Brakeman docs

---

source/manual/document-collection-emails-a-special-case.html.md
source/manual/email-signup-journeys.html.md

Minor fixes missed in https://github.com/alphagov/govuk-developer-docs/pull/4631

Minor fixes to document collection email docs

---

source/manual/2nd-line.html.md

As discussed in https://gds.slack.com/archives/C020WTDJWQZ/p1718786886850289.

Clarify PagerDuty responsibility

---

data/repos.yml

These repos have both been archived

Remove recently archived CKAN extension repos

---

data/analytics/events.yml

Clean up some information in the GA4 implementation record. See individual commits for details.
Some of the data was out of date.
None.
Trello card: https://trello.com/c/T22BPi1C/822-clean-up-some-information-in-the-implementation-record

GA4 Implementation record updates

---

data/repos.yml

Remove retired repos

---

data/repos.yml

Remove retired repos belonging to Data Science

---

data/repos.yml

Add unarchived repo

---

data/repos.yml

https://github.com/alphagov/govuk-helm-charts/issues/2052

Add govuk-crd-library to repos list

---

data/repos.yml

The teams merged and the #govuk-platform-security-reliability-team Slack channel will be archived.

Update the ownership of Platform Security Reliability repos

---

source/manual/2nd-line-drills.html.md
source/manual/github-unavailable.html.md
source/manual/howto-checkout-and-commit-to-codecommit.html.md

Updated documentation after running through drill instructions for Deploying via CodeCommit
https://trello.com/c/L46MTjI2/2369-2nd-line-drill

Codecommit drill documentation update

---

source/manual/slack-integrations.html.md

https://trello.com/c/L9GicvIj/3583-document-gem-release-tools-1
Closes https://github.com/alphagov/govuk-developer-docs/issues/4749

Add info about gem version check notifications

---

source/manual/publishing-a-ruby-gem.html.md

To show how to use them in a project.

Add examples of how to configure auto-release tools

---

data/repos.yml

This adds the govuk-platform-internal to the list of Repos.

Add the govuk-platform-internal Repo

---

data/repos.yml

For consistency, as this seems to be what we do

Mark repo as private

---

source/manual/query-cdn-logs.html.md

Description:
- Internal link was spelt incorrectly

Fix broken infra-fastly-logs-terraform

---

source/manual/schemas.html.md

Remove references to HowTo schemas following https://github.com/alphagov/collections/pull/3755

Remove HowTo schema documentation

---

source/manual/pagerduty.html.md

Change day of PagerDuty drill

---

source/manual/heroku.html.md

https://trello.com/c/ze30LwHO/247-stop-heroku-emails-coming-to-tech-2nd-line-inbox

Update instructions about resetting heroku password

---

data/repos.yml

Changing the owner team to a more relevant one

Change owner of data repos

---

source/manual/how-to-query-mysql-database-on-eks.html.md

Added how-to to query databases on EKS and export to CSV

---

source/manual/secrets-manager.html.md

Clarify that admin role needed to access Secrets

---

data/repos.yml

Updated slack channel name and removed archived govuk-mobile-remote-config repo

Update repos.yml for mobile repos

---

source/manual/govuk-env-sync.html.md

Document change to weekly env sync for integration

---

data/repos.yml

A repo to hold sensitive TFC var sets
https://github.com/alphagov/govuk-infrastructure/issues/1127

Add govuk-infrastructure-sensitive to repos.yml

---

source/manual/alerts/signon-api-user-token-expires-soon.html.md

See https://gds.slack.com/archives/C03D792LYJG/p1730717012373719
Trello: https://trello.com/c/YdGWsy0I/3035-integrate-the-specialist-finder-edit-forms-with-support-api

Fix reference to k8s cronjob

---

source/mobile/backend/remote-config-runbook.html.md

sorry should have waited for the linter to run before merging - think this will be fine though

fix lint issues

---

data/repos.yml

Add ga4-dataform repo

---

source/manual/data-gov-uk-2nd-line.html.md

This:
- removes some outdated content
- adds instructions for changing the name of a publishing organisation
- tweaks the instructions for finding the harvest source of a dataset

Update docs for common ckan tasks

---

source/manual/load-test.html.md

The Publishing Platform team have recently run a more complex load test script, so updating the documentation based on our experience.
[Trello card](https://trello.com/c/6GPP3nF6)

Update load test instructions

---

source/manual/redirect-routes.html.md

Remove section that was recently deleted.

Fix markdown

---

data/repos.yml

Add terraform-govuk-tfe-workspacer repo

---

data/repos.yml

https://github.com/alphagov/govuk-infrastructure/issues/1127

Remove govuk-aws and govuk-aws-data from repos.yml

---

data/repos.yml

Trello: https://trello.com/c/CpNHGNL3/1510-take-on-the-support-app-and-api

Change ownership of support and support api to the publishing platform team

---

source/layouts/repo_layout.html.erb

This was missed in the refactor, and was preventing the project from building

Reinstate private repo check in sidebar

---

.github/workflows/actionlint.yml
.github/workflows/deploy.yml

Bulk Update: Addresses govuk-infrastructure#1361

Add Actionlint Checks

---

source/kubernetes/manage-app/create-new-env/index.html.md

This is an update to the "new environment" documentation to instruct folks on how to set up a new AWS account (because you'll probably need to do this in order to create a new environment).

How to Create a New AWS Account

---

data/repos.yml

I don't fully know if this works, I guess we'll see!

Alert Richard about graphql repo because it's not really platforms

---

data/repos.yml

Adds the repo and assigns an owner

Add govuk-content-metadata repo

---

data/repos.yml

This application is no longer in use and the repo has been archived.
[Trello card](https://trello.com/c/YV6VNRFO)

Remove `govuk-sli-collector`

---

source/manual/retiring-an-application.html.md

This makes various changes to bring the documentation up-to-date.  See the individual commit messages for details.
[Trello card](https://trello.com/c/YV6VNRFO)

Update documentation for retiring an application

---

source/kubernetes/get-started/tutorials/app-config-deploy-helm-chart/index.html.md

See Slack thread: https://gds.slack.com/archives/C03D792LYJG/p1741195661107679?thread_ts=1741189069.825679&cid=C03D792LYJG
This seemed the best place to document it (at least for now).

Document applying config changes to workers

---

source/manual/github-new-repo.html.md

Added in https://github.com/alphagov/govuk-infrastructure/pull/1875

Mention Slack webhook in new repo guide

---

source/repos/by-team-and-type.html.md.erb

Fix names in repos by team and type

---

source/manual/how-to-rotate-fastly-api-keys-for-prometheus-exporter.html.md

https://github.com/alphagov/govuk-infrastructure/issues/1935

Add documentation on rotating fastly API keys for prometheus exporter

---

source/manual/govuk-notify.html.md

Trello: https://trello.com/c/LtvHXarF

Document escalating to Notify support

---

source/manual/govuk-notify.html.md

Trello: https://trello.com/c/LtvHXarF

Document individual account usage for Notify

---

source/manual/republishing-content.html.md.erb

Update Grafana links in republishing doc

---

source/manual/emergency-publishing.html.md

Clarify who is responsible for deploying the banner

---

source/kubernetes/get-started/access-eks-cluster/index.html.md

Found and fixed a typo. Nothing else to say, really!

Fix a Typo in the EKS documentation

---

source/manual/rules-for-getting-production-access.html.md

Details in https://github.com/alphagov/govuk-user-reviewer/pull/1548 🔒

Update Production Deploy access

---

source/manual/licensing.html.md

This process hasn't been documented before, and the non-standard way Licensify consumes these access keys caused a lot of confusion.
https://github.com/alphagov/govuk-platform-internal/issues/33

Document process for rotating IAM access keys for Licensify

---

source/manual/emergency-alerts.html.md

https://github.com/alphagov/govuk-infrastructure/issues/2286

Document the Emergency Alerts logging connection in Fastly

---

source/manual/on-call.html.md

This has changed with the move to DSIT.

Update instructions on claiming on-call pay

---

source/manual/alerts/signon-api-user-token-expires-soon.html.md

Some of this was out of date; some cases weren't well documented

[PP-7242] Update Signon API token guide

---

source/manual/cdn.html.md

This service has been enabled, so we should add some docs for it.

Add Fastly DDOS protection docs

---

source/manual/incorrect-postcode-data.html.md

Update documentation about incorrect postcode data

---

source/manual/what-to-do-if-search-is-down.html.md

Correct broken links

---

source/manual/environments.html.md

See https://github.com/alphagov/govuk_app_config/pull/488

Document how to query current environment

---

source/manual/dns.html.md

Changing the team name for clarity and consistency. 
Not sure how these were missed previously.

Update name of platform team

---

source/manual/get-started.html.md

As per the change announced here:  https://gds.slack.com/archives/C05DC0SJ6UW/p1753954435102749

Updated URL for Request an AWS User

---

source/manual/on-call.html.md

Clarify when devs are added to the rota

---

package.json
yarn.lock

Update mermaid to the latest and greatest

Update mermaid to latest version

---

startup.sh

Yarn is required to handle the repo's mermaid diagrams, ensure it is installed on startup.

chore: 🤖 ensure yarn is installed (needed for mermaid)

---

source/manual/data-gov-uk-2nd-line.html.md

This adds URLs for the different environments, and makes some minor readability changes. It also fixes display of ID

Changes to DGU support docs

---

source/kubernetes/manage-app/manage-secrets/index.html.md

Update examples for creating external secrets to set the api version to v1

Update external secrets examples to apiVersion v1 from v1beta1

---

source/manual/rename-a-country.html.md

| Before | After |
|----|----|
| <img width="783" height="359" alt="image" src="https://github.com/user-attachments/assets/ff447633-81d7-4570-b53d-1b300d9fc685" /> | <img width="783" height="411" alt="image" src="https://github.com/user-attachments/assets/eb071dac-229a-4626-9328-ee444f53a6cf" /> |

Fix list formatting in rename country guidance

---

source/manual/best-practices-for-handling-credentials.html.md

Add best practices for credentials

---

source/manual/prometheus-grafana-and-alertmanager.html.md

Description:
- Add a brief line on the Prometheus Operator

BAU - Add Prometheus Operator information

---

data/repos.yml

Description:
- Add `govuk-reports-prototype` to repos list

Add `govuk-reports-prototype` to repos list
