README.md
Running `bundle exec jekyll serve --watch --baseurl ''` starts the app
on `4000`, not `4567` for me.
Also drop the period, so the address is easier to copy and paste.
=> Fix port number for local running instructions

_data/content_stats.json, _layouts/default.html, _layouts/main.html, css/main.scss, document-types.html
Very experimental.
Shows a list of document types on GOV.UK, along with examples and information about applications.
Data from: https://github.com/alphagov/content-store/tree/add-stats-task
=> Add document types documentation

document-types.html
This makes it easier to navigate. Also allows deeplinking with anchors.
=> Add table of contents for document types

.gitignore, Gemfile, Gemfile.lock, README.md, Rakefile, config.rb, config.ru, docs/index.html
We can't use the crown & font on non-gov.uk sites. Hosting on Heroku allows us to use HTTP auth.
Also brings us awesomeness like auto-deploying review apps for each PR.
=> Configure for Heroku hosting

config.rb, lib/external_doc.rb, source/apis/search-api.html.md.erb, source/layouts/api_layout.html.erb
This PR adds pulls in the rummager documentation page for the search API.
https://github.com/alphagov/rummager/blob/master/docs/search-api.md
I think this is probably the most useful page for rummager. I've considered also pulling in pages like [indexing](https://github.com/alphagov/rummager/blob/master/docs/documents.md) docs, but they seem less complete at the moment. Perhaps we can start with this page and see how it's used?
Thoughts @MatMoore?
=> Pull in rummager's search documentation

config.rb, helpers/navigation_helpers.rb, lib/external_doc.rb, lib/publishing_api_docs.rb, source/apis/publishing-api.html.md.erb, source/index.html.erb, source/layouts/api_layout.html.erb, source/layouts/default.erb, source/partials/_header.html.erb, source/partials/_source.html.erb, source/publishing_api_template.html.md.erb
This adds the documentation for the publishing-api docs.
The list of pages to import is hard coded. I've considered using the GitHub API to fetch everything in the `/doc` directory. The downside to that is that if pages are renamed, we'll inadvertently break the pages here. Having a local list here allows us to set up redirects.
https://trello.com/c/aW1dfqD3
=> Add docs for publishing-api

Gemfile, Gemfile.lock, Rakefile, config.rb, config/tech-docs.yml, helpers/properties_table_helpers.rb, lib/content_schemas/content_schema.rb, source/content-schemas.html.md.erb, source/layouts/schema_layout.erb, source/schema_template.html.md.erb
This PR adds documentation for the [govuk-content-schemas](https://github.com/alphagov/govuk-content-schemas).
https://trello.com/c/B7iFo5SN/2-create-documentation-for-content-schemas
=> Add schema documentation

README.md, app.json, config/tech-docs.yml, docs/index.html, source/application_template.html.md.erb, source/index.html.erb
This site is now publicly available on https://docs.publishing.service.gov.uk. The repo name was updated to better communicate the repo's intent.
=> Use docs.publishing.service.gov.uk & govuk-developer-docs

Rakefile, data/applications.yml, data/dashboard.yml, lib/app_docs.rb, lib/dashboard/dashboard.rb, source/apps.html.md.erb, source/layouts/application_layout.html.erb
This PR updates the "Application" pages.
- Adds an explanation of GOV.UK frontend & publishing apps
- Adds missing applications (+ rake task to keep it in sync with puppet)
Best reviewed per-commit and with the preview on Heroku: 
https://govuk-tech-docs-pr-25.herokuapp.com/
=> Update the applications pages

data/applications.yml
Signonotron2 is now called "signon" :gift_heart:.
=> Fix signon repo name

config.rb, config/tech-docs.yml, lib/document_types.rb, source/document-types.html.md.erb, source/document_type_template.html.md.erb, source/layouts/document_type_layout.html.erb
This adds pages for all document types in the search index.
We've recently started indexing these (thanks @alecgibson & @carvil), so not all pages in the index have document types yet.
The user need for these pages is that we'd like to start creating a canonical list of document types. This will allow us to make groupings (like "publication" or "announcement") consistently across the site.
Review here: https://govuk-tech-docs-pr-30.herokuapp.com/document-types.html
cc @jennyd 
https://trello.com/c/EfrOXi9L
=> Add document type pages

config.rb
- The no_intra_emphasis option for the markdown renderer is now set to
true, which stops the renderer from trying to parse the inside of words.
- Without this setting, words with underscores in the middle of them cause
the formatting to be incorrect.
=> Configure markdown renderer option to not use intra-word emphasis

lib/document_types.rb
We currently have to make one request per document_type to find the example pages for each type.
Since https://github.com/alphagov/rummager/pull/743 we can request examples for each facet. This saves us a lot of requests when building the pages.
cc @rubenarakelyan
=> Simplify document types

lib/dashboard/github.rb, source/index.html.erb, source/layouts/api_layout.html.erb, source/layouts/application_layout.html.erb, source/layouts/document_type_layout.html.erb, source/layouts/layout_with_sidebar.erb, source/layouts/schema_layout.erb
This extracts the layout for the sidebar into a common layout, so we don't have to repeat ourselves so much.
=> Extract the sidebar HTML into shared layout

config.rb, source/layouts/header_footer_only.erb
This makes sure that all pages have the correct page titles and `<title>` tags.
=> Use correct and consistent titles

Gemfile, Gemfile.lock, config.rb, source/error.html.erb, source/templates/publishing_api_template.html.md.erb
This adds a sitemap.xml to make it easier for Google to index all pages on the site.
Will be visible on:
https://docs.publishing.service.gov.uk/sitemap.xml
This ignores the error page, the rest will be indexed.
=> Add sitemap.xml for search indexes

config/tech-docs.yml
This adds a GA tracking code, so that we can see how many people are visiting the site.
=> Add Google Analytics

Gemfile.lock, config.rb, config/tech-docs.yml, source/guides.html.md.erb
The new A/B testing method using Fastly is a fairly complicated system that touches a few parts of a stack. This is an attempt at a guide for developers that want to use the system.
This is the first "guide" on the docs site. The idea is that this is a more appropriate place than the opsmanual (which is closed and only accessible via the VPN) and the wiki (which is closed and not user friendly). Feedback welcome on that too.
I've copied most from https://gov-uk.atlassian.net/wiki/pages/viewpage.action?pageId=128385031 by @suzannehamilton. We should probably replace that page with this.
https://trello.com/c/bh7iFV7G
=> Add guide to A/B testing

config/tech-docs.yml, data/dictionary.yml, source/dictionary.html.md.erb, source/layouts/dictionary_layout.erb
- This adds a page containing the content of the dictionary that is
currently on the GOV.UK wiki.
[Trello card](https://trello.com/c/gn40a8Yn/18-add-dictionary-with-core-concepts-on-gov-uk)
=> Add a page for the dictionary

source/guides.html.md.erb, source/guides/_taxonomy.html.md.erb
This is a first pass at a page to explain the technical stuff behind the taxonomy.
It's intended for GOV.UK developers that are interested in using the taxonomy, like @pmanrubia and @tomnatt currently.
I *think* that it makes sense for a page like this to exist on this site, rather than say content-tagger, because it's a concept that touches many apps on GOV.UK - content-store, rummager, content-tagger, publishing-api and soon publishing apps and collections.
Thoughts? @pmanrubia @tomnatt @MatMoore @carvil  
**Preview**: https://govuk-tech-docs-pr-46.herokuapp.com/guides.html#taxonomy
=> Add page about the taxonomy

source/dictionary.html.md.erb
These should point at the YAML file that contains the dictionary
content instead of the source file for the dictionary page.
=> Change the urls for viewing and editing the dictionary source

data/applications.yml
Mostly taken from
https://gov-uk.atlassian.net/wiki/display/GOVUK/Product+group+structure+and+details
and
https://gov-uk.atlassian.net/wiki/display/CT/GOV.UK+Content+Tools
=> Add Content Tools to repos they own

config.rb, data/applications.yml, lib/app_docs.rb, lib/dashboard/dashboard.rb, source/apps.html.md.erb, source/layouts/application_layout.html.erb, source/templates/application_template.html.md.erb
Setting `retired: true` for an application will:
- Hide it from the dashboard
- Hide it from the sidebar on the applications page
- Doesn't count it in lists of active apps
- Shows "(retired)" in the page title, shows a link to gds-attic repo
Also marks panopticon as retired - https://trello.com/c/dGPNmVub/482-retire-panopticon
=> Allow apps to be marked "retired"

source/templates/application_template.html.md.erb
"This application is retired." is currently showing everywhere.
=> Fix bug in showing which repos are retired

data/dashboard.yml
This repo still has the old name for the gem (govuk_schemas_gem instead
of govuk_schemas) which is stopping the homepage from displaying.
=> Update name of govuk_schemas gem

source/guides/_taxonomy.html.md.erb
Add a bit more detail on the rummager fields and link to the taxonomy helpers gem.
Trello https://trello.com/c/OaHe7Ylt/514-document-taxon-fields-in-rummager
Replaces https://github.com/alphagov/rummager/pull/758
=> Expand taxonomy guide and link to the taxonomy gem

helpers/url_helpers.rb, lib/supertypes.rb, source/document-types.html.md.erb, source/templates/document_type_template.html.md.erb
Supertypes are groupings of document types. A good example of this is the concept of "announcement" (which groups document types like news and speeches) and "publication" (which encompasses things like guides and policy).
The types are taken directly from the gem.
https://trello.com/c/07lAcDtC
=> Add documentation for document "supertypes"

source/apis/content-store.html.md.erb, source/layouts/api_layout.html.erb
This is intended as the start of documenting the data we expose
externally via the public /api/content endpoint; putting it in the
developer docs for now for want of a better place.
Obviously there is some overlap with the schemas documentation which
already exists, but the audience is different.
=> Documentation for the content-store api.

lib/app_data.rb, lib/app_docs.rb, source/templates/application_template.html.md.erb
This adds a list of pages published or rendered to the application pages.
This data is fetched from the search API. Unfortunately most of the `rendering_app`/`publishing_app` is still missing, so not all pages will have the examples.
=> Add example pages for apps

lib/document_types.rb, source/document-types.html.md.erb, source/layouts/document_type_layout.html.erb, source/templates/document_type_template.html.md.erb, spec/fixtures/allowed-document-types-fixture.json, spec/lib/document_types_spec.rb
Since https://github.com/alphagov/govuk-content-schemas/pull/550 there's a central list of allowed document types. By using this list we add the types that aren't currently in the search index.
=> Show all document types

bin/deploy-to-s3
We currently keep on deploying even if middleman fails. This is causing 404s on the homepage sometimes.
=> Stop deploys on error

data/applications.yml
This commit changes the status of business-support-finder to "retired" and adds some details of its replacement.
Trello: https://trello.com/c/9O34PdXb/547-remove-business-support-finder-application
=> [DO NOT MERGE] Change business-support-finder to "retired"

config.rb, config/tech-docs.yml, source/guides.html.md.erb, source/opsmanual.html.erb, source/opsmanual/ab_testing.html.md.erb, source/opsmanual/taxonomy.html.md.erb
This adds an "Opsmanual" section to the docs. We intend to move the current opsmanual into here (first PR for that is https://github.com/alphagov/govuk-developer-docs/pull/72). I've also moved the two guides into the new section.
=> Add an "Opsmanual" section to the docs

config.rb, lib/supertypes.rb
https://github.com/alphagov/govuk-developer-docs/pull/73 broke the site, because contrary to middleman's readme we shouldn't be using leading slashes.
https://trello.com/c/5x8NHLhf
=> Fix redirect from guide to opsmanual

source/opsmanual/keeping-software-current.html.md
We currently have some documentation in the confluence wiki. We'd like to move most of this to this site, so that it's easier to find.
This page comes from:
https://gov-uk.atlassian.net/wiki/display/TECH/Keeping+GOV.UK%27s+software+current.
I've removed some outdated bits.
https://trello.com/c/RfRRgVqU
=> Add "Keeping software current"

lib/tech_docs_html_renderer.rb
Documents imported from the [publishing-api/docs](https://github.com/alphagov/publishing-api/tree/master/doc) folder have a table-of-contents which doesn't work here.
The documents are published on github, and made available here.
Due to a mismatch in Markdown -> HTML rendering between Github and
Middleman/Redcarpet, generated fragment IDs are created using a
different algorithm.
In this PR, I override the default Redcarpet `header` function to
make it use a Github flavoured ID scheme.
[Trello](https://trello.com/c/Re6fSBKj/24-change-internal-links-to-work-or-remove-internal-links)
=> Fix issue with in-document links

source/opsmanual/content-preview.html.md
This will replace:
https://github.gds/pages/gds/opsmanual/2nd-line/applications/content-preview.html
For the desks of @kevindew or @danielroseman.
https://trello.com/c/ZErfvzXs
=> Add "Content Preview" documentation

lib/tech_docs_html_renderer.rb
https://github.com/alphagov/govuk-developer-docs/pull/77 fixed the headings, but had a small bug.
Previously tried to fix in https://github.com/alphagov/govuk-developer-docs/pull/82.
=> Fix bug in header

lib/app_docs.rb, lib/github.rb, source/opsmanual/github.html.md.erb, source/partials/_source.html.erb, source/templates/application_template.html.md.erb
Topics are tags for repositories (https://github.com/blog/2309-introducing-topics). 
We've tagged most of the GOV.UK repos with `govuk` now. This page explains that, and links to other topics that have been used. Also shows the topics on the application pages.
https://trello.com/c/CdGSaozQ
=> Add page with GitHub topics + show topics on app pages

source/templates/application_template.html.md.erb
Retired apps may not have repositories.
=> Only show topics on non-retired apps

source/opsmanual/kibana.html.md
This is a rewrite of the Useful Kibana Queries page in the opsmanual:
https://github.gds/pages/gds/opsmanual/2nd-line/kibana.html
It needed to be rewritten because the table structure didn't properly convert from .rst to markdown.
I've use Ruby as the syntax highlighter because it looks nice.
 👉 https://govuk-tech-docs-pr-86.herokuapp.com/opsmanual/kibana.html
=> Port the Useful Kibana Queries page

Jenkinsfile, helpers/url_helpers.rb, lib/publishing_api_docs.rb, lib/source_url.rb, source/apis/search-api.html.md.erb, source/apps.html.md.erb, source/index.html.erb, source/layouts/api_layout.html.erb, source/layouts/application_layout.html.erb, source/layouts/getting_started_layout.html.erb, source/layouts/layout_with_sidebar.erb, source/layouts/opsmanual_layout.html.erb, source/opsmanual/dictionary.html.erb, source/partials/_source.html.erb, source/stylesheets/screen.css.scss, source/templates/application_template.html.md.erb, spec/lib/source_url_spec.rb, spec/spec_helper.rb
This PR:
- Adds a consistent link to `View source` at the bottom of all pages. For simplicity the direct edit link is removed. The link is either determined by the `page` local, the `source_url` in frontmatter or the source file in this repo.
- Adds a link to the GitHub issues with the title & url prefilled. This will allow users to easily report problems with a page.
---
=> Improve linking to GitHub

config.rb, data/redirects.yml
The dictionary was moved into the opsmanual section, but is linked from the wiki.
=> Add a redirect for the dictionary page

spec/app/app_docs_spec.rb, spec/app/content_schema_spec.rb, spec/app/document_types_spec.rb, spec/app/external_doc_spec.rb, spec/app/github_spec.rb, spec/app/source_url_spec.rb, spec/app/supertypes_spec.rb
The generated `.rspec` file contains `--require spec_helper` which will cause this file to always be loaded, without a need to explicitly require it in any files.
=> Only require the spec helper once

app/applications_by_team.rb, config.rb, data/applications.yml, source/apps/by-team.html.md.erb, source/layouts/application_layout.html.erb
First draft of a section to look at applications sorted by owning team.
[Trello](https://trello.com/c/bM1an40m/48-make-it-easy-to-determine-ownership-of-a-repo-project)
=> Add ownership by team to applications section

source/manual/changing-organisation-slug.html.md, source/manual/create-a-gpg-key.html.md, source/manual/elasticsearch-dumps.html.md, source/manual/encrypted-hiera-data.html.md, source/manual/jenkins-ci.html.md, source/manual/mongodb.html.md, source/manual/releasing-software.html.md, source/manual/remove-machines.html.md
A few pages still had the layout as "opsmanual_layout" and the page
parent as the opsmanual instead of the new names for these. This was
causing the build to fail and these pages not to display.
=> Replace all mentions of opsmanual_layout

data/dashboard.yml
Add govuk_elements_rails - a gem wrapper around govuk_elements
and govuk_frontend_toolkit_npm, a npm package for alphagov/govuk_frontend_toolkit
=> Add shared frontend repos

Gemfile, Gemfile.lock
This will prevent the build from failing on a new regex.
=> Bump govuk_schemas gem

app/developer_docs_renderer.rb, app/requires.rb, config.rb, lib/tech_docs_html_renderer.rb
To keep our application specific code seperate from the template app,
we are trying to keep our changes in the /app folder.
=> Move dev-docs specific changes to the HTML renderer out of /lib

source/layouts/application_layout.html.erb
The `githubify_fragment_id` functionality moved to the `DeveloperDocsRenderer` class in
https://github.com/alphagov/govuk-developer-docs/pull/101.
cc @whoojemaflip
=> Fix bug in apps page

config.rb, lib/page_freshness.rb, source/layouts/layout_with_sidebar.erb, source/manual.html.erb, source/manual/ab-testing.html.md, source/manual/alerts/asset-master-attachment-processing.html.md, source/manual/taxonomy.html.md, source/partials/_source.html.erb, source/stylesheets/screen.css.scss
This adds a system to keep track of pages that need to be updated.
- Every page can have a `expire_by` and `owner_slack` attribute
- When its set we will show this information at the bottom of the page
- A week before the page is set to expire, the page title appears under "Pages to be reviewed soon" on the manual homepage
- After the page is expired the page with display a warning on the top of the page indicating that it may no longer be accurate
- The expired page is also listed under "Expired pages" on the manuals page
---
https://trello.com/c/ZUd0ITTZ
=> Implement periodic review system

lib/page_freshness.rb, source/api/page-freshness.json.erb, spec/app/page_freshness_spec.rb
This JSON endpoint can be called by a hypothetical bot that announces soon to expire pages to Slack.
https://trello.com/c/ZUd0ITTZ
=> Add an "API" for page freshness

source/layouts/manual_layout.html.erb, source/stylesheets/screen.css.scss
The pages in the "Icinga alerts" section [like this one][1]  are linked from the Icinga UI:
However, when you visit the page the context isn't really made clear. 
This PR adds a block to 1) communicate that this is a page that deals with a specific alert, 2) links back to govuk-puppet, so that the user can find out what triggered the alert. See [these search results for example][2].
cc @nickcolley @fofr because I'm randomly adding a new UI element here, what do you think?
[1]: https://docs.publishing.service.gov.uk/manual/alerts/rabbitmq-high-watermark.html
[2]: https://github.com/alphagov/govuk-puppet/search?utf8=%E2%9C%93&q=rabbitmq-high-watermark
=> Make context of Icinga alert pages clearer

source/layouts/layout.erb, source/layouts/layout_with_sidebar.erb
This disables the automatic updating of the URL with the current fragment (/index.html#something) and the automatic highlighting in the sidebar. The in-page nav was designed for large pages like the PaaS docs (https://docs.cloud.service.gov.uk).
I've found that because we have very small pages, the URL updating is a bit distracting and doesn't add much. It also auto-updates on load, which will change the URL immediately. I've found myself removing the
fragment a lot when sharing a particular page.
Note that this doesn't prevent people from sharing specific headings, that's still possible.
=> Disable the in-page navigation

Gemfile, Gemfile.lock, app/app_docs.rb, app/dashboard.rb, app/external_doc.rb, app/github_repo_fetcher.rb, app/publishing_api_docs.rb, source/apis/search-api.html.md.erb, source/getting-started.html.md.erb, source/templates/publishing_api_template.html.erb, spec/app/external_doc_spec.rb, spec/app/github_repo_fetcher_spec.rb, spec/fixtures/markdown.md
Adds a number of filters that ensure external markdown docs render correctly:
- Loads external sources
- Rewrites relative links to work in this context
- Rewrites links to other markdown links to their dev docs equivalent
We have had to duplicate some of the TOC logic as this is only applied to markdown templates. Ideally we could do this for all ERB templates.
https://trello.com/c/nGPt3dpG
=> Fix doc urls

source/manual/where-to-find-what.html.md
In this page we write down the new "system" for docs on GOV.UK. Its purpose is to show where things should live.
=> Add page about where to find what documentation

app/app_docs.rb, source/templates/application_template.html.md.erb
Link to Grafana dashboard from app pages.
Include warning that not all apps have dashboards. Once the an internal Grafana hostname has been configured, the plan is to only show this link if a dashboard has been created for that application.
https://trello.com/c/6954MV1K/48-link-to-dashboards-from-app-pages-in-the-developer-docs
=> Add links to application deployment dashboards

app/manual_index_page.rb, config.rb, lib/page_freshness.rb, source/api/page-freshness.json.erb, source/manual.html.erb, source/stylesheets/screen.css.scss, spec/app/manual_index_page.rb
This is an attempt at a new index page for the manual. We currently show all pages in the sidebar. 
The goal of this version is to make it easy to understand the "shape" of all the documentation we have and to make it easy to scan the pages.
Feedback very welcome. 
👉 https://govuk-tech-docs-pr-131.herokuapp.com/manual.html
=> New manual index page

source/manual/dns.html.md
Make clear that Google Cloud credentials are not required.
=> Update DNS docs slightly

source/manual/deploying.html.md, source/manual/jenkins-ci.html.md, source/manual/tools.html.md
Adds an `On the blog` section to the bottom of these pages, with a link to a relevant article on the [GDS technology blog](https://gdstechnology.blog.gov.uk/)
=> Link to gds tech blog

data/applications.yml
This keeps it consistent with other apps maintained by Content History team since that's all done with the Holding Government to Account grouping
=> Move Link Checker to HGTA

source/apis/link-checker-api.html.md.erb, source/layouts/api_layout.html.erb
Imports [https://github.com/alphagov/link-checker-api/blob/master/docs/api.md] into the docs
Also re-orders the API layout sidebar to be alphabetical.
These don't quite render correctly (the `<details>` disclosures) because of a lack of parity with the end-of-life github-markdown and common mark that github uses now. This will be fixed when https://github.com/jch/html-pipeline/pull/274 is merged into https://github.com/jch/html-pipeline - or if we want to use it sooner I have [a branch](https://github.com/alphagov/govuk-developer-docs/tree/commonmark) using that rendering
=> API docs for Link Checker API

source/manual/add-deployment-dashboard.html.md
- Fix name of `has_workers` deployment dashboard parameter
- Fix typo in deployment dashboard parameters
- Add documentation for new deployment dashboard parameters
https://trello.com/c/lVNtP9A4/47-hide-errors-by-controller-and-slow-responses-by-controller-graphs-on-dashboards-where-they-have-no-data
=> Update deployment dashboard parameter docs

source/manual/testing-projects.html.md
Makes it clearer that `govuk.buildProject()` is the preferred way of working.
=> Update page about testing projects

source/manual/elasticsearch-dumps.html.md
This was a typo, causing the page to be uncategorised.
=> Fix section tag for elasticsearch page

source/manual/deployment-dashboards.html.md, source/manual/tools.html.md
Fix a typo and add a couple of links to help people find the deployment dashboards.
=> Add deployment dashboard links

data/dashboard.yml, source/index.html.erb, source/layouts/layout.erb, source/layouts/layout_with_sidebar.erb, source/manual.html.erb, source/partials/_search.html.erb, source/stylesheets/modules/_search.scss, source/stylesheets/screen.css.scss
- Aligns grid columns by adding `grid-row` class
- Adds label to search input for assistive tech
- Moves search input into the navigation so it uses the same padding and aligns, means it's hidden in the table contents dropdown smaller screens though 🤔 
- Update team tools sub heading so the IDs do not conflict
Before:
After:
---
Before:
After:
---
Before:
After:
=> A11Y, Spacing fixes

config/tech-docs.yml
The navigation bar contains too many things, making it wrap at ~1200px.
This changes the words to make it more compact. The page can now be viewed at ~1000px and not wrap.
=> Make navigation more compact

source/manual/heroku.html.md
heroku.gpg has moved to /2ndline.
I don't know if there's any other documentation we can link to here about using gpg.
=> Correct link to deployment repo

source/layouts/manual_layout.html.erb, source/manual.html.erb, source/manual/dictionary.html.erb, source/manual/review-page.html.md
Manual is probably vague enough to accommodate all uses. Allows us to circumvent discussions around the naming of this particular section of the docs.
Supersedes https://github.com/alphagov/govuk-developer-docs/pull/144.
=> Use "manual" throughout

source/manual/deploying.html.md
Updated to reflect that 'GOV.UK Release Calendar' needs to be added as a guest (rather than as a room).
=> Update deploying.html.md - guest not room

data/redirects.yml
- Google has indexed the old URL (`manual/virus-scanning.html`) and so
it 404s. Redirect to what appears to be the actual page.
=> Add a redirect for the virus scanning page that Google has indexed

source/manual/deploying.html.md
=> Correct the syntax for a link text

source/manual/create-a-gpg-key.html.md
Port number is required to send the user to the search page for that particular key server.
Also added a link to an overview about GPG key server pools.
=> Change GPG Key server address

source/manual/cdn.html.md
Specifies that the logging isn’t configured using VCL or other script.
=> Add some information about Fastly logging

data/dashboard.yml, source/manual/retiring-an-application.html.md, source/manual/setting-up-new-rails-app.html.md, source/manual/setting-up-new-sidekiq-monitoring-app.html.md
The development VM repo has moved from github.gds to a subdirectory of govuk-puppet, so replace links to github.gds/gds/development with links to https://github.com/alphagov/govuk-puppet/tree/master/development-vm.
There's still one link to the old repo because it's to a PR. I don't think there's an equivalent PR in the new repo yet: https://github.gds/gds/development/pull/149
=> Update links to development VM

source/manual/monitor-sidekiq-workers.html.md, source/manual/setting-up-new-sidekiq-monitoring-app.html.md, source/manual/sidekiq-retries.html.md
These got lost in the move from the opsmanual
=> Add monitoring of sidekiq workers docs

source/manual/emergency-publishing-redis.html.md
Whitehall uses memcached. The document originally suggested reloading
whitehall to clear the cache. This does not work since reloading Whitehall is done gracefully. Restarting memcached on whitehall-frontend machines clears whitehall-frontend caches properly since at the time of writing, memcached does not persist the cache between restarts (https://github.com/memcached/memcached/wiki/ProgrammingFAQ#can-you-persist-cache-between-restarts).
Also add some information about testing with cache-bust strings.
=> Correct information about clearing whitehall cache

source/manual/monitor-sidekiq-workers.html.md
The information about the NGINX configuration was incorrect, we have one NGINX Server Block and run a `Sidekiq::Web` process for each GOV.UK Sidekiq application we want to monitor – https://github.com/alphagov/sidekiq-monitoring
Also removes unnecessary detail about some of the technologies used to make this work.
=> Improve Sidekiq monitoring docs

app/search_api_docs.rb, source/apis/search/fields.html.md.erb, source/apis/search/search-api.html.md.erb, source/layouts/api_layout.html.erb
This is a first stab at making the documentation better for rummager. I've added an autogenerated list of document fields.
This pulls descriptions out of the JSON file that configures the rummager schema.
I've also put a notice on the search api page itself as it's quite wordy and hasn't been updated for a long time. I'd like to split this information out into shorter pages, eg a quickstart for using the api, and a guide to using filters and facets.
I'm also wondering if the README itself would make a better landing page for the search API?
https://github.com/alphagov/rummager/blob/master/README.md
=> Document search field definitions

app/snippet.rb, helpers/meta_tag_helpers.rb, source/layouts/manual_layout.html.erb, spec/app/snippet_spec.rb
The manual pages currently fall back to the default description "Documentation for developers working on GOV.UK". That's not super informative.
This generates a 300 character snippet from the page HTML. The goal is to generate a representative piece of text from the body, so:
- Only text after the h1 (to skip the "This page was imported" text)
- No HTML
- No headings
=> Generate nicer snippets for sharing

app/manual_index_page.rb
Redirects are also showing up on the homepage. Because they don't have a title they're displayed as an empty list item. This commit makes sure we don't include things without titles. This then enables us to be less defensive in the `sort_by` block.
=> Stop redirects from showing up on manual page

helpers/meta_tag_helpers.rb
When sharing docs, this makes it easier to see what the page is about. If there's no `section`, nothing will be shown.
=> Show page section in page title

app/snippet.rb, spec/app/snippet_spec.rb
Characters like quotes are escaped in this payload, but also when they're inserted into the page (with the `tag` helper). By unescaping here we avoid showing html entities to users:
=> Avoid double encoding in snippets

data/applications.yml
Mark the `business-support-api` as retired and add a description of what it used to do.
=> Retire business-support-api

source/manual/upgrade-rails.html.md
We have forked airbrake and made a branch from the last release of 4.x that includes a fix to silence the deprecation warnings you get when using rails 5 and airbrake 4.x.  This way we can keep the deployment recording functionality in errbit.
=> Suggest using our airbrake fork when upgrading to rails 5

source/manual/troubleshooting-vagrant.html.md
There's a bug in the nfs implementation of macOS Sierra which means we will get permissions errors when running govuk_puppet.  Advice in https://github.com/mitchellh/vagrant/issues/8061 is to run `ls -alR > /dev/null` on the host before running the VM to refresh the cache.  Hopefully a future macOS Sierra update will fix this.
=> Add note about nfs permissions error on macOS Sierra

source/manual/hmrc-paye-files.html.md
- Fix a typo
- Fix the cache purge instructions. **It'd be good to get another opinion on this in case I've misunderstood it.**
- Update the links to the related mainstream content
- Add note about manifest version numbers in instructions
- Update review date and remove review notice. (Since we've just updated the PAYE tool following these instructions and everything worked as expected.)
=> Update HMRC PAYE upload instructions

data/applications.yml, source/apis/content-store.html.md.erb
specialist-frontend was used to render specialist documents. Those were moved to government-frontend in April 2017.
Part of https://trello.com/c/UM7aecOQ/194-final-stage-decomission-specialist-frontend-2
=> Mark specialist-frontend as retired

app/search_api_docs.rb, source/apis/search/fields.html.md.erb
- Github URLs contain /blob/
- It's helpful to see similar kinds of fields together
=> Correct source URL and sorting to rummager fields reference

source/manual/deploy-fixes-for-a-security-vulnerability.html.md, source/manual/deploying.html.md, source/manual/github-enterprise.html.md, source/manual/github-unavailable.html.md
Update the github enterprise docs and add a guide for using it to deploy security fixes.
This is completely made up by me, so please flag anything that looks like the wrong thing to do.
The domain for GHE is changing on Thursday so I've updated the links as well. Don't merge until then.
Trello: https://trello.com/c/w2yA4dy6/60-document-how-to-deploy-security-fixes-action-item-from-2nd-line-incident
=> Document GitHub enterprise deploy

source/manual/copying-data-locally.html.md, source/manual/replicate-app-data-locally.html.md, source/manual/troubleshooting-vagrant.html.md
Info about syncing data locally was spread about a bit. There's now a new guide in the developer docs about it (see: alphagov/govuk-puppet#5909), so this is just to minimise the info in the Getting Started guide, and link off to the new one.
=> Move DB sync info to a new guide

source/manual/deploying.html.md
We are experimenting with slotless deployment and this is an updated process.
The old process should be removed if / when we decide to adopt the new one
permanently.
=> Update the deployment process

source/manual/deploying.html.md
https://www.gov.uk/service-manual/design/dates#how-to-write-dates
=> Follow design community guidance for dates in deploying manual

source/manual/upgrade-rails.html.md
There's a change to schema dumper in Rails 5.1 which generates noisy diffs in a post upgrade migration.
Detailing this gotcha as including a regenerated `db/schema.rb` file might be simpler.
=> Detail schema dumper changes in Rails 5.1

source/manual/dns.html.md
As part of the migration from GHE move govuk-dns-config to a github private repo
=> Update URL for the dns-config repo to github.com

source/manual/ab-testing.html.md
- Add Google Analytics instructions for A/B tests
- Document the changes to A/B test deployment, which make it easier to activate A/B tests and update the B percentage.
https://trello.com/c/HOV2ChJ9/104-simplify-a-b-test-cdn-configuration
Marked as DO NOT MERGE until alphagov/govuk-cdn-config#53 is merged.
=> Explain how to configure Fastly dictionaries in A/B tests

source/manual/emergency-publishing.html.md
The page mentioned that the types of events would be detailed below. The information was half way down the page, in the section for cache busting. It's useful to know about these event types at the beginning of the process, so this commit copies that information into the prerequisites sections. Also remove some redundant wording.
=> Update Emergency Publishing docs

data/applications.yml, source/manual/creating-a-new-environment.html.md, source/manual/tools.html.md, source/manual/vpn.html.md
The [`content_api`](https://github.com/alphagov/govuk_content_api) has
been retired, and all content has been migrated to the
[`content_store`](https://github.com/alphagov/content-store).
Therefore, we can remove all references to the Content API, and rely
solely on the Content Store.
https://trello.com/c/TsUsUwD7/153-remove-documentation-on-content-api
=> Remove references to the Content API

source/manual/setting-up-new-rails-app.html.md
Changed it to the current position of the template which is:
https://github.com/alphagov/govuk-rails-app-template/blob/master/templates/config/initializers/airbrake.rb
=> Fix url for airbrake template

data/redirects.yml, source/manual/alerts/publisher-app-healthcheck-not-ok.html.md, source/manual/alerts/whitehall-app-healthcheck-not-ok.html.md
This tries to make the alerts related to /healthcheck fails more consistent. It's a big can of worms deciding whether the compound or non compound usage of "health check" makes sense, but this just takes the lead from https://github.com/alphagov/govuk-developer-docs/blob/master/source/manual/alerts/app-healthcheck-failed.html.md
Related to https://github.com/alphagov/govuk-puppet/pull/5985
=> Healthcheck usage

source/manual/troubleshooting-vagrant.html.md
OpenConnect reference link on `Troubleshooting Vagrant` page was broken. Previous changes had explicitly set the address on the link used in the body of the page, but the reference should be fixed instead.
=> Fix OpenConnect reference link

source/getting-started.html.md.erb
This should link to the puppet repo so the "View source" page works.
=> Link to the correct source for Get started page

source/manual/elasticsearch-dumps.html.md, source/manual/retiring-an-application.html.md
The env-sync-and-backup repository is now in github (rather than GHE).
This updates links to use its new location: https://github.com/alphagov/env-sync-and-backup
=> Use private env-sync-and-backup repo

source/manual/elasticsearch-dumps.html.md
I want to make sure we can follow this guidance for managing GOV.UK
search (the api-elasticsearch cluster) so I've assigned our team as
owner.
I think this is still out of date for logs-elasticsearch because we now
store snapshots on s3 using
https://www.elastic.co/guide/en/elasticsearch/reference/1.7/modules-snapshots.html
but I've left it out of this PR.
Review this in 3 months because we're likely to setup s3 backups for
api-elasticsearch too at some point.
=> Update elasticsearch backup guidance

source/manual/deploying.html.md
Removing the badger deployment documentation as we've now properly switched over and tidied up the page.
=> Update deployment process for slotless deployment

data/redirects.yml
This file was renamed during https://github.com/alphagov/govuk-developer-docs/pull/260/files
This commit aims to redirect the page to the location.
=> Redirect offsite back to new file

source/manual/retiring-an-application.html.md
More specifically:
- updated point on DNS changes;
- added an extra point on unpublishing relevant content.
Trello: https://trello.com/c/2MF97xce/154-retire-content-api
=> Update docs on retiring an application

data/dashboard.yml
This has moved to the attic, which breaks the build:
https://deploy.publishing.service.gov.uk/job/govuk-developer-docs/1730/console
=> Remove link to ci-puppet

source/manual/alerts/search-benchmarking.html.md, source/manual/alerts/search-spelling-suggestions.html.md
Remove warning about weekend failures on integration. These jobs have now been configured to only run on weekdays, so weekend failures should no longer occur.
Set a review date for three months' time because we expect to make changes to the search benchmarking in the next quarter.
=> Review docs on search benchmark alerts

source/manual/ab-testing.html.md
Multivariate testing using JS is being deprecated in govuk_frontend_toolkit:
https://github.com/alphagov/govuk_frontend_toolkit/pull/420
This avoids the risk of developers creating AB tests that are not accessible.
cc @carvil
=> Update AB testing documentation

source/manual/monitor-sidekiq-workers.html.md
The Grafana dashboard doesn't show as much information as Sidekiq::Web, but it is handy for quickly viewing multiple queues and it allows you to view historical queue lengths.
Also clean up trailing whitespace in a separate commit.
=> Add link to Grafana dashboard for Sidekiq monitoring

source/manual/fall-back-to-mirror.html.md
Update documentation to reflect changes in GOV.UK mirror configuration:
- A new S3 backend has been added
- Skyscape VCloud mirror has been decommissioned
=> Update mirrors documentation

data/redirects.yml, source/manual/cdn.html.md, source/manual/on-call.html.md, source/manual/pingdom-bouncer-canary-check.html.md, source/manual/side-by-side-browser.html.md
This fixes a number of pages that are currently 404'ing. Their sometimes caused by old links and incorrect relative links.
Found using kibana:
```
@fields.http_host:"docs.publishing.service.gov.uk" AND
@fields.status:404
```
=> Fix common 404

source/manual/alerts/reboot-required-by-apt.html.md
From the existing documentation it isn't clear that the list of apps that require rebooting is actually in the check. This commit adds a line to that effect.
=> Update reboot required docs

source/manual/alerts/ntp-drift-too-high.html.md
I ran the `ntp.status` job on integration and it looked fine. I haven't tested `ntp.resync` but it looks correct.
=> Review NTP drift docs

source/manual/alerts/virus-scanning.html.md
Two of the links in this guide were broken because they linked to the old Ops Manual. To fix this, copy two sections from https://github.digital.cabinet-office.gov.uk/attic/opsmanual/blob/master/2nd-line/applications/whitehall.rst:
- Background on how attachments are uploaded and processed by the ClamAV virus scanner
- Instructions on how to bypass the queue and publish all clean files immediately
---
I've tested that the links work and that the directories still exist. I haven't actually tested the command to process the backlog.
I'd appreciate a review from someone who knows about asset uploading - the content I've copied from the ops manual is very whitehall-specific but it sounds like it might apply to other publishing apps too. Is that right?
=> Add instructions on processing virus scanning queue

source/manual/deploying.html.md
The badgerless deploy scheme appears to be fine, so we'll increase the review
period to 3 months rather than 1.
=> Deployment docs review

app/publishing_api_docs.rb
The files in the `doc` directory of publishing-api currently need to be hardcoded into this repo. While this isn't ideal, this PR is just a quick fix to get all the publishing-api docs displaying for now.
=> Add admin-tasks.md to the publishing-api docs

data/applications.yml
We should also be using Slack usernames and channel names here so that people can easily find the correct person/team to ask about things.
Changes:
- Luke has taken over from Holly
- Transition & Bouncer are now in the taxonomy team
- The status of `collections` is unclear at the moment, more news later
=> Update apps from taxonomy team

source/manual/alerts/es-rotate.html.md
Add an internal link to the Elasticsearch cluster health docs and bump up the review date.
=> Review the es-rotate alert docs

app/app_docs.rb, data/applications.yml, source/templates/application_template.html.md.erb
Several applications have APIs which are documented separately. Make it easier for users to find docs for the relevant API from the application page.
Joe L was looking for the content-store API docs yesterday and couldn't find them from the app page. It would also have helped me when I was first using the docs - I didn't realise there were separate API docs.
=> Add links from app pages to API docs

source/manual/alerts/virus-scanning.html.md
We had an issue on 2nd line where documents were taking 2+ hours to scan for
viruses.  This adds instructions to the virus scanning documentation to handle
such situations and clear the queue.
=> Add queue clearing for virus scanning

data/applications.yml, source/apps/by-team.html.md.erb
This is my best guess for who owns each application after the Q2 reshuffle.
Can the tech leads review this and make sure it's all correct?
👉 Rendered: https://govuk-tech-docs-pr-324.herokuapp.com/apps/by-team.html
=> Review app ownership for Q2

source/manual/alerts/asset-master-slave-disk-space-comparison.html.md
Add documentation on asset syncing and how to investigate the Icinga alert "Asset master and slave are using about the same amount of disk space".
---
This alert has appeared a few times this week on 2nd line, so I'm writing up my fairly basic understanding of the issue. It'd be good to get feedback on how accurate this all is.
Thanks to @gpeng for pointing out that there's a separate cron job for whitehall content!
I wonder whether we should also think about how this alert works: because the whitehall asset sync only happens every 24 hours, it raises a false alarm every time someone uploads a large amount of data to whitehall. For example, is it possible to add a graphite stat that just tracks disk usage in the asset-manager folders?
=> Add page about asset-slave disk space alerts

data/applications.yml
It's unclear who will own these applications, but it's not Ben / content tools.
=> Remove content-tools as owner for a bunch of apps

source/manual/review-apps.html.md
Smart Answers is also using Heroku Review apps so should be listed.
The GOV.UK Developer Docs repo itself also uses it so should be added
to the list.
=> Add smart-answers to list of apps

config.rb, docs/index.html, source/index.html.erb, source/partials/_intro.html.md
This intro is intended to show that the docs on this site are related to GOV.UK publishing, and not other "GOV.UK" branded products like Verify and Notify.
Also removes some cruft and disables GA in development.
=> Add intro text to docs homepage

app/manual.rb, config.rb, source/manual/alerts/virus-scanning.html.md, source/manual/assets.html.md, source/manual/attachments.html.md, source/manual/blocking-apps-from-release.html.md, source/manual/howto-transition-a-site-to-govuk.html.md, source/manual/redirect-routes.html.md, source/manual/rescan-infected-file.html.md, source/manual/taxonomy.html.md, source/partials/_source.html.erb, source/templates/application_template.html.md.erb
This allows us to specify "related applications" in manual pages. Doing that will generate a link in the footer to the application and link back from the application page to the manual.
=> Cross-link application pages with manual

source/apps/by-team.html.md.erb
This will highlight the "Apps" link in the main navigation.
=> Set parent page for apps by team page

source/apis/search/content.html.md.erb, source/apis/search/search-api.html.md.erb
docs/ was renamed to doc/
https://github.com/alphagov/rummager/commit/522250ae9a221414e5f1456fc6f48941f4817e79
=> Fix urls to rummager docs

source/manual/publish-to-puppet-forge.html.md
- Use `pass` instead of the credstore.
- The password for the Puppet Forge account has moved to the 2ndline
password store.
- Render numbered lists properly, delimited with `.` instead of `)`.
- Split the "Releasing" section into two - via the website, or via the
command line, to make it clearer that they're not linked.
=> Update the Publishing to Puppet Forge docs

source/manual/hmrc-paye-files.html.md
The guide said to prep the content, but didn't explicitly say when to publish it.
Also, I almost used the wrong manifest by copy pasting commands. Using an invalid version number should make sure future me doesn't do anything destructive.
=> Add implied step to PAYE tools release checklist

source/manual/testing-projects.html.md
Document how to update a project's master build number to fix tagging errors.
This has come up a few times, and not everyone knows the magic command to reset the build number.
=> Add command for resetting a build number on Jenkins

source/manual/emergency-publishing.html.md
Update the instructions for publishing an emergency banner to include information about the link text.
This should be released in conjunction with:
[Trello](https://trello.com/c/ZPkk7hnk/58-add-new-field-for-link-text)
=> Add emergency publishing link text instructions

data/dashboard.yml
A gem to document components in GOV.UK frontend applications
https://github.com/alphagov/govuk_publishing_components
=> Add publishing components gem to dashboard

data/dashboard.yml, source/manual/redirect-routes.html.md
The repository has moved from GitHub Enterprise, to a private
repository on GitHub.
=> Update the location of router-data

data/dashboard.yml
As the repository is private, adding it to the repos list doesn't work.
=> Add the router-data data explicitly

app/app_docs.rb
We'll need this to build something in https://github.com/alphagov/govuk-sentry-config/pull/1.
https://trello.com/c/Yxm08KR7
=> Expose puppet name in API

Rakefile, data/applications.yml
These apps have a different puppet name then their repo name implies, so the default (`repo_name.underscore`) doesn't work here. Having the correct puppet name will make the application page link correctly (https://docs.publishing.service.gov.uk/apps/smart-answers.html now leads to a 404).
https://trello.com/c/iTFRLCaM
=> Override puppet_name for inconsistently named apps

source/manual/deploy-puppet.html.md
- Removed a few steps that aren't necessary if you use the release app to get your build number & diff
- Remove section on `release` tag because it's in direct contradiction to the first section.
=> Update deploy puppet docs

source/manual/alerts/asset-master-slave-disk-space-comparison.html.md
The disk comparison check between assets slave & master can fail if
large reports have been compiled against zendesk. This adds a note to
this effect.
=> Add a note about size of files in support-api

source/manual/kibana.html.md
This query is also available on
https://docs.publishing.service.gov.uk/manual/alerts/fastly-error-rate.html#errr-rate-alert
but I didn't find it on that page when trying to work out how to query the CDN
logs. Adding it as an example here should hopefully make it easier for other
people to work out how to do it in future.
=> Add example of querying CDN logs in Kibana

source/manual/upgrade-to-sentry.html.md
If Airbrake isn't installed, slimmer versions < 11.0.1 will swallow any errors silently.
=> Add slimmer upgrade to the Sentry upgrade path

source/manual/alerts/data-sync.html.md
Update the "Data sync" manual page to use the word "Copy"
The jobs that perform the data sync are called "Copy ...." if you
search the manual with the name of the job you'd never find this page
because the word "copy" doesn't appear anywhere.
=> Review and update "Data sync" manual page

source/manual/vpn.html.md
The google doc linked to as the "normal GDS vpn" didn't include details for using openconnect insead of cisco anyconnect.  The page about fixing problems on the dev VM suggests we use openconnect (see: https://docs.publishing.service.gov.uk/manual/fix-problems-with-vagrant.html#are-you-on-a-vpn) instead to fix some VM issues with anyconnect so it feels like it'd be useful if this page did the same.
=> Link to better VPN instructions

source/manual/alerts/puppet-last-run-errors.html.md
Sometimes the reason for this alert is that there is a puppet lock on the machine, so add a note about it.
=> Add info about listing locks for puppet last run docs

source/manual/components.html.md
Detail what components are, where principles and conventions live and where to find component guides.
=> Add frontend components page to manual

source/manual/rebooting-machines.html.md
This makes the reboot instructions for elasticsearch consistent with the
other types of servers and is easier to follow as it's hard to know what
machines will be affected by the previous command.
=> Update elasticsearch reboot documentation

source/manual/retiring-an-application.html.md
There are ordering problems here:
- If the repo is moved before the docs are updated (adding `retired: true` and a description), the docs will start failing
- If the repo is moved before disabling release, release will crash (https://github.com/alphagov/release/issues/142).
=> Make the repo move the very last step in app retirement

data/applications.yml
Mark the `metadata-api` as retired and add a description of what it used to do.
=> Retire metadata-api

source/manual/alerts/nginx-429-too-many-requests.html.md
Document Icinga alert for Nginx HTTP 429 errors.
=> Add nginx-429-too-many-requests Icinga alert doc

source/manual/fix-problems-with-vagrant.html.md, source/manual/get-started.html.md
Sometimes the VM ends up created without a fully working `bowl` command
so the advice in the getting started guide about running apps seems like
it is out of date.  The resolution is to manually install the bowler gem
rather than trying to use `bundle exec bowl` or ignoring `bowl` in favour
of using `startup.sh` in each app folder directly.
It's not clear to me why some VMs get into this state, and others don't,
but it's happened enough that some docs on solving it wouldn't go amiss.
[Fixes #424]
=> Add tips on dealing with a broken bowl

data/dashboard.yml
This repo has moved to the attic.
=> Remove govuk-component-guide repo

source/manual/alerts/ntp-drift-too-high.html.md
Add step to disable Vmware timesync program, that is enabled by default in the
VMware images. Native NTP software is typically more accurate than VMware Tools
periodic time synchronization and is therefore preferred.
=> Update ntp drift instructions

data/applications.yml
Mark `govuk_need_api` as retired and add a description.
For: https://trello.com/c/ClCFMBlG/217-retire-need-api
=> Retire Need API

source/manual/review-apps.html.md
We have had issues with static not running correctly based on the ruby version being different on Heroku and production, this change ensures the version is the same
=> Update Heroku review apps to include ruby-version

source/manual/fix-problems-with-vagrant.html.md
Sometimes `bowl` fails to execute even after reinstalling the gem and
running `rbenv rehash`.
`rbenv` thinks that a rehash is in progress, usually indicated by a
temporary file `.rbenv-shim`. However, such file doesn't exist.
The solution to this has been to restart vagrant.
=> Add additional suggestion to get bowler working

source/manual/alerts/elasticsearch-cluster-health.html.md, source/manual/elasticsearch-dumps.html.md
The cluster health one looks good, I've just updated a reference to
api-elasticsearch, because we'll shortly be replacing it with
rummager-elasticsearch, which runs a newer version.
I've linked the elasticsearch backup/restore to traffic replay.  We're
currently changing the indexing process so this is likely to change -
I've shortened the review time to reflect that.
=> Review search docs

source/manual/replicate-app-data-locally.html.md
Puppet has been updated to install version 2.4.6. These instructions will enable users to remove incompatible plugins and re-import elasticsearch data.
https://trello.com/c/KMIQEH5p/281-es-24-cleanup-tasks
=> Add instructions for updating to Elasticsearch 2.4

source/manual/emergency-publishing.html.md
We've added a step to check your environment, hopefully this will help
people in a high stress situation to double check they're in the right environment.
We've also added a step to clear the memcache for the frontend class since government-frontend
now uses Dalli (memcache based) for it's caching, enabling a quicker update.
There is also a note left for the next 2ndline to see if a government-frontend restart is still required.
Thanks to @bevanloon for the memcache spelunking
=> Add frontend memcache clear step and echo env instructions

source/manual/retiring-an-application.html.md
Applications should be removed from error tracking after they've been retired. This commit adds that step in the list.
Following changes for: https://trello.com/c/ClCFMBlG/217-retire-need-api
=> Add step for removing from Sentry

source/manual/alerts/whitehall-scheduled-publishing.html.md, source/manual/check-for-gone-route.html.md, source/manual/screens.html.md
Caught up with Ruben from the Email team to confirm the whitehall content is still up to date.
=> Review and bump pages in review for this week

Rakefile, data/applications.yml, source/manual/creating-a-new-environment.html.md
Also removes some other references to govuk-delivery. We have retired
this app as it is no longer used.
[Trello](https://trello.com/c/xHgvQXOX/137-archive-and-remove-govuk-delivery)
=> Mark govuk-delivery as retired

source/manual/error-reporting.html.md
Low review date because we'll probably get rid of Errbit in a couple of weeks.
=> Fix page about Sentry

source/manual/error-reporting.html.md
Reverts alphagov/govuk-developer-docs#453. Actually, https://github.com/alphagov/govuk-sentry-config is the correct repo. :man_facepalming:
=> Revert "Fix page about Sentry"

data/dashboard.yml, source/manual/error-reporting.html.md, source/manual/setting-up-new-rails-app.html.md
We've renamed this repo so that we can also put other scripts there (to configure GitHub for example).
=> Rename govuk-sentry-config to govuk-saas-config

source/manual/publishing-a-ruby-gem.html.md
Adapted from https://github.com/alphagov/styleguides/blob/master/rubygems.md.
=> Add information on publishing a ruby gem

app/app_docs.rb, data/applications.yml, source/manual/components.html.md, source/templates/application_template.html.md.erb
Collections and finder-frontend now use the govuk_publishing_components gem and have Heroku review apps and pipelines set up.
=> Add two new component guides

source/manual/cdn.html.md
This looks accurate, except for the number of domains configured for transition.
=> Bump page on CDN

source/manual/lint-ruby-code.html.md
Moved from https://github.com/alphagov/styleguides/blob/master/using-rubocop.md.
=> Add page on using govuk-lint with Ruby projects

source/manual/setup-postgresql-replication.html.md
One shouldn't be running this as root, the previous text suggested running `sudo -u` which is not needed.
=> Update to not mention root

source/manual/transition-a-site.html.md
The Host model in Transition has been modified since this documentation was first written, which means that the link that references a particular line in the code is not longer highlighting the correct part. We should use a particular point in time to ensure that this doesn't happen in the future.
=> Use commit SHA to reference line in code

source/manual/whitelist-site-in-transition.html.md
Without the admin permission for Transition, it is not obvious that
there is whitelisting functionality in the app. By documenting the fact
that such a feature exists, this should help others find some
information when a whitelist request comes in.
=> Document how to whitelist site in Transition

source/manual/github-unavailable.html.md
We now use Gitlab instead of Github Enterprise. Set a short review time
as 2ndline should be Gamedaying this soon.
Actual change in https://github.com/alphagov/govuk-puppet/pull/6586
=> Update docs for deploying when Github is down

source/manual/alerts/puppet-last-run-errors.html.md, source/manual/alerts/varnish-port-not-responding.html.md, source/manual/logit.html.md
I included this in a previous PR, but I'd like to merge it early as I intend to sneakily redirect people to this document when they try to browse the old Kibana URL while testing.
https://trello.com/c/YrTOpoq7/746-logit-migration
I have also included some queries as I have given up trying to pass in a direct link to Icinga for Kibana 5/Logit.
=> Add doc on logit

source/manual/configure-github-repo.html.md, source/manual/github.html.md.erb
We now use https://github.com/alphagov/govuk-saas-config to configure repos. This adds some info on that, as well as a page on how to configure your GitHub repo.
=> Add more stuff about GitHub

source/manual/access-ci.html.md
- non-security-cleared-devs group no longer exists
- Review in 2 months
=> Update review date for Jenkins CI access

source/apis/search/faceted-search.html.md.erb
This should have been part of https://github.com/alphagov/govuk-developer-docs/pull/506
=> Commit missing page to fetch external doc

source/manual/changing-organisation-slug.html.md
The Need API has been retired to gds-attic and the
cache of Organisation in Maslow is only an hour so
we can probably let this expire organically.
=> Update documentation on changing an organisation's slug

source/layouts/header_footer_only.erb, source/partials/_search.html.erb, source/stylesheets/modules/_search.scss
This adds [Algolia DocSearch][al]. It's a free service used by prominent projects such as React, Stripe and Scala. We have an account set up, which is configured in https://github.com/algolia/docsearch-configs/blob/master/configs/publishing_service_gov_uk.json.
We previously discussed this in https://github.com/alphagov/govuk-developer-docs/pull/128. We didn't go for this then because there were questions about accessibility. I think it would make sense to implement it now after all because the Google is very slow, causing new pages to be indexed weeks after first being published. 
[al]: https://community.algolia.com/docsearch
=> Add Algolia DocSearch

app/document_types.rb, app/document_types_csv.rb, source/document-types.csv.erb, source/document-types.html.md.erb, spec/app/document_types_csv_spec.rb, spec/fixtures/document-types-export.csv
We're going to be working a lot with document types again this quarter. For analysis and design it's useful to have a CSV of the document type data we have. This CSV can be used in Google Spreadsheets too.
The export looks like this:
=> Add CSV export for document types

app/app_docs.rb, app/apps_csv.rb, source/apps.csv.erb, source/apps.html.md.erb
https://github.com/alphagov/govuk-developer-docs/pull/523 added CSV export for document types, this does the same for our applications. This will allow us to use the data in Google Spreadsheets. It will make it easier to do the [re-allocation of support work][1] in the beginning of the quarter
[1]: https://docs.google.com/spreadsheets/d/1r5Tc0ddDZpBzFGUJRIB2zPvvUjZed_0Ctk0YPAS4I0o/edit#gid=0
=> Add CSV export for apps data

source/manual/deploying.html.md
Remove references to Github Enterprise as this is not used anymore.
=> Update deployment documentation

source/manual/changing-organisation-slug.html.md
The provided command to check for existing manuals belonging to the
organisation being reslugged does not work. This change updates the
documentation to have a command that works.
=> Fix Mongoid command for Reslugging docs

source/manual/deploy-fixes-for-a-security-vulnerability.html.md
This updates the references to github enterprise to instead reference
gitlab.
=> Reference GitLab for security incident deployments

source/manual/github-unavailable.html.md
Disabling security is trivial in newer versions of Jenkins, so this should be our emergency process if github.com is down. The Jenkins UI should still be protected by IP whitelisting.
/cc @boffbowsh 
https://trello.com/c/5TGUzAGn/743-find-alternative-way-to-login-to-jenkins-if-github-is-down
=> Update docs for github.com being down

data/applications.yml, data/dashboard.yml
`bouncer` and `transition` are apps that we use to support sites
transitioning to gov.uk, but there are a handful of other tools we use as
aprt of this process.  We collect them all here in a new "Transition"
section on the dashboard.  The repos were found via [the
`govuk-transition` topic on github][govuk-transition].  Some of the repos
we link to are private, so they have to be added as sites.
[govuk-transition]: https://github.com/search?q=topic%3Agovuk-transition+org%3Aalphagov&type=Repositories
=> Add section on transition to dashboard

source/manual/encrypted-hiera-data.html.md
This commit updates the “handle encrypted hiera data” manual page with both general updates and a rewrite of the GPG key and Puppet Master sections to reflect current processes.
=> Update “handle encrypted hiera data” manual page

source/manual/ab-testing.html.md
These are out of date and will get stale in general.  The performance analyst should decide which one to use.
=> Remove custom dimension range numbers

source/manual/howto-upload-an-asset-to-asset-manager.html.md, source/manual/upload-asset-to-whitehall.html.md
Document how we manually upload large attachments to whitehall, since we cannot use the asset-manager process for this.
@fofr and @tuzz - would you mind taking a look?
Note that I've skipped the republishing step that Paul ran. I think this was only necessary because we fixed the file size metadata after the document was published. Does that make sense?
=> Add guide to uploading an asset to whitehall

source/manual/add-a-new-document-type.html.md, source/manual/make-a-new-document-type-available-to-search.html.md
This document covers how to add a new document type to govuk-content-schemas and making it available to search.
=> Add new document about how to add a new document type

app/manual_index_page.rb, source/layouts/layout_with_sidebar.erb, source/layouts/manual_layout.html.erb, source/partials/_source.html.erb, source/stylesheets/screen.css.scss
Pages in the same section are often relevant when browsing the docs. This commit adds a column with the other pages in the same section. Also does some reshuffling of elements on the page to make it clearer.
=> Link to other pages in the same section on manual pages

data/redirects.yml
The link to the documentation page from Icinga was not redirecting to the correct page.
=> Update docs link for transition logs processing error

source/manual/get-started.html.md
For new starters who don't know about SSH keys, it's better to say 'your-private-key' to avoid confusion.
=> Update to 'Get started' manual

source/manual/emergency-publishing.html.md
It is a good idea to make a note that the Fabric environment variable needs to be unset, especially for new starters to prevent them from accidentally running things in the wrong environment if switching between jobs.
=> Update to emergency publishing manual

source/manual/get-started.html.md
The old `fix-problems-ith-vagrant` page has been split up into component parts. This points the extra information about fixing a broken `bowl` to the new page.
=> Update link to bowler errors in getting started

source/manual/elasticsearch-dumps.html.md
This uses the GOR logs to resend updates to rummager if a restore is required.
=> Add details about rerunning POST/DELETE traffic for Rummager

source/manual/get-started.html.md
govuk-user-reviewer makes sure that we don't add unauthorised people to GitHub teams and Puppet. If usernames aren't added before adding them to those services 2nd line will receive an alert.
=> Add step about user monitoring system

source/manual/ab-testing.html.md
Update docs to mention multivariate tests and amend example of setting up an A/B or multivariate test to show newer config.
Also see https://github.com/alphagov/cdn-configs/pull/7 for detailed doc changes on dictionary configs.
=> Amend A/B tests docs with new multivariate config example.

source/manual/restore-from-offsite-backups.html.md
When restoring `mysql` from AWS with the command listed below you 
could get a `disk out of space` error if you have not enough space left.
```
duplicity restore --file-to-restore data/backups/whitehall-mysql-backup-1.backend.publishing.service.gov.uk/var/lib/automysqlbackup/latest.tbz2 s3://s3-eu-west-1.amazonaws.com/govuk-offsite-backups-production/govuk-datastores/ /tmp/latest.tbz2
```
But if you have enough space in the hosting machine, you could be 
specific about where to download the file, and what temporary folder to 
use. By using folders outside of the VM we overcome the disk space limitation
from the VM.
```
duplicity restore --file-to-restore data/backups/whitehall-mysql-backup-1.backend.publishing.service.gov.uk/var/lib/automysqlbackup/latest.tbz2 …
```
=> Prevent `disk out of space` error when restoring from AWS

source/manual/incidence-management-guidance.html.md
We are not moving the content wiki into the Developers docs,
as there are plans to standardize this information before
making it public.
We have decided to add a link to the docs, so developers,
which are usually incident leads, can find easily this
information.
=> Add section for Incidence Management Guidance

source/manual/incorrect-content-in-search-or-navigation.html.md
The text of these links include the slash, but the actual urls didn't.
This means we link to a page that returns no results.
=> Add a slash when linking to search.json results for specific paths

source/manual/alerts/fastly-error-rate.html.md, source/manual/kibana.html.md, source/manual/tools.html.md
This just fixes Kibana queries on three pages:
- Tools
- Kibana
- Fastly error rate
There are probably other pages which still use the old fields and syntax, but this is all I had time to review while on 2ndline.
=> Fix Kibana queries and links

source/manual/migrate-zone-from-dyn.md
This guide should detail everything required to migrate zonefiles from DynDNS to Route 53 and/or Google Cloud DNS.
https://trello.com/c/nusU3o0e/800-update-govuk-dns-to-get-route-53-and-google-cloud-dns-configuration-from-config-file
/cc @stephenharker
=> Add guide to migrate zone from Dyn

source/manual/fall-back-to-mirror.html.md
Wrap `<environment>` in code backticks so it is not interpreted as HTML.
=> Fix formatting on mirror page.

source/manual/ab-testing.html.md
This all looks accurate, since it was updated by @steventux recently (https://github.com/alphagov/govuk-developer-docs/commit/6520d7bcd80742184b096752b28a23f2b84f8f61).
=> Bump A/B testing page

data/applications.yml
When asking "who owns short-url-manager" in slack, unless you have a product
manager defined you get:
> short-url-manager is owned by `null` (#survey-and-support)
=> Lutgendorff != null

source/manual/elasticsearch-dumps.html.md, source/manual/incorrect-content-in-search-or-navigation.html.md
Add extra links.
Keep a review time of three months because we expect to have migrated most of the formats to the new index by that point, and this will change the republishing process.
I took a brief look at the Elasticsearch backup docs too, but I haven't bumped the review date because it will need to be updated in the next couple of days once we've reconfigured the background jobs.
=> Review Rummager publishing fixes

source/manual/encrypted-hiera-data.html.md
When using zsh and trying to work with the eyaml rake tasks, a common
error is one of `zsh: no matches found`. Although there is already a
note in the docs to use the `noglob` option when running zsh, the
associated error is not mentioned.
Add a description of the error to the Troubleshooting section so that
searching for the error text `zsh: no matches found:
eyaml:edit[integration]` in the docs returns a match and offers a
solution.
=> Add error description for no matches found

source/manual/alerts/email-alerts.html.md, source/manual/alerts/mongod-replication-lag.html.md, source/manual/alerts/nginx-requests-too-low.html.md, source/manual/alerts/root-filesystem-is-readonly.html.md, source/manual/alerts/user-monitor.html.md, source/manual/get-started.html.md, source/manual/resync-mongo-db.html.md
Mainly just review date bumps, but also a couple of changes to next review date for:
* email alerts, due to ongoing email changes; and
* filesystem readonly alerts, due to AWS migration.
=> Bump various page review dates

source/manual/alerts/email-alerts.html.md
This was linking to the email alert monitoring rake task only. The Travel Advice Email alert task also has output relating to failed emails and can trigger out of hours alerts upon failure.
=> Add link to travel advice email alert rake task

source/manual/hmrc-paye-files.html.md
Note the file sizes may change when new HMRC PAYE files are made available to upload. If this is the case they will need to be reflected in the content pages too.
=> Note file size changes in HMRC PAYE files docs

source/manual/manage-ruby-dependencies.html.md
We should document why we think it's safe to use a robot that updates our repositories.
https://trello.com/c/2CDzENFO/39-documentation
=> Add note about Dependabot security

source/manual/user-management-in-aws.html.md
Add initial docs about user management in AWS.
This has two links missing:
- official guidance on the central GDS users account, which should be provided by Reliability Engineering
- details on GOV.UK accounts and IDs. These could potentially be stored in the password store.
https://trello.com/c/hH4jI14U/873-add-docs-on-user-management
=> Add docs about user management in AWS

source/manual/alerts/asset-master-slave-disk-space-comparison.html.md, source/manual/alerts/virus-scanning.html.md, source/manual/mongodb.html.md, spec/pages/manual_page_spec.rb
We shouldn't use `h1` tags in manual pages, because there's already a h1 present on the page. Adds tests.
=> Don't use h1 tags in manual pages 

source/manual/taxonomy.html.md
This is from the vision work done by the Taxonomy team in Q3. Drop the
review_in to 3 months, as the taxonomy is regularly changing at the
moment.
=> Update the taxonomy page

source/manual/monitor-sidekiq-workers.html.md
The sidekiq-monitoring app now listens on port 3211 instead of port 80
so we need to change the port we tunnel to and from.  The dev VM now can
host the sidekiq-monitoring app directly without needing a tunnel so we
can remove that section entirely.
See: https://github.com/alphagov/govuk-puppet/pull/6981 for the changes
that support documentation.
=> Update ssh tunnel and local dev vm docs for sidekiq-monitoring

source/manual/howto-merge-a-pull-request-from-an-external-contributor.html.md, spec/pages/manual_page_spec.rb
Extracted from https://github.com/alphagov/publisher/pull/702
Part of https://trello.com/c/yIvCgbxI/233-document-how-to-add-a-new-interstitial-page-for-a-service-for-developers
Rendered https://github.com/alphagov/govuk-developer-docs/blob/067b30ac17211af6b1235067b15da7cec3a642fb/source/manual/howto-merge-a-pull-request-from-an-external-contributor.html.md
=> Add guide for how to merge changes from external contributors

source/manual/howto-ssh-to-machines-in-aws.html.md
- The linting tests weren't happy: https://ci.integration.publishing.service.gov.uk/job/govuk-developer-docs/job/introduction-to-aws/5/console.
=> Make h1s into h2s in the AWS SSH docs

app/app_docs.rb, source/templates/application_template.html.md.erb
This PR adds a section to all application pages with the command to SSH into the machine where the application lives. It works by fetching the YAML file that contains the mapping between machine "classes" and applications.
Some examples:
=> Show command to SSH into an app machine

source/templates/application_template.html.md.erb
💡 Now that we have the puppet info for the application (https://github.com/alphagov/govuk-developer-docs/pull/632), we can link to the rake task Jenkins job with the machine class prefilled.
=> Link app pages to rake task Jenkins job

source/manual/cookies-and-sessions-in-frontend-apps.html.md
Add documentation about sessions and cookies in frontend applications detailing issues with default Rails CSRF protection and our cookie-less configurations. Also note a potential method of allowing cookies and sessions for a front end application that is as yet untested.
This work came about because of Email team's work on Email Alert Frontend this quarter.
=> Add docs on frontened sessions and cookies

source/manual/screens.html.md
We now use a javascript-only port of blinken for the 2ndline screens
=> Update blinken docs to point to blinkenjs 

source/manual/concept-of-stacks.html.md, source/manual/govuk-in-aws.html.md
The concept of stacks is something which is fundamentally different in the AWS architecture. This is a small, high level view on what their use case is, and how they may be used.
The ADR needs to be updated to present a clearer view on the implementation of the stacks and how DNS works with them.
=> Add a guide about the concept of stacks

source/manual/emergency-publishing.html.md
The emergency banner tests often result in pages not showing the banner
or not clearing the banner despite the use of cache-bust strings or
origin cache-clearing. Add some hints and tips for developers. 
In particular, remind us to test on the appropriate environment
(staging/integration) and discount any browser based "from memory"
caching (hello Chrome) by using curl. Also note the possibility that the
caching layers on GOV.UK might have evolved, requiring changes to the
fab scripts that clear caches.
=> Add cache troubleshooting for emergency banner

source/manual/editing-an-existing-route.html.md
Drop the review time, as I'm not sure when production will move to
AWS, and thus a different way of accessing the relevant machine will
be needed.
Add a paragraph to make it clearer when manually editing routes is
appropriate, and that it's only a short term fix/change.
Also, improve some capitalisation.
=> Update "Edit an existing route in the Router"

source/manual/emergency-publishing.html.md
During the emergency banner drill the step to reload government
frontend was not needed and so the corresponding section was
removed from the manual.
=> Removed the section about restarting frontend.

.vale, source/manual/encrypted-hiera-data.html.md
Add a note about checking the output after encrypting, and simplify some of the language so the linter complains a bit less.
I've disabled one of the PlainLanguage linters because it triggers on repository names. There is also a lot of noise from the other PlainLanguage ones like `ComplexWords` and `PassiveVoice` but I've left these warnings in for now.
=> Check encrypted values are encrypted

source/manual/alerts/email-alerts.html.md
This was meant to be 2018 rather than 2017.
=> Update review date for email not sent page

source/manual/alerts/elasticsearch-cluster-health.html.md, source/manual/alerts/enhanced-ecommerce.html.md, source/manual/alerts/fetch-analytics-data-for-search-failed.html.md, source/manual/alerts/search-benchmarking.html.md, source/manual/alerts/search-spelling-suggestions.html.md, source/manual/elasticsearch-dumps.html.md, source/manual/incorrect-content-in-search-or-navigation.html.md, source/manual/rummager-traffic-replay.html.md
There is no search team next quarter, so assign everything to 2ndline.
There is now only one app (whitehall) indexing documents the old way, so there's less of a need for the GOR traffic replay, but it could still be used. Don't duplicate this in the backup guide though.
All the `es_dump` stuff should go away when we move to AWS as infra have set up S3 backups.
=> Review search team stuff

source/manual/development-disk-space.html.md, source/manual/get-started.html.md
The development VM can now require up to 150GB of disk space.
See https://github.com/alphagov/govuk-provisioning/pull/27
=> Update VM disk space requirement

source/manual/incorrect-content-in-search-or-navigation.html.md
To reindex people pages in search, you need to republish the page in whitehall. Running the publishing API rake task only works for formats which have been migrated to the govuk index, which does not yet include whitehall formats.
=> Fix instructions for fixing blank finder options

source/manual/ssh-config.html.md
The CI stanza needs to be more like the integration one otherwise it doesn't work 
correctly.  We define the ci-jumpbox separately, and we strip `.ci` from the end of
the host name we're trying to ssh into through the jumpbox.
=> Add jumpbox definition to CI ssh-config

source/manual/rotate-offsite-backup-gpg-keys.html.md
Following an incident with GPG key generation caused by the last two steps of the relevant docs not being clear enough about requiring two _different_ commands to export the private versus the public key, I've added a bit more text to make people more aware that they need to read the last two steps more thoroughly.
Current version can be seen here: https://docs.publishing.service.gov.uk/manual/rotate-offsite-backup-gpg-keys.html#header
=> Make the last 2 steps of gpg generation clearer

source/manual/encrypted-hiera-data.html.md
"Puppet fails because my it can’t find a usable GPG key" should read
"Puppet fails because it can’t find a usable GPG key"
=> Remove spurious "my" in a troubleshooting headings

source/manual/alerts/low-available-disk-inodes.html.md
I've manually run this on `ci-master-1` and `ci-agent-*` but I think it's useful to document this in case we run out of inodes on other machines, too.
=> Document a possible fix for high inode usage

data/dashboard.yml
This repo has moved to public Github.
=> Update URL for alphagov-deployment repo

source/manual/howto-ssh-to-machines-in-aws.html.md
The example is not helpful as 2 developers took it at face value
and tried to ssh with that username within hours of each other.
Also added a missing `.integration` so that people can actually
ssh to the right box.
=> Remove the friendlygiraffe username

source/manual/rotate-offsite-backup-gpg-keys.html.md
This is required to avoid issues with incremental backups.
=> Update offsite backup to recommend keeping the passphrase

source/apis/search/add-new-fields-or-document-types.html.md.erb, source/layouts/api_layout.html.erb, source/manual/add-a-new-document-type.html.md, source/manual/alerts/elasticsearch-cluster-health.html.md, source/manual/alerts/redis.html.md, source/manual/alerts/search-reindex-failed.html.md, source/manual/fix-blank-finder-filter-options.html.md, source/manual/incorrect-content-in-search-or-navigation.html.md, source/manual/logging.html.md, source/manual/reindex-elasticsearch.html.md, source/manual/tools.html.md
This should hopefully make it a bit easier for 2ndline to debug search issues. In particular:
- Explain how to run the reindexing job
- Add some example ES queries
- Remove references to the old logs-elasticsearch cluster
=> Update Elasticsearch docs

data/applications.yml
I think we need this to be able to set up sentry
https://docs.publishing.service.gov.uk/manual/setting-up-new-rails-app.html#configuring-sentry
I'll update that page in a separate PR if I get it working.
This also changes the slack channel associated with the apps.
=> Add content audit tool to dev docs

source/manual/reindex-elasticsearch.html.md
Add a simpler way to republish documents published in a certain time window.
cc @elenatanasoiu
=> Add new publishing-api rake task to reindexing docs

data/dashboard.yml
https://trello.com/c/DEeV9Bcp/76-add-app-to-docspublishingservicegovuk
=> Add govuk-dependencies to the list of team tools

source/manual/get-started.html.md
This PR adds an instruction on how to import a new ssh key into keychain.
=> add instruction to the getting started page

source/manual/howto-remove-change-note-from-whitehall.html.md
For: https://trello.com/c/sOPRBrrT/63-2-remove-change-note-and-redirect-html-attachment-url
This documents the process to go through when having to remove a change note from Whitehall.
=> Adds docs about how to remove a change note

source/manual/rebooting-machines.html.md
We stopped using Redis rivers when we migrated the logs from self-hosted Kibana to Logit.
=> Remove reference to Redis rivers

source/manual/govuk-in-aws.html.md
The GOVUK_APP_DOMAIN is now set to the internal domain, so the
overrides have changed.
=> Remove some old information about Plek in AWS

source/manual/get-started.html.md
A user needs to be in both the old and new hieradata files to have access to both integration and CI
=> Include old hieradata instruction for CI

source/manual/jenkins-ci.html.md
Correct URL is this: https://docs.publishing.service.gov.uk/manual/ssh-config.html
=> Fix broken link to SSH config page

source/manual/encrypted-hiera-data.html.md
The existing docs didn't mention that you should recrypt the hieradata entirely to remove access.  We add references to the puppet_aws folder (which may be temporary, but we still need to remember about it while it's there) and a note about rebases.
=> Add notes about recrypting hieradata for leavers

app/app_docs.rb, data/dashboard.yml, source/manual/publishing-e2e-tests.html.md, source/templates/application_template.html.md.erb
Follow through to the repository README for now.  Will look at automatically generating E2E test information on each app at in a later story.
=> Add documentation on the publishing e2e tests suite

source/manual/howto-remove-change-note-from-whitehall.html.md
After further investigation into how to remove change notes, we've updated the documentation to reflect that.
For: https://trello.com/c/sOPRBrrT/63-2-remove-change-note-and-redirect-html-attachment-url
=> Updates docs for change note removal

source/manual/howto-ssh-to-machines-in-aws.html.md
It's always a good idea to abstract the technical detail into a wrapper coded in bash, so add documentation about how to use this particular wrapper.
This documents how to use the `govukcli` tool which will hopefully make SSHing into different environments easier. This also allows the use of one method to use in different environments while we migrate.
=> Update docs for SSHing to environment

source/manual/receiving-emails-in-integration-and-staging.html.md
Since any subscription won't immediately receive emails like in production.
This PR introduces a new documentation section for emails which we may want to use more of in the future.
[Trello Card](https://trello.com/c/UwM5NwqV/549-spike-enabling-a-full-test-run-for-integration)
=> Add a page about receiving emails in integration and staging

.vale, Jenkinsfile, source/manual/encrypted-hiera-data.html.md, source/manual/howto-remove-change-note-from-whitehall.html.md, source/manual/restore-from-offsite-backups.html.md
I added Vale as a pre-commit hook in b3dcb10783b238de3fbc0acc808da2647ee851f7.
The idea is that we can "lint" our documentation for grammar and readability. Documentation is often as important as the code we have to support, so we should ensure it is concise and accessible, particularly to people where English is not their first language.
This adds the tool to the CI chain. It can be further configured using `.vale`, and further styles may be added to `styles/`.
=> Add ValeLint to CI

source/manual/howto-remove-change-note-from-whitehall.html.md
As we discovered in this PR: https://github.com/alphagov/publishing-api/pull/1167/files, removing a change note does not automatically remove it from the change history on an edition. This has to be done manually.
We're updating the docs to reflect this.
=> Adds further information about change note history

app/app_docs.rb, data/applications.yml, source/templates/application_template.html.md.erb
When viewing docs for Email Alert Api, we want to display a link to the Email Alert Api metrics dashboard. To do that:
* Add a new variable `metrics_dashboard_url`
* Conditionally render the url in the application template if the metrics dashboard url exists for the application
* Add the `metrics_dashboard_url` data to Email Alert Api yaml definition
=> Add metrics dashboard link for Email Alert Api

source/manual/uptime-metrics.html.md
This is a small update to clarify which apps we keep uptime metrics on.
=> Update uptime metrics docs with latest apps

source/manual/alerts/recreate-a-mongo-instance-in-aws.html.md
This will make it clear it is an alert and not a manual page.
We've also reassigned the category to Icinga Alerts.
=> Renaming doc

source/manual/taxonomy.html.md
I added more information about getting a taxon’s
tagged content using rummager. I added information
on how to choose the structure of each returned 
content item and filter by field name.
=> Edit taxonomy page in the dev docs manual

source/manual/user-management-in-aws.html.md
- This means that people will only need to use their MFA device once per
day for AWS CLI commands. They will still have to refresh their
assume-role tokens per environment each hour.
- Related to https://github.com/alphagov/govuk-aws/pull/498.
=> Update the AWS users docs to recommend `sts get-session-token`

source/manual/get-started.html.md
This commit updates the “get started” page to:
* Move all links to use a consistent format
* Change information relating to the new AWS integration environment
* Make some small tweaks
=> Update “get started” page

source/manual/emergency-publishing.html.md
Trello: https://trello.com/c/ktLcZLIN/102-emergency-publishing-drill
This makes it a bit quicker to access the pages when you are running the
drill instead of constantly changing the live ones to staging.
=> Add staging links to sit with the live links

source/manual/move-apps-between-servers.html.md
This commit adds a new manual page detailing how to move apps between servers in both Carrenza and AWS.
Trello: https://trello.com/c/oqi6Xvnu/629-move-email-alert-api-and-email-alert-service-to-dedicated-vms
=> Add docs about moving apps between servers

source/manual/alerts/user-monitor.html.md
New joiners will trigger an alert in Icinga for "Check that correct users have access" which might make people on 2ndline remove their access. This alert happens when people haven't had a chance to open a PR in govuk-puppet to give themselves access, but have already been added to the alphagov organisation and can see repos.
=> Improves docs for user access alert

data/dashboard.yml, source/apps.html.md.erb, source/manual/incorrect-content-in-search-or-navigation.html.md
The repo was renamed because it's now also available for Firefox.
=> Update links to govuk-browser-extension

source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md, source/manual/alerts/email-alerts.html.md, source/manual/email-notifications-how-they-work.html.md, source/manual/test-email-sending.html.md
This commit adds documentation for the new email notifications system.
Trello: https://trello.com/c/J01s1e6c/661-make-documentation-live
=> Add docs for new email notifications system

source/manual/alerts/postgresql-replication-too-far-behind.html.md, source/manual/resync-postgres-standby.html.md
Review postgresql replication documentation, update the last reviewed
dates.
Add some extra commands detailing a way to get a quick view of
postgresql sender and receiver's current log location.
Note how to restart `collectd` and point out that you might have to do so
to clear icinga alerts.
Note where to get passwords so we have a less stressful time figuring
stuff out when trying to solve an alert.
=> Add to and review postgresql replication docs

source/manual/environments.html.md
We now host integration on AWS, not Carrenza and we don't turn integration off out of hours.
=> Review GOV.UK's environments

source/manual/vpn.html.md
The link to the gds-vpn page was broken (it had an extra `/how-to/` path segment).  The words seem fine though.
=> Review GOV.UK and Virtual Private Networks (VPNs)

source/manual/errors.html.md, source/manual/howto-merge-a-pull-request-from-an-external-contributor.html.md, source/manual/merge-pr.html.md, source/manual/naming.html.md
This adds the content from following RFCs as pages:
- https://github.com/alphagov/govuk-rfcs/pull/52: Merge a Pull Request
- https://github.com/alphagov/govuk-rfcs/pull/63: Name a new application or gem
- https://github.com/alphagov/govuk-rfcs/pull/87: How to deal with errors
Those RFCs describe policies on GOV.UK that we should often refer to. Having them in the docs makes them more easily findable and linkable. Some of the RFCs have already been added (https://github.com/alphagov/govuk-developer-docs/pull/76).
I've considered importing all the RFCs (using the method we use for API docs), but a lot of them are reflect a change or plan rather than something that is permanently relevant.
=> Add RFCs about pull request merging, naming, errors

source/manual/emergency-publishing.html.md
A recent fabric-scripts change broke fabric's ability to find
suitable servers from the role attached to a task definition.
Until this is fixed, we need to specify the class explicitly
when flushing caches.
=> Use an explicit fab class for emergency publishing

source/manual/user-management-in-aws.html.md
This is needed by govukcli for `aws sts get-session-token` in https://github.com/alphagov/govuk-aws/pull/507
=> Add an MFA serial to the gds AWS profile

source/manual/replicate-app-data-locally.html.md
Fixes the 'AWS access' section so that it displays correctly as an ordered list. We need to indent the content within each list item or the markdown renderer interprets each list item as a new list.
Also contains a number of spelling, grammar and punctuation fixes.
=> Replicate app data locally fixes

source/manual/stop-all-email-subscription-sending.html.md
This commit adds new documentation detailing how to stop the email subscription system from sending any emails in an emergency.
Trello: https://trello.com/c/JCuEPDye/716-add-documentation-on-how-to-stop-email-alert-api-workers-in-an-emergency
=> Add docs on stopping email subscriptions

source/manual/alerts/high-priority-tests.html.md
It can be confusing what these are or where they come from.
=> Add a page on high priority test alerts

source/manual/cookies-and-sessions-in-frontend-apps.html.md
This commit amends the documentation on cookies and sessions now that email-alert-frontend uses both.
=> Amend docs on cookies and sessions

source/manual/get-started.html.md
Erroneous markdown was pointing to https://docs.publishing.service.gov.uk/manual/govuk-tech-blog (404).
=> Fix markdown for GOV.UK Technology Blog link

data/applications.yml, source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md, source/manual/alerts/email-alerts.html.md, source/manual/email-notifications-how-they-work.html.md, source/manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html.md, source/manual/send-test-email.html.md, source/manual/stop-all-email-subscription-sending.html.md, source/manual/test-email-sending.html.md
This PR changes the owner of the email apps to Platform Support and changes the owners of email-related documentation to 2nd line.
=> Move email team docs to 2ndline

source/manual/manage-email-subscribers.html.md
This commit adds documentation about the “manage” rake tasks in email-alert-api.
Trello: https://trello.com/c/FbSV2AIl/742-add-documentation-for-second-line-eg-rake-tasks-in-email-alert-api
=> Add docs on email-alert-api rake tasks

source/manual/remove-machines.html.md
When using `govuk_node_clean`, it is helpful to list the nodes that the puppet master knows about so you can enter the correct machine name in to the command.
Also, we must remember to disable puppet on the machines we are removing, otherwise they call the puppetmaster and get re-registered.
=> Add instructions to list puppet nodes

source/manual/alerts/logs-are-not-being-received-from-the-cdn.html.md, source/manual/alerts/reboot-required-by-apt.html.md, source/manual/alerts/root-filesystem-is-readonly.html.md, source/manual/dns.html.md, source/manual/merge-pr.html.md, source/manual/migrate-zone-from-dyn.html.md, source/manual/rebooting-machines.html.md, source/manual/retiring-an-application.html.md, source/manual/setting-up-new-rails-app.html.md
- These have been replaced with either "GOV.UK senior technologists",
"Platform Support", or "Reliability Engineering", as appropriate.
=> Remove references to the GOV.UK Infrastructure team

source/manual/hmrc-paye-files.html.md
- Explain how to scp files to the upload directory as the assets user
- Fix the fab script for purging the cache
I'm not entirely sure why the old versions of these commands didn't work, so I'd welcome suggestions for alternative fixes.
I wonder whether the owner of `/mnt/uploads/whitehall/clean/uploaded/hmrc/` changed to `assets` as part of the recent asset migration, but I haven't been able to track down the change.
I don't know whether the fab scripts changed to require a host class or if the `cdn:purge_all` command never worked exactly as written.
=> Update HMRC PAYE tool instructions

source/manual/get-started.html.md, source/manual/replicate-app-data-locally.html.md, source/manual/vagrant-dns.html.md
~Also resurrects the `troubleshooting-vagrant` page, which was referred to on the `get-started` page, but didn't exist.~
~Alternatively, that page could remain as-is and I could put the extra information directly in the `get-started` page.  This might be better, as I'm not sure an issue with VirtualBox installation really belongs on a troubleshooting page.~
The new troubleshooting stuff is scattered around the existing pages, and I've added a couple of extra links to the getting started page to aid discoverability.
=> Document issues I encountered following the getting started docs

source/manual/alerts/offsite-backups.html.md
This commit adds information about how to recover from offsite backup errors caused duplicity asking for a GPG passphrase to fix earlier failed backups.
=> Add docs for fixing failed offsite backups

source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md
This commit adds docs about technical failures that happen when the hieradata and Notify whitelists for staging/integration are not in sync.
=> Add docs about Notify whitelist

source/manual/screens.html.md
This commit updates the screens manual with the things we’re currently running on the 2nd line screen.
=> Update screens manual

source/manual/upgrading-mysql.html.md
This commit updates the MySQL upgrade docs and removes references to integration since upgrades there are done via Terraform.
=> Update MySQL upgrade docs

data/dashboard.yml
This commit points the developer docs to our fork of the Seal since this is where team changes should now be made.
=> Point to our fork of the Seal

source/manual/alerts/data-sync.html.md
This commit adds the new attachment sync jobs to the docs as well as a note on failing Smokey tests before the `Data Sync Complete` job has run.
=> Add information on new attachment sync jobs

source/manual/user-management-in-aws.html.md
- Now that tokens have an eight hour expiry
(https://github.com/alphagov/govuk-aws/pull/533), we don't need to do
the intermediary workaround of calling `aws sts get-session-token` for
a longer session without MFA.
- This has the side effect that you'll need to re-authenticate with MFA
if you wish to switch environments, but I don't think that's
necessarily a bad thing at the moment.
=> Document the use of `aws sts assume-role` and eight hour token expiry

source/manual/alerts/data-sync.html.md
This page will now be linked from the relevant Icinga alert. The page
is still very content light, and this area of our stack is changing a
bit at the moment, so I’ve shortened the review time.
=> Add note about whitehall db sync to docs

source/manual/alerts/clamav-definitions-out-of-date.html.md
Using this has fixed a bunch of the clamav alerts for me on this 2nd line shift and is hopefully useful for others to come.
=> Clamav tip to remove blacklisted mirrors

source/manual/fix-blank-finder-filter-options.html.md
This test was removed when the policies/all finder was removed.
=> Remove the reference to the smokey test for missing people

source/manual/deploy-puppet.html.md
You now don't need to deploy puppet by going to the deploy app and
running the job `Deploy Puppet job`, as this is now done via the
release app. Docs changed accordingly.
=> Update dev docs on instructions to deploy puppet

source/manual/incident-reports.html.md
We've transferred this page over from the Incident management guidance wiki page with the latest version of the report template (thanks Tim Blair). This is so it's more accessible to developers on 2nd line who have to respond to an incident.
=> Updated with latest version of incident report template

source/manual/rabbitmq.html.md
The previous command doesn't work any more since we moved to AWS.
The ssh-fu is based on what we suggest in the sidekiq monitoring page.
If there's a simpler way to do this please let me know and I'll
update all the examples.
The user journey is still broken because you can't get the password
for integration without getting full production access.
Devs do not get access to govuk-secrets on day 1.
=> How to monitor rabbitmq on integration/dev

source/manual/data-gov-uk-continuous-integration-and-deployment.html.md
The 'temporary' elastic server on AWS is no longer necessary and has
been shutdown, so we are removing mention of it from the docs.
=> Remove the wombles from data.gov.uk docs

source/manual/data-gov-uk-architecture.html.md, source/manual/data-gov-uk-continuous-integration-and-deployment.html.md
https://trello.com/c/umQQu7Kj/133-update-documentation-for-heroku-review-apps
The new Heroku stuff is currently acting as an integration environment,
so it also made sense to tidy up references to 'staging' and PaaS
services, so that the architecture docs are more environment agnostic -
the PaaS docs should be sufficient for people to discover PaaS-specific
information.
The Signon doc will need to evolve as we refine our organisation mapping
strategy and permission model.
=> Update data.gov.uk docs with Heroku and Signon

source/manual/replicate-app-data-locally.html.md
The current instructions don't explain that downloads end up in `./backups` which makes the next instruction confusing.
=> Make clear where replicated data is imported to

source/manual/manage-email-subscribers.html.md
Tickets relating to email notifications can at first be handled by the
1st line support team, so note this in the documentation on manging
email subscribers.
=> Add note about Zendesk tickets relating to email

source/manual/rabbitmq.html.md
This prevents it from rendering `--` as an em dash and causing confusion when copy and pasting!
=> Add code blocks around commands

source/partials/_intro.html.md
This has caused panic more than once, with folks external to GOV.UK believing that private, interal information about GOV.UK has accidentally been made public.
=> Remove the word 'internal'

spec/pages/manual_page_spec.rb
Although the tests check for the presence of a H1 (#) on the page, the
presence of a comment in a code block also triggers a failure.  This
isn't easily fixable without a markdown AST.
This PR adds a hint as to a possible cause, to avoid confusion when this
edge case occurs and fixes #933
=> Add failing test hint for unnecessary H1

source/manual/data-gov-uk-common-tasks.html.md
Adds information on how to run rake tasks to operate on the
database/search-index.  These commands are currently heavily used but
should eventually be less important.
Documents:
* How to delete a dataset
* How to delete a lot of datasets
* How to synchronise a single dataset
* How to synchronise an entire organisation's datasets
As a 'drive-by' change, also documents that you can increate the batch size when reindexing above the default setting of 50.
=> Adds more information on common data.gov.uk publish data tasks

app/app_docs.rb, data/applications.yml, source/manual/data-gov-uk-supporting-ckan.html.md, source/templates/application_template.html.md.erb
As we are now relying on CKAN for metadata harvesting, this document
describes how to run various commands to interact with it.
The hosting setup is yet to be determined, and so this section has been
left blank.  Once hosting is confirmed the application_template can be
reverted to remove the pending_hosting? check.
=> Start documentation on how to support CKAN

source/manual/alerts/email-alerts.html.md
Trello: https://trello.com/c/q4BLjTfL/179-post-incidents-clean-up
This commit
- Updates the email address used for checking whether emails sent ok
- Tries to make it clearer that the check email is not used for courtesy
copies
- Cleans it up to fit in the 80 character tramlines
=> Update email not sent documentation

source/manual/removing-a-user-from-puppet.html.md
This is an attempt to clarrify the process that should be used as
different developers seem to approach this in different ways and if you
log onto any of our machines you'll see many home directories for staff
that have left.
A better alternative would be that the govuk_user module removed every
home directory of users who aren't available as this would simplify
the process.
=> A guide to removing users from Puppet

source/manual/alerts/redis.html.md
Occasionally, the `uniquejobs` key in Redis gets so large that it causes
high memory alerts for Redis. Deleting the `uniquejobs` key helps reclaim
some memory.
=> Add instruction about deleting uniquejobs from Redis

source/manual/raising-issues-with-reliability-engineering.html.md
This serves as documentation of the process to raise issues with
Reliability Engineering when on 2nd Line. It intends to provide some
useful info to help determine whether the problem is for Reliability
Engineering but this may need to evolve/iterate to become actually
useful.
=> Raising issues with Reliability Engineering on 2nd Line

data/applications.yml
This commit adds organisations-publisher to the list of apps fo the developer documentation.
=> Add organisations-publisher

source/manual/data-gov-uk-common-tasks.html.md, source/manual/data-gov-uk-continuous-integration-and-deployment.html.md, source/manual/data-gov-uk-incidents.html.md, source/manual/data-gov-uk-monitoring-logging-alerting.html.md
Adds "for data.gov.uk" to manual titles so they aren't confused with GOV.UK manual pages.
At the moment somebody searching for "Incidents" would find a manual page titled "Incidents" but not realise it is about data.gov.uk incidents.
=> Differentiate titles for data.gov.uk manuals

source/manual/give-a-content-designer-access-to-github.html.md
Trello: https://trello.com/c/m1f54bYg/183-define-process-for-content-designers-to-work-on-smart-answers
This outlines the reasons why a content designer may have access to
GitHub and the processes that someone on 2nd Line should follow to
grant/remove their access.
Note to self:
=> Content designer adding/leaving process for 2nd Line

source/manual/resync-mongo-db.html.md
After triggering the resync process at a time of MongoDB stress, a cautionary warning seems advisable
=> Add cautionary warning to MongoDB resync guidance

source/manual/taxonomy.html.md
Trello: https://trello.com/c/qpvXmK3z
Changes include:
* Fix broken link to taxonomy edit page
* Link to the example guidance on production rather than integration
* Correct the statement about the visibility of taxons. All topic pages exist for all published taxons,
so even ones that aren’t “live” can be found on GOV.UK, if you know where to look.
* Remove out of date text. We don’t really have a concept of a draft taxonomy anymore. The entire
taxonomy is published, and we use “phases” to determine how it’s used on the live site.
* Add a link to the metrics gathering rake task
* Update information about who can tag.
* Update the review date for this page
=> Update the taxonomy manual page

source/manual/test-email-sending.html.md
There are a number of places in the documentation where this would be appropriate to sit, but this feels like the best.
[Trello Card](https://trello.com/c/57dlFFOn/254-send-more-useful-courtesy-copies-for-email-alert-api)
=> Add an important note about courtesy copy emails

source/manual/rename-a-country.html.md
The list of world location taxons must be updated in Rummager BEFORE updating the taxon or it will not be reindexed for search.
https://trello.com/c/QOnoeNA2/272-eswatini-help-and-services-not-appearing-in-govuk-search
=> Update instructions for renaming a country

source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md
Some new healthchecks have been added so this improves the documentation for them.
[Trello Card](https://trello.com/c/yGEsHaY9/253-email-alert-api-healthcheck-should-monitor-more-critical-areas)
=> Add more information about email alert healthchecks

app/app_docs.rb, source/templates/application_template.html.md.erb
DGU-isms were spread around the `App` class, which was fine when DGU was the only special snowflake, but we need to add some documentation for Licensing, so it makes sense to extract the specifics for those cases to separate objects.
=> Better encapsulate customisations for special snowflake apps

source/manual/howto-replace-an-assets-file.html.md
The markdown variant in the dev docs doesn't support the "```language" style.
=> Fix bad formatting on replace asset page

source/manual/rebooting-machines.html.md
https://trello.com/c/lDiAvOhV/145-speedup-fabric-scripts-so-theyre-quicker-than-doing-stuff-manually
The fabric command referenced in this doc doesn't apply to AWS.
=> Remove redundant doc for rebooting all machines

app/app_docs.rb, data/applications.yml, data/dashboard.yml, source/templates/application_template.html.md.erb
Because Licensify is a private repo, we need to access the repo list in a different way, and that requires an auth key with permission to access those private repos in the alphagov org (which the current deployment process doesn't have.)
**Update:** Approach changed to just use data from the applications.yml file instead of needing access to private repos.
=> Add basic page about Licensify app

source/manual/alerts/whitehall-scheduled-publishing.html.md, source/manual/cache-flush.html.md, source/manual/fall-back-to-mirror.html.md, source/manual/hmrc-paye-files.html.md, source/manual/howto-manually-remove-assets.html.md, source/manual/rebooting-machines.html.md
https://trello.com/c/lDiAvOhV/145-speedup-fabric-scripts-so-theyre-quicker-than-doing-stuff-manually
Previously some fabric tasks would automatically set the group of
hosts on which they should run, such as 'cache' or 'whitehall_backend'.
The code to support this magic was causing all fabric tasks to take a
long time to run. As only a few tasks had this behaviour, it's more
consistent to enforce the group of hosts be specified when running all
fabric tasks, while also making it easy to remove the task bottleneck.
=> Enforce use of classes for fabric tasks

app/page_freshness.rb, source/page-reviews.html.erb
We have a system that enforces regular documentation review. It works by settings a review date, the time in which it needs to be reviewed and who needs to review it. The overdue things are announced  in Slack.
We currently have a backlog of 43 pages that are overdue, out of a total of 239 pages (18%). While this is not super bad, it seems the number of overdue pages is rising. @thomasleese tried to fix this by limiting the number of messages in Slack in https://github.com/alphagov/govuk-docs-monitor/pull/5. This didn't have the desired effect yet.
I've gone through the overdue ones and came up with a best guess why we aren't updating the page ([source sheet](https://docs.google.com/spreadsheets/d/12rWY86ecNGUf2Bk6zH1xi47ahKt0kVN1gqdMkUTOGiU/edit#gid=309294042)):
| Why | How many | 
-- | …
=> Improve docs updating

app/http.rb
Faraday now complains if middleware is set after adapter which causes
Heroku to error when trying to build assets annoyingly. It doesn't seem
particularly logical that this will fix it but it seems to.
=> Fix Faraday warning

source/manual/gem-file-permission-errors.html.md
This commit adds a manual page on gem permission errors in the development VM and how to fix them.
=> Add docs on gem permission errors in development VM

source/manual/logit.html.md, source/manual/raising-issues-with-reliability-engineering.html.md
Update Logit docs:
- Provide link to the RE logit incident docs.
- Remove links to Kibana URLs, these are often unhelpful if you're not signed in.
reliability-engineering
Update RE docs:
- Provide a link to the RE manual
=> Update RE and Logit docs

source/manual/migrate-testing-from-phantomjs-to-selenium-chrome.html.md
This commit adds a manual page on migrating an app from PhantomJS to Chrome for browser-based testing.
=> Add docs on migrating from PhantomJS to Chrome

data/applications.yml
* Add `govuk-` prefix to channel names
* Update channel names for taxonomy and data informed content
* Move organisations-publisher to platform health team
=> Update team channel names

source/manual/dns.html.md
It may not be immediately clear to someone reading the DNS documentation how to
obtain AWS credentials to run the "Deploy DNS" Jenkins job. This provides a
link to the documentation that explains how to get these credentials.
=> Link to AWS user management doc from DNS doc

app/external_doc.rb
This is used to disable the hardbreaks option with commonmark that is
forced here: https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/markdown_filter.rb#L25
This option makes markdown such as:
hello
there
be rendered as <p>hello<br />there</p> rather than <p>hello there</p> as
markdown does by default, which therefore makes this inconsistent with
the other markdown rendering done in developer docs and Github's own
markdown rendering.
=> Turn off hardbreaks option for importing markdown

source/apis/email-alert-api.html.md.erb, source/layouts/api_layout.html.erb, source/manual/email-alert-api-analytics.html.md.erb
This imports the API endpoint documentation for Email Alert API so it can be shown in the API's section.
It also imports a doc on accessing analytics which documents how to get insights into Email Alert API data through the database and through the S3 based archives.
=> Add more Email Alert API documentation

source/manual/testing-projects.html.md
Updates the Jenkinsfile documentation link to point to the `govuk-jenkinslib` repo instead of `alphagov/govuk-puppet`
=> Update url for jenkinslib

source/manual/encrypted-hiera-data.html.md
The `.rcp` file for Vagrant is no longer in `govuk-puppet` as it was removed in https://github.com/alphagov/govuk-puppet/pull/7572. I guess (as I don't have access) now it's in `govuk-secrets`.
=> Update the .rcp file for Vagrant link

source/manual/generate-csr.html.md, source/manual/renew_ssl_certificates.html.md
Rendered versions of these docs are [here](https://govuk-developer-docs-pr-1038.herokuapp.com/manual/renew_ssl_certificates.html) and [here](https://govuk-developer-docs-pr-1038.herokuapp.com/manual/generate-csr.html#renewing-a-certificate).
=> Add some docs on renewing SSL certificates

source/manual/deploy-puppet.html.md
This didn't work as -v isn't supported, and govuk_puppet will refuse
to run while locked. I've put a change in to fix the second issue.
Depends on https://github.com/alphagov/govuk-puppet/pull/7802
=> Fix the govuk_puppet --noop command

source/manual/kibana.html.md
Most errors don't show up with the existing query, as the status field
in the data seems to be inconsistent.
=> Update "5xx errors returned from cache layer" query

source/manual/incorrect-content-in-search-or-navigation.html.md
Docs were missing a link to http://localhost:9200/_plugin/head/ so it wasn't clear where the Any Requests tab was
=> Add link for checking the search index

source/manual/deploy-fixes-for-a-security-vulnerability.html.md, source/manual/github-unavailable.html.md
https://trello.com/c/TX8kPxzK/319-start-backing-up-our-code-in-aws-codecommit-not-gitlab
We mirror GOVUK Github repos to AWS CodeCommit instead of Gitlab now so update docs to reflect this.
=> Update vcs docs with aws cc info

source/manual/data-gov-uk-architecture.html.md, source/manual/data-gov-uk-deployment.html.md
It seems like there are issues using terraform to manage things in the
Paas. Remove the references to it so we don't overly confuse people.
=> Remove reference to datagovuk_infrastructure

source/manual/rename-a-country.html.md
Just reslugging the world news page makes the new slug available on the site, but doesn't redirect the old slug.
---
[Trello card](https://trello.com/c/iwDCm6tR/353-change-slugs-from-gambia-to-the-gambia?menu=filter&filter=member:michaelswalker)
=> Cover need to redirect the old world news slug

source/manual/hmrc-paye-files.html.md
This isn't actually the new process until we devops all the current files into the asset manager and update puppet to not route the requests to whitehall.
---
[Trello card](https://trello.com/c/SFeIQ9Dp/371-serve-hmrc-assets-from-the-asset-manager)
=> Rewrite HMRC PAYE docs for new process

source/manual/data-gov-uk-supporting-ckan.html.md
These servers are a little different to our normal GOV.UK set up so it's
worth having explicit instructions on how to ssh in to them.
=> Include ssh instructions for DGU Bytemark machines

source/manual/alerts/aws-rds-memory.html.md
The month and day were the wrong way around.
=> Fix last reviewed date for AWS RDS memory utilisation

app/app_docs.rb
When viewing the docs for an application, if the
app has not been merged in govuk-puppet, you see
a load of json instead of which type of machine
it runs on.
This commit adds a message to this effect when
it does not exist in puppet.
Before:
After:
=> Sensible message when the app isn't in puppet

source/manual/howto-manually-remove-assets.html.md
This updates this documentation to make note that the file removed from
the file system may not exist and that the asset should be removed from
S3.
=> Remove asset docs reflect S3 removal

source/manual/naming.html.md
These are apps which don't have an API or a web interface and predominately response to events on the publishing queue.
We're going to formalise the idea of naming apps with a -service suffix because we're developing a new app similar to email-alert-service.
=> Add a section about naming service apps

source/manual/user-management-in-aws.html.md
The note for the MFA ARN now makes a point to stop people accidentally
using their User ARN instead, as this looks very similar and is shown on
the same page in the AWS Console UI.
The note for the Role ARN now gives an example of how this should look,
with a link to the Account IDs and a link to where the role names are
defined, in case they change.
=> Help avoid AWS ARN pitfalls for Roles/MFAs

data/applications.yml
We can't include private repos in this list because the deployment script can't see them.
=> Remove datagovuk_infrastructure from apps

source/manual/transition-architecture.html.md
Remove a reference to "current" 2017 transition, and set the review time to 1 month since we're actively working on moving transition stats.
=> Update transition architecture document

source/manual/alerts/rummager-queue-latency.html.md
This alert triggered this week, but didn't have any documentation. Linked from https://github.com/alphagov/govuk-puppet/pull/8063.
=> Create page to explain rummager queue latency

config/tech-docs.yml, helpers/url_helpers.rb, source/layouts/layout_with_sidebar.erb, source/partials/_source.html.erb, source/stylesheets/screen.css.scss
The contribution banner was moved up to the gem:
https://github.com/alphagov/tech-docs-gem/blob/master/CHANGELOG.md#new-feature-contribution-banner
We have to copy-paste a little bit into `layout_with_sidebar`, because we're overriding that template so the HTML won't be added by default. We'll try to use the layout from the gem soon, which means we won't have to customise it anymore.
=> Use "contribution banner" feature from gem

source/manual/cdn.html.md, source/manual/query-cdn-logs.html.md
This adds documentation on the process to query the CDN logs via Athena. It intends to explain what is stored in AWS log wise, how you can access it and some example queries so you can use it.
It also updates the existing CDN documentation in light of this change.
=> Querying CDN logs

source/manual/deploying-terraform.html.md
This commit prioritises deploying using the Jenkins job and removes references to Terragov since it's not a supported deployment method and confuses matters.
=> Update deploying Terraform

source/manual/manage-ruby-dependencies.html.md
This commit clarifies that we're now using Dependabot properly.
=> Update manage ruby dependencies

source/manual/fetching-packages.html.md
This commit consolidates advice about ancient Vagrant versions into a general note, as well as making some formatting tweaks.
=> Update fetching packages on VM docs

config/tech-docs.yml
This commit redirects two now-deleted pages to the index page.
=> Add redirects for deleted pages

source/manual/setting-up-new-rails-app.html.md
This should be specified in .rubocop.yml instead.
=> Remove --rails from lint command suggestion

source/manual/retiring-an-application.html.md
We have both nightly and incremental database backups in both Carrenza and AWS, so manually archiving a database is not necessary.
=> Remove database archive step for retiring an app

source/manual/get-started.html.md
Expanded and clarified the importing production data section in the getting started guide by adding links and guidance on AWS permissions and profiles.
=> Clarify AWS access when importing production data

source/manual/alerts/email-alerts.html.md
Add some advice and links to email alert api to help diagnose and fix
travel and drug advice emails not being sent.
Remove a redundant sentence as well.
=> Add extra actions to email alerts not sent

source/manual/rebooting-machines.html.md
During a recent incident we had to do this twice, and we learnt that it can actually cause more problems by creating extraneous load on the machines.
=> Add a note about the dangers of rebooting Elasticsearch in hours

source/manual/give-a-content-designer-access-to-github.html.md
Some minor changes:
* Link to correct govuk_non_tech.yml file for non-technical users
* Update link to an example PR for adding user so the PR shows an
example in the new govuk_non_tech.yml file
* Update some wording to make it clearer
=> Update content designer access docs

source/manual/data-gov-uk-architecture.html.md
This is maintained by DEFRA (and outsourced to Airbus Defence &
Space), so we should include this information in the docs to avoid
confusion when requests come into 2nd line.
=> Add information about environment.data.gov.uk

source/manual/nfs-errors-vm.html.md
Here we suggest to use OpenConnect, if we have troubles with Cisco AnyConnect,
but when I followed this guide, the command suggested didn't initially solve the
problem. The issue was fixed by restarting the computer and trying the same
command again, without launching Cisco AnyConnect first, so I'm adding this step
to the guide.
=> Add suggestion to restart the computer

source/manual/data-gov-uk-operations.html.md, source/manual/data-gov-uk-supporting-ckan.html.md
Remove `co-prod2` form the docs because we have turned it off.
Add note mandating pairing on `co-prod3`.
Make 2nd line the first port of call for any SSH access issues.
=> Update CKAN docs to include pairing mandate

source/manual/cache-flush.html.md
The process of clearing cache is simpler now using the Cache Clearing Service.
[Trello Card](https://trello.com/c/9k1peA1F/434-make-the-new-cache-clearing-app-invalidate-cache-in-fastly)
=> Update the page about purging cache

source/manual/manage-ruby-dependencies.html.md
These Gems aren't installed in production, so we can be confident that they won't have any affect if they're broken. Instead, it's much more likely that these will break the tests which will be visible on the PR anyway.
This came out of a retro the Platform Health team had about the number of open Dependabot PRs.
[Trello Card](https://trello.com/c/CnEq5wbu/352-consider-allowing-single-approve-and-merge-for-test-updates)
=> Allow merging of Gems in the test block with only 1 review

Gemfile.lock, config.rb
The middleman build is currently failing (since https://github.com/alphagov/govuk-developer-docs/pull/1230) because our customisations aren't compatible with the latest version of the `govuk_tech_docs` gem.
https://deploy.publishing.service.gov.uk/job/govuk-developer-docs/5362/console
=> Fix compatibility with latest tech docs

source/manual/documents-are-published-but-links-arent-updated.html.md, source/manual/help-with-publishing-high-priority-content.html.md, source/manual/manually-setting-search-popularity-of-content.html.md
Add some basic documentation that should be helpful when high priority content is being published and 2nd line need to manually intervene.
It's based heavily on a card that was written up when this happened recently.
[Trello Card](https://trello.com/c/9cqVuUDy/491-document-problems-dealing-with-high-priority-content)
=> Document problems with publishing high priority content

source/manual/alerts/high-priority-tests.html.md
Browsermob proxy processes can be left behind from restarting the smokey loop. Document how to clean these up and what to look for in the logs.
=> Document smokey loop browsermob proxy issues

source/manual/use-terraboard-to-monitor-terraform-state.html.md
This commit adds documentation on Terraboard, including links and technical information about how and where it runs.
Trello: https://trello.com/c/6UMlTRpa/490-get-terraboard-running-on-the-monitoring-machines-in-each-environment
=> Add docs on Terraboard

source/manual/ssh-config.html.md
This means that there is only one version of the `.ssh/config` file.
=> Add a link to the ssh_config in puppet

source/manual/bowl-error.html.md
Looked at the documentation, it is still valid and works. (Used it myself only a few days ago).
=> Updates review date for bowl error documentation

source/manual/publish-to-puppet-forge.html.md
Modulefile was deprecated a long time ago and we should no longer
be using it.
=> Update the instructions to use metadata.json

source/manual/encrypted-hiera-data.html.md
This commit makes a number of tweaks and changes to the encrypted hiera data documentation, mostly to clarity the new joiners process and also remove duplicated content.
=> Update encrypted hiera data docs

source/manual/change-base-path-in-specialist-publisher.html.md
We now have a rake task that updates a document's `base_path` in `specialist-publisher`. This often comes through to 2ndline as a Zendesk request so is worth adding information on how to do this.
Dependent on these PR's being merged and deployed:
https://github.com/alphagov/specialist-publisher/pull/1317
https://github.com/alphagov/specialist-publisher/pull/1318
Trello card: https://trello.com/c/kTKWF48j/530-document-how-to-change-a-url-in-specialist-publisher
=> How to change a base_path for a specialist document

source/manual/deploying.html.md
A refresh of the page, rewriting it to be more step-by-step and remove information not necessarily relevant to deploying so that we can follow it more easily.
There are no real changes to policy, but I've changed a few things to reflect current working practices.
- Add step to check deployment dashboards
- State that most deploys take place during core hours (between 10 and 4)
https://govuk-developer-docs-pr-1302.herokuapp.com/manual/deploying.html
=> Refresh the deploy instructions

source/manual/aws-console-access.html.md, source/manual/deploying-terraform.html.md, source/manual/set-up-aws-account.html.md
This commit adds the `platformhealth-powerusers` role to the relevant AWS documentation to explain what it is.
=> Add platformhealth-powerusers AWS role

source/manual/replicate-app-data-locally.html.md
In a lot of cases this will mean that just copying and pasting this line will just work, since `$USER` is set to the current username, and on GDS issued laptops this will match the username of the person in Puppet.
=> Use $USER environment variable

source/manual/data-gov-uk-supporting-ckan.html.md
There were two sections explaining how to stop a harvester.  This should be merged into one.
=> Remove duplication on CKAN support page

source/manual/ssh-from-vm.html.md
I had a permissions error where the default username 'vagrant' was causing issues when SSH-ing into integration, specifying a username fixes this.
=> Add username note to potential SSH issues

source/manual/alerts/fastly-error-rate.html.md, source/manual/alerts/logs-are-not-being-received-from-the-cdn.html.md, source/manual/cdn.html.md, source/manual/logging.html.md, source/manual/query-cdn-logs.html.md
[Trello card](https://trello.com/c/D8dyNE9y/524-transition-athena-logs-stretch-goal-remove-logs-cdn-1)
=> CDN logs are now stored on monitoring-1, not logs-cdn-1

source/manual/aws-cli-access.html.md
Make life easier for folks who are less au fait with the AWS console.
=> Add IAM link to AWS command line setup

source/manual/before-you-start.html.md
* Add AWS staging and production Icinga URLs
* Make BlinkenJS request over HTTPS
* Clarify that the PagerDuty drill is at 10am UTC
=> Update 2nd line docs

source/manual/data-gov-uk-map-previews.html.md
https://trello.com/c/Go7bVEFZ/615-document-dgu-map-preview-javascript
Map previews on DGU are fairly large client-side javascript applications which rely on external Web Mapping Services and assets, here's some docs to explain.
=> Add docs for DGU map previews

source/manual/deploy-puppet.html.md
I couldn't find the URL of Jenkins for AWS in the docs.  Adding it here as it will be start becoming more relevant as apps get migrated to AWS.
=> Add links to deploy Puppet in AWS

source/manual/data-gov-uk-migrating-ckan.html.md
We were previously using the API to migrate data from one CKAN to another.  The new method takes a database dump and updates this to reflect the changes to the schema and models.
Trello card: https://trello.com/c/e3qWIvmc/48-implement-new-method-for-importing-data-from-old-ckan-to-new-ckan
=> Update instructions for migrating between CKAN instances

source/manual/upgrade-development-vm-to-postgresql-9.6.html.md
This relates to this [1] change in govuk-puppet. It describes an error
that will appear the first time you run govuk-puppet with those
changes, as it installs the 9.6 version of PostgreSQL, and attepmts to
start it.
It also describes the manual steps required to upgrade to PostgreSQL
9.6.
1: https://github.com/alphagov/govuk-puppet/pull/8240
=> Add page on upgrading PostgreSQL in the development-vm

source/manual/alerts/rabbitmq-no-consumers-consuming.html.md
[Trello card](https://trello.com/c/d3ouXvUN/626-add-alerting-around-high-rabbitmq-queues-for-email-alert-service)
=> Add alert docs for RabbitMQ queue size alert from govuk-puppet#8354

source/manual/fall-back-to-mirror.html.md
The docs tell us how to switch on the failover to our mirrors, but not how to revert back. Seeing as these are emergency docs, it's nicer to not make our on-call people have to dig that out.
=> Add how to disable mirror failover

source/manual/adding-disks-in-vcloud.html.md, source/manual/alerts/data-sync.html.md, source/manual/clone-mysql-slave.html.md, source/manual/data-gov-uk-supporting-ckan.html.md, source/manual/debian-packaging.html.md, source/manual/deploy-puppet.html.md, source/manual/move-apps-between-servers.html.md, source/manual/resync-mongo-db.html.md, source/manual/stop-all-email-subscription-sending.html.md, source/manual/use-aws-xray-to-trace-app-requests.html.md
This commit is just to use the same style in all the warnings. We had warnings in many different styles, so I picked the one that seemed used most often and applied it everywhere. As I haven't reviewed the content of the docs, I left last_reviewed_on unchanged.
=> Make warnings consistent by using same style

source/manual/alerts/fastly-error-rate.html.md, source/manual/fall-back-to-mirror.html.md, source/manual/kibana.html.md
In [RFC-93](https://github.com/alphagov/govuk-rfcs/blob/master/rfc-093-retire-govuk-cdn-logs-monitor.md), `govuk-cdn-logs-monitor` was deprecated and not replaced.  Removing all references to this app, as the Kibana queries do not return any results and the Graphite dashboard shows no data.
=> The app govuk-cdn-logs-monitor has been deprecated

source/manual/alerts/fastly-error-rate.html.md
Fastly CDN logs are now written to S3 and can be queried using AWS Athena.  Adding some guidance on the relevant Fastly alert and giving an example query.
=> Add instructions for getting CDN errors

data/applications.yml
The repos in the attic were moved back to alphagov when GitHub added
support for archiving repositories.
=> Update gds-attic URLs

source/manual/set-up-aws-account.html.md
If a developer has moved teams, and already has an user with MFA set up, they don't need to request a new account from Reliability Engineering. This should save people having to go through the MFA set up all over again.
I've checked that using the same user ARN in `~/.aws/config` works as well 🎉
=> Existing IAM users can log in, then switch roles

source/manual/ssh-into-vm.html.md
The example below worked for me with a local Docker image running Elasticsearch (the rummager app could connect from inside the VM).
=> Reverse port forwarding for SSHing into a VM

source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md
The link didn't work and the account details suggested to be obtained from the password store were not the right ones for checking email status.
=> Update instructions for logging into GOV.UK Notify

source/manual/deploying.html.md
This commit makes a number of changes to the documentation about deploying apps, mostly to codify existing practices.
=> Update app deployment docs

source/manual/deploying-terraform.html.md
This commit adds instructions on how to use the new `deploy.rb` script to deploy Terraform via Jenkins.
=> Add instructions on using deploy.rb to run Terraform

source/manual/alerts/cannot-ping-across-AWS-Carrenza-VPN.html.md
During the AWS migration, there is a VPN tunnel between the Carrenza and AWS VPC to enable private applications in both VPCs to communicate with each other.
Since the status of the VPN along with the configuration of security groups and firewalls are paramount to the effective communication between the two VPCs, it was decided to add Icinga ping probes between specific virtual machines. 
1. add documentation here about the Icinga ping probes that are being introduced to check connectivity between the 2 VPCs
=> add documentation about the ping alert in icinga for the Carrenza-AWS VPN

source/manual/replicate-app-data-locally.html.md
After previously running `vagrant destroy` on my local VM, `vagrant up` didn't actually run the provisioning step. Thankfully there's a separate command for that.
=> Add troubleshooting tip on reprovisioning VM if Elasticsearch not installed

source/manual/elasticsearch-dumps.html.md, source/manual/reindex-elasticsearch.html.md, source/manual/rummager-traffic-replay.html.md
- `curl` command for a quick indices status check
- info on S3 backup process
- change replay command to use 'between' option (likely to be more
practical)
- note about the lack of ES5 support on `es_dump_restore`
=> Add info following Elasticsearch backup/restore drill

source/manual/transition-architecture.html.md
This commit adds information about HTTPS support in Bouncer.
=> Add HTTPS information to transition docs

source/manual/rebooting-machines.html.md
This adds a note about the incidents that have occurred recently have running the safe reboot script, so that if someone encounters these issues again they have a reference point.
=> Add incident notes to reboot RabbitMQ docs

source/manual/deploy-puppet.html.md
* Add warning about restarting Puppet server when changing hiera config
* Clarify that Puppet should always be deployed to both Carrenza and AWS environments
=> Update puppet deployment docs

source/manual/logit.html.md
These have changed. Fixes https://github.com/alphagov/govuk-developer-docs/issues/1380.
=> Fix Logit links to RE site

app/app_docs.rb, app/apps_csv.rb, data/applications.yml, source/apps.html.md.erb, source/templates/application_template.html.md.erb
At the moment it's not easy to find in the document whether an app is hosted on Carrenza or AWS, because we're currently migrating apps over.
This PR adds where the application is hosted to the application page, application index pages and CSV export. It should make it easier to find the location of the apps, as well as automating some parts of the docs. Source of the apps is [this Trello ticket on 2nd line](https://trello.com/c/49OGPxEk/314-%F0%9F%94%AD-where-are-our-apps-apps-are-moving-from-carrenza-to-aws).
- Add hosting to app page
- Add list of providers and number of apps to application home
- Add hosting to CSV and JSON export for reuse
- Fix SSH instructions
=> Document where applications are hosted

app/app_docs.rb, data/applications.yml, source/templates/application_template.html.md.erb
This documents the applications running on Heroku that perform some kind of useful function (but aren't part of the official GOV.UK estate). I've omitted all the review apps for the frontend. A better name than "Utilities" would be welcome but unlikely.
=> Document Heroku apps

source/manual/give-a-content-designer-access-to-github.html.md
It was supposed to be 2019, not 2018.
=> Update 'Give a content designer access to GitHub'

source/manual/alerts/pagerduty-drill.html.md
I didn't realise and spent a while trying to work out why it wasn't triggering in Carrenza before trying AWS.
=> Add a note that the PagerDuty drill runs in AWS

data/applications.yml
These apps have now been migrated.
=> Move support and support-api to AWS

source/manual/on-call.html.md
We had an incident where we realised that not all on-call developers have access to the mirrorer boxes.
=> Add your ssh keys to govuk_mirror-puppet as part of being on-call

Rakefile, app/github_repo_fetcher.rb, app/http.rb, app/requires.rb
Currently it's really slow to repeatedly rebuild the site during development. This commit adds caching to HTTP requests, so that we only do the requests once per hour. This doesn't affect the building on CI because the cache will always be empty.
```
$ time be middleman build
real	1m29.137s
user	4m36.747s
sys	0m57.113s
```
```
$ time be middleman build
real	0m56.648s
user	4m7.461s
sys	0m45.406s
```
=> Cache all HTTP requests for an hour

source/manual/alerts/publishing-api-app-healthcheck-not-ok.html.md
This should be visible when someone clicks on the relevant link in
Icinga.
This is following up on the addition of a check for the
`downstream_high` Sidekiq queue, which has got stuck a few times
recently.
=> Add documentation for the Publishing API app healthcheck

source/manual/republishing-content.html.md
Currently only includes a new Rake task in Whitehall.
[Trello Card](https://trello.com/c/6EIwWTyj/735-create-rake-task-for-representing-content-from-whitehall-to-publishing-api)
=> Add a page about republishing content

source/manual/debian-packaging.html.md
The job has previously been moved but the link was not updated. This commit
adds a working link.
=> Update link for build_fpm_package Jenkins job

source/manual/email-alert-api-callback-from-notify-fails.html.md
We now have two rake tasks that allow us to query Notify's API
if the callbacks fail and may be useful when on 2ndline.
Trello cards: 
https://trello.com/c/lUfUspdh/18-easily-query-the-govuk-notify-api-from-email-alert-api-for-specific-emails
https://trello.com/c/4wdSvV7T/744-document-email-alert-api-rake-tasks
Related PR: https://github.com/alphagov/email-alert-api/pull/766
=> Add page about email-alert-api rake tasks

source/manual/howto-remove-change-note-from-whitehall.html.md
We have added some new Rake tasks in Publishing API and Whitehall to make the process of remvoing document change notes easier. This adds some documentation and links to the Jenkins jobs.
[Publishing API rake task](https://github.com/alphagov/publishing-api/pull/1426)
[Whitehall rake task](https://github.com/alphagov/whitehall/pull/4610)
=> Update Change Note Removal docs

source/manual/bowl-error.html.md, source/manual/business-readiness-publish-changes.html.md, source/manual/business-readiness-update-content.html.md, source/manual/data-gov-uk-migrating-ckan.html.md, source/manual/data-gov-uk-monitoring.html.md, source/manual/data-gov-uk-supporting-ckan.html.md, source/manual/data-gov-uk-troubleshooting.html.md, source/manual/query-cdn-logs.html.md, source/manual/raising-issues-with-reliability-engineering.html.md, source/manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html.md, source/manual/republishing-content.html.md, source/manual/rummager-traffic-replay.html.md, source/manual/screens.html.md, source/manual/ssh-config.html.md, source/manual/troubleshooting-jenkins-performance.html.md, source/manual/working-on-2nd-line.html.md, spec/pages/manual_page_spec.rb
The docs styleguide says to use active titles:
https://docs.publishing.service.gov.uk/manual/docs-style-guide.html#title
This PR updates the titles to be consistent and adds a test to make sure we never end titles `ing`.
=> Use consistent titles in the manual

source/manual/platform-health-dashboard.html.md
During the 2nd line tech support retro it was requested that this information was more easily available to look at.
[Trello Card](https://trello.com/c/nF5gJoCK/425-share-data-on-2nd-line-performance)
=> Add a page about the platform health dashboard

source/manual/publish_special_routes.html.md
This commit adds a new manual page for special-route-publisher to explain what it does.
=> Add manual page for special-route-publisher

source/manual/data-gov-uk-supporting-ckan.html.md
There is no `CKAN_INI` variable in AWS, so all the commands that were
using `$CKAN_INI` should use `/var/ckan/ckan.ini` instead.
=> Change commands to use `/var/ckan/ckan.ini`

source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md
Adds context to explain that for some alerts triggered by the
email-alert-api, these are due to thresholds being too low when
emails are being sent out.
=> Add note on emails being sent causing alerts

app/related_things.rb, config.rb, source/layouts/manual_layout.html.erb, source/partials/_related_content.html.erb
Currently, when a page is the only one in the section, we show "Learn" and "How to.." headings at the footer, but nothing below it. This removes that.
=> Don't show "related" headings when there's nothing

source/manual/rummager-traffic-replay.html.md
Go programs only use a single dash for long arguments.  Also
remove note, as this worked for me.
=> Correct gor invocation

source/manual/get-ssh-access.html.md, source/manual/get-started.html.md, source/manual/replicate-app-data-locally.html.md
Plot twist! Unless I'm mistaken, since we moved the data sync to S3 (https://github.com/alphagov/govuk-puppet/pull/7209), new starters don't actually need integration SSH access to be able to replicate data to the VM. They probably won't need integration access at all for the first few months.
This commit moves the docs about getting integration access into a separate page, and updates some old references to SSH'ing into integration.
Should make life a little easier for new joiners.
=> Move integration access out of "Get started" guide

bin/deploy-to-s3
We're currently seeing the search feature fail because it doesn't recognise `/search.json` as JSON, since it has the default content type of `text/css`.
The `--guess-mime-type` flag should set this automatically, which means we don't have to set it for the the CSS as well.
=> Guess the mime type when deploying

source/manual/reindex-elasticsearch.html.md
The rake task for representing publishing-api updates is already described in the replaying document.  Therefore it doesn't need to be duplicated here, since it just confuses things.
=> Remove duplication in the reindexing of Whitehall instructions

source/manual/alerts/content-performance-manager-app-healthcheck-not-ok.html.md
[Trello card](https://trello.com/c/lJ0YzNDt/1145-3-raise-2ndline-alarms-when-the-core-google-analytics-metrics-are-not-collected-from-google)
When the ETL process to collect Google Analytics metrics fails, an alarm
is triggered, and 2ndline need to run a rake task to repopulate the
data.
=> Document missing GA metrics Icinga Alerts

source/manual/raising-issues-with-reliability-engineering.html.md
The '3rd line infrastructure team' queue has been renamed or bundled in with '3rd line--GDS Reliability Engineering' queue. I checked with Julian Standring and the AWS migration team will have oversight of tickets coming into this queue.
=> update Zendesk queue for RE tickets

source/manual/alerts/content-performance-manager-app-healthcheck-not-ok.html.md
[Trello card](https://trello.com/c/gcw7CXav/1146-3-raise-2ndline-alarms-when-the-number-of-searches-metrics-are-not-collected-from-google)
When the ETL process to collect the number of internal searches from Google Analytics 
metrics fails, an alarm is triggered, and 2ndline need to run a rake task to repopulate the
data.
=> Document missing Internal Searches in Icinga CPM

source/manual/alerts/content-performance-manager-app-healthcheck-not-ok.html.md
[Trello card](https://trello.com/c/56rS8RRM/1147-2-raise-2ndline-alarms-when-user-feedback-metrics-are-not-created)
When the ETL process to collect the number of internal searches from
Google Analytics metrics fails, an alarm is triggered, and 2ndline need
to run a rake task to repopulate the data.
=> Document missing Feedex comments in Icinga CPM

source/manual/rebooting-machines.html.md
* Make it clear that single point-of-failure machines can be rebooted during an incident
* Add a note to ensure rummager workers are rebooted after a redis machine reboot
Incident review: https://docs.google.com/document/d/1I_BC3SyvoTD9N_JcaYq5gifsLYqoVls9yvOZHq5VBzI/edit
=> Update docs following incident review (failure of search indexing)

README.md, Rakefile, bin/deploy-to-s3, startup.sh
Middleman uses a dope/weird system that implements types in Ruby using metaprogramming (I highly recommend watching the talk by middleman's creator about this - https://www.youtube.com/watch?v=W7qj_WFClls).
It's quite slow though. `NO_CONTRACTS=true` will turn off the system and speed up building. It's [recommended in the middleman docs](https://middlemanapp.com/basics/build-and-deploy).
```
$ time bundle exec middleman build
real	1m9.209s
user	4m55.782s
sys	0m51.051s
```
```
$ time NO_CONTRACTS=true bundle exec middleman build
real	0m58.144s
user	4m3.325s
sys	0m46.966s
```
=> Speed up site build

source/manual/create-a-gpg-key.html.md
Updates the passhprase check section to make it clearer that the
passphrase doesn't need to be inserted into the command that is run.
=> Clarify passphrase check

data/dashboard.yml, source/manual/cdn.html.md, source/manual/run-ab-test.html.md
The CDN secrets repo was renamed:
https://github.com/alphagov/govuk-cdn-config-secrets
=> Rename cdn-configs to govuk-cdn-config-secrets

source/manual/alerts/email-alerts.html.md
If the title of a content item changes after it was first published, but before the email alerts has been sent, the email alert
check will fail. Once you’ve confirmed  that the email was in fact sent, it’s ok to add it to the list of emails for the check to ignore.
=> Add how to acknowledge emails where subject doesn’t match title

source/manual/provision-machines-for-data-science-research.html.md
This commit adds documentation about the data science machines in the govuk-tools AWS account and how to configure them.
=> Add docs for data science machines

source/manual/merge-pr.html.md
This commit adds a new rule about dismissing stale PR reviews when making changes before merging, unless they are minor changes and the author is confident there are no side-effects.
It also adds two example of the new rule at work.
=> Add details about when to dismiss stale PR reviews

source/error.html.erb
The error page is currently indexed in search. If I understand middleman-search correctly `index: false` will prevent this from happening.
=> Don't index the error page

source/manual/alerts/elasticsearch-cluster-health.html.md
Remove text implying there are multiple Elasticsearch clusters, when we only have the one.
=> There is only one Elasticsearch cluster for GOV.UK

source/manual/logging.html.md
Add information about accessing logs from the managed AWS Elasticsearch service.
Trello cards: https://trello.com/c/jc1LM6nM/58-set-up-export-of-error-logs-from-elasticsearch-to-cloudwatch and https://trello.com/c/44CAPD5j/57-set-up-export-of-logs-from-cloudwatch-to-s3
=> Add information about AWS managed Elasticsearch logging

source/manual/business-readiness-update-content.html.md
View rendered: https://github.com/alphagov/govuk-developer-docs/blob/f303137903d7e9f92515c1fe7a678036a75368a3/source/manual/business-readiness-update-content.html.md#pinning-content-to-sections-in-the-business-readiness-finder
=> Add pinning for business readiness finder

source/manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html.md
The docs are slightly outdated, and have spoken to Notify to confirm
the steps on adding a member to a team.
=> Update docs about test email setup

source/manual/upgrade-development-vm-to-postgresql-9.6.html.md
I don't know of any issues with this guidance, it can probably be
removed the next time it's up for review.
=> Bump the last reviewed date of the PostgreSQL update page

source/manual/on-call.html.md
This doesn't exist as it wasn't imported from the opsmanual.
=> Remove the link to the non-existent Nagios page

source/manual/alerts/high-memory-for-application.html.md
I have backdated the review for 3 days ago as around 80 manuals got triggered for review today.
=> Update high-memory-for-application docs

source/manual/logit.html.md
We noticed that Logit stopped collecting data recently for Staging.
It looked like the logs just dropped off a cliff (when viewing the
"Statistics") and Logstash logs reported the following error repeatedly:
```
INFO org.logstash.beats.BeatsHandler Exception: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 8463678787, max: 8476557312)
```
Restarting Logstash seemed to solve the problem.
=> Add docs on restarting Logstash when data suddendly stops

source/manual/rename-a-country.html.md
It turns out that the first data migration already changes the slug.
It triggers a new edition of the news page to be sent to the `publishing_api`
and `rummager` https://github.com/alphagov/whitehall/blob/master/app/models/world_location.rb#L26
=> Remove data migration from whitehall steps

source/manual/get-started.html.md, source/manual/vm-vpn-issues.html.md
The GDS VPN modifies your Mac's routing table to direct traffic to *.dev.gov.uk through the VPN.  These instructions allow you to revert that without restarting the machine.
Networking team will soon add this as a script on VPN disconnect, but this solves the problem in the meantime.
=> Add instructions for accessing *.dev.gov.uk after using GDS VPN

source/manual/rabbitmq.html.md
The link to a path in `govuk-secrets` was broken
=> Fix the repo URL for RabbitMQ guidance

source/manual/emergency-publishing.html.md
The job now exists in AWS so we need to update the links to point to the right place.
Depends on https://github.com/alphagov/govuk-puppet/pull/8832 being deployed.
=> Update emergency banner links following move to AWS

source/manual/rummager-traffic-replay.html.md
Update the rummager replay docs.
Running things at 60x speed seems to cause lots of lost connections. Drop this down to 10x which seems more reliable.
Make sure we are explicit about running the replay on all 3 servers.
Also tighten up some language to point out that you `must` make a copy of the logs.
=> Update rummager replay docs

data/applications.yml
These apps have also been migrated to AWS as part of the frontend migration.
=> Move authenticating-proxy and cache-clearing-service to AWS

source/manual/reindex-elasticsearch.html.md
Because `rummager` is called `search` once deployed
=> Update reindexing command that is run directly on the machine

source/manual/alerts/low-available-disk-space.html.md, source/manual/reindex-elasticsearch.html.md
Closing and deleting old Elasticsearch indices is mentioned in the
reindex page. We also have docs on our low disk space page. The docs on
the low disk space page detail how to use the Elasticsearch web
interface to perform the task.
Link these two pages together so developers have all the information at
their fingertips.
=> Link reindex and low disk space Elasticsearch docs

source/manual/business-readiness-update-content.html.md
As we are in the middle of migrating some services off of Carenza,
some of the steps were confusingly in different places. This makes
the examples more explicit.
=> Add details on updating Business Readiness content

source/templates/application_template.html.md.erb
Not all example published pages are on the `www.gov.uk` domain. This means that we sometimes create a malformed link such as `https://www.gov.ukhttp//www.gravesham.gov.uk`.
This adds a check to ensure that, if a protocol is present, example pages will link to their full
external path.
If no protocol is present, we continue to prefix a `www.gov.uk` domain.
https://docs.publishing.service.gov.uk/apps/search-admin.html
before: `https://www.gov.ukhttp//www.gravesham.gov.uk`
after: `http://www.gravesham.gov.uk/`
=> Add absolute path check to example publishing app pages

source/manual/deploy-fixes-for-a-security-vulnerability.html.md
AWS credentials can stick in the KeyChain which will cause 403 errors
when trying to use CodeCommit. Add instructions to remove the
credentials so developers can actually push commits.
=> Delete codecommit http creds from keychain

source/manual/publish-to-puppet-forge.html.md
- We did this for the first time in _a while_, and the new version
changed the build process.
=> Update the docs for publishing a module to Puppet Forge

source/manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html.md
I followed the docs while working on https://trello.com/c/pH0tEctw/242-migrate-all-existing-business-finder-email-subscriptions . Adding some more details for the govuk-puppet changes that need to be made.
https://github.com/alphagov/govuk-developer-docs/blob/6c4329484023b3e4fae0b7dba40264586fa45f5b/source/manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html.md
=> Add more detail to testing emails docs

source/manual/alerts/low-available-disk-inodes.html.md
We stopped installing the docs a fair while ago so they should no longer be present on the machines.
=> Remove some dead documentation

source/manual/run-ab-test.html.md
It's no longer necessary to tell Content Support the names of AB test cookies, as we don't list them individually on the GOV.UK Cookies page.
=> Remove unnecessary steps from the AB test setup guide

source/manual/cache-flush.html.md
This can now be done on the cache machines and there is no need to SSH onto a
mirror machine.
=> Update purging a page from Fastly manually

source/manual/howto-redirect-html-attachment-urls-from-whitehall.html.md
https://github.com/alphagov/whitehall/pull/4702
adds a Rake task to manually redirect an unpublished Edition's HtmlAttachments.
This commit adds some documentation and links to the tasks in Jenkins Integration.
=> Add documentation for Whitehall Rake task for redirecting HtmlAttachment Urls

source/manual/manage-ruby-dependencies.html.md, source/manual/merge-pr.html.md
This PR updates the guidance on merging PRs to include Dependabot specific advice, in particular to recognise Dependabot as an external contributor and to ensure two approvals when necessary.
This commit also updates the guidance on deploying changes after they have been merged to emphasise their deployment to production as soon as possible, practicing continuous deployment and ensuring that we can release our apps at any time without worry of a backlog of unreleased changes.
=> Update guidance on merging PRs to include Dependabot

source/manual/alerts/elasticsearch-cluster-health.html.md, source/manual/elasticsearch-dumps.html.md, source/manual/logging.html.md
These documents allow 2nd line to continue supporting Elasticsearch after the upgrade.
Not to be merged until applications in production are switch to ES5/`search-api`.
Trello card: https://trello.com/c/yQ0uSINr/91-update-high-priority-documentation
=> Update high priority documentation for Elasticsearch upgrade

source/manual/business-readiness-publish-changes.html.md, source/manual/business-readiness-update-content.html.md
Small amendments to the docs include:
- fixing some broken links
- fixing some styling/layout issues
- review of content now that we are using `search-api` rather than
`rummager`
=> Updates to Business Readiness docs

source/manual/data-gov-uk-contracts-archive.html.md
The docs were not quite explicit enough and assumed far too much
knowledge about govuk-secrets. Add explicit instructions on how to
decrypt the required contracts archive key. At the same time make the
file name a bit more sensible.
=> Clarify how to use govuk-secrets to get the ssh key file

source/manual/run-ab-test.html.md
- Make the link to `govuk-secrets` more specific, so you know which credentials to use
- Link to Jenkins in staging, rather than production
=> Update instructions for AB testing

source/manual/get-started.html.md
GDS Self Service, Managed Software Center and App Store all have different Xcode versions and may not be compatible with the base OS version. This is a workaround to use if you run into difficulties.
=> add workaround for installing vagrant-dns-plugin

source/manual/encrypted-hiera-data.html.md
This step snuck in through [1], but I'm not sure why. The commit
message hints at "removing access", but this doesn't make sense. As
the warning immediately below in the documentation states,
re-encrypting the hieradata doesn't prevent anyone who previously had
access from accessing the secrets.
1: 231f71610980a54b0b6175c5c3d1d9ff592cf0ad
=> Remove the guidance around re-encrypting secrets for leavers

source/manual/get-started.html.md
I initially put it under `~/Sites/gds` but then decided to move it to `~` based on other instructions I've read, and had to run `vagrant destroy` and `vagrant up` in the new place (as there were outdated references to `~/Sites/gds`).
I believe Vagrant mounts `~/govuk/` to `/var/govuk` so it is important this is cloned in the right place originally.
=> clarify where repo should be cloned

source/manual/manage-ruby-dependencies.html.md, source/manual/merge-pr.html.md
Following on from RFC 103 [1], Dependabot Pull Requests can now be
merged with only a single review.
Therefore, update the guidance on merging Dependabot Pull Requests to
talk more about what to pay attention to when reviewing Pull Requests
by Dependabot, rather than how many people should approve the Pull
Request before it can be merged.
1: https://github.com/alphagov/govuk-rfcs/blob/master/rfc-103-merge-dependabot-pull-requests-with-a-single-review.md
=> Update Dependabot guidance

source/manual/get-started.html.md, spec/pages/manual_page_spec.rb
I found that I couldn't complete the "Import production data" step without installing bundles, which required bundler, which required a version of ruby that isn't locked down
Initially went into detail around installing `rbenv` via the `rbenv-installer` but we can do it through Homebrew more easily. Have left the debug instructions in the PR.
Also tweaked our linter to allow `#` lines in code blocks.
=> adds ruby / bundler / rbenv instructions

source/manual/get-ssh-access.html.md
Current instructions generate a private key but then rely on you committing your public key.
Maybe I've misunderstood or have missed a step somewhere, but I had to do a little bit of work to derive my public key and put it in my manifest. Now documented here.
=> add instructions for generating public key

data/applications.yml
They've both been moved to AWS.
=> Update hosting for the Data Informed Content apps

source/manual/get-ssh-access.html.md
part 1: the actual command for linking to the `govukcli` binary (not immediately clear that `~/govuk/` is mounted under `/var/govuk`).
part 2: removes the confusing 'optional' instruction for copying the alphagov keypair into your VM. My understanding is that built-in key forwarding in vagrant does this for you already. Would appreciate an expert pair of eyes on this to double-check my understanding is correct before merging...!
=> clarify setting up remote-access inside VM

data/applications.yml, data/dashboard.yml, source/manual/before-you-start.html.md
This commit adds `govuk-zendesk-display-screen` to the list of apps and updates the link to the fully configured 2nd line dashboard screen.
=> Add govuk-zendesk-display-screen to list of apps

source/manual/publishing-e2e-tests.html.md
I had to ask in Slack - and if this instruction existed, I wouldn't have had to 😄
=> adds instructions for testing changes to publishing-e2e-tests

source/manual/howto-change-slug-and-create-redirect.html.md, source/manual/howto-redirect-html-attachment-urls-from-whitehall.html.md
It is a common 2nd line task, which currently is not documented
in the docs.
=> Add a doc on changing a slug and creating a redirect in Whitehall

source/manual/cache-flush.html.md, source/manual/emergency-publishing.html.md
These were not including the stack name in the URL, therefore were being redirected to the default stack.  The redirection lost the query string and path.
=> Fix deploy URL in AWS

source/manual/get-ssh-access.html.md
Keep having to remember to run this command when I restart my machine.
=> add ssh key to keychain persistently through bash_profile

source/manual/business-readiness-publish-changes.html.md, source/manual/tag-content-with-facet-values.html.md
Trello: https://trello.com/c/T2ibAO7v
`govuk-app-deployment` is no longer copying `shared_config` from `govuk-app-deployment-secrets`
and `govuk-app-deployment-secrets` is in the process of being archived, the docs need to be updated
to reflect that.
=> Remove references to govuk-app-deployment-secrets

source/manual/alerts/search-reindex-failed.html.md, source/manual/reindex-elasticsearch.html.md
Deploy with https://github.com/alphagov/search-api/pull/1532
---
[Trello card](https://trello.com/c/QFqYu8XR/656-%F0%9F%92%80-update-rummager-code-and-documentation-to-refer-only-to-search-api-%F0%9F%92%80)
=> Rename the "rummager:" rake tasks and parameters

source/manual/readmes.html.md
Scanning the page, it looked as though "One-line summaries on GitHub repositories" came _under_ "Things we shouldn't put in the README". Took a few seconds to figure out that GovUK guidelines _encourage_ writing the one-line summaries, rather than discourage it!
Reordering the sections would remove those few seconds of doubt.
=> reorder sections for readability

source/manual/alerts/app-healthcheck-failed.html.md, source/manual/alerts/search-api-healthcheck-failed.html.md
These alerts will start after this PR is merged: https://github.com/alphagov/govuk-puppet/pull/9101
I'm keeping this doc (https://docs.publishing.service.gov.uk/manual/alerts/search-api-queue-latency.html) for now, since though it's duplicated content, we haven't yet removed the alert for this (there'll be a healthcheck alert and a graphite check alert).
Trello: https://trello.com/c/cNvfdZfU/372
=> Add documentation for search api healthcheck alerts

source/manual/hmrc-paye-files.html.md
It's useful if the content team knows about this as soon as we do so they can schedule the work in.
Also updated the numbering so that it's easier to fiddle with the steps from now on.  (It still works)
=> Amend HMRC PAYE tool instructions

source/manual/before-you-start.html.md, source/manual/hmrc-paye-files.html.md, source/manual/managing-product-support-tickets-zendesk.html.md, source/manual/raising-issues-with-reliability-engineering.html.md, source/manual/who-do-i-ask-for-support.html.md, source/manual/working-on-2nd-line.html.md
Main update:
Added instructions on how to escalate a long-standing incident to the RE GOV.UK team to 'working with Reliability Engineering'.
Small updates to other pages:
Added a link to the new Zendesk flow diagram to pages linking to the old version. 
Updated the name of the 3rd line Zendesk queue for tickets we triage to RE GOV.UK.
=> 2nd line dev docs update

source/manual/incorrect-content-in-search-or-navigation.html.md
The Rake task that is mentioned was removed in https://github.com/alphagov/search-api/commit/9fe17e305bbf2eecd7b539680481cf7aef672a1d with the message of:
> it's impossible for two documents to have the same
> ID, so this logic can go away now.
[Trello Card](https://trello.com/c/nePyXuDD/975-transparency-data-showing-as-official-statistics-on-org-page)
=> Remove a section about duplicate search results

source/manual/howto-redirect-html-attachment-urls-from-whitehall.html.md
Added guidance for redirection URL. The job return success in Jenkins but fails to actually take effect if there is no `/` at the beginning of the URL.
=> Adds additional notice for redirection URL

source/manual/alerts/content-data-api-healthcheck-not-ok.html.md
With the migration to AWS, the Content Performance Manager has been
renamed to the Content Data API. This includes the healthcheck alert,
so update the documentation page accordingly.
=> Rename the content-performance-manager app healthcheck page

source/manual/alerts/datagovuk-publish-healthcheck-not-ok.html.md, source/manual/data-gov-uk-monitoring.html.md
We recently added an [Icinga healthcheck](https://github.com/alphagov/govuk-puppet/blob/master/modules/monitoring/manifests/checks/datagovuk_publish.pp)
for `datagovuk_publish`. This is the doc that the alert links to
in icinga.
Related PR: https://github.com/alphagov/govuk-puppet/pull/9161
Trello card: https://trello.com/c/ba8SOqEM/960-add-an-icinga-alert-to-notify-us-if-any-of-the-scheduled-dgu-sync-jobs-are-disabled
=> Add doc for datagovuk_publish healthcheck

source/manual/alerts/content-data-api-app-healthcheck-not-ok.html.md
This PR updates the link to Jenkins, now that it is on AWS.
=> Update link to Jenkins for content_data_api_import_etl_master_process job

source/manual/alerts/content-data-api-app-healthcheck-not-ok.html.md, source/manual/errors.html.md
As it's been renamed from the content-performance-manager.
=> Update links to the content-data-api repository

source/manual/alerts/puppet-last-run-errors.html.md
The instructions need you to specify a "short name", so it's nice to provide an example of what this looks like in each hosting environment.
=> Provide example of "short name" on AWS

source/manual/aws-console-access.html.md, source/manual/deploying-terraform.html.md, source/manual/set-up-aws-account.html.md
This is a new role, with the same permissions as the
govuk-administrators role. Like govuk-powerusers, there were too many
people for a single role, so the admins internal to GOV.UK were moved
to a new role.
=> Add details for the new govuk-internal-administrators role

README.md
Some of the commands listed in the readme were wrapped in single backticks, which meant that the commands were displayed inline. This made it harder to read as two commands would appear on the same line next to each other, rather than on their own lines. Wrapping the code in triple backticks makes it a block, with the commands on individual lines.
=> Update readme code to be more readable

source/manual/deployment-dashboards.html.md
A review turned up that the links on the page about deployment dashboards had links that weren't working correctly; the links are now fixed.
Updated review date.
=> Fix links on 'Monitor your app during deployment'

source/manual/data-gov-uk-supporting-ckan.html.md
This PR does two things:
- Updates the soft-delete guidance in response to a [recent ticket](https://govuk.zendesk.com/agent/tickets/3699596)
- Condenses the section about CKAN APIs (not fussed about this one, if people prefer the current version)
=> Update dgu delete api guidance

source/manual/get-started.html.md
There were instructions for working around a failing Python install by doing:
```
dev$ cd /var/govuk/fabric-scripts
dev$ virtualenv .venv
dev$ source .venv/bin/activate
dev$ pip install --upgrade setuptools
dev$ pip install -r requirements.txt
```
...which single-update-pip.sh was doing anyway.
When following those instructions, it didn't fix my issue, which was this:
```
Updating fabric-scripts...
fabric-scripts                            failed to upgrade setuptools with pip output:
Traceback (most recent call last):
File "/var/govuk/fabric-scripts/.venv/bin/pip", line 6, in <module>
from pip._internal import main
File "/var/govuk/fabric-scripts/.venv/local/lib/python2.7/site-packages/pip/_internal/__init__.py", line 40, in <module>
from pip._internal.cli.autocompletion import …
```
=> Advise removing `venv` if failing to install Python deps

source/manual/data-gov-uk-monitoring.html.md
The organisation name has been renamed in the PaaS.
[Trello Card](https://trello.com/c/032AYbj3/1037-change-the-org-name-in-the-paas)
=> Rename DGU PaaS organisation name

app/github_repo_fetcher.rb
This retries errors when talking to GitHub, which should cut down on the number of failing builds like https://deploy.publishing.service.gov.uk/job/govuk-developer-docs/7417/console.
Faraday's default is also to retry timeouts:
https://github.com/lostisland/faraday/blob/master/lib/faraday/request/retry.rb
=> Retry GitHub server errors

source/manual/get-started.html.md
No need to do this in dev machine as of https://github.com/alphagov/govuk-puppet/pull/9212. Your git config will automatically be copied into your VM.
NOT setting your git config could make the VM step fail (it's expecting a `~/.gitconfig` file), so it's important to put this earlier in the docs.
=> Instruct setting global git config on host machine

source/manual/get-ssh-access.html.md
As of https://github.com/alphagov/govuk-puppet/pull/9209, we no
longer need to manually symlink the `govukcli` command inside the VM.
This is now done for us automatically.
=> Remove obsolete VM symlink instruction for govukcli

source/manual/data-gov-uk-2nd-line.html.md
I had a query asking how to upload an organogram dataset, and couldn't
find anything about it in this guidance, so went and created an account for
myself on integration to walk myself through the steps manually in order to
write out instructions for the user.
But halfway through the manual process there was a link to the data guidance
(https://guidance.data.gov.uk/publish_and_manage_data/harvest_or_add_data/add_data/)
which would have been the answer to my issue right away!
Having the link in the 2nd line queries doc will help future 2nd line people find
the right link to share.
=> Link to data guidance

source/manual/before-you-start.html.md
=> Fix link `Manage product support tickets (Zendesk)`

source/manual/data-gov-uk-2nd-line.html.md
If a request comes in to 2nd line to get a user added to data.gov.uk, we should encourage that
the request is processed by an organisation admin rather than a GOV.UK sysadmin.
Linking to the guidance.data.gov.uk gives us something handy we can copy & paste in support
emails (i.e. "Get an admin to follow [these instructions] to get added"). We want to avoid sharing
dev documentation links outside of internal GOV.UK usage.
=> Link to guidance.data.gov.uk instead of dev docs

README.md, app/developer_docs_renderer.rb, app/external_doc.rb, app/string_to_id.rb, config.rb, source/layouts/manual_layout.html.erb, spec/app/external_doc_spec.rb, spec/fixtures/markdown.md
This PR adds a section link to the top of dev doc pages, so that we can see what `section` a page is assigned to and can easily get to the manual page linking to other pages of that `section`. Example:
> ![Screen Shot 2019-06-12 at 11 51 17](https://user-images.githubusercontent.com/5111927/59345629-6c6f5080-8d08-11e9-9118-a7378ba95b4d.png)
Visual change before and after:
| Before | After |
|--------|------|
|![Screen Shot 2019-06-12 at 11 49 38](https://user-images.githubusercontent.com/5111927/59345543-434ec000-8d08-11e9-9b51-a2e2dee43ef5.png)|![Screen Shot 2019-06-12 at 11 49 15](https://user-images.githubusercontent.com/5111927/59345558-48137400-8d08-11e9-887b-1e5c4734a0e5.png)|
The links to the anchor in the manual:
> ![Screen Shot 2019-06-12 at 11 49 …
=> Adds `section` 'breadcrumb' link to pages

source/manual/howto-change-slug-and-create-redirect.html.md
In Zendesk ticket 3712180 I had to process a redirect. I followed these instructions, initially
on integration, and they worked perfectly. When I followed the same instructions on production,
the redirect was applied but the new URL would 404.
Working with @cbaines we saw that the `downstream_low` queue in publishing-api was quite full,
and suspect that the rake task had put it in the downstream_low queue. In the meantime we ran
a rake task to bump it to high priority to process the content change more quickly. I feel it is worth
documenting the workaround in the same instructions that led to the issue.
=> Document redirect 404 issue and workaround

source/manual/alerts/search-reindex-failed.html.md, source/manual/reindex-elasticsearch.html.md
This doesn't actually add any safety because the jenkins job which
invokes this task does it automatically - it just adds an extra step
for people invoking `rake` directly.
---
Depends on https://github.com/alphagov/search-api/pull/1585
=> Remove CONFIRM_INDEX_MIGRATION_START

Gemfile.lock, README.md
1. Pull in v1.8.3 of tech docs gem to fix [search results 'new tab' issue](https://github.com/alphagov/tech-docs-gem/pull/86)
2. Clarify location of Jenkins job (took me a minute or two of exploring the different Jenkins instances) and timings (found it interesting we don't deploy overnight!)
=> 2 small fixes: govuk_tech_docs update & README tweak

source/apis/content-store.html.md.erb
Pulls in content-store README:
In order to keep the information in one place and reduce duplication,
and to keep the documentation closer to the code, I've followed the
style of the [step by step docs](https://github.com/alphagov/govuk-developer-docs/blob/master/source/manual/side-by-side-browser.html.md.erb)
and pull in an external README instead.
I've decided to keep the 'limitations' part separate for the time being
as it covers areas outside of the content-store itself and provides a
bit of context more than anything.
Dependent on: https://github.com/alphagov/content-store/pull/579
=> Pull in content store README

source/manual/deploying-terraform.html.md
This is a convinient wrapper of the underlying aws command.
=> Mention the `govuk aws` tool when deploying Terraform

source/manual/dns.html.md
This is a more convinient alternative to the `aws sts assume-role`
command.
=> Mention the `govuk aws` tool when deploying DNS

source/manual/alerts/search-benchmarking.html.md, source/manual/alerts/search-spelling-suggestions.html.md
They should be pointing to the AWS environments
=> Update Jenkin job urls

source/manual/business-readiness-publish-changes.html.md, source/manual/business-readiness-update-content.html.md
- The 'update content' document links back to the 'publish changes' document. It seems sensible to provide a link back, given we're helping people who may accidentally be looking in the wrong place for their answer.
- The 'publish changes' document now describes how to publish changes to the start page and email signup page, which felt like it was missing as they're explicitly mentioned as part of the 'full journey of the finder'.
NB, there was a lot more in the original PR, but that content was moved to finder-frontend: https://github.com/alphagov/finder-frontend/pull/1203
Trello card: https://trello.com/c/czkf0pRT
=> Update the publish/update business finder docs

source/manual/tag-content-with-facet-values.html.md
The 'pinning' feature has been removed, so references to it should be removed too.
=> Remove reference to pinning

source/manual/alerts/email-alert-api-app-healthcheck-not-ok.html.md
When there is an email alert api error in icinga regarding content changes, this command will allow
bulk resend of content changes
=> Resend content changes in bulk

source/manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html.md
Testing an immediate email is simple: subscribe to the topic, then make an immediate, expect an email.
Digest runs are more difficult since they are scheduled for 08:30 and the data sync will have cleared any updates/subscriptions made in integration.  This PR adds instructions for testing digest runs on demand.
=> Add instructions for testing digest runs

source/manual/transition-architecture.html.md
Some of our jobs now run in our AWS infrastructure. Point our links
towards the AWS jobs so that they correctly reflect our current
architecture.
Remove some redundant links and consolidate some duplicates.
Move the link to the transition app in the dev docs up to a point in the
page where it is last used to consolidate it with other links that are
in that portion of the page.
=> Fix links to jenkins jobs to point to AWS instances

source/manual/logit.html.md, source/manual/review-apps.html.md, source/manual/setting-up-request-tracing.html.md
This PR bumps the review date of docs `Use Logit for GOV.UK`, `Set up Heroku review apps for pull requests` and `Set up request tracing`.
=> Bump docs review date

source/manual/alerts/content-data-api-app-healthcheck-not-ok.html.md
We need better documentation of the alerts thrown by `content-data-api`
This commit updates the docs.
=> Update alert documentation for content data admin

source/manual/howto-manually-remove-assets.html.md
HMCTS often ask for us to remove PDFs from GOV.UK and Google because the file contains the name of someone who's asked for anonymity. You can follow this process when they do that, so I've added a note that hopefully indicates that!
=> Add helpful note for 2nd Line

source/manual/vpn.html.md
The new version of the VPN gateway support full subnet setting
1. remove the warning about full subnet setting restriction
=> remove warning about subnet when swapping VPN

source/manual/local-frontend-development.html.md
For local development, it's a slightly convoluted process to get
things hooked up to work for local testing of the frontend apps.
Add the same for `govuk-docker`
=> Add guide on how to set up frontend dependencies

data/applications.yml
Ran this past Simon and Bevan but we feel it's only fair that Search & Nav look after finder-frontend, since we're the ones tinkering with it.
There's probably other PRs for me to raise off the back of this. Seal? Anywhere else?
=> Change finder-frontend ownership to Search and Nav

app/app_docs.rb
Some of the SSH commands in the Developer Documentation are broken.
The common theme seems to be that they all have a different puppet_name
and app_name. The fix ensures the code checks for both variables before
rendering an error.
More information on this issue can be found here:
https://github.com/alphagov/govuk-developer-docs/issues/1827
Fixes #1827
=> Add Fix For Issue 1827

source/manual/web_application_firewall_rules.html.md
WAF rules can now be configured for load balancers from the
infra-public-services project. this adds some sign posts to the repos
and upstream docs
:warning: depends on https://github.com/alphagov/govuk-aws/pull/1051
=> adds some links to the WAF configuration terraform

source/manual/resync-postgres-standby.html.md
We developed a new method to sync standby postgres from its primary which is more reliable.
1. document the process so that any developer can do it.
=> add a new method to resync standby from primary for postgesql

app/app_docs.rb
The ssh section `transition` [page](https://docs.publishing.service.gov.uk/apps/transition.html#ssh-access-aws) is not rendered properly: the puppet node class is rendered as an error `Unknown - have you configured and merged your app in govuk-puppet/hieradata_aws/common.yaml`.
rather than `backend`
This is due to an error in the aws_machines function of the app_docs.rb where a `common` variable is reused and not updated as not empty.
1. use another variable other than `common` to hold the puppet class for aws machines
1. correct rendering can be viewed here: https://govuk-developer-docs-f-pr-1872.herokuapp.com/apps/transition.html#ssh-access-aws
=> correct aws_machines not obtained correctly

source/manual/cookie-consent-on-govuk.html.md, source/manual/cookies-and-sessions-in-frontend-apps.html.md
Documenting the new cookie consent approach on GOV.UK
=> Add cookies documentation

source/manual/web_application_firewall_rules.html.md
All the ACL logs end up in splunk for all environments. Document how to
query them and how to get access.
=> adds info on how to access WAF ACL logs in splunk

source/manual/cdn.html.md
2nd line [received an alert this morning about Fastly IPs being out of date](https://deploy.publishing.service.gov.uk/job/Check_CDN_IP_Ranges/1444/console), which they attempted to fix but ran into a few problems. After discussing with RE, we've agreed that it should be the responsibility of RE to update these IP ranges if the alert happens again.
I've also updated the whitespace in this PR, so a4ea6fa15d512b883fcb2f8e817f74fb985a9122 is the specific commit which adds this information.
=> Make it clear that RE can update Fastly IPs

source/manual/removing-a-user-from-puppet.html.md
The current docs don't list the need to remove users from our
AWS training environment, this fixes that.
=> Update the guide for removing a user from puppet

source/manual/alerts/search-api-app-healthcheck-not-ok.html.md
Related to https://github.com/alphagov/govuk-developer-docs/pull/1887
Filename was changed due to a redirect issue but the title within wasn't.
=> Change search api healthcheck docs title

source/manual/related-links-on-govuk.html.md
This PR adds developer docs for related links - specifically the new process which uses machine learning to generate links. This documentation details how the related links are generated, how they're ingested, the rules that determine when they're shown, and what to do if there's a problem with the generated links.
Trello: https://trello.com/c/ivIVYQVT
=> Add developer docs for related links

source/manual/run-ab-test.html.md
The job uses the API key, not the credentials.
=> Link to API key for CDN deploys

source/manual/remove-redirected-url-from-transition.html.md
Rather than manually removing the models we can actually just run this Rake task instead:
https://github.com/alphagov/transition/blob/4a13421139095842364be0f7fa597bea55b559fc/lib/tasks/import/revert_entirely_unsafe.rake
[Thanks @jennyd!](https://github.com/alphagov/govuk-developer-docs/pull/1856#issuecomment-515700916)
=> Mention revert_entirely_unsafe

source/manual/howto-find-hardcoded-markup-govspeak.html.md
Reverts alphagov/govuk-developer-docs#1461
I have a need, and also @vanitabarrett said this would have been useful a couple of weeks ago for the YouTube embed work she recently did.
=> Revert "Remove "Find hardcoded markup in GovSpeak""

source/manual/deploying.html.md
Don't think these instructions are covered elsewhere, and this
is the page that looked most promising when I was searching
the dev docs.
=> Adds instructions for deploying branches

source/manual/alerts/nginx-429-too-many-requests.html.md
The workaround is no longer needed as of https://github.com/alphagov/govuk-puppet/pull/9421
=> Remove obsolete workaround for 429 rate false alerts

source/manual/non-ha-node-classes.html.md
The node classes documented here are assumed to be non-critical for the operation of
GOV.UK and not highly available. This means that developers looking to
implement critical services should avoid to rely on these instance types.
@schmie
=> Add documentation of node classes with single instances

source/manual/transition-a-site.html.md
When transition was originally started, fewer sites were HTTPS enabled.
More and more recent transitions are for sites that are TLS terminated.
We should offer advice and guidance to departments who's domains are
not in our SAN when transitioning sites that are TLS terminated. In
these cases, setting up redirects on their existing infrastructure would
provide the most consistent service for now.
[Trello](https://trello.com/c/kNeA4XEM/991-improve-guidance-for-the-transition-tool)
=> Add transition checklist item to check for HTTPS

source/manual/migrate-terraform-resources-betweeen-states.html.md
- As part of consolidation of S3 buckets for DR / cost savings we have
migrated terraformed S3 resources between Terraform code bases / state
files
- The added notes document the steps required for moving Terraform
resources between Terraform states without affecting running hardware.
=> Doc on migrating Terraform resources between states

source/manual/change-in-hours-time-period-for-dst.html.md, source/manual/merge-pr.html.md, spec/pages/manual_page_spec.rb, spec/spec_helper.rb
This adds a test to prevent review dates from being set in the future. 
Also fixes two dates in the future, including one which closes https://github.com/alphagov/govuk-developer-docs/issues/1894.
=> Prevent review dates in the future

source/manual/alerts/nginx-5xx-rate-too-high-for-many-apps-boxes.html.md
Update grafana link as current grafana dashboard link was broken
=> Update nginx alert 5xx rate too high grafana link

data/applications.yml
We need to temporarily make the Github repository for Collections
Frontend private - this commit makes the developer docs aware of
this.
=> The github repository for Collections Frontend will be private

source/manual/alerts/defined-cpu-type-does-not-match.html.md
Some apps are on Carrenza, making this still relevant.
=> Update CPU types does not match doc

source/manual/make-github-repo-private.html.md
In cases of politically sensitive changes, we want to work in private rather than public. This documents how to make an existing repo private.
=> How to make a Github repo private

source/manual/connect-to-vcloud-director.html.md
Having just been through this process and had to ask a lot of questions and figure things out, I thought I'd write up the steps which I took. This corrects several inaccuracies and ambiguities in the previous instructions.
It should now be possible to more or less copy and paste the commands step by step to complete the process of setting up VPN access, at least for Mac/AnyConnect users.
=> Provide step-by-step instructions for Carrenza VPN access

source/manual/uptime-metrics.html.md
The UptimeCollector in govuk-puppet has recently been updated in https://github.com/alphagov/govuk-puppet/pull/9435
This updates the relevant doc.
=> Update uptime collector docs

source/manual/alerts/pingdom-homepage-check.html.md
If someone has confirmed GOV.UK is down the other people on-call shouod be notified ASAP and an incident probably started.
=> Remove the wording indirection

source/manual/email-notifications-how-they-work.html.md
Otherwise just links to https://docs.publishing.service.gov.uk/manual/email-notifications-how-they-work.html#
=> Fix Notify dashboard link

source/manual/alerts/gor.html.md, source/manual/govuk-env-sync.html.md
Some additional configuration has been added in Puppet to disable
traffic replay whilst the `govuk_env_sync` jobs are running - https://github.com/alphagov/govuk-puppet/pull/9489
Trello card - https://trello.com/c/tfBZywz4/1188-disable-the-traffic-replay-to-integration-and-staging-during-data-replication
=> Update to gor documentation

source/apis/search/add-new-fields-or-document-types.html.md.erb, source/apis/search/content.html.md.erb, source/apis/search/faceted-search.html.md.erb, source/apis/search/fields.html.md.erb, source/apis/search/search-api.html.md.erb, source/manual/make-github-repo-private.html.md
Search API is currently private, which means we can't pull in the API docs from the repo. This hides the docs and documents this in the page about private repos. This causes the docs build to crash currently.
The commit should be reverted once the repos can be opened.
=> Hide search-api docs

source/manual/rename-a-country.html.md
Search admin removes the result temporarily so a permanent solution is added to the docs
Trello: https://trello.com/c/DauneS2z
=> Update documentation on how to remove duplicate search results

bin/deploy-to-s3
These commands are currently [manually set in the Jenkins job](https://deploy.publishing.service.gov.uk/job/govuk-developer-docs/configure). I'm putting the job in govuk-puppet, so moving the commands here makes the Jenkins job cleaner.
=> Move commands for deploying into deploy script

source/manual/alerts/email-alerts.html.md
- Clarified that these instructions are useful for both investigating Icinga alerts and responding to user queries
- Split out into two sections; one for specific troubleshooting for Travel/Drug/Medical alert emails, and one general troubleshooting guide
- Keeps line length consistent
- Cuts down duplicate references to `govuk_email_check@digital.cabinet-office.gov.uk` and encapsulates these instructions in the Icinga alerts section
- Reorders URLs A-Z
=> Review and update 'Email alerts not sent' page

source/manual/zendesk.html.md
The link to the triage flowchart is currently erroring because the
format of the link is currently an inline style when it should be a
reference style link.
=> Change link for triage diagram to a reference style

source/manual/nagstamon.html.md
- People can now install `govuk connect` via Homebrew:
`brew install alphagov/gds/govuk-cli`.
- Power users may want to still use the `govuk connect` from the
`govuk-guix` repo, and this is fine.
- But we don't need this much text specifying where `govuk connect`
comes from these days.
=> Update Nagstamon docs now that `govuk connect` is available elsewhere

data/applications.yml
This is currently causing the build to fail: https://deploy.publishing.service.gov.uk/job/deploy-developer-docs/80/console
=> Mark alphagov/frontend as private

data/applications.yml
These repos are now public again, so this removes the `private_repo` label.
=> Update marking of private repos

source/manual/connect-to-vcloud-director.html.md
GOV.UK developer docs handles Markdown code blocks subtly differently to the Github preview, which led to my not noticing that I'd broken the formatting here previously.
Inserting a blank line before the code block fixes the problem.
=> Fix formatting of code blocks in Carrenza VPN docs.

source/manual/related-links-on-govuk.html.md
This commit updates the related links doc to add a sentence about a new automated exclusion that's in place when links are ingested.
=> Update exclusion information for related links

source/manual/debug-underperforming-search.html.md
One of the graphs in the SLI dashboard is broken: https://github.com/alphagov/govuk-puppet/pull/9567
=> Review debug underperforming search

source/manual/load-testing.html.md.erb
I've set the review date for one years time because most of this page is copied from the `README.md` of the govuk-load-testing repo.
[Trello Card](https://trello.com/c/Juuu8OvE/1251-5-host-the-gatling-reports-graphs-somewhere)
=> Add a page about load testing

source/manual/rebooting-machines.html.md
This removes AWS notes for sections of the reboot manual, as they seem
to contradict the "Carrenza only" statements in the titles.
=> Remove AWS reboot notes for "Carrenza only" VMs

source/apis/collections.html.md.erb
This is being added in https://github.com/alphagov/collections/pull/1195
=> Add link to APIs in collections
