alphagov/govuk-developer-docs

- source/manual/alerts/check-process-running.html.md
I wasted time following these instructions as this was the alert I happened to click on, rather than the other one.
Better signposting might have stopped that!
> Signpost unicorn herder remediation instructions

- source/manual/transition-a-site.html.md
Looks like this got missed from #2964.
The [link](https://docs.publishing.service.gov.uk/manual/transition-architecture.html#https-support-for-transitioned-sites) that supposedly confirms HTTPS is not supported currently deeplinks to a section stating:
> Bouncer in late 2020 began supporting HTTPS for transitioned sites, through a new feature in Fastly.
> Remove conflicting information around HTTPS support

- source/manual/alerts/rebooting-machines.html.md
Redis clusters have been moved to AWS Elasticache.
> Remove instructions on how to reboot redis

- source/apps.html.md.erb
- source/manual/ownership-meaning.html.md
This adds detail about what it means for a team to own a GOV.UK application, and links to it from the list of applications. The content has previously been shared internally. 
[Trello](https://trello.com/c/uo5XfoKb/2912-add-meaning-of-application-ownership-to-developer-docs)
> Add application ownership meaning

- source/manual/data-gov-uk-2nd-line.html.md
This adds information and an example for viewing a log of publisher activity on a specific dataset in CKAN. It can be useful when troubleshooting. As far as I know, the activity log isn't available through any links in CKAN.
> Add guide to viewing publisher activity for a CKAN dataset

- source/manual/get-started.html.md
We've found that people posting in #govuk-tech-leads to ask for GitHub access isn't particularly helpful as we often get a message from someone asking to be added and don't know who they are. 
This change makes the process instead the same as the one used for a content designer joining where we request an email sent to a list of people who can access the request (https://docs.publishing.service.gov.uk/manual/give-a-content-designer-access-to-github.html)
I was undecided on whether we should suggest the new starter emails or whether their tech lead should do it. It seemed slightly simpler to ask the new starter.
> Change GitHub access process to emailing owners

- Rakefile
- config/tech-docs.yml
- data/rendering-apps.yml
- data/repos.yml
- source/apps.html.md.erb
Remove reference to manuals-frontend, update docs for apps that use it to mention government-frontend instead.
We'd like to migrate the rendering so we can retire manuals-frontend as on trello ticket.
https://trello.com/c/CfH8SX6D/1130-manuals-update-developer-documents
https://github.com/alphagov/hmrc-manuals-api/pull/664
https://github.com/alphagov/manuals-publisher/pull/1844
> Remove mentions of manuals-frontend

- data/repos.yml
Changes the dependency owner to match the application owner. The coronavirus team doesn't exist anymore so the dependencies are not being monitored.
> Update dependencies owner for collections

- source/manual/post-a-statuspage-message.html.md
This adds instructions for using statuspage's "Backfill" option - which lets you add a status update later.
> Add how to post a statuspage update retrospectively

- README.md
In response to: https://github.com/alphagov/govuk-developer-docs/pull/3561#discussion_r890023456
I've also removed the part about avoiding certain pages, as these
are unlikely to generate rate limit errors on their own - I don't
see any issues using them locally.
> Clarify approach to storing GitHub tokens

- source/manual/development-pipeline.html.md
We no longer run Smokey automatically for manual deployments [^1].
[^1]: https://github.com/alphagov/govuk-puppet/pull/11611
> Fix misleading Smokey guidance in deploy manual

- source/manual/create-a-gpg-key.html.md
- source/manual/get-started.html.md
This updates the documentation to include instructions for users of a YubiKey.
Adds the following steps:
- creating a GPG key
- using the key for SSH
- using the key as a MFA device for AWS
[Trello card](https://trello.com/c/cardhOqm)
> Update documentation for usage of a YubiKey

- config/tech-docs.yml
- source/manual/development-pipeline.html.md
- source/manual/testing.html.md
https://trello.com/c/fRihmgQ8/266-add-top-level-guidance-about-where-we-write-tests-on-govuk
**Deadline for discussion: 2022-06-21 12:00**
👉 [Rendered version](https://github.com/alphagov/govuk-developer-docs/blob/how-we-test-govuk/source/manual/testing.html.md)
This is the culmination of:
- RFC 128, which was really a new testing strategy [^1].
- Work to improve individual documentation [^2][^3][^4].
- A final piece of missing strategy for smoke tests [^5].
All together we now have a complete picture of how we test GOV.UK,
which this new manual summarises.
This ability to describe how we test GOV.UK is the first step towards
making it better, as agreed in RFC 128 [^6]. The next step is to look
at the culture of testing we have in each team and agree what we need
to do to meet these new …
> Add guidance on how we test GOV.UK

- source/manual/flush-the-arp-cache.html.md
Since [upgrading the kernels on our machines](https://github.com/alphagov/govuk-puppet/pull/11696) we don't expect this to be required any more. We'd like to know if this isn't the case.
> Deprecate arp cache flushing instructions

- data/repos.yml
- source/manual/alerts/publisher-scheduled-publishing.html.md
- source/manual/alerts/publisher-unprocessed-fact-check-emails.html.md
- source/manual/alerts/whitehall-scheduled-publishing.html.md.erb
- source/manual/assets.html.md
- source/manual/change-base-path-in-specialist-publisher.html.md.erb
- source/manual/documents-are-published-but-links-arent-updated.html.md
- source/manual/documents-arent-live-after-publishing.html.md
- source/manual/manage-assets.html.md.erb
- source/manual/publish-special-routes.html.md.erb
- source/manual/publishing-e2e-tests.html.md
- source/manual/rabbitmq.html.md
- source/manual/rename-a-country.html.md
- source/manual/republishing-content.html.md.erb
- source/manual/request-fastly-tls-certificate.html.md
- source/manual/transition-a-site.html.md
- source/manual/transition-architecture.html.md
- source/manual/whitehall-file-stuck-uploading.html.md
- source/manual/whitehall-historical-accounts.html.md
Trello: https://trello.com/c/6ij2W9kf/131-split-combined-govuk-publishing-tech-alerts-for-each-team
This updates the references to #govuk-publishing-tech in this repo to split responsibilities to #govuk-publishing-experience-tech and #govuk-publishing-platform.
There is further info in the commits.
> Allocate GOV.UK Publishing ownerships across teams 

- source/manual/get-started.html.md
- some of the steps in the [getting started guide](https://docs.publishing.service.gov.uk/manual/get-started.html) are not necessary for frontend developers to complete when they first join GDS
- adding notes to these steps to help highlight this to avoid future confusion
> Clarify getting started steps for frontend devs

- source/manual/rules-for-getting-production-access.html.md
It seems odd that people with full production access to GOV.UK, don't also have the equivalent access to Sentry. The manager permission allows people to manage people and teams in Sentry as well as actioning alerts.
> Add Sentry manager role to prod admin permissions

- data/repos.yml
- source/manual/content-security-policy.html.md
We are archiving this repository.
Trello card: https://trello.com/c/bgDwxO6a/2917-check-if-govuk-csp-forwarder-is-still-needed-and-retire-if-not-2
> Remove references to govuk-csp-forwarder repo

- source/manual/alerts/whitehall-scheduled-publishing.html.md.erb
These are being coverted into ASCII characters and is breaking the
anchor link to these sections. We also don't include quote marks
for our other alerts that are documented.
> Remove quote marks in headings

- source/manual/encrypted-hiera-data.html.md
`pass` is required in order to re-encrypt hieradata. Without it the script blows up. I've added an extra line so it's clear it's required as a dependency.
> Add line of guidance about installing dependency for re-encryption of hieradata

- data/repos.yml
It has not been used for a long time, and is broken in all
environments. We've now archived the repo. The environments will
die when PaaS is decommissioned, if we don't do anything ourselves
sooner.
> Mark 'datagovuk_publish_queue_monitor' as retired

- source/manual/github-unavailable.html.md
Various fixes to the documentation based on testing and simulating GitHub being unavailable with Chris A.
https://trello.com/c/D942W8FL/2929-disaster-recovery-recommendations-for-code-mirroring
> Code mirror changes

- config/tech-docs.yml
- source/manual/rate-limiting.html.md
Rate-limiting page with information about infrastructure level and app-level rates currently in place.
> Add docs on rate-limiting

- config/tech-docs.yml
Whoops! Accidentally added the new page to the redirect list pointing to itself, so that it rendered empty but with a timed redirect. Removes that redirect.
> remove rate-limiting page from redirect list

- data/repos.yml
The `deprecated_columns` gem has been [deprecated](https://github.com/alphagov/deprecated_columns/pull/15) and the repo has been archived. 
This simply marks it as retired in our list of repos (and there's no need to have it owned by a team).
> Mark deprecated_columns as retired and remove owner team

- data/rendering-apps.yml
Rendering has now been moved from Whitehall to collections
> Update rendering app for topical events

- source/manual/vpn.html.md
Add some technical details about what happens when the Licensify->UKCloud VPN is down. This hopefully clarifies how the alert is implemented so that troubleshooting is easier.
An assumption about the implementation of the vpn-down alert led to some unfortunate confusion and delay in resolving an incident recently, hence adding the extra info here.
> Clarify the internals of the Licensify/UKCloud alert.

- source/manual/rules-for-getting-production-access.html.md
This is to clarify the reasoning for having different permissions around production access. This include information stated in [RFC 146](https://github.com/alphagov/govuk-rfcs/blob/main/rfc-146-production-deploy-access.md).
> Add explanation why we have production access

- source/manual/howto-modify-change-note.html.md.erb
In https://github.com/alphagov/whitehall/pull/6618, we implemented a rake task to modify change notes in Whitehall.
This updates the documentation to reflect the usage of this task, instead of logging into a production console.
> Update steps for changing Whitehall change note

- source/manual/encrypted-hiera-data.html.md
Without this, the next step ("gpg --fingerprint") won't show the fingerprint for the key you've just been given.
> Clarify you need to import GPG key before you can get its fingerprint

- source/manual/republishing-content.html.md.erb
In https://github.com/alphagov/whitehall/pull/6715, we have consolidated a number of rake tasks into one.
This updates the documentation to reflect that and also makes minor changes to make the documentation more readable.
[Trello card](https://trello.com/c/dOpjWvGr/169-update-rake-task-for-republishing-content-items)
> Update documentation for republishing Whitehall content

- source/manual/on-call.html.md
The docs now also include a list of the alerts set up to page on call
developers.
Trello card: https://trello.com/c/7sWsJfy8/104-identify-the-level-of-support-we-provide-for-our-apps-during-out-of-hours
> Update the on call docs

- data/rendering-apps.yml
The document type has changed to the non-placeholder version
[Trello](https://trello.com/c/5vpV1JUu/194-update-world-news-location-document-type)
> Update world location news page document in rendering apps

- source/manual/alerts/security-updates.html.md
Remove references to manually upgrading mysql
The link is broken as the file was removed in the Pull Request below:
Review Upgrade MySQL in production - https://github.com/alphagov/govuk-developer-docs/pull/2767
> Remove reference to upgrading mysql

- source/manual/zendesk.html.md
Previously this section said to create a tech leaver card
when the user was in the `govuk_tech.yml` and a non-tech
leaver card when they were in `govuk_non_tech.yml`. But it
didn't say anything when the user was in neither (which happens).
The Trello template ticket for leavers has the answer:
"you can confirm the leaver was in a tech role by finding their name in govuk_tech.yml. If they're not there, you may need this card: ... (non tech role).
This card updates the documentation to relect that.
> Clarify when to create a non-tech leaver card

- data/repos.yml
The repo only contained a very brief README (one sentence) and the main / only link to further docs was broken.
[Archived repo](https://github.com/alphagov/govuk-account-scaling-docs)
> Remove as repo is archived

- data/rendering-apps.yml
Update rendering apps for world location news
Collections now renders english world location news pages, other locales still rendered by whitehall.
> Update rendering apps for world location news

- source/manual/alerts/low-available-disk-space.html.md
The correct AWS role is `govuk-integration-poweruser` (singular) not `govuk-integration-powerusers` (plural)
> Fix typo in AWS command

- source/manual/ruby.html.md
The PRs used to be generated by the Platform Reliability team. This will no longer be the case and now the teams are solely responsible for upgrading ruby versions in the apps/repos they own. 
Running the script with access token from a personal account would unnecessarily increase the burden on team's devs. The person who raised the PR would not be able to approve it. 
The PRs would also be posted to the slack channel by the Seal. Since upgrading to the latest ruby version doesn't tend to be the priority, the PRs are likely to hang around for long time and add noise to the Slack channels.
It removes the example PR because it got out of date and the setup instructions are now well described in the README.
Related PR: https://github.com/alphagov/upgrade-ruby-version/pull/8
> Update ruby upgrade docs to reflect the current process

- source/manual/rules-for-getting-production-access.html.md
The old workflow expected access to be granted and revoked on the very first shadow shift. Granting Production Admin access to all the necessary systems requires a significant level of time and effort, and it's clear the documented process was somewhat idealistic and not rigidly followed.
After discussing with the 2nd line leads and the Lead Developers, we've agreed to change the process such that no additional access is granted on the first shadow shift. Access is now to be granted on the second shadow shift (assuming probation has been passed), and the access is retained by the developer at the end of the shift. This means the work only has to be applied once, not three times.
A concern was that the shadow developer may not be able to learn much without the additional access, but …
> Document change in process for getting Production Admin access

- source/manual/pentests.html.md
I'm always forgetting the name of the repo where we've documented our pentest procedures. This placeholder page contains some keyword stuffing to make it easier for developers to find in future.
> Add 'Pentests' document

- source/manual/get-started.html.md
The Markdown syntax was wrong, causing this link to be broken.
> Fix a broken link

- source/manual/encrypted-hiera-data.html.md
- source/manual/removing-a-user-from-puppet.html.md
Update the leavers procedure. The [current doc](https://docs.publishing.service.gov.uk/manual/removing-a-user-from-puppet.html) lists two things to remove the user from (production hieradata and AWS hieradata) but it looks like we only have AWS hieradata now, so merging this into a single bullet point and removing the unnecessary one.
Also clarifies the [What to do when someone leaves](https://docs.publishing.service.gov.uk/manual/encrypted-hiera-data.html#what-to-do-when-someone-leaves) procedure to include a generic step to remove any other references to the user, which seems easier than listing them specifically and keeping that list up to date.
> Update leavers procedure

- source/manual/republishing-content.html.md.erb
Now that [`WorldLocationNews` has been moved out of the `WorldLocation` model into a model of its own](https://github.com/alphagov/whitehall/pull/6722), we have removed the special rake task to publish this content type. This type of document can now be republished in the same way as all other document types.
> Add WorldLocationNews to republishable content types

- source/manual/2nd-line.html.md
This is the policy as informally agreed between Lead Developers and 2nd line delivery manager and tech leads. Note that until now, standby developers have not been allowed to attend All Staff events in person, so as well as general documentation, this is also documenting a small change in policy.
> Document expectations of standby developers

- source/manual/post-a-statuspage-message.html.md
Added a note that sometimes the statuspage is used with a wider audience than publishers (eg linked from a tweet or blog post)
> Clarify audience for statuspage

- source/manual/howto-backup-and-restore-in-aws-rds.html.md
This should make it clearer that we should create a snapshot of the original database before deleting it and why.
Trello card: https://trello.com/c/Lumo76IF/2998-updates-to-how-to-restore-an-rds-instance-doc
> Update docs on deleting a database

- source/manual/removing-a-user-from-puppet.html.md
When removing a user from govuk-user-reviewer, don't remove them from the .mailmap file. Updated 2L docs.
> Add reminder not to remove user from .mailmap

- source/manual/test-a-branch-of-the-components-gem.html.md
Adds documentation for testing an application both locally and on integration with a branch of `govuk_publishing_components`.
> Add testing a branch of components gem

- data/repos.yml
The repo is now archived, and http://reference.data.gov.uk/ is unreachable.
> Mark datagovuk_reference as retired

- source/manual/encrypted-hiera-data.html.md
A few developers have encountered this in recent months. This addition should bring up this page as a search result for "No secret key" and give developers a useful starting point.
> Document the troubleshooting steps for "No secret key"

- source/manual/incorrect-postcode-data.html.md
- source/manual/licensing.html.md
Mapit is no longer used by Frontend.
We need to update the postcode-related mentions in the dev docs.
Trello card: https://trello.com/c/6TO6GDJM/2934-switch-frontend-to-use-locations-api-5
> Update docs that mention mapit where is no longer used

- source/manual/components.html.md
Fix the links on [this page](https://docs.publishing.service.gov.uk/manual/components.html#component-guides) as some of them were out of date.
> Fix links to component guides

- source/apps.html.md.erb
The link `government-frontend` was broken and being rendered as `[government-frontend][government-frontend]` because there was no corresponding reference.
Also clean up reference-style links which had unnecessarily duplicated link text and reference.
> Fix broken link on `/apps` page.

- source/manual/remove-machines.html.md
Reading this doc, I get the impression it used to have two main sections: "AWS" and "Carrenza". We now only use AWS, so I've tweaked the structure to make it clearer there is only one process to follow.
> Remove references to Carrenza

- source/manual/access-to-licensing-for-third-parties.html.md
I've reordered the headings to make the documentation a bit easier to follow (previously things like "accessing mongo" came before "using ssh", but the latter is a prerequisite of the former so that doesn't make sense).
I've also noted that third parties generally don't have access to ssh in staging or production, and attempted to clarify when they should be given Production Deploy Access.
> Update access licensify for thrid parties

- data/repos.yml
Spun out of https://trello.com/c/AqLwVouU/2981-automatically-include-pr-template-in-dependabot-pr-descriptions-5.
Adds the new [`bulk-changer`](https://github.com/alphagov/bulk-changer) repo to `data/repos.yml`.
> Add `bulk-changer` repo

- source/manual/github-unavailable.html.md
- source/manual/rules-for-getting-production-access.html.md
We should now grant admin access to the Tools environment at the same time as granting said access to Production/Staging.
> Document that Production Admin role grants access to Tools env

- source/manual/pact-testing.html.md
This updates some broken links and changes statements that no longer reflect the conventions of GDS API Adapters.
> Reflect changes to pact test organisation

- source/manual/removing-a-user-from-puppet.html.md
I was reviewing this document by chance, and this is an easy replacement with a point to our most recent 'multiple machines' docs.
> Remove reference to fabric scripts

- data/repos.yml
We are retiring this application, so removing it from here.
[Trello](https://trello.com/c/z08hU3Ov/360-retire-the-dummy-content-store)
> Remove reference to the dummy content store

- source/manual/data-gov-uk-2nd-line.html.md
This moves the monitoring section nearer the top, and fixes some broken links. 
[Trello card](https://trello.com/c/HPTO3Oof/136-combine-and-update-datagovuk-ckan-developer-docs)
> Update data.gov.uk support page

- source/manual/access-to-licensing-for-third-parties.html.md
Also the default branch is main now, so fix that too.
> Update licensify docs now that the Jenkins build is fixed

- .github/workflows/dependabot-auto-merge.yml
This workflow will auto-merge Dependabot PRs for selected internal dependencies if they're minor or patch version bumps.
https://trello.com/c/uwoMBinS/3015-create-proof-of-concept-for-auto-merging-internal-prs-5
> Add dependabot auto-merge workflow

- data/repos.yml
Trello: https://trello.com/c/rv3f6V9H/378-retire-side-by-side-browser
This application is being retired. It has been non-operational for an unclear amount of time due to being hosted on a personal Heroku account. Due to this strange hosting it has never been a full part of the GOV.UK stack.
We decided that, since to the very infrequent usage of transition, it was a better option to retire the app that try to resurrect it.
> Retire side-by-side-browser

- source/manual/2nd-line.html.md
There has been some debate about what their role is so this documents the current stance. The apprentice one had to be little more complex about line manager discretion as we currently have an exception to the rule that we wanted to codify.
> Clarify support role for juniors/apprentices

- .github/workflows/ci.yml
- Gemfile.lock
- Rakefile
- app/content_schema.rb
- app/document_types.rb
- data/repos.yml
- source/content-schemas.html.md.erb
- source/manual/add-a-new-document-type.html.md
- source/manual/add-translation-whitehall.html.md
- source/manual/architecture-deep-dive.html.md
- source/manual/conventions-for-rails-applications.html.md
- source/manual/intro-to-docker-advanced.html.md
- source/manual/rename-a-country.html.md
- source/manual/test-and-build-a-project-on-jenkins-ci.html.md
- source/manual/test-and-build-a-project-with-github-actions.html.md
- source/manual/world-taxonomy.html.md
- spec/app/content_schema_spec.rb
- spec/app/document_types_spec.rb
This updates dev docs following the recent move of schemas into publishing api.
[Trello](https://trello.com/c/ZUK2duYI/361-add-govuk-content-schemas-to-publishing-api-repo)
> Retire govuk schemas

- source/manual/keeping-software-current.html.md
- source/manual/publishing-a-ruby-gem.html.md
- source/manual/ruby.html.md
This adds documentation on the approach we take for managing Ruby versions with gems, this is added as documentation is this is not widely known. I've also added some links to documentation that may be used when updating Ruby to hopefully bring this to peoples attention (thanks for the suggestions Murilo, Ollie and Jonathan).
With our Ruby apps we aim to run them, in dev, CI and production on the newest Ruby version available. However with a Rubygem we aim for it to be compatible across the range of supported Ruby versions - this allows our apps to upgrade Ruby versions when the teams are ready and is friendly to anyone outside GDS who also uses the gems.
When supporting a number of Ruby versions it is better to run on the lowest version by default in development. This is because it …
> Add policy on Ruby versions for Rubygems

- data/repos.yml
This project was archived in October 2022, the functionality has been ported into content-tagger in https://github.com/alphagov/content-tagger/pull/1391
> Mark govuk_taxonomy_helpers as retired

- config/tech-docs.yml
- data/repos.yml
- source/manual/manage-ruby-dependencies.html.md
We have started using the Seal repo to alert of us Dependabot PRs and have archived the govuk-dependencies repo.
https://trello.com/c/Vl80xssv/3046-archive-govuk-dependencies
> Remove references to govuk-dependencies

- source/manual/alerts/rabbitmq-dead-nodes.html.md
- source/manual/alerts/rabbitmq-no-consumers-listening.html.md
- source/manual/deploy-puppet.html.md
- source/manual/on-call.html.md
- source/manual/removing-a-user-from-puppet.html.md
Fabric is an old tool that can no longer be used by [GOV.UK](http://gov.uk/) Devs. We should therefore remove all references to it from our docs and replace them with alternative commands
Fabric used to let us apply an ssh command across lots of machines. However in recent years the tool has become difficult for many devs to install.
It relies on an old deprecated form of python, and its dependencies cannot be installed today in a way that function.
It has still been referred to as a command in numerous places in [GOV.UK](http://gov.uk/) developer documentation, causing confusion for 2ndline shifts which are unable to use the tool.
This PR therefore seeks to remove said references. 
Trello: https://trello.com/c/AGdifoDb/250-remove-fabric-and-replace-references-in-docs
> Remove references to fabric

- source/manual/howto-block-arbitrary-urls.html.md
Fabric is now deprecated.
https://trello.com/c/AGdifoDb/250-remove-fabric-and-replace-references-in-docs
> Remove references to fabric scripts

- source/manual/alerts/search-api-learn-to-rank.html.md
The `View Extra Service Notes` link on Icinga for `Train and deploy LTR model for Search API` alert shows a 404 page when clicked.
This change adds a minimal page at the expected URL. This page serves only to point to the correct page at [https://docs.publishing.service.gov.uk/repos/search-api/learning-to-rank.html](https://docs.publishing.service.gov.uk/repos/search-api/learning-to-rank.html).
> Add missing `search-api` Learn to Rank alert document

- source/manual/where-to-find-what.html.md
This is no longer being used. The relevant contact numbers we need are in the "GOV.UK - So, you're having an incident" Google doc.
Trello card - https://trello.com/c/PSHgTLC9/137-remove-link-to-legacy-ops-manual-from-developer-docs
> Remove reference to the Ops manual

- source/manual/publishing-a-ruby-gem.html.md
Trello: https://trello.com/c/QrxjshEm/270-move-ruby-gems-from-jenkins-to-github-actions
This supersedes the Jenkins approach. As of today only a couple of applications are using Jenkins to release gems. Soon 
this will be zero and that functionality will be removed.
> Document GitHub Actions process to release a gem

- source/manual/pact-testing.html.md
Trello: https://trello.com/c/QrxjshEm/270-move-ruby-gems-from-jenkins-to-github-actions
With GDS API Adapters moving to GitHub Actions, most of the CI specific documentation is out of date. This change updates it to reflect the changes incurred by GitHub Actions.
There are a couple of notable changes with GitHub Actions:
1) There is not the concept of a parameterised build that can change CI
status, as per Jenkins, which means we can't do some delicate custom
builds to get a green tick. GitHub Actions does have the workflow
dispatch option, but this won't change a PR status. Therefore I've
suggested running locally
2) Pact runs aren't required checks pre-merge which will allow a
developer to merge in breaking pact changes.
3) We've switched from both consumer and provider having their own …
> Pact documentation for GitHub Actions

- source/manual/howto-modify-change-note.html.md.erb
- source/manual/howto-remove-change-note.html.md
These were previously edited or deleted by developers using rake tasks.
In https://github.com/alphagov/whitehall/pull/7131, we have introduced a user interface, so need to update the documentation to reflect this.
[Trello card](https://trello.com/c/bMwFRQ3e)
> Update process for editing Whitehall change notes

- source/manual/government-changes.html.md.erb
During a reshuffle, a minister can gain two positions of state, known as RoleAppointments in Whitehall. One of these is perceived to be a more senior role than the other. However, Collections will just render these by ascending order of ActiveRecord IDs as default.
We've built a UI into Whitehall so we don't have to manually hit the db via Rails console.
This updates the docs with instructions of how to access the UI.
https://trello.com/c/Tpq1mo6W/4-allow-ministers-roles-to-be-reordered-in-the-ui-probably-quite-a-large-task
> Update docs for reordering role appointments

- source/manual/content-security-policy.html.md
This does an overall update of our Content Security Policy documentation, which hasn't really been changed since 2019. It's updated to reflect the current status of the work and the somewhat long history.
We now have a new report system [1] which means we can now query reports again, this includes documentation on how to query the reports.
[1]: https://github.com/alphagov/govuk-aws/pull/1664
> Update Content Security Policy for new reporter

- source/manual/2nd-line-drills.html.md
- source/manual/howto-modify-change-note.html.md.erb
1. Expand on the Whitehall instructions. Though we shouldn't have to do this ourselves anymore, it's useful to know the feature exists.
2. Add Content Publisher instructions. It's not immediately clear that 'change notes' are a concept that exist in multiple publishing apps, so this serves as a useful reminder of that.
3. Frontload the warning about not making changes directly in Publishing API unless absolutely necessary. It's arguable that we should remove this section entirely, but it seems useful to know about the two different approaches to editing changenotes within Publishing API.
> Improve instructions for editing changenotes

- source/manual/2nd-line.html.md
We have a few special rules depending on the role of the person on 2nd line. It seems helpful to consolidate them into their own section, and link to the new-and-improved flow diagram.
This PR also clarifies that apprentices should only be given Production Deploy access.
> Create new "Role specific policies" section

- source/manual/query-cdn-logs.html.md
This step is no longer needed since
https://github.com/alphagov/govuk-aws/pull/1668.
We have now created a bucket and configured it for the primary workgroup so queries run without extra set-up.
> Remove query result location instruction

- .github/workflows/ci.yml
- .github/workflows/dependabot-auto-merge.yml
Currently the auto-merging workflow doesn't work as it doesn't have permission to merge to the repo, because not all PR checks have passed at the time the workflow runs.
This change uses https://github.com/marketplace/actions/wait-on-check to fix this.
I've tested the approach on a personal repo, here: https://github.com/ChrisBAshton/test-auto-merge/pull/1
Trello: https://trello.com/c/uwoMBinS/3015-create-proof-of-concept-for-auto-merging-internal-prs-5
> Make auto-merging workflow wait for tests to pass

- .github/workflows/ci.yml
- .github/workflows/dependabot-auto-merge.yml
PRs have started being 'stuck' on a 'test' GitHub Action that is seemingly never triggered:
This appears to be because the CI action with a key of `test` was recently given a `name` of "Run tests" (see
a869cc3b0bb987c778697943c7a841198bd16ce0), and a custom name doesn't seem to be compatible by the 'required status checks' configuration in govuk-saas-config:
https://github.com/alphagov/govuk-saas-config/blob/8cfb23db6a200214411fc1de150d3c8582950588/github/lib/configure_repo.rb#L106
There's no need for the custom name (other than making things a bit more explicit / readable), so we'll remove the custom name and revert to the action using the key name as its name.
> Fix hanging GitHub PR checks

- .github/workflows/ci.yml
We trigger our CI on both push (to branches, irrespective of there being an associated PR) and on `pull_request` (which triggers on any push to a branch which has a PR open - not just when the PR is first opened).
Consequently, we run two CI builds for each push, which is unnecessary and can slow us down (as sometimes one build langushes behind the other quite noticeably).
There should be no disadvantage to disabling build-on-push to branches which have no associated PR, except that any lint failures won't be brought to light. In practice, many branches are created directly from the GitHub interface, and a PR created in the same transaction, so this would only affect developers who create docs branches locally. In such cases, developers can always run their linter locally too.
> Stop building PRs twice

- source/manual/documents-arent-live-after-publishing.html.md
This came up on a recent 2nd line shift.
Trello: https://trello.com/c/bfAEuv4S/1576-consider-improving-documentation-on-the-consequences-of-running-representdownstream-rake-task-on-publishing-api
> Add note warning about possible unexpected draft publishing

- .github/workflows/ci.yml
Reverts alphagov/govuk-developer-docs#3816
This goes against our [agreed guidance on how CI workflows should run](https://docs.publishing.service.gov.uk/manual/test-and-build-a-project-with-github-actions.html#when-the-ci-workflow-should-run), with the biggest issue being that a merge to `main` would not trigger a build and could be disguising an issue if the branch was not recently rebased.
> Revert "Stop building PRs twice"

- .github/workflows/dependabot-auto-merge.yml
Currently, the auto-merger waits for CI to pass, before attempting to merge. However, the merge fails, as PRs require at least one approving review before merge.
We've already established the conditions under which an auto review is sufficient: a patch upgrade of govuk_publishing_components, where the associated CI checks pass. Therefore we already approve of the PR, we just need a mechanism to make that happen. We're using https://github.com/hmarr/auto-approve-action to use a GitHub Actions 'bot' to approve the PR.
I've tested this approach in:
https://github.com/ChrisBAshton/test-auto-merge/pull/2
Trello: https://trello.com/c/uwoMBinS/3015-create-proof-of-concept-for-auto-merging-internal-prs-5
> Make auto-merger wait on auto-approval of PR before merging

- .github/workflows/dependabot-auto-merge.yml
The auto-merge spike is failing to merge because we have disabled the "Allow GitHub Actions bot to approve PR" at the org level. Whilst we're evaluating the spike, we'll use a personal access token instead as a workaround.
I've created a fine grained access token with permissions only to read/write PRs for the govuk-developer-docs repository. I've tested that it should work in theory, by creating an identical token but for a test repository, where we can see the 'approve PR' step attempting to use the token:
https://github.com/ChrisBAshton/test-auto-merge/actions/runs/3757933226/jobs/6385682455
In the test case, it failed because I was also the person who raised the PR (`Error: Unprocessable Entity: "Can not approve your own pull request"`). This will not be an issue in …
> Use fine grained access token to auto-approve qualifying PR

- .github/workflows/dependabot-auto-merge.yml
In #3819, I added a personal access token to auto-approve a given PR. However, [it didn't work](https://github.com/alphagov/govuk-developer-docs/actions/runs/3758439417/jobs/6386787033).
Turns out I'd missed https://github.com/hmarr/auto-approve-action#approving-dependabot-pull-requests:
> When a workflow is run in response to a Dependabot pull request
> using the pull_request event, the workflow won't have access to
> secrets. If you're trying to use a Personal Access Token but
> getting an error on Dependabot pull requests, this is probably
> why.
> Fortunately the fix is simple: use the pull_request_target event
> instead of pull_request. This runs the workflow in the context
> of the base branch of the pull request, which does have access
> to secrets.
Trello: …
> Dependabot-specific fix for auto-approving via access token

- source/manual/new-instances-fail-to-provision.html.md
Our instances sometimes try to install ESM Ubuntu packages (which require authentication) before Puppet has configured the machine to allow said authentication. The machine then fails to provision.
I followed some troubleshooting steps from [an old Trello card](https://trello.com/c/rqu9XNb2/871-vms-outstanding-security-updates-errors) and confirmed that they work when I encountered this issue today.
> Document ESM auth issues

- source/manual/kibana.html.md
This was new to me - I'd previously been pasting long URLs inside backticks to get around third party parsers. The short URL is much friendlier to share with colleagues.
> Document Kibana "Short URLs"

- data/repos.yml
https://trello.com/c/LB4NJ3z5/3055-retire-upgrade-ruby-version-repo
> This repo was archived

- .github/pull_request_template.md
Broken link syntax now fixed.
Also converted to HTML comment as these instructions are aimed at developers, not intended to be included in the PR description itself. It's too easy to open the PR with the text included.
> Fix link syntax and convert to HTML comment

- source/manual/zendesk.html.md
"Access" is vague - often devs can _see_ a ticket but not respond to it. User Support understand what GDS Resolver Agent means.
> Use "GDS Resolver Agent" terminology

- source/manual/local-frontend-development.html.md
Updates the documentation on [local frontend development](https://docs.publishing.service.gov.uk/manual/local-frontend-development.html#using-startup-scripts-and-govuk-docker). Recent changes mean that local modifications to the startup script to access a local static must be more specific.
(credit goes to @theseanything for finding the solution to this problem)
> Update local frontend documentation

- data/repos.yml
The lambda fuctions from this repo were migrated to govuk-aws, except email_alert_notifications which is no longer used.
Trello card: https://trello.com/c/6hvNCAhx/2957-check-if-govuk-lambda-app-deployment-is-still-needed-and-retire-if-not
> Mark govuk-lambda-app-deployment as retired

- source/manual/govuk-env-sync.html.md
In putting together a presentation on data backups strategy, I dug into this a bit and it appears as though [Whitehall Integration pulls from Staging](https://github.com/alphagov/govuk-puppet/blob/f9c6b136d058b6e0e20fba5d3716b36e60462e2f/hieradata_aws/class/integration/whitehall_db_admin.yaml#L12), where the [data has already been sanitised](https://github.com/alphagov/govuk-puppet/blob/f9c6b136d058b6e0e20fba5d3716b36e60462e2f/hieradata_aws/class/staging/whitehall_db_admin.yaml#L32). The current docs are a bit misleading in that they suggest Integration always pulls from Production directly.
> Clarify that env sync pulls from Staging if data-sanitisation happens

- source/manual/gtm-change-process.html.md
Adds a change process for analysts and developers making changes to Google Tag Manager on GOV.UK.
Trello card: https://trello.com/c/WdqsuhbE/231-create-gtm-change-process
> Add GTM change process

- source/manual/debian-packaging.html.md
Add step for publishing a previous snapshot when managing debian packages.
> Add step for publishing a previous aptly snapshot

- data/repos.yml
Proposed new owners:
* `govuk-connect`: Platform Reliability (it's "platform")
* `govuk-docker`: Platform Reliability (it's "platform")
* `govuk-ithc-documentation`: Platform Reliability (it's historically been a Platform Health/Reliability task to aid the pentesters in their testing, and we recently oversaw a Trello card for our security contractor to review the ITHC documentation)
* `govuk-rota-announcer`: Platform Reliability (we already own other Slack based apps, i.e. Dependapanda and Seal)
* `govuk-user-reviewer`: Platform Reliability (it drives a 2nd line alert, which Platform Health/Reliability have historically helped implement/refine)
* `slimmer`: Find & View (it injects the user-facing header/footer & GOV.UK Components. The team also owns static)
> Update team ownership following retiring of Developer Tools group

- source/manual/configure-github-repo.html.md
The `GOV.UK Production Admin` team url has been renamed from `https://github.com/orgs/alphagov/teams/gov-uk-production` to `https://github.com/orgs/alphagov/teams/gov-uk-production-admin`.
> Fix broken Github Team URL

- source/manual/dns.html.md
- source/manual/google-cloud-platform-gcp.html.md
Previously we didn't mention the gds cli automation we have that wraps triggering the Jenkins build. There's a minimum of four Jenkins builds required (plan aws, plan gcp, apply aws, apply gcp) to deploy a change, so this automation makes life immensely easier.
I've documented this, and made it clear it's the preferred option. I've also pulled out the manual steps into their own section, and simplified the deployment instructions (now that they're not interleaved with instructions about getting credentials).
I've also recommended the poweruser role instead of the admin role, as DNS changes don't touch IAM so they don't need admin.
> Improve DNS deploy docs

- data/repos.yml
This add `accessible-autocomplete-multiselect` repo to the list.
This is currently a fork of `accessible-autocomplete` which is maintained by the GOVUK Publishing Service team.
https://trello.com/c/iNuMxfk4/893-adopt-kevins-fork-of-accessible-autocomplete
> Add `accessible-autocomplete-multiselect`

- data/repos.yml
I searched for govuk-dependencies in the Developer Docs and could not find any reference to it - we should include retired repos in the repos.yml file but mark them as retired, rather than delete as happened in #3774.
> Document the retiring of govuk-dependencies

- data/repos.yml
This was removed in #3830 but should have been kept but with a `retired: true`.
> Re-add reference to retired repo 'upgrade-ruby-version'

- source/manual/keeping-software-current.html.md
The [guidance](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) itself says:
> Rails version numbers are in the form Major.Minor.Patch. Major and Minor versions are allowed to make changes to the public API, so this may cause errors in your application. Patch versions only include bug fixes, and don’t change any public API.
Developers tend to merge patch versions freely anyway, but this always felt ambiguous against this guidance, so let's update the guidance to make it clear that it's fine.
> Clarify that patch versions of Rails can be merged without manual steps

- data/repos.yml
We [use this in govuk-secrets](https://github.com/alphagov/govuk-secrets/blob/ee9bcb5e60f7b77f5e91b317630539ff9b045e47/Gemfile#L12-L14).
Platform Reliability is the most appropriate owner for this.
> Add capistrano_rsync_with_remote_cache to list of known repos

- source/manual/dns.html.md
This documents learnings from a recent 2nd Line shift, in which we needed to delegate DNS for a non-`gov.uk` subdomain.
> Document DNS for non-gov.uk domains

- source/manual/2nd-line.html.md
My first commit to these docs - fixing a small typo. Because unfortunately, our SREs probably don't have Knighthoods.
> [BAU] Fix a Typo on 2nd Line Page

- source/manual/add-an-hmrc-manual.html.md
https://trello.com/c/5pJBXAQP/1784-documentation-for-hmrc-manuals-api-slug-add
> Add 2nd line instructions for adding an HMRC manual

- data/repos.yml
Smart Answers ownership is moving from I&P to user experience measurement, so mark it as so and redirect Seal / Dependapanda messages to their channel
https://trello.com/c/r0ChcHsm/1807-update-dev-docs-to-hand-over-smart-answers-to-uxm
> Transfer Smart Answers ownership from I&P to UXM

- source/manual/deploy-banner-to-certain-pages.html.md
We had to deploy a banner for some org pages on 2ndline as a result of a request during a mini-reshuffle. This documentation should be make it easier if we need to deploy another banner.
> Add docs for creating a bespoke banner

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
This moves the deploy job to a separate workflow that specific to deploying the site. It was unclear the purpose of the CI workflow as it did both testing and deployments. This makes the scope of each workflow well defined and more understandable.
This PR has no functional change.
> Move deploy job to separate workflow

- source/manual/emergency-publishing.html.md
This adds the documentation with instructions on how to deploy the banner using Kubernetes. It also removes outdated information about cache clearing, as this no longer apart of the process of deploying banner since cache times were shortened to 5 mins.
> Add emergency banner docs for EKS

- source/manual/emergency-publishing.html.md
This is an additional troubleshooting step to check different parts of the rendering stack to better locate the source of any issues.
> Add extra troubleshoot step to emergency banner

- config/tech-docs.yml
- source/manual/alerts/amazonmq-high-number-of-unprocessed-messages.html.md
- source/manual/alerts/amazonmq-no-consumers-listening.html.md
- source/manual/alerts/rebooting-machines.html.md
- source/manual/amazonmq.html.md
- source/manual/architecture-deep-dive.html.md
- source/manual/conventions-for-rails-applications.html.md
- source/manual/help-with-publishing-content.html.md
- source/manual/make-a-new-document-type-available-to-search.html.md
We've now migrated publishing-api's RabbitMQ usage onto AmazonMQ in all environments ([Trello card](https://trello.com/c/to4fHvoa/458-run-amazonmq-migration-process-on-production)). This means updating the developer docs in a few places to reflect the change.( [Trello card](https://trello.com/c/fIjdBjZb/468-update-developer-docs) )
I'm conscious that I've been very close to the technical details of this migration, and documentation is not my specialty - so I'm particularly interested in the opinion of those who haven't been. Does the addition of `/source/manual/amazonmq.html` make sense? Do the redirects and removals make sense? etc etc. All feedback most welcome.
> Update rabbitmq docs for amazonmq

- source/manual/manage-ruby-dependencies.html.md
This is an attempt to bring the guidance up to date, and to better reflect the actual working practices of GOV.UK developers. See [RFC-156](https://github.com/alphagov/govuk-rfcs/pull/156) for details of the informal survey we ran.
Our review process is (and should be) different when comparing major and patch versions of a dependency, and when reviewing a Rails core dependency bump vs some obscure library we may have included in Whitehall 8 years ago.
This commit documents the minimum review steps each PR requires, and also details how you can perform a more in depth review when it is needed.
It also reflects a change in policy around auto-merging, which we expect to enable on 'internal' dependency PRs in the coming weeks.
PS the documentation steps were based on me looking at two …
> Update "Reviewing Dependabot PRs" guidance

- source/manual/get-started.html.md
- source/manual/tech-lead-responsibilities.html.md
The seal no longer contains individual team members so no longer needs to be update for new starters.
Also removed from the tech leads responsibility section.
> Remove seal from get started

- config/tech-docs.yml
- data/rendering-apps.yml
- data/repos.yml
The rendering was moved to government-frontend
This updates the docs to reflect that.
https://trello.com/c/gICwB7Ej/1195-retire-service-manuals-frontend-app-m
> Retire Service manual frontend

- source/manual/get-started.html.md
also added a link to the reliability engineering site with better instructions
> updated AWS instructions to specify MFA name needed

- data/repos.yml
Part of [Work through list of missing repos tagged as govuk](https://github.com/alphagov/govuk-developer-docs/pull/3913).
`govuk-ask-export` is owned by the User Experience Measurement (UXM) team.
[Trello](https://trello.com/c/iJj8Qyjr/401-add-govuk-ask-export-to-data-reposyml)
> Add `data/repos.yml` entry for `govuk-ask-export`

- data/repos.yml
Part of [Work through list of missing repos tagged as govuk](#3913).
public-asset-checker is owned by the User Experience Measurement (UXM) team.
[Trello](https://trello.com/c/g7eHKMPo/402-add-public-asset-checker-to-data-reposyml)
> Add `data/repos.yml` entry for `public-asset-checker`

- data/repos.yml
Part of [Work through list of missing repos tagged as govuk](#3913).
govuk-google-analytics is owned by the User Experience Measurement (UXM) team.
[Trello](https://trello.com/c/gmY02y8h/403-add-govuk-google-analytics-to-data-reposyml)
> Add `data/repos.yml` entry for `govuk-google-analytics`

- source/manual/configure-github-repo.html.md
GOV.UK repos should be included in [the list of repos](https://github.com/alphagov/govuk-developer-docs/blob/main/data/repos.yml) because other things rely on that list.
> Adds requirement to include repo in list of repos

- data/repos.yml
Add the repo `alphagov/whitehall-prototype-2023` to `repos.yml`
> Add alphagov/whitehall-prototype-2023

- source/manual/2nd-line-drills.html.md
See commits for details. Merges some smaller tasks together, and removes some unnecessary ones.
At time of writing, we have 17 separate drill tasks, which take 17 weeks to rotate through under our current standard of 1 drill per week. One of 2nd line's OKRs is to increase our percentage of drills completed in a given time frame, so merging some of the less onerous drills together (where they're already related) will help.
On merge, I'll update https://docs.google.com/spreadsheets/d/1iopyMaXgdseUINzpjENJtg6AnHSqfiSmzKmliJua9KI/edit#gid=0 to remove rows and update anchor links.
> Review of drill tasks

- source/manual/get-started.html.md
The Get Started documentation implies that only tech leads or 2nd Line can review certain changes. This is not the case as it can be done by anyone with production access.
Updating the documentation to reflect this, since developers in the new starter's team are better placed to do this than 2nd Line or #govuk-developers.
> Change who can review changes in get started docs

- source/manual/get-started.html.md
New starters will need to set up their machines to access the GOV.UK Kubernetes cluster.
Adding a link to the relevant documentation until we have fully reviewed this guide to update it for the new platform.
> Add link to kubernetes set up instructions to get started guide

- source/manual/publishing-a-ruby-gem.html.md
Updates https://docs.publishing.service.gov.uk/manual/publishing-a-ruby-gem.html#ruby-version-compatibility
There appears to be a precedent for major version releases when Ruby versions are dropped, e.g. https://github.com/alphagov/gds-api-adapters/blob/main/CHANGELOG.md#2800.
Let's document it.
> Update "Ruby version compatibility" docs to disambiguate semver

- source/manual/howto-add-organisation-brand-colour.html.md
- was out of date
- extending to include a quick way of doing this, while hopefully still highlighting the correct way of doing this
Note that this change doesn't include a fix for the renamed rake task (e.g. `publishing_api:republish_organisation[slug]`) being wrong - apparently it doesn't work anymore. I don't know whether this needs to be changed or removed.
Runs but errors: 
```
17:28:37 warning: parser/current is loading parser/ruby31, which recognizes 3.1.3-compliant syntax, but you are running 3.1.2.
17:28:37 Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
17:28:37 rake aborted!
17:28:37 Don't know how to build task 'publishing_api:republish_organisation' (See the list of available tasks with `rake --tasks`)
17:28:37 Did you mean? …
```
> Update adding an organisation colour documentation

- data/repos.yml
- source/manual/pentests.html.md
The repo was archived https://github.com/alphagov/govuk-ithc-documentation/pull/185 and relevant documentation should live in the respective app repo. Sensitive information included in the private repos should live in the ITHC Google doc. 
This way is easier to keep information up to date.
https://trello.com/c/EJXbs0ae/3120-retire-govuk-ithc-documentation-repository-2
> Retire govuk-ithc-documentation

- source/manual/publishing-a-ruby-gem.html.md
This softens our previously documented stance: we now encourage releasing the dropping of EOL Ruby versions as minor gem upgrades, as opposed to major upgrades. This follows a [discussion on Slack](https://gds.slack.com/archives/CAB4Q3QBW/p1680164984754749) where the consensus was that it should be changed, for the reasons outlined in this document.
Note that I've also standardised the markdown links approach to use aliases as per the rest of this section, and have reordered the aliases alphabetically.
> Revise policy on semver RE dropping ruby versions

- data/repos.yml
We used this for generating the rota for Q1 and intend to keep using it. We even [presented it in the Software Engineering show and tell](https://docs.google.com/presentation/d/14eBhW5MR7EgWn5BWKaBuwD56pZ27ChfevRNuNhyR1lU/edit). Time to make it official!
This repo _may_ be merged with [pay-pagerduty](https://github.com/alphagov/pay-pagerduty) at some point, under a new name. But until that happens, let's get it documented here.
NB `#govuk-2ndline-tech` might be a more accurate 'owner' for this utility, but following the precedent set by similar utilities like govuk-user-reviewer and govuk-zendesk-display-screen, this should fall under `#govuk-platform-reliability-team`.
> Add govuk-rota-generator

- source/manual/emergency-publishing.html.md
This remove steps on how to deploy the banner in EC2 (no longer necessary as we serve traffic on EKS now) and simplifies EKS process by removing an unnecessary extra step to get the pod name.
> Simplify emergency banner docs

- source/manual/deployments.html.md
This adds links to help readers understand further whether process occur and are defined.
> Add links to the deployment documentation

- data/repos.yml
It is not an app, so I've left the repo entry.
> Remove duplicate whitehall-prototype entry

- source/manual/howto-backup-and-restore-in-aws-rds.html.md
To check for a newly created database via RDS instead of Route 53 because it's easier and makes more sense in this context.
> Update database restore docs

- source/manual/alerts/email-alerts-travel-medical.html.md
- source/manual/alerts/publisher-scheduled-publishing.html.md
- source/manual/documents-are-published-but-links-arent-updated.html.md
- source/manual/documents-arent-live-after-publishing.html.md
- source/manual/fix-out-of-date-search-indices.html.md
- source/manual/help-with-publishing-content.html.md
- source/manual/howto-add-organisation-brand-colour.html.md
- source/manual/howto-change-slug-and-create-redirect.html.md
- source/manual/howto-redirect-html-attachment-urls-from-whitehall.html.md
- source/manual/howto-remove-change-note.html.md
- source/manual/howto-remove-invalid-about-page-drafts-from-world-organisations.html.md
- source/manual/manage-assets.html.md.erb
- source/manual/redirect-routes.html.md.erb
- source/manual/related-links.html.md
- source/manual/rename-a-country.html.md
- source/manual/running-rake-tasks.html.md
We should be running rake tasks on EKS now, and these links to Jenkins may be confusing.
> Remove references to run Rake tasks on Jenkins

- source/manual/publish-special-routes.html.md.erb
No sense in duplicating the usage instructions.
> Link to up-to-date usage for special-route-publisher.

- source/manual/alerts/content-data-api-app-healthcheck-not-ok.html.md.erb
ETL job was moved from Jenkins to Kubernetes in https://github.com/alphagov/govuk-helm-charts/pull/1068 / https://github.com/alphagov/govuk-puppet/pull/12050.
https://trello.com/c/v9XYF5EB
> Update playbook for content-data-api ETL cronjob.

- source/manual/publish-special-routes.html.md
No idea why devdocs doesn't linkify URLs, but hey 🤷
While we're at it, make that a page a plain Markdown document instead of an ERB template, since it contains no Ruby.
Tested: renders as expected when running `bundle exec middleman server` locally.
> Fix un-linkified URL in Publish Special Routes.

- source/manual/kubernetes-infrastructure.html.md
- Removes some duplicated guidance and links
- Removes superfluous document history introduction
- Adds new 'Quick reference' section to top of file
- Adds some annotated detail to each 'task', replacing what was going to be a tutorial (but decided against it): https://github.com/alphagov/govuk-kubernetes-cluster-user-docs/pull/85#issuecomment-1514844034
> Add more detail to the EKS guide

- source/manual/retiring-a-repo.html.md
- source/manual/retiring-an-application.html.md
There are a few more steps than simply clicking 'archive' in the repo settings. This commit documents those steps and removes the duplication from the "Retire an application" steps.
> Document how to archive a repo

- .github/workflows/ci.yml
- source/manual/test-and-build-a-project-with-github-actions.html.md
This has been produced following the discussiona in: https://github.com/alphagov/govuk-developer-docs/pull/3950 and https://github.com/alphagov/govuk-developer-docs/pull/3816
This is to try resolve a consistency issue we have in GOV.UK where we have an agreed approach to using GitHub Actions documented which doesn't reflect the configurations used across GOV.UK.
Since we agreed the approach of running CI GitHub Action on `[push, pull_request]` and adopted it has become clear that this is not unanimously popular and, due to the appearance of duplicate jobs, can imply misconfiguration.
The motivation to document a new approach is to try form consensus on an approach that can be good enough for most cases and cover common concerns. This can then reduce the time we spend debating how to …
> Proposal on consistent approach for running GitHub actions

- source/manual/sentry.html.md
Hard-coded `active_sentry_environments` were removed in https://github.com/alphagov/govuk_app_config/pull/290
> Remove 'Ignoring environments' from Sentry docs

- source/manual/running-rake-tasks.html.md
The segment on EC2 is no longer relevant, to avoid confusion we should remove it.
> Remove redundant references to Jenkins in 'run a rake task' 

- source/manual/retiring-a-repo.html.md
Adds section about closing PRs and issues before archiving.
> Update docs on retiring a repo

- build.sh
- config.rb
- data/analytics/attributes.yml
- data/analytics/events.yml
- data/analytics/navigation.yml
- data/analytics/trackers.yml
- data/dashboard.yml
- helpers/analytics_helpers.rb
- source/analytics/analytics.html.md.erb
- source/analytics/approach.html.md.erb
- source/analytics/attributes.html.md.erb
- source/analytics/data.html.md.erb
- source/analytics/docs.html.md.erb
- source/analytics/events.html.md.erb
- source/analytics/pii.html.md.erb
- source/analytics/templates/attribute.html.erb
- source/analytics/templates/event.html.erb
- source/analytics/templates/tracker.html.erb
- source/analytics/trackers.html.md.erb
- source/layouts/analytics_layout.html.erb
- source/stylesheets/screen.css.scss
- spec/helpers/analytics_helpers_spec.rb
This change converts the existing [GA4 Implementation record](https://alphagov.github.io/govuk-google-analytics/) to be a sub-section of the GOV.UK developer docs. 
The original repository was held in this [GitHub repo](https://github.com/alphagov/govuk-google-analytics), was written using [Jekyll](https://jekyllrb.com/), and was hosted via [GitHub Pages](https://pages.github.com). 
Why convert? There are 3 main reasons:
* The team and other interested parties have decided to  make the implementation record the public face of GOV.UK's GA4 documentation.
* We should not use the [GOV.UK](http://gov.uk/) crown, unless we are hosting on a .gov.uk domain.
* We want the deployment of this documentation to be as simple as possible, and as much content as possible to be contained in easily edited …
> Add analytics documentation

- source/manual/alerts/RouterErrorRatioTooHigh.html.md
- source/manual/content-data-architecture.html.md
- source/manual/kubernetes-infrastructure.html.md
https://github.com/alphagov/govuk-helm-charts/pull/1102
https://trello.com/c/GO8lk2ql/1159-human-readable-ids-for-grafana-dashboards
> Replace machine generated grafana dashboard IDs with human readable versions

- data/repos.yml
#tech-interaction-and-personalisation is now #tech-content-interactions-on-platform-govuk, update repo ownership so that docs are correct and Dependapanda will post to the correct slack channel.
> Update slack channel ownership of CIOP apps.

- .github/workflows/ci.yml
The concept of the "deployed-to-production" branch no longer exists in GOV.UK infrastructure since we switched to a Kubernetes platform. Thus this branch is stale and no-longer represents the deployed version of Publishing API.
Switching this to "main" means that we will be using schemas from the version of Publishing API that is expected to be deployed - as Publishing API is continuously deployed.
> Use main branch of Publishing API for schemas

- source/manual/architecture.html.md
- source/stylesheets/screen.css.scss
The architecture diagram was looking a little out of date.
In particular:
- Mapit instead of locations-api
- manuals-frontend still there even though it's been retired
- info-frontend making calling out to performance platform (which has been retired)
I fixed these things in the source diagram, but that seems to have broken the original embedding code (draw.io has moved to diagrams.net, so I'm not surprised the embed broke).
This commit updates the embed, and attempts to size the diagram so it takes up more of the screen.
My CSS is a bit hacky, but the idea is "the whole view width, minus the sidebar and margins, appart from on mobile where it's the whole view width minus the margins". The 700px height is arbitrary. Seems to just about work.
> Update architecture diagram

- data/analytics/events.yml
- data/analytics/navigation.yml
- helpers/analytics_helpers.rb
- source/analytics/progress.html.md.erb
- source/analytics/templates/event.html.erb
- source/layouts/analytics_layout.html.erb
- spec/helpers/analytics_helpers_spec.rb
This change:
- Adds a new progress page for our analytics implementation
- Adds a link to the analytics layout page to the new progress page
- Adds status tags to each trackable event
- Updates the events data YAML file to add `implemented` and `priority` status tags
We want to have a visual representation of the teams progress.
[Trello](https://trello.com/c/JbLX3n2C/388-implementation-record-additions-and-improvements)
> Add progress page for analytics

- data/analytics/events.yml
- data/analytics/navigation.yml
- data/analytics/trackers.yml
- helpers/analytics_helpers.rb
- source/analytics/approach.html.md.erb
- source/analytics/data.html.md.erb
- source/analytics/docs.html.md.erb
- source/analytics/pii.html.md.erb
- source/analytics/templates/attribute.html.erb
- source/analytics/templates/event.html.erb
- source/analytics/templates/tracker.html.erb
- source/layouts/analytics_layout.html.erb
- source/stylesheets/screen.css.scss
- spec/helpers/analytics_helpers_spec.rb
Improvements to the analytics documentation (GA4 implementation record) including:
- broad text improvements
- all data for analytics events has been added, even if not implemented, to give us a better view of overall progress
- various visual and accessibility fixes
We're working towards a public release of this information.
Trello card: https://trello.com/c/JbLX3n2C/388-implementation-record-additions-and-improvements
> Analytics data update

- data/analytics/attributes.yml
- data/analytics/events.yml
Fixes missing/incorrect data on the link and step by step documentation.
> Improve link and step by step documentation

- data/analytics/navigation.yml
- helpers/analytics_helpers.rb
- source/analytics/approach.html.md.erb
- source/analytics/attributes.html.md.erb
- source/analytics/cookies.html.md.erb
- source/analytics/data.html.md.erb
- source/analytics/docs.html.md.erb
- source/analytics/events.html.md.erb
- source/analytics/pii.html.md.erb
- source/analytics/progress.html.md.erb
- source/analytics/templates/attribute.html.erb
- source/analytics/templates/event.html.erb
- source/analytics/templates/tracker.html.erb
- source/analytics/trackers.html.md.erb
- source/javascripts/cookie-consent.js
- source/layouts/analytics_layout.html.erb
- source/stylesheets/screen.css.scss
Adds GA4 analytics tracking to the implementation record pages, using Google Tag Manager. This includes:
- cookie banner
- default opt out
- Javascript to handle cookie consent/deny
- a cookies page where users can change their preferences and learn about cookies
Note that this only adds GA4 to the implementation record part of the site, not to any of the rest of the dev docs (the JS to do this is only included in the implementation record page layout).
Also updates all of the pages of the implementation record to have page titles, so that they can be more easily distinguished in GA4.
This PR is a slightly rush job so here's a quick list of things to fix soon:
- the JS needs refactoring and improving, ideally as a proper GOV.UK module (if possible)
- cookie handling in particular in the …
> Add analytics to the analytics pages

- source/manual/republishing-content.html.md.erb
The WorldwideOffice model in Whitehall is now publishable with an associated
presenter and content item.
---
> Add WorldwideOffice to the list of republishable models

- data/repos.yml
This adds https://github.com/alphagov/widdershins to the list of repos, and assigns an owner
> Add widdershins to the repos list

- source/manual/get-started.html.md
Two new team members have separately made the same assumption, and came up against the same error, when naming our MFA devices in AWS.
The assumption was that "must be prefixed" meant the name could, and maybe even should, also have a suffix.
However, we couldn't authenticate in the AWS console on the command line with the codes generated by devices with suffixed names. The only way to successfully authenticate was to add an MFA device and name it with the exact string of the email address.
> Add clarification about MFA device name

- source/manual/setting-up-new-rails-app.html.md
Update the docs for setting up a new application to reflect that Puma has replaced Unicorn as the web server [1].
[1]: https://github.com/alphagov/govuk_app_config/pull/286/commits/71f4f2fa3871721e5c8140bcf73d683e09d8d7b2
> Replace unicorn docs with puma

- source/repos.html.md.erb
I thought this was fixed in [#4007](https://github.com/alphagov/govuk-developer-docs/pull/4007) but missed this file
> Fix column heading for repos list

- data/repos.yml
The Access and Permissions team are now responsible for Signon.
I believe this change is enough to update the docs, dependapanda and seal.
> Move Signon to Access and Permissions team

- data/repos.yml
The GOV.UK Publishing Access and Permissions team are now responsible for the gds-sso gem.
> Move gds-sso to Access and Permissions team

- source/manual/github-unavailable.html.md
- source/manual/howto-checkout-and-commit-to-codecommit.html.md
Moving away from the shared credentials method of checking out code from CodeCommit as it is insecure and using IAM authentication instead.
> CodeCommit IAM authentication setup and update previous github unavailable process

- source/manual/get-started.html.md
Following feedback from recent GOV.UK starters I've updated the "Get started developing on GOV.UK" with a distinct step on GOV.UK User Reviewer, for more clarity of role and purpose, and a section on supporting services that a dev may need to access.
More info in the commits.
> Update get started: distinct user reviewer step and new supporting services step

- app/proxy_pages.rb
- app/repos.rb
- spec/app/proxy_pages_spec.rb
- spec/app/repos_spec.rb
Scraping docs from retired repos is more harmful than beneficial to user experience, because it causes unmaintained and often irrelevant pages to appear in search results. It also makes local development of devdocs painful because so many additional requests are made on startup.
Excluding these legacy pages will improve relevance of search results and make it easier for developers to find relevant, up-to-date information.
We already exclude retired repos from the lists of repos by category on `/repos`.
This doesn't stop us from scraping the repo metadata for retired repos/apps. Retired repos will still appear in search results when searching for all or part of their name, and we'll still generate pages for them under `/repos/${repo-name}.html`.
> Stop scraping docs from retired repos.

- source/manual/analytics.html.md
> Fix access to analytics link

- data/repos.yml
The GOV.UK Publishing Access and Permissions team are now responsible for the authenticating-proxy app.
> Move authenticating-proxy to Access and Permissions team

- source/manual/dns.html.md
I've refined the existing documentation to cover some specific quirks and provide some more detailed steps.
1. Explain that membership of specific Google Groups is required - and provide links to them.
2. Explain the relationship between Google and Terraform Cloud accounts. This tripped me up initially because I'd assumed it was a SSO flow, so I didn't understand why I needed to set an account password. This hopefully explains that a bit.
3. Advise users who to speak to if they have problems following the documented self-serve sign-up steps.
> Clarify how engineers can access Terraform Cloud

- source/manual/deploy-static.html.md
The aim here isn't so much to change the procedure, rather to document what's (more or less) already happening. The existing doc was clearly out of date and out of sync with the note in the Release app.
- Extract the playbook steps and the background info into separate sections.
- Update the playbook steps to reflect the current state of GOV.UK.
- Clarify why the clunky manual process is the way it is for now, so that it's easier to figure out when it's ok to change or eliminate it in future.
Please review for accuracy in particular :) It's entirely possible that I've made mistakes based on misinterpreting what I've read in the code or other docs while putting this together.
I'd also be open to deleting this entirely, if people feel it's not useful/discoverable enough to be worth keeping.
> Update the playbook for deploying Static.

- source/manual/rules-for-getting-production-access.html.md
In practice we don't supervise these users or do it for temporary periods of time. We typically use this approach for people who've joined and won't go through 2nd line (senior role or part of a managed service). So this updates this doc to reflect actual process.
> Remove temporary and supervised caveat for granted prod admin access

- source/manual/run-ab-test.html.md
Updates the docs on running A/B tests. The current docs are ambiguous when it comes to generating tests so this change should make it clearer. It also removes old links connecting to archived repos and provides more up-to-date examples to look at.
> Update documentation on running A/B tests

- data/repos.yml
[Trello](https://trello.com/c/a5yl1un5/544-create-separate-uxm-slack-channel-dedicated-to-bots-move-bots-to-new-channel-and-remove-from-old-team-channel)
The `team` in [repos.json](https://docs.publishing.service.gov.uk/repos.json) needs to `== team_channel` for [Seal notifications to work](https://github.com/alphagov/seal/blob/main/lib/team_builder.rb#L97). The User Experience Measurement Team have created a new Slack channel (user-experience-measurement-govuk-robot-invasion) for notifications. This aims to reduce noise in their main team channel. The channel name was updated for the Seal in [this PR](https://github.com/alphagov/seal/pull/430).
Updating the team name will also mean that the badger notifications are sent to the robot-invasion channel. It looks like badger notifications …
> Update ownership for User Experience Measurement repos

- source/manual/emergency-publishing.html.md
- source/manual/global-banner.html.md
- We no longer run Varnish.
- Update the troubleshooting steps to reflect that Jenkins is no longer involved, Static's template cache no longer persists across rollouts, etc.
- Simplify the structure to make the playbook steps easier to follow (e.g. separate non-essential / background information from playbook steps).
- Minor fixes for accuracy, clarity and house style.
- Add alt text descriptions for images.
Tested rendering locally with `SKIP_PROXY_PAGES=true NO_CONTRACTS=true bundle exec middleman server`.
> Update global/emergency banner playbooks.

- source/manual/dns.html.md
- source/manual/kubernetes-infrastructure.html.md
- source/manual/terraform-cloud.html.md
We're using it for more than just DNS rollouts now, and it feels increasingly odd to deep-link to a specific heading in the DNS doc page when referring to how to get Terraform Cloud access.
Giving Terraform Cloud its own page gives us room to document it fully.
> Create canonical doc for Terraform Cloud

- source/manual/slack-integrations.html.md
[Trello](https://trello.com/c/IZw96keW/552-add-docs-for-configuring-popular-govuk-slack-integrations)
To review:
`./startup.sh`
http://localhost:4567/manual/slack-integrations.html
> Add docs for configuring popular Slack integrations

- source/manual/alerts/search-reranker-healthcheck-not-ok.html.md
The logs are difficult to find from the AWS SageMaker landing page
> Add link to SageMaker endpoint

- data/repos.yml
This is used by GOV.UK engineers for getting to grips with the new platform.
> Add missing 'govuk-replatform-test-app' repo

- source/manual/on-call.html.md
This links to a table that shows the breakdown of on-call rates (e.g. the higher rate for bank holidays).
Not including the rates here as I'm not sure whether they should be public and don't want to include yet another thing we'll need to keep up-to-date.
> Add link to on-call allowance rates

- data/repos.yml
- spec/app/run_rake_task_spec.rb
- spec/fixtures/puppet-hieradata-common.yaml
Bouncer is on EKS: https://github.com/alphagov/govuk-helm-charts/blob/0043196/charts/app-config/values-production.yaml#L230
This also adds information on other apps. I'm hoping that by updating this .yml we can remove duplicated information in https://github.com/alphagov/release/blob/main/data/ec2_deployed_apps.yml and the risk of those two files getting out of sync.
> Update and specify hosts in the repos.yml

- source/manual/dns.html.md
The DNS changes need to be applied manually in order to go live. At the moment, the docs suggest that the apply is done automatically.
> Update steps for DNS changes to other government services

- data/repos.yml
These were all added in #3547, but without much context. We don't want to import _all_ Data Products' repos into the GOV.UK Developer Docs, just the ones that are pertinent to us. See justification in #4051.
By omitting the `govuk` topic from these repos, the Data Products teams have implied that these repos are not pertinent to GOV.UK and should therefore be removed from our repos.json list.
> Remove untagged repos

- data/repos.yml
govuk-s3-mirror is "important for GOV.UK to know about": https://github.com/alphagov/govuk-developer-docs/pull/3913/files#r1132282271
govuk-knowledge-graph-search "should be [referenced in the Developer Docs]. Not only it's going to be on signon alongside the publishing apps, but the dependency with gov.uk content is very strong so it's important that it's mentioned somewhere here, if only to link to its own documentation on the data community docs."
See
https://github.com/alphagov/govuk-developer-docs/pull/3913/files#r1132281588
There's a wider conversation to be had about how Data Products (and indeed other directorates like Pay and Notify) fit into GOV.UK. But in the meantime, our rough litmus test for whether or not an external repo should have the `govuk` topic (anf therefore be …
> Add undocumented Data Products repos where GOV.UK needs visibility

- app/repo.rb
- data/repos.yml
- spec/app/repo_spec.rb
`shortname` is the terminology used in the Release app, where exactly the same values have been provided there as they have here, e.g. `licence-finder` => `licencefinder`:
https://release.publishing.service.gov.uk/applications/licencefinder/edit
An app's 'shortname' is used for several things, all of which will probably go away at some point:
- name of the app in Puppet, e.g. https://github.com/alphagov/govuk-puppet/blob/603dc08f1a0e9148c844590d006ad22d0bc21737/modules/govuk/manifests/apps/licencefinder.pp
- Sentry DSN configuration, e.g. https://github.com/alphagov/govuk-saas-config/blob/ba6a612caa61920a57d388013b0a7968b51c60fd/sentry/Rakefile#L32
- For use in Graphite metrics
- Colloquially, e.g. "Contacts" shortname as opposed to "Contacts Admin" application name. (But not always, e.g. …
> Rename puppet_name to shortname

- source/manual/redirect-routes.html.md.erb
Update redirect routes documentation, replacing the GDS CLI and GOV.UK tools and code examples with EKS.
> Update redirect routes documentation

- data/analytics/attributes.yml
- data/analytics/events.yml
- data/analytics/navigation.yml
- data/analytics/trackers.yml
- source/analytics/further_docs.html.erb
- source/analytics/templates/event.html.erb
Update some of the information in the GA4 implementation record section, specifically:
- smart answers
- get emails and RSS link clicks
Also adjust how examples are contained in data and displayed, and adds a 'further reading' page in the docs listing our blog posts to date.
Part of the work to document our GA4 approach.
Trello card: https://trello.com/c/JbLX3n2C/388-implementation-record-additions-and-improvements
> GA4 implementation record updates

- app/proxy_pages.rb
- app/repo.rb
- app/repos.rb
- data/repos.yml
- source/apps.html.md.erb
- spec/app/proxy_pages_spec.rb
- spec/app/repo_spec.rb
- spec/app/repos_spec.rb
Defines new optional `app_name` property for our repos.yml config, to allow specifying multiple applications per repo.
This fixes the GitHub repo link (on various pages / JSON endpoints) for the two Licensify projects that live in the [licensify](https://github.com/alphagov/licensify) repo but do not share its name (i.e. `licensify-feed` and `licensify-admin`).
The Release app [will need updating)(https://github.com/alphagov/release/blob/8a2d2e1daefb41be3db6c0ce4bbbcc85f23fee72/app/models/repo.rb#L6) to use the new endpoint, as it cares about 'apps' and deployment status, as opposed to abstract repos. The `repos.json` endpoint is also used by govuk-dependencies, seal and govuk-saas-config but in these cases we _do_ care about the repo rather than the app, so they don't need updating.
We …
> Support multiple apps per repo in our data models

- data/repos.yml
`production_hosted_on` needs to be specified for a repo to be classified as and app.
It's necessary because we switched to use apps.json in the Release app in https://github.com/alphagov/release/pull/1210
manuals-publisher is hosted on EKS: https://github.com/alphagov/govuk-helm-charts/blob/bcfbda7b2dbc2a9cc21f6f6464c349d494ed45e5/charts/app-config/values-production.yaml#L1473
> Update production hosts

- source/manual/merge-pr.html.md
- Github runs CI tests against external PRs now, so we don't need to force that by making our own copy branches.
> Simplify external contributor instructions

- source/manual/configure-github-repo.html.md
Updated to:
- Remove reference to Production Deploy team having admin access to the repo. This is not the case (looking at a handful of production apps at random) and should never have been the case either, since it would leave apps vulnerable to privilege escalation. We only [use the team as 'metadata'](https://github.com/alphagov/govuk-infrastructure/blob/f97e2e420f875a3b5fb9d4a575a98de499c2b075/.github/workflows/deploy.yml#L84-L97) in deciding whether or not to allow merging.
- Removes link to old Jenkins job, now links to GitHub Action workflow instead.
> Remove ref to Production Deploy team & Jenkins

- source/manual/kubernetes-infrastructure.html.md
The example curl command doesn't render on a new line as the author intended.
> <img width="730" alt="Screenshot 2023-06-20 at 14 57 24" src="https://github.com/alphagov/govuk-developer-docs/assets/5111927/8c247541-3af7-45bf-a8d7-02430ce20793">
Better to just omit the example command altogether (we can expect engineers following these docs to know that they can run any arbitrary command once they've opened a shell).
> Remove example command

- data/dashboard.yml
So, even though the bulk of the Documentation can be found via search or via "Manual" in the site header, it isn't very intuitive for a user landing at the Dev Docs Dashboard/Home page.
This is just a small change that adds the following links to the landing page, as they are likely the most common destinations for someone arriving at the Developer Docs:
* 2nd-line Support Manuals
* Developer Documentation
* Kubernetes Documentation (hosted separately)
Here's what it looks like:
> [BAU] Add helpful links to Docs Homepage.

- data/repos.yml
#govuk-platform-reliability-team was renamed to
#govuk-platform-security-reliability-team
> Update docker-collectd-plugin owner

- Rakefile
- data/repos.yml
This adds some retired repos to our repos.yml file (for documentation's sake) and removes said repos from the 'verify deployable apps' check, since we won't need to check for them anymore.
> Update retired repos and 'deployable apps' check

- data/repos.yml
I searched the Developer Docs for `designprinciples` (as it is referenced in govuk-puppet) and nothing came up, because the repo name is `design-principles`. Keyword stuffing should fix the search.
> Add 'designprinciples' short name to `description` for retired repo

- source/manual/content-security-policy.html.md
As we've started to push the CSP into enforcement mode on a few applications, this updates the documentation to reflect that.
It also updates the guide on changing the CSP to put a greater emphasis on in app modifications as this seems to be an area that people don't know so well.
> Reflect CSP enforcement status in documentation

- source/manual/content-security-policy.html.md
As queries to Athena involve writing to an S3 bucket they can't be run as a readonly user. This seems surprising as you'd expect that you could run a query as readonly.
Hopefully this clarification stops people getting stuck.
> You need poweruser or greater access to query CSP

- data/analytics/events.yml
Adds the finder tracking to our analytics docs
> Add GA4 finder tracking docs

- source/manual/get-started.html.md
- source/manual/github-access.html.md
With many joining remotely, and many new starters being contractors, we need a more stringent process for giving access.
> Add clarification on how to ask for access

- source/manual/logging.html.md
- source/manual/logit.html.md
- source/manual/query-cdn-logs.html.md
- Rewrite "How logging works on GOV.UK" to reflect how it works since we moved to Kubernetes.
- Update the page about using Logit.io.
- Update the "Query CDN logs" page.
- Reorganise sections based around the intended topic and audience + edits for clarity and house style throughout.
Note to would-be reviewers: comments welcome, but if your review wasn't requested then I'll consider them nonblocking and may address them in a future PR.
> Revamp logging documentation.

- source/manual/logit.html.md
We currently have a 14-day retention window in Logit both for production and non-production.
Logit quota is quite expensive and I doubt we're getting value from storing integration/staging logs for more than a week.
I propose reducing the non-prod retention window from 14 to 7 days, saving $1092 / month ($832 / month once we drop the stacks for the old EC2/Puppet environments).
Raising this PR here for discussion/awareness since the actual setting is only in the Logit web UI.
Context: part of a broader push on [making logging more usable and cost-effective](https://docs.google.com/document/d/e/2PACX-1vS31XeKiFRcLmqcmjp2V6Zob-mxLV2oIALb_ZHj7MCK34-8Dko1PQCW0zjDtGG5cxLjChxKIN2g7f3x/pub).
> Keep non-production logs for one week instead of two.

- config/tech-docs.yml
- data/repos.yml
- source/manual/alerts/amazonmq-high-number-of-unprocessed-messages.html.md
- source/manual/alerts/amazonmq-no-consumers-listening.html.md
- source/manual/amazonmq.html.md
- source/manual/architecture-deep-dive.html.md
RabbitMQ docs is left unchanged (cache-clearing-service is used to show an example of binding). Only the govuk_crawler is still on self hosted RabbitMQ and there are plans remove it in the next couple of weeks so that doc can be removed then.
[GIFT week summer 2023 card](https://trello.com/c/ENPwB2vT/41-retire-cache-clearing-service)
[Tech debt card](https://trello.com/c/TX9wLihh/101-cache-clearing-app-exists-and-we-dont-think-its-necessary-replacing-cache-clearing-app-only-clears-path-not-query-strings)
> Remove Cache clearing service

- source/manual/github-access.html.md
In an offline conversation with @kevindew, we felt it was more appropriate that requests for GitHub access (where a team technical lead does not exist) is better routed to GOV.UK Senior Tech rather than 2nd Line.
> Tighten up instructions for teams without a tech lead

- source/manual/alerts/whitehall-scheduled-publishing.html.md.erb
- source/manual/government-changes.html.md.erb
- source/manual/republishing-content.html.md.erb
These were outputting commands like:
```
k exec deploy/whitehall -- rake publishing:overdue:list
```
...which would not work, as the pod name differs. It should actually be:
```
k exec deploy/whitehall-admin -- rake publishing:overdue:list
```
> Fix rake task snippets for Whitehall

- source/manual/test-and-build-a-project-with-github-actions.html.md
Reading this doc, it is already our policy to avoid unnecessary use of `name`. This commit just expands on some of the non-obvious reasons why that's a good idea (specifically with regards to the `test` CI job).
> Caution against providing a `name` for `test` CI job

- source/manual/alerts/email-alerts-travel-medical.html.md
The array that this link points to seems to have changed position and length since this document was updated. Let's just link to the first line of its definition.
> Update link in email-alerts-travel-medical.html.md

- helpers/url_helpers.rb
- source/partials/repo/_ownership.html.erb
- spec/helpers/url_helpers_spec.rb
This adds a hyperlink to the team Slack channel names so they can be clicked on.
> Link to team channels from repo pages

- source/manual/get-started.html.md
This step is not necessary as the relevant permissions should be granted in step 6. 'Get added to the GOV.UK user monitor system'.  
`admin` access is granted as it inherits from the `integration_admin_access` access level group. 
See: https://github.com/alphagov/govuk-user-reviewer/blob/48b85cd/config/govuk_tech.yml#L7 
The details are included in the govuk-user-reviewer README so there is no need to duplicate them here.
Also updated an anchor link in step 6.
I'm going to update the the user reviewer.
> Remove unnecessary instructions for aws integration access

- source/manual/retiring-an-application.html.md
Update to add information for retiring apps from EKS, and to note that several steps are now only valid for apps still being handled by puppet/jenkins.
> Update "retiring an application" documentation

- data/repos.yml
Add siteimprove_api_client gem to repos list.
> Add Siteimprove gem to repos list

- source/manual/get-started.html.md
- source/manual/setup-a-yubikey.html.md
- source/manual/using-a-yubikey.html.md
This updates the "Get started" documentation to reference the correct process for getting access to GitHub, AWS and other third party services.
Since govuk-user-reviewers now automates the process of apply permissions, joiners no longer need to manually give themselves permissions.
This also refactors the documentation to link to external documentation where possible.
> Update "Get started" documentation with new process for user permissions

- source/manual/2nd-line-drills.html.md
> Fix link for 'Update popular links' docs in 2nd line drill page

- source/manual/get-started.html.md
I intended to address a couple of problems with this PR and then the scope crept a little as I found other issues.
1. I noticed a new starter missed the Slack profile step and that it was rendering the list wrong
2. That things are a bit confused for tech lead help, so I wanted to make that an initial qualifier
3. That new starters may not realise they can't see the govuk-user-reviewer until they're added to GitHub
I also, while reviewing the doc following those issues, fixed a few things: 
- broken anchor links
- out-of-date slides link
- odd grammar to get started
- set frontend instructions as asides.
Full details in the commits
> Various minor improvements to "Get Started"

- source/manual/content-security-policy.html.md
This updates our documentation on the GOV.UK Content Security Policy to state that we now run this on our rendering applications in enforcement mode.
> Reflect that Content Security Policy is now enforcing

- data/repos.yml
These repos were owned by Platform Security and Reliability (PSR), however it makes more sense for them to be owned by Platform Engineering (PE). PE are retiring Puppet and Jenkins this quarter, which will render all of these repositories obsolete. In the meantime, therefore, there is no point in PSR attempting to make any improvements to these repos.
> Transfer ownership of some repos to Platform Engineering

- data/repos.yml
Unclear what this was for. Repo now archived. Not even worth keeping as a 'retired' repo in this file. Suspect it may have been used for developing in private (as needed sometimes, described here: https://docs.publishing.service.gov.uk/manual/make-github-repo-private.html ). These repos are ephemeral in nature and don't need to be recorded in the Developer Docs.
> Remove govuk-app-deployment-private

- data/repos.yml
This was temporary fork of docker-library/ruby which only had a single, trivial commit from 2 years ago that just changed a version number.
Considered archiving it, but that would be of negative value both to us and to the wider community.
> Delete govuk-ruby repo.

- source/manual/2nd-line-drills.html.md
- Delete obsolete "Drill detaching an instance".
- Update "Drill enabling a code freeze".
The manual page that the code freeze one links to almost certainly needs updating too, but that's for another PR.
> Update 2nd-line drills page.

- data/repos.yml
This was not replatformed in 2023, so no longer works. Nobody has complained or noticed that the service hasn't been reachable in several months, suggesting it is safe for retirement.
There is also a question as to whether metrics were ever that useful, as we’ve got alerts in Sentry.
> Archive govuk-sentry-monitor

- source/manual/retiring-a-repo.html.md
GitHub pages site commonly use URLs like this: https://alphagov.github.io/. If we retire a standard site like this (that has no custom DNS configuration on our side), then we should be mindful to update our docs and code beforehand because it would be a nuisance if something broke because it relied on this.
We should also be a little careful because we don't own the github.io domain. It could change ownership at some point, and we don't want to have to go through our archived repos to clean everything up when we could have done it at the time.
If we use a custom domain and disable the site, we're at risk of a domain takeover. That is: someone else could host a site using our URL.
We can protect against this by using [domain verification](https://docs.github.com/en/pages/configuring-a-custo …
> Retire GitHub pages sites carefully

- data/repos.yml
This reverts commit dc7dfda1a4c60213b32590c80340b3a628a04e53.
This completes transfer of ownership of `smart-answer` to On-platform Content Creation team
> Revert "Revert "Move smart-answers""

- source/manual/retiring-an-application.html.md
This adds a step about updating the architecture diagram to the guidance on retiring an application, which should help us keep an accurate picture of things.
> Add step to update the architecture diagram when retiring an application

- data/repos.yml
It's been decided that this sits better with the publishing platform team because they own transition and transition config.
Doc on change - https://github.com/alphagov/govuk-rfcs/blob/main/rfc-161-technical-direction-in-publishing-2023.md
> Update ownership of bouncer

- data/repos.yml
The nested_form gem is [only used by][1] the Publisher app. As is [customary with repo ownership][2] in GOV.UK, I've updated the owning team of this gem to #govuk-publishing-on-platform-content-tech since they [now own][3] the Publisher app.
Note that this gem is [considered to be tech debt][4] since it's not widely used or actively maintained.
[1]: https://github.com/search?q=org%3Aalphagov+nested_form+path%3AGemfile++NOT+is%3Aarchived&type=code
[2]: https://github.com/alphagov/govuk-developer-docs/pull/3913/files#r1132283866
[3]: https://github.com/alphagov/govuk-developer-docs/pull/4018
[4]: https://trello.com/c/0VmJQQRO/4-mainstream-publisher-uses-a-fork-of-a-gem-called-nestedform-which-is-no-longer-supported
> Update the owner of nested_form gem

- source/manual/dns.html.md
Related: https://github.com/alphagov/govuk-dns-tf/pull/64
> Remove independent-commission.uk from list of manually managed DNS zones

- source/manual/redirect-routes.html.md
Update from single points of contact to group email address.
> Update campaign redirect contact info

- source/manual/kubernetes-infrastructure.html.md
Moves the reminder closer to the commands that rely on it so that it's easier to spot.
> Move reminder to set kubernetes namespace

- data/rendering-apps.yml
- data/repos.yml
Whitehall no longer renders any public content, so we can remove all references to Whitehall Frontend.
[Trello card](https://trello.com/c/2wA7AA8J)
> Remove remaining references to Whitehall Frontend

- source/manual/dns.html.md
Make clear that there is a plan to migrate all domains into govuk-dns-tf.
Also removes all but one example domain, as this list is liable to falling out of date. Better to document how one can find out whether or not a domain is managed in Terraform.
> Link to pending domain migration work

- source/manual/dns.html.md
This duplicates https://docs.publishing.service.gov.uk/manual/terraform-cloud.html
> Remove "Getting Terraform Cloud access" section

- source/manual/zendesk.html.md
We should be reducing references to the (legacy) Interruptible SRE docs, only referring to it when absolutely necessary.
Let's point to our main DNS docs now, which are pretty comprehensive and which themselves link to the SRE docs where needed.
> Point to DNS documentation

- source/manual/zendesk.html.md
It took us a while to find the guidance for this so feels helpful to include here.
> Add guidance for automated SSL/TLS certificates

- source/manual/github.html.md
Fix a few broken or missing links on the GitHub index page.
> Fix broken links in GitHub docs

- source/manual/deploy-puppet.html.md
h/t @dj-maisy for tracking down the (ridiculously well-hidden copies of the) expired token.
Also fix headings to match house style.
> Remove workaround for broken Jenkins GitHub token.

- source/manual/kubernetes-infrastructure.html.md
We were lacking information on switching AWS environment. I've also frontloaded the 'common tasks' section and split out the 'prerequisites' section, as the former will be referred to time and again, and the latter should only be needed once.
Also nudges devs to use the [Rails console sandbox mode](https://andycroll.com/ruby/play-in-a-sandbox-in-production/) where possible.
> Tweaked Kubernetes cheat sheet

- helpers/properties_table_helpers.rb
This reverts commit 070b74540a3e0a5fb907a13003381545e59dabfa.
Whilst it succeeded in linking to a schema's associated document type...
> ![good](https://github.com/alphagov/govuk-developer-docs/assets/5111927/78219e66-f515-4824-ae31-6dcbf005e898)
...it also unexpectedly added links to things that were _not_ document types...
> ![bad](https://github.com/alphagov/govuk-developer-docs/assets/5111927/c286a625-4f4a-4fdf-aef5-e34371f5d95c)
Having the link apply only to document types requires too tight a coupling between govuk-developer-docs and content schemas, so it's simplest to just revert this, as it was only a micro optimisation in the first place.
> Revert "Make content schemas' "document_type" items linkable"

- source/manual/data-gov-uk-contracts-archive.html.md
We are completing the process of retiring this service, but the docs might still be useful if we ever need to reinstate it again.
Trello card: https://trello.com/c/lN55wEjL/3289-finish-retiring-contracts-finder-archive-3
> Update the Contracts Finder Archive docs

- data/repos.yml
Depends on https://github.com/alphagov/govuk-kubernetes-cluster-user-docs/pull/100
> Retire govuk-kubernetes-cluster-user-docs

- .github/workflows/ci.yml
The build is taking somewhere in the region of [12m](https://github.com/alphagov/govuk-developer-docs/actions/runs/6099566750) to [21m](https://github.com/alphagov/govuk-developer-docs/actions/runs/6098915283). The vast majority of the time comes from all of the GitHub API requests made by the build script, to pull in documentation from all of our external repos.
That's necessary for building and deploying the site, but is not necessary for CI.
_Occasionally_ we see issues with the build script struggling with unexpected characters etc in a remote file, but we haven't seen this in a long time. In the meantime, docs are painful to update because the build script takes so long.
Better to just test our local docs, and step in later if the deploy script fails.
> Skip proxy pages for CI

- source/manual/github.html.md
It was unclear whether Terraform handled this or not. There is indeed still a manual step whereby the user being added must accept the email invite before they're added to the alphagov org.
> Document that GitHub access relies on invitation

- source/manual/github.html.md
We had a page for this (source/manual/configure-github-repo.html.md) but it was removed in #4137 in an effort to consolidate our GitHub documentation. This commit better structures the revised docs, to make it clear this is a list of steps to follow, and to make it easier to find in search.
> Document setting up a new GOV.UK repo

- data/repos.yml
> Add a bit of context to retiring of govuk-cdn-config

- source/manual/notify-emergency-alerts.html.md
How we configure the `/alerts` endpoint has changed in the move to govuk-fastly - see changes for details.
Also, I've removed the section around manually enabling POP shielding. This was a limitation of Fastly's VCL insofar as it had to be set in the Fastly UI instead and then 'merged' into our config at deploy time.
Now, we manage some (but not all) configuration in Terraform. We now [enable POP shielding by default](https://github.com/alphagov/govuk-fastly/blob/ffd54b5c495a6daad6f6a774d53296924cb4e784/modules/www/service.tf#L83), using the london-uk datacenter ([see Fastly Terraform provider docs](https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_vcl)). We're no longer just enabling shielding on this specific backend.
> Update to refer to govuk-fastly

- README.md
Add command `./startup.sh` to the readme to start the application
> Add command to start the app on the README

- source/manual/github.html.md
Repeats info written in https://github.com/alphagov/govuk-user-reviewer#addingremoving-users, but worth having here for completion.
> Clarify how users are removed from GitHub

- source/manual/architecture.html.md
One day it would probably be good to consolidate our diagrams, but for now, adding a link here so it doesn't get lost.
> Link to Publishing's architecture diagram

- source/manual/transition-a-site.html.md
The bouncer deploy script was migrated to terraform and now doesn't run automatically when a subdomain is added to transition-config. There is also an additional domain verification step.
Given the plans to consolidate transition-config into the transition app, updating a doc seems sufficient at this stage.  The product team can later decide on automation of this process.
> Add a step to 'Transition a site to GOV.UK' docs

- source/manual/github.html.md
Previous docs didn't name the topics that you can use to configure the automation of your repo. That's now updated (and fixed in https://github.com/alphagov/govuk-infrastructure/pull/952).
It also makes it clear that you do need to manually trigger a build to run the automated setup in govuk-infrastructure.
> More comprehensive docs on how to set up repo

- source/manual/architecture-deep-dive.html.md
- source/manual/changing-organisation-slug.html.md
- source/manual/remove-site-from-transition-tool.html.md
- source/manual/transition-a-site.html.md
- source/manual/transition-architecture.html.md
[Trello](https://trello.com/c/puypazMP/817-update-documentation-for-transitioning-a-site)
The Publishing Platform team has enabled support for adding and removing sites and hosts directly through the Transition app, deprecating the previous process that involved transition-config.
**Note**: I have not updated the architecture diagram. I asked permission to access the source diagram but haven't heard back yet.
> Reflect the current transition process

- source/manual/backups.html.md
Removing this section as it was only aspirational and does not reflect any of the backups we actually have implemented.
Platform Security & Reliability [investigated using AWS Backup](https://trello.com/c/EENvDlD4/3229-decide-how-we-should-use-aws-backup-vaults) but concluded that the engineering effort would be quite considerable, and that we could get many of the benefits of AWS Backup by making relatively modest changes to our existing setup. We may revisit this in future, but for now, removing the section.
> Remove AWS Backup section from backups doc

- source/manual/transition-a-site.html.md
- source/manual/transition-architecture.html.md
The Publishing Platform team discussed whether to persevere in trying to locate the source for the diagram (not found in the arch-folder) and to rebuild the diagram, or remove it entirely.
We concluded that the system architecture is documented elsewhere, so we don't lose much by removing the outdated diagram entirely.
[Trello](https://trello.com/c/puypazMP/817-update-documentation-for-transitioning-a-site)
> Remove the outdated architecture diagram

- data/repos.yml
Merge after archiving [transition-config](https://github.com/alphagov/transition-config). (I don't have permissions to archive it myself.)
[Trello](https://trello.com/c/toGB61iI/809-remove-cron-job-that-imports-site-data-from-transition-config-to-transition-then-archive-the-transition-config-repo)
> Retire transition config

- source/manual/assets.html.md
- source/manual/manage-assets.html.md.erb
This question comes up quite often on 2nd line.
The limit is 500MB, imposed by our nginx config.
In practice, publishers would do well to keep far below this limit, for a variety of reasons.
That said, the biggest asset we have is 425 MB in size. I'll avoid linking to it directly here in case that info gets abused, but it's referenced in this Trello comment: https://trello.com/c/snmx8e2L/368-test-uploading-of-massive-pdf-to-whitehall-3#comment-5fe0840c15463b4930dd4c8e
> Document asset size limit

- source/manual/backups.html.md
This question comes up every so often, so let's document it.
Note from @martynipratt: when you request encryption on S3 buckets, it returns that the use of a KMS key is "False" but that doesn’t mean it’s not encrypted - just that it doesn’t use KMS as the encryption method.
> Add note about encryption at rest

- data/repos.yml
This app used to be used for monitoring the Elasticsearch queue pre-replatforming. It is no longer used, and its days are numbered as the GOV.UK PaaS is being switched off in December 2023.
https://trello.com/c/NikGC9ja/3319-retire-datagovukpublishelasticsearchmonitor-2
> Retire datagovuk_publish_elasticsearch_monitor

- data/repos.yml
Sidekiq Monitoring was switched off as part of replatforming to EKS.  Therefore marking the repo as retired.
Depends on https://github.com/alphagov/sidekiq-monitoring/pull/113.
> Mark `sidekiq-monitoring` as retired

- data/repos.yml
> Add govuk-mirror and govuk-dependabot-merger to repos.yml

- data/analytics/attributes.yml
- data/analytics/schemas.yml
Adds all of the new pageview attributes to our docs.
> Update GA4 pageview schema and attributes

- source/manual/data-gov-uk-2nd-line.html.md
This updates the documentation around CKAN api calls:
- adds a note about the default number of rows returned and how to change it
- adds an example for returning all datasets from a specific publisher (a common use case)
> Update ckan support page

- source/manual/2nd-line-drills.html.md
- Added links to accounts
- Updated password locations
- Removed duplicate for CKAN/datagov.uk as there is only one shared password
Trello card: https://trello.com/c/HxGp6kHH/2113-2nd-line-drill-drill-logging-into-shared-individual-accounts-eg-rubygems
> Update 2ndline drills doc

- data/repos.yml
As spotted by Chris Banks:
> govuk-related-links-recommender (the ML pipeline that used to augment hand-curated recommended links with auto-generated ones) has been disused since around the beginning of this year, isn't actually installed anywhere as far as I can tell
> Mark govuk-related-links-recommender as retired

- source/manual/fall-back-to-mirror.html.md
We've recently migrated the process to populate mirrors to EKS. This updates and improves the existing documentation:
- Change title to make it clear which type of mirror this is referring to
- Remove referrences to CloudFront as not relevant here
- Simplified explaination about how CDN serves traffic, better suited for arch documentation
> Update main documentation about GOV.UK mirrors

- source/manual/run-ab-test.html.md
We've retired govuk-cdn-config in favour of govuk-fastly, which means these docs need updating now.
The new process is significantly simpler than the old one (no Jenkins, no generating VCL configuration manually and committing it), but there are still some complexities around diffing the VCL which I've tried to call out.
I haven't mentioned the other govuk-fastly caveat, which is that it hits all three environments at the same time. That's surprising, but already documented in the govuk-fastly repo. For AB tests, it's probably not a massive problem having the environments locked together.
https://trello.com/c/jKWA7Nu3/543-ab-test-content-for-find-your-utr-number
> Update AB test docs to work with govuk-fastly

- source/manual/retiring-a-repo.html.md
Try to reduce the burden involved in archiving a repo (since we want people to archive disused stuff and not be put off by a big toily process) by clarifying that there are situations where e.g. it may be overkill to add a signpost to the README (in addition to the banner that GitHub adds anyway).
Also simplify some of the wording and make it a bit clearer as to why the remaining toil is needed.
> Update the checklist for archiving a GitHub repo.

- data/repos.yml
Nav team is no longer responsible for these apps.
https://trello.com/c/5uSILmtp/2200-router-and-router-api-cleanup-tasks-s
> Move Router and Router-API Ownership to Platform Engineering

- data/analytics/events.yml
I realised the file attachment docs were out of date, so I've updated it in this PR. Thanks :+1:
> Fix GA4 file attachment docs

- source/manual/codeql.html.md
- Grammatical tweaks
- fix YAML example
- move alias links to bottom of each section, for consistency
- remove hard newlines mid-sentence, for consistency
> Tweak CodeQL documentation

- source/manual/howto-find-hardcoded-markup-govspeak.html.md
This makes the following changes:
- includes instructions for a rake task that has been added to Whitehall
- updates the title to be more reflective of the content
- removes instructions linking to the wiki that are no longer valid (running GovGraph on Jenkins)
- updates the instructions for accessing a Publishing API Rails console to reflect the current infrastructure
[Trello card](https://trello.com/c/jD9VLG1A)
> Update documentation for finding usage of Govspeak in content

- source/manual/logging.html.md
Adding URL to internal Vulnerability Scanner policy
> Added vulnerability Scanner docs

- data/repos.yml
This repo has been archived, so it needs to be removed from the repos.yml file.
> Remove repo govuk-intent-detector

- data/repos.yml
This is owned by the #data-products team, as per this Slack thread:
https://gds.slack.com/archives/C015XA8KC4F/p1698236780002839
> Add the repo govuk-analytics-engineering

- data/repos.yml
https://github.com/alphagov/govuk-exporter
> Add repo govuk-exporter

- data/repos.yml
Builds were failing because I'd forgotten to mark this repo as private in #4273 / 1909d6603bf333aea9950f3bab85e06d425b60c4.
> Mark govuk-analytics-engineering repo as private

- app/github_repo_fetcher.rb
- app/http.rb
Build logs currently produce 100ks of log lines - every request / response header of every HTTP request. Feels like a bit much.
Faraday documentation says they can be turned off: https://github.com/lostisland/faraday/blob/5fccc208549650b129b13a173af3f3f40d44c14d/docs/middleware/included/logging.md?plain=1#L79
After this change, we still get logs, but only for the URL of the request and the status code of the response:
I, [2023-10-20T17:20:53.404626 #75707]  INFO -- request: GET https://api.github.com/users/alphagov/repos?per_page=100
I, [2023-10-20T17:20:54.871930 #75707]  INFO -- response: Status 200
I, [2023-10-20T17:20:54.999323 #75707]  INFO -- request: GET https://api.github.com/user/596977/repos?page=2&per_page=100
I, [2023-10-20T17:20:56.319073 #75707]  INFO -- response: Status 200 …
> Don't log every header of every HTTP request

- data/repos.yml
As per https://docs.publishing.service.gov.uk/manual/github.html#create-and-configure-a-new-gov-uk-repo
The PR to add a README to this repo is still open: https://github.com/alphagov/govuk-chat-infrastructure/pull/1
> Add govuk-chat-infrastructure

- source/manual/2nd-line-drills.html.md
> Fix typo in URL to documentation on how to fall back to CloudFront

- source/manual/pagerduty.html.md
Update docs for pagerduty drills as they have been moved to alertmanager
https://trello.com/c/atcbGHh1/2156-move-pagerduty-drill-out-of-puppet
> Update pagerduty drill docs

- data/repos.yml
- source/manual/pact-testing.html.md
[Trello card](https://trello.com/c/7f3F6Xij/3338-migrate-from-the-old-paas-based-pact-broker-to-the-new-instance-on-heroku)
Our Pact Broker instance is being migrated from PaaS to Heroku.
> Update Pact Broker URL

- source/manual/request-fastly-tls-certificate.html.md
The names have changed in the UI since these instructions were written.
> Update names of TLS configurations

- data/repos.yml
Seal isn't hosted on Heroku anymore. I should've removed this in #4250 but missed it somehow 🙈
> Remove a broken link from repos.yml

- data/analytics/attributes.yml
- data/analytics/events.yml
- data/analytics/trackers.yml
- source/analytics/templates/event.html.erb
Updates the [GA4 implementation record](https://docs.publishing.service.gov.uk/analytics/) part of the dev docs to match actual live events.
Part of the GA4 migration.
Includes a new jump menu for the events pages, to allow easier navigation to different events within the same category.
Trello card: https://trello.com/c/JQPHy26m/661-check-implementation-record-is-up-to-date
> Update analytics section

- source/manual/2nd-line-drills.html.md
- source/manual/fall-back-to-aws-cloudfront.html.md
[Trello card](https://trello.com/c/s0zckoYC/2164-2nd-line-drill-drill-cdn-failover)
We performed this drill for the first time on 2nd line this week, and noted several gaps/confusing things in the documentation. This PR addresses those.
> Update documentation around CDN failover, and associated drill

- source/analytics/approach.html.md.erb
Update dev docs on our current development approach to GA4 tracking.
Our approach has changed since this doc was written.
Trello card: https://trello.com/c/Xwp7dgJN/294-tracking-auditing-tracking-by-default
> Update GA4 dev docs on tracking approach

- app/repo.rb
- source/partials/repo/_links.html.erb
- spec/app/repo_spec.rb
Adds logit links - these links for apps go to a now-3h view in Kibana/Logit.io filtered to the appropriate app, showing time/request/status and message, giving people an easy way into viewing appropriate logs.
https://trello.com/c/n8ZCNgzv/189-add-logit-links-into-apps-pages-links-in-dev-docs
> Add Kibana urls to app pages

- data/analytics/attributes.yml
Adds `alt/option` click to the examples for `method`
> Add alt/option click to GA4 docs

- source/manual/get-started.html.md
The `backend` machine class doesn't exist any more so: `gds govuk connect --environment integration ssh backend` fails.
`jumpbox` still exists and works so updating the instructions to use that.
> Update the command used to test AWS connectivity

- data/repos.yml
The GOV.UK Design System owns this repo and it shouldn't be listed here, just as their other repos aren't.
> Remove stylelint-config-gds repo

- source/manual/2nd-line.html.md
We should use the term "Technical 2nd Line" consistently throughout the docs, so I fixed some here. 
Plus some other tidying up, and removed the potentially confusing word "downtime" :)
> Consistent naming of Tech 2nd Line, and more

- source/manual/howto-block-arbitrary-urls.html.md
> Fix Markdown link syntax

- data/analytics/attributes.yml
- data/analytics/events.yml
- data/analytics/schemas.yml
Update the implementation record (GA4 events data).
- add action link events in browse pages
- remove `link_path_parts` references as no longer in use
- update `taxonomy_all` and `taxonomy_all_ids` as now strings, no longer objects
Part of the GA4 migration.
Trello card: https://trello.com/c/lstNprcf/717-add-tracking-to-action-link
> Analytics browse update

- source/manual/ruby.html.md
The use of a service account/machine user was a workaround to replicate someone creating a trivial PR, but is not recommended as it is a security loophole.
> Update Ruby doc

- app/repo.rb
- app/repos.rb
- source/gems.json.erb
- spec/app/repo_spec.rb
- spec/app/repos_spec.rb
Created endpoint to list all GOV.UK gem repositories, in the same fashion as the already existing apps.json and repos.json
This is to aid the [gem-release-alert](https://github.com/alphagov/gem-release-alert) application.
> gems.json endpoint

- source/manual/migrate-to-dart-sass-from-libsass.html.md
https://trello.com/c/pfadNyDZ/2197-dart-sass-add-documentation
Add docs on migrating to Dart Sass from LibSass.
[Rendered version](https://github.com/alphagov/govuk-developer-docs/blob/e95adfcafe487ec9ec2fd71e35d27f2deb19c4e3/source/manual/migrate-to-dart-sass-from-libsass.html.md)
> Migrate to Dart Sass from LibSass

- source/manual/dns.html.md
Thoughtworks completed a DNS delegation document for us, which we should link to from here. As per a recent security recommendation, I'm linking to a Drive 'search' page instead of the document directly, to avoid external folks being able to request access to it.
Also removes the section about what to do about manually managed hosted zones, since these should all have been imported into Terraform now.
Trello: https://trello.com/c/xSv4EfX1/1547-hostmaster-tasks-you-may-encounter-domain-delegation-and-domain-validation-requests
> Update dns.html.md to refer to new doc

- source/manual/zendesk.html.md
Update the Zendesk leaver ticket documentation to advise that the leaver ticket can be closed if no reference is found when searching the `govuk-user-reviewer` repository.
This should help improve the process when dealing with leaver tickets and avoid creating Trello cards that require no further action. Currently, the only other action to do when a user is not listed in either govuk_tech or govuk_non_tech, is to check if they are a member of a GitHub team, for which we already have automated checks in place for.
> Update ZenDesk leaver ticket process

- data/analytics/attributes.yml
- data/analytics/events.yml
- data/analytics/schemas.yml
- data/analytics/trackers.yml
Update the GA4 implementation record. See individual commits for details.
Part of the GA4 migration.
Trello card: https://trello.com/c/s6uLhovR/751-add-tracking-browser-copy-events
> Implementation record document copy event

- source/kubernetes/create-app/index.html.md
This adds a documentation page on how to get a brand new app up and running on the Kubernetes platform.
> Add basic documentation for new app on k8s

- data/analytics/events.yml
Updates a very small thing in the implementation record for GA4 event data, browse pages.
I missed adding it in a previous PR.
Trello card: https://trello.com/c/mI6jxJru/752-fix-indexes-on-action-links-when-more-than-one-link-present
> Amend GA4 browse data

- source/manual/get-started.html.md
2 new starters on the team have missed this.
When I asked in slack others had already asked - in fact it's in the `reliability-eng` channel header.
***Making it bold and obvious***
> Make the note about AWS MFA device name bold

- source/manual/alerts/email-alerts-travel-medical.html.md
Somehow the update to the Grafana URLS did not make it into the original PR.
> Grafana Dashboard Fix for travel/medical alerts page

- data/repos.yml
[Trello](https://trello.com/c/Ls0VAovK/737-junior-dev-suitable-change-the-name-of-the-user-experience-measurement-govuk-robot-invasion-slack-channel-and-move-the-various-n)
The team's previous channel `user-experience-measurement-govuk-robot-invasion` caused some slight confusion on which team monitors the channel, so we decided to rename our channel to `dev-notifications-ai-govuk`.
I've also amended the ownership of the `public-asset-checker `to the `analytics_team` (note: this will change to a different channel, more likely a front-end slack channel).
> Update ai-govuk repos ownerships

- source/manual/test-and-build-a-project-with-github-actions.html.md
As described in the documentation change, we no longer define
`test` jobs, and now define `CI` workflows, which work slightly
differently insofar as they're made up of several parallel jobs.
This commit makes a few other updates, including:
- Remove reference to small steps within a CI workflow:
We've actually been heading in the opposite direction: lots of
small steps defined within the CI workflow. This is partly because
we're now making use of a lot of shared workflows, so what we lose
in ease of local development, we gain in cross-GOV.UK consistency.
- Remove old example code
Looking at the Content Publisher GitHub Actions, we no longer have
the complexity referred to in these docs. I've deleted the docs
that are no longer relevant.
I've kept the instructions for testing Ruby gems, as …
> Update guidance: `test` "job" is now `CI` "workflow"

- data/repos.yml
Mark `govuk-google-analytics` repo information as retired.
Repo has been archived and content moved here.
Trello card: https://trello.com/c/xaWtlQ8O/754-archive-repo-for-govuk-google-analytics
> Retire govuk-google-analytics

- Rakefile
- data/repos.yml
- source/manual/architecture-deep-dive.html.md
These were replaced by govuk-mirror in October 2023.
> Mark govuk_crawler_worker and govuk_seed_crawler as retired

- data/repos.yml
The prototype is no longer in use for design experimentation.
> Mark whitehall prototype 2023 as retired

- data/repos.yml
This repository is no longer in use because the work that was informed by this analysis has been completed.
> Retire the Whitehall Asset Analysis repository

- data/repos.yml
The content-store migration from Mongo to Postgres is now completed, we're no longer running content-store-proxy, and we've archived the content-store-proxy repo. So we need to update the description of the repo in these pages to reflect that.
[Trello card](https://trello.com/c/sQIA1Q7d/977-update-all-content-store-documentation-relevant-to-mongo-postgres-switch)
> Update content-store-proxy description after archiving the repo

- data/repos.yml
We've recently added a new repo for development of a visual editor based on ProseMirror.
> Add govspeak-visual-editor to repos

- source/kubernetes/contact-platform-engineering-team.html.md
Also mention that we host the CMS as well as the website itself.
> Fix a grammatical error.

- data/repos.yml
This is really just hacking around a bug (#4259), but for now it seems that when a private repo is listed in repos.yml without `private_repo: true`, CI [fails](https://github.com/alphagov/govuk-developer-docs/actions/runs/7450974838/job/20271040876#step:6:646) in at least some circumstances.
> Fix `alphagov/govspeak-visual-editor not found` in CI.

- data/analytics/events.yml
Adds GA4 event data for details elements, like on this page: https://www.gov.uk/government/organisations
Part of the GA4 migration.
Trello card: https://trello.com/c/xhASj1rp/765-add-tracking-to-details-component
> Add GA4 event data for details elements

- source/javascripts/application.js
Fix the search. The search should work internally, but [recent changes](https://github.com/alphagov/govuk-developer-docs/pull/4376) broke the JS for this, so instead search was going to an external Google search result page.
Specifically:
- extra JavaScript from the components gem (for GA4 tracking) has conflicted with existing JS in the tech docs gem, specifically the modules start code
- the JS modules start code in the gem only works for modules that have an `init` function, but the tech docs gem code is based on older JS (using jQuery) where the module is initialised with a `start` function
- to fix this we include a reworked version of https://github.com/alphagov/govuk_publishing_components/blob/main/app/assets/javascripts/govuk_publishing_components/modules.js here, with manual …
> Fix JS modules initialisation

- data/repos.yml
None of these have been touched in 5 years.
[Have checked in Slack](https://gds.slack.com/archives/CHR4UQKU4/p1704194218367839) and we're fine to archive them.
> Remove ancient data products related repos

- source/manual/data-gov-uk-2nd-line.html.md
Add a link to the Grafana dashboard for datagovuk apps on the datagovuk 2ndline support page.
> Add Grafana link to data-gov-uk-2nd-line.html.md

- source/manual/data-gov-uk-2nd-line.html.md
- source/manual/databases.html.md
Also add an example to the _Databases on GOV.UK_ page (so people don't have to backtrack if they come across that page first).
> Update examples for connecting to CKAN DB with psql.

- source/manual/howto-modify-change-note.html.md.erb
Unfortunately at present only Whitehall and Content Publisher have an automated method for updating change notes. Hopefully this note will save time spent on 2nd line looking for something that isn't there.
The Publishing Experience team will look into providing a better way of doing this going forward, as it's obviously something that comes up on 2nd line fairly often.
> Document change note update process for publishing apps

- data/repos.yml
https://trello.com/c/HutMFiHP/2329-retire-email-alert-monitoring-application
> Mark email-alert-monitoring as retired

- source/manual/access-to-licensing-for-third-parties.html.md
This updates the Third Party Documentation for the Licensing app stack. It provides examples of how to use the `kubectl` command line to interact with the apps in the cluster and how to perform basic checks, as well as how to find and update the configuration and update secrets.
> Re-write the Licensing Third Party Docs for the EKS Move

- source/manual/access-to-licensing-for-third-parties.html.md
This addresses a few typos in the Argo CD environment links, and formats the digital.cabinet-office.gov.uk email domain to look nicer.
> Licensify Third Party Docs: Address Typos and Email Formatting.

- source/manual/access-to-licensing-for-third-parties.html.md
This is needed for accessing the clusters for the first time.
> Add steps for setting up kubectl context for licensify

- source/manual/access-to-licensing-for-third-parties.html.md
Typo in the alias flag and making setting env vars cred consistent.
> Fix commands in third party access for Licensify

- source/manual/purge-cache.html.md
[Trello card](https://trello.com/c/zuGLgJZe/3399-have-a-procedure-for-cache-invalidation-with-cloudfront)
Adds documentation for how to purge the cache for our standby CloudFront distributions.
> Add docs for purging the standby CDN's cache

- source/manual/reindex-elasticsearch.html.md.erb
This is the process that is run to adopt OpenSearch schema changes within search-api.
People are meant to clean up old indices once they're content that their change worked, but this has a habit of slipping through the net.
This process is eminently automatable, but writing it down helps, as does the instructions for finding out the state of the search cluster.
> Add preflight checks to OpenSearch reindexing

- data/repos.yml
> Update Licensify to be hosted on EKS

- source/manual/amazonmq.html.md
The Hiera encrypted YAML stuff is no more.
It's not really feasible for us to eliminate this shared login and it's not really offering any meaningful extra defence-in-depth anyway since the dashboard is only reachable from inside the VPC (and it'd be pretty hard to change that by accident).
So it's moving to `pass` for now until we get a better solution for necessary-evil shared creds such as these. https://github.com/alphagov/govuk-secrets/pull/1520
> Fix up signpost to the shared MQ dashboard login.

- data/repos.yml
This was removed in #4424, but is still used by search-api: https://github.com/alphagov/search-api/blob/faf0e74546aa3a491c19c648e61ada17c3f58329/Gemfile#L26
> Re-add rack-logstasher

- data/repos.yml
Following convention in #4424, we'll remove these rather than mark them as retired, as they have little value in being surfaced in the developer docs from now on.
> Remove two more repos from repos.yml list

- source/manual/backups.html.md
The backups page still had a reference to content-store running a Mongo cluster - this PR removes it
> Remove reference to content-store Mongo cluster

- source/manual/data-gov-uk-architecture.html.md
A general tidy up of this page, plus removing out of date information about subdomains which no longer exist.
> Remove more outdated info about DGU subdomains

- source/manual/incorrect-content-in-search-or-navigation.html.md
This adds something about working with external search engines - identified as a documentation gap in a recent incident review.
(I also fixed the heading levels)
> Add link to Google Search Console guidance

- data/repos.yml
Better to just remove this one than keep it around cluttering up search results.
> Delete icinga_slack_webhook from the list of repos.

- source/manual/zendesk.html.md
I keep digging out the link from https://github.com/alphagov/govuk-developer-docs/commit/8ec753a39e8f2f02a6decd0c2727d37e778d6f56, so it should really be added to the docs.
> Link to advanced search options

- source/manual/zendesk.html.md
This updates the Zendesk guidance to state that you should include a copy of any commands that are executed directly on a console as internal notes on Zendesk tickets.
By including the commands, it helps the next shift (and/or product teams) understand what has already been attempted and identify any possible problems that could arise.
> Add information about including code snippets as Zendesk notes

- source/manual/conventions-for-rails-applications.html.md
- Fix broken links (closes #4448)
- Add feature test code example
- Clean up the code more generally
> Fix "Conventions for rails apps"

- source/stylesheets/screen.css.scss
- cookie banner was recently updated to be hidden when JS is disabled
- but we had styles in here that also handled this behaviour, which were aligned with the component until the change
- removing unnecessary styles fixes the problem
- fortunately cookie consent was still being done correctly, even though the banner wasn't disappearing
> Fix cookie banner showing when it shouldn't

- data/repos.yml
This repo has been archived,so can be marked as retired in the list of repos.
> Mark `govuk-user-journey-analysis-tools` as retired

- data/repos.yml
Now removed the `govuk` topic from the repo.
A [chat on Slack](https://gds.slack.com/archives/CARGH33JS/p1707320417551859) concluded that this repo is owned by the Design System and should not be monitored here.
> Remove 'govuk_frontend_toolkit_gem'

- source/manual/data-gov-uk-2nd-line.html.md
This simply adds a link to documentation on querying CDN logs, especially useful now [the data.gov.uk ones are in Splunk](https://github.com/alphagov/govuk-developer-docs/pull/4460).
> Add link to CDN logs docs

- source/manual/2nd-line.html.md
- source/manual/rules-for-getting-production-access.html.md
- source/manual/tech-lead-responsibilities.html.md
- source/manual/zendesk.html.md
We no longer process leavers on 2nd line. It is currently handled by members of Senior Tech, but is also ultimately a Platform responsibility and should be handled internally there, rather than delegated to 2nd line.
This commit therefore removes documentation that instructed devs to raise leavers tickets.
It also softens the documentation around revoking access if you will be away for 6 months, since we don't consistently do this in practice.
> Remove references to "leavers tickets" on 2nd line

- source/manual/incident-management-guidance.html.md
Also updates the owner of the doc
> Add link to incidents spreadsheet

- source/manual/ab-testing.html.md
This adds a link to the AB test log, which could be useful for troubleshooting. 
It also tidies things up a bit - removing old references and moving some things around
> Adds link to the AB test log

- data/repos.yml
This tool has not been running since Jenkins was switched off and the repo is being archived.
> Retire govuk-ask-export

- source/manual/data-gov-uk-2nd-line.html.md
This reinstates links to Logit and Grafana (and fixes one unrelated typo)
> Fix links in datagovuk docs

- source/kubernetes/before-you-start/index.html.md
- source/kubernetes/get-started/index.html.md
- source/manual/get-started.html.md
- Link to GitHub's guide to setting up SSH instead of (not) maintaining our own.
- Cut out some verbose/unnecessary prose which detracts from the already fairly complex procedures.
- Fix highlighting of shell examples and make them easier to copy/paste.
[Preview](https://github.com/alphagov/govuk-developer-docs/blob/sengi/getting-started/source/manual/get-started.html.md)
> Update Getting Started on GOV.UK.

- source/manual/alerts/email-alerts-travel-medical.html.md
- Add missing instructions for re-sending a medical safety alert email.
- Edit for clarity.
- Use lists where appropriate.
- [House style].
[House style]: https://www.gov.uk/guidance/style-guide/technical-content-a-to-z
[Preview](https://github.com/alphagov/govuk-developer-docs/blob/sengi/email-alert-playbook/source/manual/alerts/email-alerts-travel-medical.html.md)
> Revamp travel/medical email alert playbook.

- source/manual/setup-a-yubikey.html.md
Unfortunately we're still stuck with old phishable OATH OTPs because of aws-vault etc. but we can at least use U2F for logging into the web UI now that AWS supports having more than one MFA device per IAM user.
Fixes #4319.
[Preview](https://github.com/alphagov/govuk-developer-docs/blob/sengi/fix-yubikey-instructions/source/manual/setup-a-yubikey.html.md)
> Fix instructions for setting up Yubikeys with AWS.

- data/repos.yml
This moves ownership of 2 apps and a gem to the Publishing Platform team.
> Switch ownership of some publishing-related apps

- source/manual/databases.html.md
This link was to a point in time document from 2022 and is not maintained. The information in it is outdated and risks being misleading as time continues to pass by. I'm not aware of an alternative document that is kept up-to-date (the GOV.UK dependencies sheet doesn't have the DB engine specificity https://docs.google.com/spreadsheets/d/137KZhjctJ8qTKYPnq2QNVkyoIC6ok7KA2G1vErNC6Oo/edit#gid=0)
> Remove link to database engines

- data/repos.yml
These repos and their README files still show up in search, which makes it harder to find relevant information.
~~Are we trying to [compete with Google](https://killedbygoogle.com/)?~~
> Remove retired repos

- source/manual/emergency-alerts.html.md
- source/manual/how-to-rotate-fastly-api-keys-for-emergency-alerts.html.md
- We only provide them one token now, because it's not a very privileged token. Having separate tokens per environment was no better for security and definitely worse for maintainability.
- Remove extraneous detail. The details are already in the linked playbook on changing the token.
- In the playbook, mention an acceptable way to transfer the token after generating it.
- Use the same Markdown heading syntax as the rest of devdocs.
> Update docs on Emerg. Alerts Fastly automation token.

- source/manual/access-to-licensing-for-third-parties.html.md
- source/manual/get-started.html.md
The GDS Request an AWS Account Tool is being migrated off PaaS this month.
From a user perspective, the tool will still function exactly as before, although the URL of the tool will change. For the time being, the current URL for the tool will redirect to the new URL, which is: https://request-an-aws-account.gds-reliability.engineering
The change is going live by the 26th February.
Via email from Patrick Berkeley
> Update "Request an AWS account" URL

- source/kubernetes/cheatsheet.html.md
- source/kubernetes/get-started/access-eks-cluster/index.html.md
- source/kubernetes/get-started/index.html.md
- Omit unnecessary detail and commentary.
- Keep the document focused on being a quick-reference.
- Avoid duplicating information from elsewhere in devdocs, except where it's important to the quick-reference purpose of the document.
- Add an example for listing available Rake tasks.
- Add a couple of links to further information.
- Use numbered and unnumbered lists appropriately.
[Preview](https://github.com/alphagov/govuk-developer-docs/blob/sengi/clean-up-k8s-cheatsheet/source/kubernetes/cheatsheet.html.md)
> Clean up k8s cheatsheet.

- source/content-schemas.html.md
- source/document-types.html.md
- Add a short paragraph about how document types and content schemas relate to each other. (Could use a fact check on this — hopefully I've not introduced any inaccuracies!)
- Fix wrong information about importing CSV data into Google Sheets.
- Remove redundant empty `[]` from reference links.
- House style / general tech writing style fixes: prefer active voice, delete unnecessary "Note:" prefixes, etc.
> Clarify docs on document types and content schemas.

- source/manual/changing-organisation-slug.html.md
it was introduced after a section got deleted
> Fix really small numbering error

- data/repos.yml
Remove govuk-technical-2ndline-dashboard which is now retired
> Remove govuk-technical-2ndline-dashboard

- source/manual/howto-backup-and-restore-in-aws-rds.html.md
Turns out you need two newlines and precisely 4 spaces before the blockquote for it to render properly.
> Fix blockquotes in RDS restore playbook

- config/tech-docs.yml
- data/rendering-apps.yml
- data/repos.yml
Trello:
https://trello.com/c/jBC7bj9r/2382-mark-app-as-retired-in-the-various-places
> Retire info frontend

- data/repos.yml
This adds govuk_chat to the repos.yml file. I've added a new type of `AI apps` as it doesn't fit the other categories.
> Add govuk-chat application to repos.yml

- data/repos.yml
Causing a check to fail: https://github.com/alphagov/govuk-saas-config/actions/runs/8138204601/job/22238440069
> Remove retire flag until we archive Github repo

- data/repos.yml
This is more likely to reach relevant engineers.
As well as the docs, this config powers the Release app's [deploy badger](https://docs.publishing.service.gov.uk/manual/slack-integrations.html#release-app-badger). I think it will get more response going to the new channel.
> Update the licensing team slack channel

- source/javascripts/filter-list.js
Fix a small bug in the filtering functionality recently added to some pages in the implementation record.
The JS was using `innerText` but we include hidden elements to match the title of the sections on events by type. `innerText` is less reliable than `textContent` as it doesn't include hidden text, and during testing it produced some slightly odd results. This change fixes them.
None.
Trello card: https://trello.com/c/m6vL7lJy/186-add-filters-to-events-and-attributes-pages-on-implementation-record
> Fix implementation record filtering

- .github/workflows/ci.yml
- .github/workflows/security.yml
See #4333.
These checks take a while to run and they don't do anything useful with Markdown, so avoid running them on changes that only touch Markdown files.
We still run all the checks on changes that touch docs that can contain embedded Ruby (`**/*.html.erb`).
Also update the checkout action.
> Only run static analysis tools on code changes.

- source/manual/backups.html.md
- Focus on describing the backup policies and strategies for each type of database.
- Summarise key parameters in a table instead of describing them in prose.
- Omit a lot of unnecessary detail which is better covered in (for example) Amazon's docs. Link to them in a couple of places where appropriate.
- Avoid going into details that are covered in restore playbooks, because that makes it harder to find the right information in a DR situation.
[Preview](https://github.com/alphagov/govuk-developer-docs/blob/sengi/backups/source/manual/backups.html.md)
> Restructure + rewrite Backups overview page.

- data/repos.yml
Mark repo as retired.
Trello: https://trello.com/c/sWZM0a38/2387-archive-repo-in-github
> Retire info-frontend

- source/manual/retiring-an-application.html.md
The mark an app as retired step is already covered in the last step [1] in the retiring an app doc and doing this prematurely of archiving the repo will cause consistency checks to fail in govuk-sass-config [2].
Also updates the kube command for retrieving resources for an app as the old command doesn't return anything.
Trello:
https://trello.com/c/Mv4qiBEI/2386-check-and-remove-kubernetes-resources
[1]: https://docs.publishing.service.gov.uk/manual/retiring-a-repo.html
[2]: https://github.com/alphagov/govuk-saas-config
> Update retire app docs

- README.md
There's no advantage to running devdocs inside govuk-docker as far as I can tell. It's much easier and quicker — especially for external contributors — to run it directly using Bundler.
Issue #4528 is an example of where the complexity of the previous build/run instructions prevented an external contribution.
Folks can still use govuk-docker if they wish, of course.
Fix some minor style issues along the way, like avoiding unnecessary use of the passive voice and preferring the imperative mood in section headings.
[Preview](https://github.com/alphagov/govuk-developer-docs/blob/sengi/readme/README.md#govuk-developer-docs)
> Update build/test instructions in README.

- data/analytics/events.yml
- source/analytics/templates/event.html.erb
In the GA4 implementation record, where an event occurs on a component, document and link to the component guide page for that component. This is done per-event, as some event groupings apply to more than one component.
Part of improving the implementation record for users.
> Add components to implementation record

- source/kubernetes/cheatsheet.html.md
kramdown is buggy (or at least quirky in a way that I couldn't figure out within a few minutes) with regard to nested lists that contain paragraphs.
Fixes #4528.
Credit to @userbradley for raising the issue.
> Fix buggy formatting in k8s cheatsheet.

- source/manual/dns.html.md
Updating the location of the terrafrom cloud check for post PR merge as the link from the PR didn't lead me to the correct Terraform Cloud check.
> Update location of the Terraform Cloud check

- source/manual/alerts/signon-api-user-token-expires-soon.html.md
- Put the sections in order so that e.g. the information about special cases is presented before the reader starts down the non-special-case procedure.
- Avoid ambiguity and unnecessary choices in the procedure.
- Call out that this is toil and should be eliminated; we just haven't got around to it yet.
- Fix syntax highlighting in source examples and make them easier to copy-paste by using code blocks.
- Use ordered lists for procedures where the order of steps is important.
- Split up a bunch of compound steps into simpler, individual steps that are hopefully a bit easier to follow.
- Remove the step where we trigger a rolling update of the application; [reloader](https://github.com/stakater/Reloader) takes care of this automatically.
- Give a practical example of testing an API call …
> Update playbook for rotating a Signon API token.

- data/analytics/events.yml
- source/analytics/events.html.md.erb
- source/analytics/events_by_group.html.erb
- source/javascripts/filter-list.js
Changes to the events pages on the GA4 implementation record, specifically:
- rename tabs on the events pages to better reflect their content
- rename top level events to more closely match their events types (where possible)
- minor event data additions
- fix a missing bit of functionality on the events pages where form submission wasn't being prevented, which could frustrate users (as it's in-page filtering)
Part of improving the implementation record for users.
Trello card: https://trello.com/c/7pwKVz4k/188-update-names-of-tabs-on-implementation-record
> Implementation record events listing updates

- source/manual/github-unavailable.html.md
- source/manual/howto-checkout-and-commit-to-codecommit.html.md
During the drill we discovered a number of things which can improve the docs:
- add missing tags, the `docker push` would fail otherwise
- re-enable auto-sync after confirming that the deployment of the image from code commit has worked
- use `govuk-replatform-test-app` rather than `whitehall` as the example as we spent quite a long time downloading and waiting for `whitehall` to build, and we should be able to make visible changes to the test app without affecting a live service.
> Updates following the codecommit drill

- data/analytics/navigation.yml
- source/analytics/consent.html.md.erb
- source/analytics/docs.html.md.erb
Updates the GA4 implementation record with a link to the data docs and consent handling information.
Part of improving the implementation record.
Trello card: https://trello.com/c/MrU0YOd5/757-update-implementation-record-with-consent-handling-gtm-blocklist-information-and-data-docs-link
> Ga4 consent

- source/manual/manage-assets.html.md.erb
Some of the rake tasks require the ID, but we are sometimes only provided with the URL when the request to remove it comes through Zendesk.
> Add section on how to get an asset's ID

- source/manual/alerts/signon-api-user-token-expires-soon.html.md
It is possible to trigger the cron job through the Argo user interface, which is probably easier than working out how to login to run the command.
Therefore adding this as an alternative method.
> Update Signon key rotation docs

- source/manual/development-pipeline.html.md
While drilling deploying a code freeze on 2ndline we noticed that this set of documentation is now out of date.
While you previously just had to check the Freee deployments checkbox on the applications edit page on release, you now need to manually run a GitHub Action to toggle off CD.
This updates the docs to reflect this.
https://trello.com/c/KgWxwGzt/2289-2nd-line-drill-code-freeze
> Update deploy code freeze documentation

- source/analytics/docs.html.md.erb
- source/analytics/events.html.md.erb
- source/analytics/templates/event.html.erb
Adds the following to the GA4 implementation record:
- fix link to data docs
- add links from events page to GA4/Looker studio reports for traffic for those events
- minor code cleaning
Part of improving the GA4 implementation record for users.
> Make improvements to the GA4 implementation record

- source/manual/howto-add-organisation-brand-colour-logo.html.md
Update the existing documentation for adding organisation brand colours, to also include adding organisation logos.
There appears to be quite a few other steps involved when amending or adding new organisation logos that we did not have documentation for.
[Trello card](https://trello.com/c/QtTiOIWM/2420-create-documentation-for-updating-organisation-logos-m)
> Add documentation for Organisation Logos

- .github/workflows/security.yml
Permissions have changed due to integration with Code scanning.
> Update Snyk permissions

- Gemfile
- Gemfile.lock
- app/string_to_id.rb
- spec/app/string_to_id_spec.rb
- Add some tests.
- Don't "crudely remove HTML tags"; use a library that does it properly. Not a huge deal cos this is only gonna see semi-trusted input, but it's not a good look to be rolling our own with that.
- Remove comments that just give false reassurance.
- Use the simplest string functions for the job rather than hitting everything with the regex hammer.
Fixes https://github.com/alphagov/govuk-developer-docs/security/code-scanning/2.
Gemfile.lock changes were generated by `bundle install`.
Alternatives considered:
Since we're already pulling in `activesupport`, we could just use `ActiveSupport::Inflector::parameterize` and do away with this little utility module altogether. I assumed that would probably break a bunch of existing links to heading anchors, though. (If not then …
> Make StringToId more robust to arbitrary input.

- .gitignore
- data/analytics/events.yml
- data/analytics/trackers.yml
- Adds the filter events to the docs
- Adds the focus loss tracker to the docs
- Updates the `.gitignore` as it tries to add `node_modules` to your commits and `.DS_Store` if you've ever worked with images in this repo
> Add GA4 'filter' events to the analytics docs

- source/manual/publishing-a-ruby-gem.html.md
[Trello card](https://trello.com/c/bYVP288R/3447-5-automate-release-of-new-gem-versions)
So far this new workflow has only been rolled out to PSR repos, but let's get the docs updated now in case any other teams want to try it out.
> Add autorelease workflow docs

- data/analytics/trackers.yml
Updates links to some GA4 analytics documentation following [changes in govuk_publishing_components](https://github.com/alphagov/govuk_publishing_components/pull/3963).
None.
Trello card: https://trello.com/c/j2SEemPJ/195-extend-developer-documentation-to-help-developers-other-devs-use-ga4-tracking-on-govuk-components
> Update GA4 links

- data/analytics/attributes.yml
- data/analytics/events.yml
Update the GA4 implementation record. See individual commits for details.
To keep the information stored here accurate and up to date with the latest changes.
None.
Trello card: https://trello.com/c/6OGGsNFt/811-add-error-action-to-formerror-event-on-contact-form
> Implementation record updates

- source/manual/slack-integrations.html.md
The instructions for teams have changed.
https://github.com/alphagov/seal/pull/512
https://trello.com/c/2ucOpKId/3455-simplify-configuration-architecture-for-seal-dependapanda-3
> Update Seal instructions

- data/repos.yml
https://trello.com/c/6GdfNb6n/3482-move-gem-alerts-into-seal-and-retire-gem-release-alert-repo
> Remove retired repo

- source/manual/retiring-an-application.html.md
Puppet isn't used any more, so it's not necessary to differentiate Puppet/EKS steps in retiring an app.
> Remove puppet steps from retiring an app

- source/manual/github-unavailable.html.md
Do not enable auto-sync if Github is unavailable.
> Only re-enable auto-sync at end of drill or when Github is available

- data/repos.yml
Adds the following repos - used by the mobile app development team:
-  govuk-mobile-android-homepage - [Jira](https://govukverify.atlassian.net/jira/software/projects/GOVAPP/boards/405?selectedIssue=GOVAPP-409) | [GitHub](https://github.com/alphagov/govuk-mobile-android-homepage)
-  govuk-mobile-android-onboarding - [Jira](https://govukverify.atlassian.net/jira/software/projects/GOVAPP/boards/405?selectedIssue=GOVAPP-395) | [GitHub](https://github.com/alphagov/govuk-mobile-android-onboarding)
-  govuk-mobile-android-services - [Jira](https://govukverify.atlassian.net/jira/software/projects/GOVAPP/boards/405?selectedIssue=GOVAPP-396) | [GitHub](https://github.com/alphagov/govuk-mobile-android-services)
> Add Android mobile module repos

- source/manual/get-started.html.md
The link to the instructions in govuk-user-reviewer for adding a user was broken (the referenced section within the page doesn't exist)—update the link to point to the correct section of the document.
> Fix link in get-started.html.md

- source/manual/conventions-for-rails-applications.html.md
This updates our conventions to reflect the demise of Rails.application.secrets which will be removed in Rails 7.2.
It reflects the view that Rails.credentials is not suitable for our use case and that really we don't need anything special since we're just using env vars and can just reference secrets in our config files since they come from env vars.
A thing to note is that for apps migrating from config/secrets.yml they will not need to set anything up for secret_key_base. Rails automatically generates secret_key_base values in dev and test environments and automatically reads the ENV["SECRET_KEY_BASE"] env var [1]. So if this is all in app has in secrets.yml then the file can just be deleted.
[1]: https://api.rubyonrails.org/classes/Rails/Application.html#method-i-secret_key_base
> Document Rails secret approach post Rails 7.1 deprecations

- source/manual/amazonmq.html.md
`gds govuk connect` was specific to the old Puppet infrastructure. Neither exists any more.
Plus some minor edits.
[Preview](https://github.com/alphagov/govuk-developer-docs/blob/sengi/mq/source/manual/amazonmq.html.md)
https://github.com/alphagov/govuk-infrastructure/issues/1267
> Fix instructions for connecting to RabbitMQ web UI.

- source/manual/2nd-line.html.md
- source/manual/pagerduty.html.md
This PR updates the documented time for the PagerDuty drill to address the difference in UTC and BST times.
The drill is documented as being triggered at 10am UTC and 10am BST (and should be 10am UTC and 11am BST).
> Update PagerDuty drill time

- source/manual/github.html.md
The ticket should be tagged with `govuk_platform_support` so it's triaged to appropriate view.
> Update Getting access to GitHub

- source/manual/gtm-change-process.html.md
- source/manual/implementation-record.html.md
Updates some of the GA4 documentation, specifically the GTM change management process and adds a page about keeping the implementation record up to date.
The change management process has changed and analysts are asking for a guide to updating the implementation record.
Trello cards:
- https://trello.com/c/kmqdNjDm/209-update-gtm-publishing-change-process-to-new-bau
- https://trello.com/c/mO7L5dPh/164-intro-to-updating-the-implementation-record
> GA4 doc improvements

- config/tech-docs.yml
- source/kubernetes/contact-platform-engineering-team.html.md
- source/manual/ask-for-help.html.md
- Add a redirect from /platform-engineering so we have a stable URL to use in other docs such as repo READMEs.
- Add some links to Slack channels for convenience.
- Minor edits for clarity.
> Update links to Platform Engineering team.

- source/manual/manage-assets.html.md.erb
The innocent-looking extra indent on this example macro wreaks havoc with the formatting of the rest of [the doc](https://docs.publishing.service.gov.uk/manual/manage-assets.html#removing-an-asset) 😅
> Fix broken formatting in "Removing an asset".

- source/manual/rename-a-country.html.md
Updating the documentation for renaming a country following the recent change made to Micronesia. The old documentation was quite old, so a lot of the links no longer worked. This PR updates the links and makes minor changes to reflect the current way of doing things. 
[Trello](https://trello.com/c/BjZeFZvx/2531-update-govuk-developer-docs-to-reflect-current-process-for-updating-the-name-of-a-country)
> update links in doc

- source/manual/zendesk.html.md
- Document the views, macros and triggers of relevant product areas (as these can be hard to dig out later)
- Document our implementation of one-time Slack alerts per ticket, and our mechanism for keeping tag configuration in one place
- Remove outdated or unuseful info that is no longer worth keeping as our support model evolves
- Make the document more about generic Zendesk usage, but encapsulating specific Technical 2nd Line knowledge in its own section
> Rewrite Zendesk doc

- data/repos.yml
The team configuration for AI is based on the #dev-notifications-ai-govuk team name (see: https://github.com/alphagov/seal/blob/74724c9cd1f64e7cbbf18b3d756f864323440007/config/alphagov.yml#L28-L42) which is why we're not getting any notifications about PRs for this application from seal
> Replace govuk-chat repo name

- config/tech-docs.yml
- source/manual/ask-for-help.html.md
AFAICT the only way to influence [content-type/disposition in GitHub Pages] is by making the filename of the resource [match the desired MIME type].
[content-type/disposition in GitHub Pages]: https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#mime-types-on-github-pages
[match the desired MIME type]: https://github.com/jshttp/mime-db/blob/master/db.json
> Redirected paths have to end in `.html`.

- source/manual/alerts/signon-api-user-token-expires-soon.html.md
These keys auto rotate, so just adding a note about it until we can axe that alert for that api user
> Add note about auto rotation

- source/manual/fall-back-to-aws-cloudfront.html.md
This has been updated based on a 2ndline drill. The distinction between actions to take on **production** vs **staging** were unclear and have been improved. I've also added a couple of new details regarding how to do the manual failover, and how to check if the fallback domain is working. Bullet lists have been split up and nesting improved/removed for clarity.
> Update instructions for "Fall back to AWS CloudFront"

- source/manual/government-changes.html.md.erb
To make developers aware of exisiting task that can be used when working on supporting government changes.
[Trello card](https://trello.com/c/LvERbnKk/2585-update-developer-docs-to-add-reference-to-publishing-api-bulk-updater)
> Add reference to bulk retagging task in publishing_api

- config.rb
- data/analytics/attributes.yml
- helpers/analytics_helpers.rb
- source/analytics/attributes.html.md.erb
- source/analytics/data.html.md.erb
- source/analytics/templates/attribute.html.erb
- source/layouts/analytics_layout.html.erb
- spec/helpers/analytics_helpers_spec.rb
Add data and functionality into the Implementation Record to display the GTM parameter names and GA4 display names of attributes in events. This allows analysts (familiar with reading the display names in GA4) to find the attributes, which are sometimes called something different in the dataLayer.
Complicating this is that dataLayer attributes and GA4 display names don't have a 1:1 relationship. Sometimes one attribute will have different GA4 display names. 
For example, `text` by default has a GA4 display name of `UI text`, but when included from a search event (where the `event_name` is `search`), this translates through to a GA4 parameter name of `Search term`. The implementation record didn't allow for this, so the code has been extended to allow for 'variants' of attributes. If an …
> Add GA4 parameter names into GA4 implementation record

- source/manual/documents-arent-live-after-publishing.html.md
- source/manual/howto-add-organisation-brand-colour-logo.html.md
- source/manual/republishing-content.html.md.erb
[Trello](https://trello.com/c/temaFDnM/1150-delete-redundant-republishing-rake-tasks-and-update-docs)
We've recently built a user interface for republishing individual pieces of content, and we will soon remove the Rake tasks these were based on. This updates the docs to advise using the user interfaces when needing to republish Whitehall content
> Update Whitehall republishing guidance

- source/manual/retiring-an-application.html.md
- This tidy up is now done automatically in all environments, not just integration.
> Remove requirements to clear up k8s resources in staging/prod when retiring an app

- Gemfile.lock
- config/tech-docs.yml
- data/dashboard.yml
- source/mobile/android/index.html.md.erb
- source/mobile/general/index.html.md
- source/mobile/index.html.md
- source/mobile/ios/index.html.md.erb
- source/partials/repo/_mobile.html.erb
This change adds a new section for the GOV.UK mobile app documentation. 
We do not introduce too much by way of document structure at this point, preferring to leave those decisions for later. However, as the app itself is mobile native - i.e. is built in iOS and Android - it does naturally suggest a broad set of initial sections: 
- iOS - for iOS specific documentation
- Android - for Android specific documentation
- General - for documentation that is either the same for both iOS and Android, or documents that describe more general and architectural elements of the system and its development. 
GitHub repository links have been added for iOS and Android.
A [Notification banner](https://design-system.service.gov.uk/components/notification-banner/) has also been added to the `/mobile` page …
> Add GOV.UK mobile section

- .github/workflows/security.yml
We've decided to stop using Snyk for the reasons described [here](https://docs.google.com/document/d/1elh1hQoxcE-oMcHEPH3NuipFw0vkDe_T3wWmzqXRCoA/edit#heading=h.nwe71munrcvd). 
This PR will be reviewed and merged by the Platform Security and Reliability team. Any questions or concerns, please reach out in our channel: #govuk-platform-security-reliability-team.
[Trello card](https://trello.com/c/z36ZcRzL/3532-remove-snyk-jobs-from-all-ci-pipelines-3)
> Remove Snyk job from workflow

- config/tech-docs.yml
- source/manual/pact-testing.html.md
https://trello.com/c/HAEH2bVF/4-rename-imminence
> Replace references to Imminence with places manager

- data/repos.yml
This repo was useful as part of the python 2 to 3 upgrade and replatforming but as those have now been completed it has been retired.
> Set ckan-functional-tests to retire

- source/javascripts/application.js
- source/javascripts/dependencies.js
- source/javascripts/modules.js
- Copy over `modules.js` and `dependencies.js` from the publishing components gem.
- Update developer docs version of `modules.js` to add support for initialising modules from the tech-docs gem that rely on jQuery
Although it would be possible to update `modules.js` in the publishing components gem to avoid copying over from the gem, we would likely need to include some checks for jQuery which doesn't feel like quite the right approach as it could send the wrong message for jQuery support in the govuk-publishing-components gem.
Site search in the developer docs was defaulting to use Google search following a recent update in `modules.js` in the publishing-components-gem - https://github.com/alphagov/govuk-developer-docs/pull/4664
It appears this was conflicting with the approach used in …
> Fix site search

- source/manual/manage-assets.html.md.erb
Description:
- Bring the 'get asset ID' documentation to the top for ease of reading
- Add the correct rake task for adding redirects to Whitehall
> Reword assets documentation

- source/manual/republishing-content.html.md.erb
[Trello](https://trello.com/c/2nRbOaFp/1200-add-a-user-interface-for-whitehalls-bulk-republishing-documents-by-type-rake-task)
These were a little wrong/out of date. This list has been generated by finding models that match either of the following criteria:
- `ApplicationRecord` subclasses that include `PublishesToPublishingApi`
- `Edition` descendants with no descendants of their own
`EditionableWorldwideOrganisation` also meets the second criteria, but the feature is not yet turned on
> Update bulk republishable types

- source/manual/document-collection-emails-a-special-case.html.md
- source/manual/email-signup-journeys.html.md
Add documentation to explain the taxonomy_topic_email_override feature present on some document collection pages.
- [Rendered page 1](https://github.com/alphagov/govuk-developer-docs/blob/b2b5ac2b940efea67bf8ad41de5db134fb45ec01/source/manual/document-collection-emails-a-special-case.html.md)
- [Rendered page 2](https://github.com/alphagov/govuk-developer-docs/blob/b2b5ac2b940efea67bf8ad41de5db134fb45ec01/source/manual/email-signup-journeys.html.md)
- Trello cards: 
https://trello.com/c/OSr529Am/2080-workflow-to-manage-future-requests-from-hmrc-to-set-topic-level-email-notifications-on-new-not-yet-published-document-collection
https://trello.com/c/apWwP9dh/2554-complete-any-gaps-in-our-technical-documentation-for-specialist-topic-retirement
> New documentation for document-collection emails

- source/manual/howto-remove-change-note.html.md
Add documentation on how to edit a change note in manuals publisher, via de UI.
[Trello card](https://trello.com/c/0o6xP2vR/2282-remove-change-notes-from-page-manuals-publisher)
> Change notes in manual publisher

- data/repos.yml
Adds GOV.UK mobile app backend repos to the repo owners list.
> Add GOV.UK mobile app backend repos

- data/repos.yml
Repo is excluded from CI checks for now:  https://github.com/alphagov/seal/commit/69efdbeff1e6b139b7420cc87ae57c2d4f000001
I'll add `govuk` tag/topic once the PR is merged.
> Add govuk-dns-ui repo

- source/manual/web_application_firewall_rules.html.md
This was first added in f811326d2a57bfb61333d70aee97f16688799fa5, but seems to have been removed in a docs reorganisation.
> Re-add SRT team access instructions

- source/manual/update_popular_links.html.md
https://trello.com/c/KxCmWZAB/2342-2nd-line-drill
> We no longer show popular links in the the dropdown, so remove that from the drill

- data/repos.yml
https://github.com/alphagov/govuk-mobile-ios-ui-components
> [GOVUKAPP-495] Add new iOS repo to docs

- source/manual/government-changes.html.md.erb
I found a few problems with this documentation when I drilled closing the government in staging.
- It takes a long time after clicking the close governments button for anything to happen (around 1 minute, although I think [this PR](https://github.com/alphagov/whitehall/pull/9188) should speed that up)
- The links to grafana were broken 😪 
- The /api/governments endpoint is [no longer a thing](https://github.com/alphagov/govuk-rfcs/blob/main/rfc-159-switch-off-whitehall-apis.md)
- It wasn't clear to me when I could run the search reindexing task, but I'm pretty sure the answer is "straight away, once the government is closed". Which makes me wonder why it isn't just kicked off automatically? But anyway.
> Update government changes documentation

- app/document_types.rb
- app/proxy_pages.rb
- app/schema_names.rb
- source/layouts/schema_layout.erb
- spec/app/document_types_spec.rb
- spec/app/schema_names_spec.rb
This schema uses a `type` of `email_address`, something which is not supported in older versions of `govuk_schemas`. We can’t bring in the new version yet, because of dependency issues with Middleman.
We have an [upstream PR](https://github.com/middleman/middleman/pull/2709) to fix this, but in the interests of unblocking things, we can safely ignore this new schema for now.
> Ignore content_block_email_address schema

- source/manual/government-changes.html.md.erb
- source/manual/running-rake-tasks.html.md
- Moves "Reindexing political content in search" section to be subsection of "Closing a government", since we instruct devs to do it as part of that task.
- Fixes formatting of examples of history mode pages
- Links to new doc on history mode
- Adds some basic documentation to give devs a head start in working with CSVs on Kubernetes.
Trello: https://trello.com/c/v9gqCJiR/2705-review-dev-documentation-in-what-happens-after-the-election-doc
> Update "Support government changes" doc & document CSV rake tasks

- source/kubernetes/get-started/tutorials/app-update-deploy-monitor-logs/index.html.md
Fix the grafana link to the apps dashboard for the govuk-replatform-test-app
> Update kubernetes tutorial grafana link

- source/manual/amazonmq.html.md
While doing some bulk requeuing of messages to populate an index on Opensearch, we followed this guide. It was good, but there was one thing that could potentially catch people out, which is you need to admin credentials to access the dashboard.
When you run
```bash
k relay host/publishingmq.<environment>.govuk-internal.digital 4430:443
```
it doesn't give you any useful feedback if you're using poweruser creds so i think it's worth documenting.
> Update RabbitMQ web control panel docs

- source/kubernetes/fix-app/index.html.md
- source/kubernetes/manage-app/release-new-version/index.html.md
- source/kubernetes/manage-app/roll-back-app/index.html.md
It looks like the `/kubernetes` prefix was added to these pages at some
point, but a couple of links got missed.
> Update some links to Kubernetes pages

- source/kubernetes/manage-app/access-ci-cd/index.html.md
It looks like the links to these workflow config files has changed at
some point, so this updates them to point to the right files in the
repo.
Also adds a link to the Argo docs; see that commit's message for details.
> Update govuk-helm-charts URLs

- config/tech-docs.yml
- data/repos.yml
Search Analytics has been archived as it is no longer functional following the retirement of Google Universal Analytics.
> Remove search-analytics

- source/manual/testing.html.md
> Remove reference to Jenkins

- source/manual/changing-organisation-slug.html.md
Updating the slug in Manuals Publisher is much easier as of https://github.com/alphagov/manuals-publisher/pull/2427.
And updating 'best bets' has changed.
Trello: https://trello.com/c/G6OS639d/2731-reslug-ministry-of-housing-communities-local-government
> Update "Change an organisation's slug" instructions

- source/manual/manage-assets.html.md.erb
This documentation was duplicated throughout the doc, and was superseded by a new rake task added in https://github.com/alphagov/asset-manager/pull/1439.
> Consistently find an asset's ID

- data/repos.yml
Adding `production_hosted_on` should cause these to show up in the list of "apps", rather than just repos.
I think #data-insights-team is a more accurate team name than #data-products
This should make it a little more difficult to forget that govsearch exists, which we should be careful not to do because the app meets an important need for publishing users that is otherwise not coverd by GOV.UK.
> Update govsearch apps in repos.yml

- source/manual/development-pipeline.html.md
Description:
- Since the `set-autometic-deploys` workflow is now deleted (https://github.com/alphagov/govuk-helm-charts/pull/2195) update the docs to show the manual method of disabling automatic deployments
> Update docs for disabling automatic deployment

- app/repo.rb
- data/repos.yml
- spec/app/repo_spec.rb
Fixes the Kibana links on https://docs.publishing.service.gov.uk/repos/whitehall.html. See commits for details.
> <img alt="screenshot of whitehall doc page" src="https://github.com/user-attachments/assets/e29d606e-4cdd-4143-992f-f94b4e861065" width="400">
> Fix Kibana links for Whitehall

- source/manual/alerts/content-data-api-app-healthcheck-not-ok.html.md.erb
- source/manual/ask-for-help.html.md
- source/manual/content-data-architecture.html.md
- source/manual/sentry.html.md
The team is now merged with Platform Engineering and no longer has its own Slack channel.
> Update remaining references to the Platform Security and Reliability team

- source/manual/govuk-sitemap.html.md
This was a recommended action following a recent incident: https://docs.google.com/document/d/1ycI4Zd-vIUl9xFz3InSLAOI_KS8uc_7Lg7Z5Xqt7OQ8/edit#heading=h.p3b9bm9twi19
> Document how GOV.UK's sitemap is generated

- data/repos.yml
Licensify consists of three different apps in a single repo. The app names in the docs should match the actual app names.
> Rename Licensify apps

- source/manual/access-to-licensing-for-third-parties.html.md
- source/manual/deployments.html.md
- source/manual/github-unavailable.html.md
- source/manual/github.html.md
The ECR repositories are now set up as ghcr.io pull through caches, which has caused a name change.
> Update references to ECR images

- source/manual/migrate-to-dart-sass-from-libsass.html.md
Searching for "sassc" quickly brought up this page in the docs, which has a lot of useful info about the migration from LibSass to Dart Sass, but didn't specifically explain how to fix this issue. Hopefully it helps a future dev.
> Fix for "LoadError: cannot load such file -- sassc" error

- source/manual/manage-assets.html.md.erb
Otherwise we get `zsh: bad pattern: assets:delete[content_id,` in the output and the task fails to run.
> Remove space from rake task

- source/stylesheets/screen.css.scss
Adds a warning to the main sass file about a compilation problem. In a nutshell:
- https://github.com/alphagov/govuk_publishing_components/pull/4106 fixes some Sass compilation warnings, but only when compiled using `dart-sass`, which most of our applications have been migrated to
- dev docs doesn't use `dart-sass` yet, because it relies on `Middleman` for sass compilation, and we can't upgrade that
- fortunately, none of the changed Sass files in the PR above are included in the dev docs, so currently this isn't a problem
- however it seems sensible to add this warning to future devs if and when they encounter this problem (sorry future devs)
None.
Trello card: https://trello.com/c/gW2NW1sB/142-fix-sass-compilation-warnings
> Add warning about Sass compilation

- source/javascripts/dependencies.js
Removes the initialisation of Universal Analytics, which has now been turned off and replaced with Google Analytics 4.
Not needed, plus was causing an error in the console that's been happening since upgrading to the version of `govuk_publishing_components` that removed the UA code that was being called here.
```
application.js:3 Uncaught TypeError: window.GOVUK.loadAnalytics.loadUa is not a function
at HTMLDocument.<anonymous> (application.js:13:12775)
at d (application.js:3:7048)
at h (application.js:3:7351)
```
None.
Trello card: https://trello.com/c/fKGle0gD/187-remove-ua-code-from-applications
> Remove UA code

- source/manual/rules-for-getting-production-access.html.md
The term “Senior Technologist” can be ambiguous as it can be interpreted as referring to any Senior Developers/SRE/Technical Architects. Also later in the doc “Apprentice Technologist” is used.
We commonly use phrase “Senior Tech” to describe the group of Lead Developers/SRE/Technical Architects. This change makes is consistent with other manuals.
This also adds a link to the doc describing how to contact that group.
> Clarify the wording in 'When you get Production Deploy access'

- source/kubernetes/manage-app/roll-back-app/index.html.md
From chatting with Helen about the roll back process we couldn't understand why we'd need the SHA hash when we could use the simpler version id.
I've optimistically assumed that this information is outdated and we can use the version tag and thus updated the documentation. Will seek a review from someone more in the know.
> Document rolling back by version tag rather than SHA hash

- source/manual/logit.html.md
Config moved from `govuk-saas-config` to `govuk-infrastructure`, as govuk-saas-config will be retired in https://github.com/alphagov/govuk-infrastructure/pull/1429
Closes https://github.com/alphagov/govuk-infrastructure/issues/1405
> Update where we store logit config

- source/manual/sidekiq.html.md
https://github.com/alphagov/publishing-api/pull/2839 added the sidekiq UI to publishing API. The doc needed adjusting to reflect this.
> Adjust sidekiq instructions after enabling UI for Publishing API

- source/manual/rules-for-getting-production-access.html.md
I've made a best guess for the deployment docs. The list of links in the manual feel like the most obvious starting point
> Add links to prod admin access instructions

- source/manual/rules-for-getting-production-access.html.md
There's a slash that shouldn't be there, as this is linking to a section of the "manual" page.
> Fix broken link to deployment docs

- source/manual/github-unavailable.html.md
The admin login was not needed, as when the drill was tested, the github permissions were sufficient. Fixed up a few minor details that might have changed since document was made.
https://trello.com/c/qRcySnzp/20-update-the-documentation-on-the-drills-for-the-shift
> Remove Default Admin Login instructions when logging into ArgoCD

- data/repos.yml
This functionality was ported to Support API: /support-tickets endpoint [^1] is exposed via GDA API Adapters's [^2].
We want to consolidate onto one centralised way of raising support tickets. This will minimise the maintenance overhead if we ever switch away from Zendesk (rumoured to be happening in 2024) and will make the process more vendor agnostic.
https://github.com/alphagov/gds_zendesk/issues/108
[^1]: https://github.com/alphagov/support-api/blob/c0b6ca3587f6673c9512573deeecd66a2aaa0d98/app/controllers/support_tickets_controller.rb
[^2]: https://github.com/alphagov/gds-api-adapters/blob/9aabf9d/lib/gds_api/support_api.rb#L25-L39
> Retire 'gds_zendesk' gem

- source/manual/alerts/chat-ai-alerts.html.md
Add a runbook for the Chat AI Service alerts
This is to help anyone who may need to investigate an alert
> Add manual for Chat AI Alerts

- source/manual/on-call.html.md
A small update to reflect that we no longer use Icinga or Puppet, plus mentioning a recently-added extra alert.
> Update Pagerduty alert section

- source/manual/2nd-line-drills.html.md
Update 'Drill making changes to the homepage' docs
It is no longer necessary to drill into updating popular links on the homepage, as this can now be managed through Signon / Homepage. Therefore, I have removed that section.
> Update 'Drill updating homepage popular links' docs

- source/manual/alerts/chat-ai-alerts.html.md
We recently renamed this dashboard to "GOV.UK Chat Technical". This was missed as part of the rename.
> Update Chat Grafana dashboard title

- source/manual/alerts/chat-ai-alerts.html.md
Add the URLs for the GOV.UK Chat Technical Dashboards
To make it easier for people to access them from the runbook
> Add URLs for Grafana dashboards to Chat Alerts doc

- config/tech-docs.yml
- data/repos.yml
- source/manual/publish-special-routes.html.md
Preparation for retiring the repo (rake tasks now moved to publishing-api as of https://github.com/alphagov/publishing-api/pull/2881)
- point publish-special-routes docs at publishing-api
https://trello.com/c/9rOxWNnD/396-retire-special-route-publisher
> Remove special-route-publisher from docs

- source/manual/alerts/chat-ai-alerts.html.md
New Slack alerts have been created to warn when GOV.UK Chat is nearing the OpenAI rate limits for tokens or requests. This PR adds these alerts to the runbook.
> Add OpenAI rate limit alerts to Chat Alerts doc

- source/manual/transition-a-site.html.md
Updates the "Transition a site to GOV.UK" documentation to fix a broken link and clarify the process for new domains.
[Trello card](https://trello.com/c/PZ237KPX)
> Minor updates to Transition documentation

- source/mobile/backend/index.html.md.erb
- source/mobile/backend/remote-config-runbook.html.md
First pass at a runbook for making updates to remote config for 2nd line support - focusing mainly on the 'emergency' changes that might be needed, e.g. switching off a particular platform
> Runbook for mobile backend remote config

- source/manual/rules-for-getting-production-access.html.md
Update **GOV.UK Production GitHub team** url.
> Update url for prouction admin github team

- data/repos.yml
This was previously flagged as just a repo, this had the effect that nags to say it was not released was appearing in #govuk-developers and not in #dev-notifications-ai-govuk as we'd hope.
I've also added the dashboard links
> Configure GOV.UK Chat as an app

- data/repos.yml
- source/manual/development-pipeline.html.md
- source/manual/github.html.md
- source/manual/merge-pr.html.md
- GitHub configuration was ported to govuk-infrastructure: https://github.com/alphagov/govuk-infrastructure/tree/main/terraform/deployments/github
- Logit configuration was migrated to govuk-infrastructure: https://github.com/alphagov/govuk-infrastructure/tree/main/docs/logit/logit
- Verify repos script was migrated to seal: https://github.com/alphagov/seal/pull/561/files
https://github.com/alphagov/govuk-infrastructure/issues/1459
> Retire govuk-saas-config

- source/manual/rename-a-country.html.md
Single reference removed as part of [retiring the smart answer for Get Married Abroad](https://trello.com/c/JQUKmEBh). The [old version](https://www.gov.uk/marriage-abroad) has been replaced with a [new version](https://www.gov.uk/marriages-civil-partnerships-abroad) which is now managed by FCDO. Therefore, the renaming countries process detailed here will no longer have an effect on the smart answer.
> Remove reference to now retired smart answer - marriage-abroad

- source/manual/howto-add-organisation-brand-colour-logo.html.md
> Fixes to "change org brand colour" docs

- source/manual/alerts/signon-api-user-token-expires-soon.html.md
This makes the following changes:
- removes the need to wait overnight or execute the cron job on a command line
- makes it clear that tokens used outside GOV.UK need to be dealt with differently
[Trello card](https://trello.com/c/ciBHfk6a)
> Update documentation for rotating an expiring token

- source/manual/keeping-software-current.html.md
We currently spend an unacceptable amount of time patching all of our repos to the very latest versions of all dependencies, when actually we have some repos that are barely used and are already marked for retirement.
In these cases, the risk of loosening our Dependabot policy for deprecated repos should be very low. In fact, the risk of accidentally breaking something in the deprecated repo - through bumping a dependency - is moderately high, as we'd be relying purely on tests to catch any regressions. (There may be too little user activity for it to be noticed otherwise).
Security updates should still be applied.
See https://docs.google.com/document/d/1qcnGDzw5PKKg97c3ivDpBtmbbutsUcIfk5GZxqLqFjg/edit for more.
Trello: https://trello.com/c/kpf7rWEq/2979-change-dependabot-configs-for-conte …
> Add exception for 'deprecated repos'

- source/manual/licensing.html.md
Description:
- Licensify lives in the `licensify` namespace not the `app` namespace
> Fix licensify port forward proxy

- data/repos.yml
This now runs on EKS, instead of Heroku, so updating the docs to reflect this.
[Trellon card](https://trello.com/c/dhgDqvBa)
> Update hosting for govspeak-preview

- app/repo.rb
- app/repos_csv.rb
- data/repos.yml
- source/partials/repo/_ownership.html.erb
- spec/app/repo_spec.rb
The `dependencies_team` value was [used by](https://github.com/alphagov/govuk-dependencies/blob/578a76784671cd0ca3070e15afb53ab3a09bd3dc/lib/gateways/team.rb#L27) the (now deprecated) `govuk-dependencies` application to allow dependabot alerts to be posted to channels other than the team's main channel.
It is currently unused by any application, but we would like to alert to a different channel in the release app.
Therefore renaming the field to make it more generic, so it can be used by all alerts, not just dependencies.
[Trello card](https://trello.com/c/NKbo84JK)
> Allow alerts to be sent to a different channel for GOV.UK Publishing Platform

- source/partials/repo/_ownership.html.erb
It appears this code has never been executed before, so the long-standing typo has never been discovered.
[Trello card](https://trello.com/c/NKbo84JK)
> Fix typo in `link_to` method call

- source/manual/on-call.html.md
- Move on-call charter to top of doc - this is the bit of documentation we'll be pointing on-call engineers towards on a regular basis, so shouldn't be tucked away at the bottom
- Removes duplication of on-call checklist, which is covered by the Trello card template
PS: I hope to soon consolidate https://docs.publishing.service.gov.uk/manual/2nd-line.html into https://docs.publishing.service.gov.uk/manual/on-call.html, but we can do that in https://trello.com/c/d2z5WSze/254-rebrand-2nd-line-to-simply-on-call
Trello: https://trello.com/c/WAVXDbAr/263-review-and-consolidate-checklist-template-cards
> Update on-call docs

- source/manual/2nd-line.html.md
- source/manual/pagerduty.html.md
Standby roles were reduced from 2 to 1 in Q2, and from 1 to 0 in Q3.
Shadow roles are of very little value now, as activity on Tech 2nd Line is now negligible. We'll instead explore a system for shadowing incidents.
References to these two roles have now been removed, and I've fixed up some other obviously broken / out of date info while I'm here. A more full review of the doc will happen when we consolidate the Tech 2nd Line and On Call docs.
Trello: https://trello.com/c/BDcPvHJM/262-consider-archiving-the-shadowing-2nd-line-on-govuk-template-card
> Remove references to shadow and standby roles

- source/manual/ownership-meaning.html.md
- source/manual/tech-lead-responsibilities.html.md
Effectively a TLDR of
https://docs.google.com/document/d/1I4o4hLjpjUMthTOXEbmecBqpHvms2HV3EXKCHSCAK3U/edit, which has already been accepted and implemented.
> Document that the responsibility for owning drills is now in teams

- source/manual/slack-unavailable.html.md
- source/manual/terraform-cloud.html.md
2nd-line-support is deprecated.
Trello: https://trello.com/c/348IuAYs/259-set-up-new-govuk-technical-oncall-comms-google-group-to-replace-2nd-line-support
> Document new Google group for Technical On-Call

- source/manual/manage-assets.html.md.erb
This is by far the most common use case for following these instructions - so let's make it a bit less abstract.
Trello: https://trello.com/c/tKtV5zHj/3025-older-documents-are-appearing-in-google-search-results
> Clearer instructions for removing assets originating from Whitehall

- source/manual/secrets-manager.html.md
It took some digging to find this from the old govuk-secrets instructions. We don't need it often, but it's useful to know how to do this for the odd occasion we need to sign into a shared account.
> Document how to use 2fa-seed strings

- source/manual/deployments.html.md
See [Slack thread](https://gds.slack.com/archives/C013F737737/p1730365648215849): the Argo UI caught me out and I was pointlessly clicking "Sync" and waiting for its commit sha to update. There's a bug in the UI where it still references the old sha.
The more reliable method is to look at the Details view as documented here.
> Expand docs for checking app branch has deployed

- source/manual/dns.html.md
This fixes a broken link (the search was returning nothing helpful)
> Fix broken link to DNS support documentation

- source/manual/post-a-statuspage-message.html.md
> Document manual process for granting StatusPage access

- data/repos.yml
This repo was deleted as we no longer need to store sensitive information there
> Remove govuk-infrastructure-sensitive repo

- .github/workflows/deploy.yml
See #4865 - our docs were failing to deploy for around a week and nobody noticed. This is an attempt to remedy that.
The 'notify failure' action is copied from govuk-rota-generator and the secret used is `govuk/slack-webhook-url` from AWS Secrets Manager.
> Add Slack notification on deployment failure

- source/manual/alerts/RouterErrorRatioTooHigh.html.md
- source/manual/alerts/chat-ai-alerts.html.md
- source/manual/alerts/email-alerts-travel-medical.html.md
- source/manual/alerts/signon-api-user-token-expires-soon.html.md
- source/manual/debug-underperforming-search.html.md
- source/manual/errors.html.md
- source/manual/graphite-and-deployment-dashboards.html.md
- source/manual/pagerduty.html.md
- source/manual/pingdom-bouncer-canary-check.html.md
- source/manual/pingdom.html.md
- source/manual/screens.html.md
- source/manual/sentry.html.md
- source/manual/sidekiq.html.md
As a fairly simple first step to getting some of these docs sorted out, I've consolidated these sections:
- `Alertmanager alerts`
- `Pagerduty alerts`
- `Pagerduty`
- `Monitoring`
into a single `Monitoring and alerting` section. 
Further work is still needed - part of https://github.com/alphagov/govuk-developer-docs/issues/4797
> Create a new Monitoring and alerting section and move some docs to it

- source/manual/govuk-env-sync.html.md
This feels like a better place for the data sync docs, and it was the last thing in the now-superseded `Monitoring` section. 
I somehow missed this in https://github.com/alphagov/govuk-developer-docs/pull/4863
> Move data sync page to Backups section

- source/manual/republishing-content.html.md.erb
This is now fully supported in the UI and the rake tasks will be removed in https://github.com/alphagov/whitehall/pull/9628
See https://whitehall-admin.publishing.service.gov.uk/government/admin/republishing
Trello: https://trello.com/c/yi1ExGvz/3179-audit-rake-tasks-that-rely-on-scp-push
> Update docs on republishing Whitehall content

- data/repos.yml
Our team has recently revived and taken over the `govuk-display-screen` application.
This PR adds our team as owner of the repository.
Is the `team` value supposed to be our team's channel name in Slack? Or something else?
> repos: add "govuk-display-screen" repo to the repos.yml

- data/repos.yml
This adds the newly-minted [govuk_content_block_tools](https://github.com/alphagov/govuk_content_block_tools) gem to the list of repos.
> Add govuk_content_block_tools gem to repos.yml

- source/manual/load-test.html.md
This gives instructions for running a load test on AWS using k6.
The need originated from [this Trello card](https://trello.com/c/P7cdLbnK).
> Add instructions for running a load test with k6

- data/repos.yml
> Add govuk_web_banners repo information

- source/manual/github-new-repo.html.md
- source/manual/github.html.md
A few smallish changes to:
- Try to make requirements for setting up a new GOV.UK repo clearer (some of these steps are regularly missed) by splitting this out into a separate page
- Fix heading structure
- Improve general readability and fix typos
> Tweaks to Github docs

- source/manual/post-a-statuspage-message.html.md
Updated the "Incident Management" linked on the Status Page.
The previous link would result in a 404 error.
> Fix broken incident management link

- source/manual/configure-linting.html.md
- source/manual/find-a-rails-template-based-on-a-govuk-url.html.md
- source/manual/github-new-repo.html.md
- source/manual/how-to-escalate-to-AWS-support.html.md
- source/manual/slack-integrations.html.md
Slightly pedantic, but this changes how the pages are displayed on https://docs.publishing.service.gov.uk/manual.html, and how related links are displayed at the bottom of pages. 
Several pages were incorrectly marked as "Learn" when actually they're guides for how to do something.
> Change some pages from"Learn" to "How to"

- Gemfile.lock
- source/manual/email-notifications-how-they-work.html.md
- source/manual/email-signup-journeys.html.md
Update email notification documentation to cover lack of support for foreign language publications. 
[Trello](https://trello.com/c/24HBupfM/3107-hide-single-page-notification-button-on-welsh-pages)
> Update email notifcation docs

- source/manual/manage-assets.html.md.erb
[Trello](https://trello.com/c/YIs8YZmF/3146-fix-live-assets-on-superseded-editions)
> Update guidance on assets

- source/manual/load-test.html.md
The instructions missed the step to remove the configmap file.  Not removing this can result in an error (because of duplicated names) when running another load test.
Also we need to use a stable version of `k6-operator` (rather than the main branch).  Therefore pinning this to the version that was used when writing these instructions.
[Trello card](https://trello.com/c/sVW4QFue)
> Update instructions for load testing

- data/repos.yml
Our fork of `widdershins` has been archived, since we no longer use it in any applications.
Depends on https://github.com/alphagov/govuk-content-api-docs/pull/152.
[Trello card](https://trello.com/c/7LqhcraV)
> Remove `widdershins` from list of repos

- data/repos.yml
This updates the channel govuk-frontenders to govuk-ruby-frontenders as it has been renamed for clarity now that the Design System frontenders are also in the GOV.UK programme
> Update renamed channel

- source/manual/brakeman.html.md
The reusable workflow for running Brakeman[1] doesn't rely on any
secrets, so there's no need to pass `secrets: inherit` when calling the
workflow.
[1] https://github.com/alphagov/govuk-infrastructure/blob/main/.github/workflows/brakeman.yml
> Remove secrets from Brakeman workflow example

- source/manual/howto-add-organisation-brand-colour-logo.html.md
Trello: https://trello.com/c/LeyNfXgg/
> Add missing step for adding org logo

- data/repos.yml
This is a private gem for the govuk-chat repo that is used to store parts of govuk-chat that were agreed to not be suitable for open sourcing.
While it's not a particularly interesting addition to the dev docs, being private, it is required for terraform handling of repo configuration.
> Add govuk_chat_private repo

- data/repos.yml
Both of these were archived in the last couple of days and need to be removed from the dev docs to stop terraform trying to write to them (terraform tries to unarchive them but mercifully fails)
> Remove archived repos

- app/proxy_pages.rb
- app/repo.rb
- app/repos.rb
- data/repos.yml
- spec/app/proxy_pages_spec.rb
- spec/app/repo_spec.rb
The siteimprove client includes [extensive auto-generated API documentation](https://docs.publishing.service.gov.uk/repos/siteimprove_api_client.html), which doesn't need to be mirrored to the developer docs.
If someone wants to read this documentation while working with the siteimprove client, they can still read it in GitHub.
> Add skip_docs option, and skip siteimprove docs

- source/manual/retiring-a-repo.html.md
- Advise to cancel workflow runs before archiving a repo
- Add an explicit step to remove GitHub config for the archived repo
Details in the commit messages.
We may want to replace steps 4. and 5. by using `archived` argument in the TF config.
> [`archived`](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository#archived-1) - (Optional) Specifies if the repository should be archived. Defaults to false. NOTE Currently, the API does not support unarchiving.
> Update retire repo docs

- source/manual/add-translation-whitehall.html.md
This is hugely simplified since https://github.com/alphagov/whitehall/pull/9845/ and https://github.com/alphagov/whitehall/pull/9855
Trello: https://trello.com/c/T2neQSyf/3319-add-language-support-for-kyrgyz
> Update instructions for adding language to Whitehall

- source/manual/government-changes.html.md.erb
Also reorders the instructions for the other publishing apps, and brings the Publishing API rake task to the bottom of the list, since we should be making all changes in the publishing apps themselves where possible.
Trello: https://trello.com/c/o9iYyNxf/623-add-ui-for-re-tagging-organisations-to-content-in-bulk
> Document Whitehall retagging form

- .github/workflows/deploy.yml
The deployed-to-production branch no longer exists in the Publishing API repository. It has not been used for some time, as far as we are aware.
> Fetch the content schemas from Publishing API's main branch

- data/analytics/navigation.yml
- source/analytics/approach.html.md.erb
- source/analytics/attributes.html.md.erb
- source/analytics/consent.html.md.erb
- source/analytics/data.html.md.erb
- source/analytics/docs.html.md.erb
- source/analytics/events.html.md.erb
- source/analytics/events_by_group.html.erb
- source/analytics/further_docs.html.erb
- source/analytics/pii.html.md.erb
- source/analytics/progress.html.md.erb
- source/analytics/schema.html.md.erb
- source/analytics/templates/attribute.html.erb
- source/analytics/templates/event.html.erb
- source/analytics/trackers.html.md.erb
- source/layouts/analytics_layout.html.erb
Improves page titles and adds metadata descriptions for the [analytics section of the dev docs](https://docs.publishing.service.gov.uk/analytics/).
Previously no meta descriptions, so sharing pages didn't provide enough information.
None.
Trello: https://trello.com/c/PmI26YFF/839-update-ga4-implementation-record-page-titles
> Improve Implementation Guide page titles and meta descriptions

- source/manual/conventions-for-rails-applications.html.md
We've revised our approach to timezones in Rails apps and updated the default configuration, so this updates the related guidance. Relevant links in the diff
> Update guidance on Rails timezones

- README.md
- app/document_types.rb
We were having trouble getting this working locally, which wasn't helped by sporadic docs and swallowed errors. See commits.
> Improvements to documentation around getting Developer Docs running locally

- source/kubernetes/create-app/index.html.md
It's useful to link to the "Configure a new GOV.UK repository" guide so those steps are not missed.
> Mention new repo guide in Create a new application guide

- source/manual/organisations-api.html.md
We lacked any documentation on the Organisations API, which has a surprisingly complicated architecture. This commit documents the current state of play and hopefully highlights areas that are ripe for improvement.
Rendered page: https://github.com/alphagov/govuk-developer-docs/blob/ade3b1a998cd8df18978a778e17b264128c9ce13/source/manual/organisations-api.html.md
Trello: https://trello.com/c/nrScGlbr/3445-document-the-organisations-api
> Document the Organisations API

- source/manual/rules-for-getting-production-access.html.md
We are no longer using `govuk-aws-data`, with access to AWS granted through `govuk-user-reviewer`.
Updating the documentation to reflect this.
> Fix broken links in production rules document

- source/manual/global-banner.html.md
Do not merge before https://github.com/alphagov/static/pull/3561
https://trello.com/c/pDinfQqK/296-update-static-to-use-the-gem-for-global-banner-handling
> Update global banner deployment instructions

- source/kubernetes/manage-app/index.html.md
- source/kubernetes/manage-app/set-permissions/index.html.md
Description:
- Describe the error that occurs when a deployment doesn't conform to PSS restricted
- Closes https://github.com/alphagov/govuk-helm-charts/issues/1883
> Update Kubernetes documentation for PSS restricted

- app/repo_sidebar.rb
- data/dashboard.yml
- source/content-modelling/index.html.md.erb
- source/layouts/multipage_layout.html.erb
- source/layouts/repo_layout.html.erb
- source/partials/_in_page_navigation.html.erb
- source/partials/repo/_sidebar.html.erb
- spec/app/repo_sidebar_spec.rb
This contains the beginnings of the content modelling documentation. Because we don't have a repo per se to refer to, I've added a new section, which then links out to the relevant documentation in the relevant repos. I've also done a bit of a refactor of a repo's navigation to support multiple levels of directories.
> (917) Add content modelling docs

- .github/workflows/deploy.yml
- Rakefile
The build is [currently failing](https://github.com/alphagov/govuk-developer-docs/actions/runs/13657932250/job/38181773085), but it's difficult to see why. This PR adds verbose logging as well as failing fast so the build bails at the first error, so we can see what's going on a bit more easily. I've also fixed the bad JSON that was preventing the Slack alerts from sending.
> CI Improvements

- source/content-modelling/schemas/adding-a-new-content-block-type.html.md.erb
- source/content-modelling/schemas/index.html.md.erb
Trello card: https://trello.com/c/JfbTFW0e/917-tech-documentation
This adds some documentation about how schemas work in Content Block Manager, as well as guidance on how to add a new schema.
> Add information about content block schemas

- source/manual/data-gov-uk-2nd-line.html.md
Various tweaks to make things clearer, plus to:
- Reflect we no longer create ZD tickets directly from Find
- Remove reference to an obsolete ZD queue and to "technical 2nd Line"
- Fix some non-rendering links
- Update example department names
> Various changes to data.gov.uk support docs

- source/content-modelling/preview/index.html.md.erb
https://trello.com/c/JfbTFW0e/917-tech-documentation
A brief overview pointing to the parts of code that relate to previewing a Content Block.
> Add documentation of Preview code in Content Block Manager

- source/manual/test-and-build-a-project-with-github-actions.html.md
As recommended by GitHub’s security hardening documentation, this adds a
new section to the “Test & build a project with GitHub Actions” guide
instructing developers to pin untrusted (third-party) actions to a
specific commit SHA.
Pinning helps protect against supply chain attacks, breaking changes,
and unanticipated updates.
This change also includes examples illustrating how to reference a
commit SHA within a workflow.
> 📝 Add guidance on pinning untrusted GitHub Actions to commit SHAs

- source/manual/manage-assets.html.md.erb
- Known bugs have been fixed and are no longer an issue
- Added links to the flow diagrams in the repos for useful debugging
https://trello.com/c/UTDPROlf/3576-consolidate-existing-asset-diagrams
> Update Manage Assets manual

- source/manual/alerts/whitehall-error-ratio-too-high.html.md
This alert will be added in govuk-helm-charts in a separate PR.
> Document whitehall error rate alert

- source/layouts/repo_layout.html.erb
This updates a bit of old code and updates the breadcrumbs for non-app repo pages to use /repos instead of /apps, since the latter doesn't cover non-app repositories
> Improve apps and repos breadcrumbs

- data/repos.yml
This is a protoype JS library to demonstrate how we could highlight content blocks within publishing apps.
> Add content-block-editor repo

- source/manual/run-ab-test.html.md
Two issues are fixed here:
- a broken link
- an instruction to remove a dictionary when you actually need to add it
[Trello card](https://trello.com/c/stxnESVI)
> Fix A/B testing documentation

- README.md
- source/kubernetes/get-started/access-eks-cluster/index.html.md
- source/manual/how-to-upgrade-rails.html.md
The Markdown engine used by the tech docs template is very particular about how it parses lists. I think quite a few lists in the docs are parsed in unintentional ways. This fixes a couple of guides and adds some guidance to be wary of this in future
Auditing all existing content would be nice but very time consuming, so it's probably a fix it when you see it job. Hopefully the brief notes here will help with that
I've included full page screenshots so that comparison can be made with other markup on the affected pages
Pay attention to the numbers, indentation, and element types of the first ordered list
Pay attention to the "Update configuration using the Rails update task" section:
- its ordered list
- its subsection "Guidance for all upgrades" …
> Fix list markup and document list parsing issues

- source/manual/manage-assets.html.md.erb
Point to the repository documentation around known bugs and unsupported features
> Add more information for asset management

- source/manual/manage-assets.html.md.erb
Fix accidental copy paste that broke links.
> Fix links for assets documentation

- .github/workflows/deploy.yml
Since the govuk-developer-docs' hand-rolled version was added, Platform Engineering have added a new pipeline that any GOV.UK repo can reuse:
https://github.com/alphagov/govuk-infrastructure/pull/1729
On merge, we should be able to delete the `SLACK_WEBHOOK_URL` secret from govuk-developer-docs, as we're now using the `GOVUK_SLACK_WEBHOOK_URL` secret which is "added to all GOV.UK repositories as an organisation secret in the GOV.UK GitHub Infrastructure configuration.":
https://github.com/alphagov/govuk-infrastructure/tree/main/.github/actions/report-run-failure#notes-on-using-this-action
The output of the alert should look the same, according to the [test](https://gds.slack.com/archives/C08D696LAEA/p1740667524061079), with our optional message included.
> Use shared 'notify Slack' GitHub Action workflow

- source/manual/brakeman.html.md
- source/manual/codeql.html.md
- source/manual/dependency-review.html.md
- source/manual/security-alerts.html.md
A few tweaks to the guidance on dealing with security alerts:
- removes duplicate content from the individual pages and instead links to the general page
- removes the list of reasons for alert dismissal - it didn't match what was in Github and it may change anyway. Users can see the up to date list in Github. 
- some general language simplification
Part of https://github.com/alphagov/govuk-platform-internal/issues/3
> Changes to security alerts guidance

- source/content-modelling/schemas/adding-a-new-content-block-type.html.md.erb
https://trello.com/c/Fa5E0qo6/1031-tech-task-create-basic-contact-content-block-schema
This adds step to add the new schema type to Content Data API, so that its integration tests don't stop Publishing API merging https://gds.slack.com/archives/CAB4Q3QBW/p1745595957204829
> add instructions for adding new schema to Content Data API

- data/repos.yml
This adds the new https://github.com/alphagov/content-modelling-e2e repo, which contains a more extensive suite of e2e tests for content modelling, which can be run on demand.
> Add content-modelling-e2e repo

- .github/workflows/deploy.yml
This workflow calls actions-gh-pages and triggers a Slack notification if it fails. This works great if there's an issue with the build script, but is also firing if the deployment action fails "as intended":
1. When two deployments are triggered in quick succession (e.g. two documentation PRs are merged within a couple of minutes of one another), the first deployment fails with an error at the actions-gh-pages step, along the lines of:
``` To https://github.com/alphagov/govuk-developer-docs.git ! [remote rejected] gh-pages -> gh-pages (cannot lock ref 'refs/heads/gh-pages': is at cf14548dd550851ca839b1378a51feda827f46b1 but expected c7de622d49bcde05531980b279f7defcfa23b931) error: failed to push some refs to 'https://github.com/alphagov/govuk-developer-docs.git' ```
2. This is causing a …
> Enforce only 1 deployment workflow at a time (always latest)

- source/manual/github-new-repo.html.md
Make it easier to know which licence to select, and also enforcing having a licence file in all the repos.
> Link to licensing guidelines from create a new repo instructions

- source/manual/github-new-repo.html.md
Link to the GDS Way docs for licensing rather than developer docs licensing.html which is a licensify manual.
> Linking to the correct Licensing Guidelines for new repos

- data/repos.yml
This is incorrectly listed as Platform Engineering. This commit corrects that.
> ♻️ Change CKAN ownership

- source/manual/rules-for-getting-production-access.html.md
This updates the Dev Docs to keep them up to date with the role changes that are being applied to our AWS Accounts. Further info will be available on our govuk-user-reviewer (internal) repo.
See:
* https://github.com/alphagov/govuk-user-reviewer/pull/1540
> Update Prod Deploy and Prod Admin descriptions.

- source/manual/sentry.html.md
This removes links to dashboards that were retired a while ago.
> Remove links to obsolete dashboards

- source/manual/test-and-build-a-project-with-github-actions.html.md
https://github.com/alphagov/govuk-infrastructure/issues/2056
> Add recommendation to enable concurrency controls to app CI workflows

- source/manual/how-to-rotate-fastly-api-keys-for-prometheus-exporter.html.md
Description:
- Fix correct Fastly API token secret name
> BAU - Fix correct Fastly API Token secret

- data/repos.yml
Description:
- Add `search-with-select-component` repo
- Add `govuk-design-guide` repo
> BAU - Add search-with-select-component and govuk-design-guide repos

- data/repos.yml
`govuk-design-guide` is owned by a team outside of Publishing so should have it's own category similar to Data science.
`select-with-search-component` is a gem so should have this type listed so it can be picked by automation such as Gem auto release workflow.
@minhngocd, @nnagewad We added those repos to the list. Please ensure you follow all the remaining steps in [Configure a new GOV.UK repository](https://docs.publishing.service.gov.uk/manual/github-new-repo.html) guide (alternatively remove the `govuk` GitHub topic).
> Update `select-with-search-component` and `govuk-design-guide` repo types

- source/manual/govuk-notify.html.md
Given this access comes with production admin access, it should be the same as the ‘sponsor’ (Tech Lead, Senior Tech). 
All users have permissions to invite new users and "Manage settings, team and usage".
Platform Engineering team is unlikely to have enough context to be able to make a decision if a user should be granted access.
> Change who grants Notify access

- source/kubernetes/get-started/access-eks-cluster/index.html.md
There are some examples of the old AWS roles still being displayed on the EKS Access page. This will use the correct role names and add some other bits of information to the documentation.
> Update Roles on the EKS Clusters Access page

- source/kubernetes/cheatsheet.html.md
- source/manual/create-a-local-transaction.html.md
- source/manual/dns.html.md
- source/manual/fall-back-to-aws-cloudfront.html.md
- source/manual/get-started.html.md
- source/manual/github-unavailable.html.md
- source/manual/how-to-escalate-to-AWS-support.html.md
- source/manual/how-to-query-mysql-database-on-eks.html.md
- source/manual/howto-change-slug-and-create-redirect.html.md
- source/manual/howto-checkout-and-commit-to-codecommit.html.md
- source/manual/manage-assets.html.md.erb
- source/manual/purge-cache.html.md
- source/manual/redirect-routes.html.md
- source/manual/reindex-elasticsearch.html.md.erb
- source/manual/secrets-manager.html.md
- source/manual/web_application_firewall_rules.html.md
`readonly` and `admin` roles were deprecated and removed from gds-cli in https://github.com/alphagov/gds-cli/pull/955/files `developer` and `fulladmin` roles should be used.
This naively replaced:
- `readonly` and `poweruser` with `developer`
- `admin` with `fulladmin`
I'd appreciated a through review especially around CDN docs.
Related to https://github.com/alphagov/govuk-infrastructure/issues/1833 https://github.com/alphagov/govuk-infrastructure/issues/1757
> Update references to deprecated AWS roles

- source/manual/environments.html.md
Simply removes the link to a doc about the VPN, which is changing
Part of https://github.com/alphagov/govuk-infrastructure/issues/2134
> Remove VPN doc link which will soon be obsolete

- source/kubernetes/get-started/access-eks-cluster/index.html.md
- source/manual/rules-for-getting-production-access.html.md
This documents the new `platformengineer` roles that have been implemented for use by GOV.UK Platform Engineers.
> Document the Platform Engineer role and access

- data/repos.yml
The repo is now archived.
NB, since https://github.com/alphagov/govuk-developer-docs/pull/4497, we seem to encourage removing the repo from the repos.yml entirely, rather than adding `retired: true` and a `description`.
I'll update https://docs.publishing.service.gov.uk/manual/retiring-a-repo.html#6-update-the-developer-docs in a separate PR.
Trello: https://trello.com/c/MiBvG4Xs/3767-retire-contacts-admin
> Remove Contacts Admin from repos list

- source/manual/retiring-a-repo.html.md
We have a check that ensures all repos are listed in dev docs so it’s fair to assume this will always be the case.
We no longer mark repos as retired with `retired: true` as they were included in the Dev docs search results making the search results less relevant and harder to find information.
> Update 'Retire a repo' step about updating dev docs

- source/content-modelling/schemas/adding-a-new-content-block-type.html.md.erb
We've added some detailed documentation on how to configure how schemas are presented in Content Block Manager, so let's link out to it
> Link to Content Block Manager config vars

- source/manual/howto-backup-and-restore-in-aws-rds.html.md
Description:
- Role is now `fulladmin` rather than `admin`
> Update gds govuk role references for restoring RDS snapshot

- source/kubernetes/get-started/access-eks-cluster/index.html.md
We have added a readonly role (ADR0015). We also update our docs to reflect its existence and reinforce the default usage of it.
> Mention and reinforce readonly role usage in Kubernetes getting access guide

- source/manual/add-support-new-language.html.md
It really is just three lines of config now, not >400 files of locale files as per the previous example.
> Update example PR for Whitehall

- app/document_types.rb
- app/proxy_pages.rb
- app/schema_names.rb
- source/content-modelling/schemas/index.html.md.erb
- source/layouts/schema_layout.erb
- spec/app/document_types_spec.rb
- spec/app/schema_names_spec.rb
Updates the Content Modelling documentation to reflect changes to the way email address is handled.
The "email address" content block schema no longer exists. Email address is now (since [May 23, 2025 42ecacc3b99eba8e087e4e60f7b33e59d17469f2](https://github.com/alphagov/publishing-api/commit/42ecacc3b99eba8e087e4e60f7b33e59d17469f2)) a part of the "content_block_contact"
schema.
(This PR replaces https://github.com/alphagov/govuk-developer-docs/pull/5150 which is proving difficult to merge, perhaps due to a misconfiguration of permissions or user accounts, which may now be resolved.) Second replacement PR.
> Content modelling: remove email address content block reference

- data/analytics/attributes.yml
- data/analytics/schemas.yml
- Add `user_id` to implementation record
- Add `content_id` to `event_data` of `schemas.yml`
These are new attributes requested to be added by Publishing PAs to the schema so should be also documented here.
> Add new GA4 schema attributes to implementation record

- source/manual/add-a-best-bet.html.md
- source/manual/boost-or-demote-a-document-in-search.html.md
- source/manual/get-or-delete-a-document-from-VAIS.html.md
- source/manual/govuk-search.html.md
- source/manual/govuk-site-search.html.md
- source/manual/how-to-clear-the-redis-cache.html.md
- source/manual/how-to-resync-content-in-vertex.html.md
- source/manual/prevent-a-page-being-returned-in-search-results.html.md
- source/manual/prevent-an-unhelpful-autocomplete-suggestion.html.md
- source/manual/search-synchronisation-errors.html.md
- source/manual/what-to-do-if-search-is-down.html.md
The anchor link for the [Search section] wasn't working.
[Search section]: https://docs.publishing.service.gov.uk/manual.html#search
> Rename Search section to GOV.UK Search

- source/manual/govuk-env-sync.html.md
This came up today and I always forget how to `k`.
> Expand troubleshooting docs for failed env sync

- source/manual/get-started.html.md
This PR switches the Homebrew install method from the "curl|bash" method to the ".pkg" method, which Homebrew introduced as another official install method a couple of years ago.
The reason for this switch is a security improvement. I buy this LLM reasoning:
> Why is it better security than bash|curl?
> * Malicious Homebrew insiders need only modify the install.sh script via GitHub repository access to achieve immediate global impact across all new installations. Whereas the .pkg would also require the attacker to have privilege for their GitHub Actions release workflows, and obtain access to the Apple Developer ID Installer certificate. This creates higher privilege thresholds and additional detection opportunities throughout the attack chain. The 2024 malvertising campaign that created …
> Install Homebrew with more secure .pkg method

- source/kubernetes/manage-app/get-app-info/index.html.md
- source/manual/kibana.html.md
- source/manual/logging.html.md
- source/manual/logit.html.md
This is a follow on to #5184 updating more pages with information about querying the kubernetes events via logit
* Fixes the mermaid rendering on the "How logging works" page (it needs to be a pre tag with lang=mermaid, backticks codeblocks wont get rendered)
* Add example kibana queries
* Add info about querying logit to get an apps kubernetes events in logit
* Update the logit page to say we also send kubernetes events
> Update pages for querying kubernetes events via logit

- source/manual/logging.html.md
My mermaid diagram still doesn't render (see https://docs.publishing.service.gov.uk/manual/logging.html#architecture-of-kubernetes-events-log-delivery), I didn't realise that it needs to be a code block, inside a pre (with lang=mermaid).
You can see the query selector https://github.com/alphagov/govuk-developer-docs/blob/85d04764b0b0f6e9ce6f1eebb2226ed8962789fd/source/javascripts/mermaid-init.js#L5 so I'm confident this change should work
> Fix codeblock for mermaid rendering

- source/manual/publish-special-routes.html.md
> Document special route / search api quirks

- data/repos.yml
This is a temporary app, created while we work on migrating Publisher from MongoDB to PostgreSQL.
> Add publisher-on-pg as an app

- data/repos.yml
JIRA: https://gov-uk.atlassian.net/browse/WHIT-2020
> Retire markdown-toolbar-element (WHIT-2020)

- source/manual/request-fastly-tls-certificate.html.md
We have a number of GlobalSign certificates already paid for in our account, so this works out cheaper for us at present.
> Switch Bouncer cert provider to GlobalSign

- source/manual/setting-up-new-rails-app.html.md
This caught me out when deploying a new app - as the upload-assets job requires this to be present when booting the app (see https://github.com/alphagov/govuk-helm-charts/blob/c9e5255fc485af4b7b1877a1f1ef6a30f44d18bd/charts/generic-govuk-app/templates/assets-upload-job.yaml#L3)
> Add asset-related documentation

- data/repos.yml
This adds the new [Content Block Manager](https://github.com/alphagov/content-block-manager/) repo to the repos.yml config. We'll need to migrate some of the docs from Whitehall, but this will at least stop the alerts.
> Add `content-block-manager` to `repos.yml`

- source/kubernetes/how-to-disable-or-re-enable-an-app/index.html.md
- source/manual/how-to-disable-or-re-enable-an-app.html.md
Add a how-to which describes how to disable, or re-enable an app.
This guide stems from RDS maintenance work where we had to figure this out on the fly.
> Add how-to disable an app instructions

- source/manual/fall-back-to-aws-cloudfront.html.md
Now that we have successfully completed a CDN failover drill in staging, update the docs to refine them a little.
> Following CDN failover drill, update failover docs

- data/repos.yml
Update the repos section so that `public-asset-checker` is owned by Patterns and Pages.
This repo currently has no ownership and no one was updating any of its packages, so there were some significant security warnings in place. Those have mostly now been dealt with, but there needs to be more ownership of this repo from this point on.
`public-asset-checker` is a tool developed during the GA4 migration to do two things - monitor the size of the JS on GOV.UK (to ensure that changes to GTM/GA4 don't artificially inflate our asset size) and to alert when new versions of [RUM](https://github.com/alphagov/govuk_publishing_components/blob/main/docs/real-user-metrics.md) are available (a dependency that needs to be manually updated in `govuk-publishing-components` fairly regularly). It posts the …
> Assign public-asset-checker to P&P
